In [2]:
from pathlib import Path
import importlib
import sys

import numpy as np
import pandas as pd
import torch

PROJECT_ROOT = Path.cwd()
if PROJECT_ROOT.name == "notebooks":
    PROJECT_ROOT = PROJECT_ROOT.parent

SCRIPTS_DIR = PROJECT_ROOT / "scripts"
if str(SCRIPTS_DIR) not in sys.path:
    sys.path.append(str(SCRIPTS_DIR))

import two_tower_training
importlib.reload(two_tower_training)

from two_tower_training import (
    TrainConfig,
    compare_on_common_objectives,
    export_frozen_embeddings,
    load_processed_two_tower_data,
    run_config_grid,
    summarize_results,
)

PROCESSED_DIR = PROJECT_ROOT / "data" / "processed"
PREFIX = "vehicle_sensor_subset_200ms"
RUN_DIR = PROJECT_ROOT / "experiments" / "runs" / "two_tower"

# Set to a small integer like 800 for quick iteration; use None for the full run.
MAX_TIME_STEPS = None

data = load_processed_two_tower_data(
    PROCESSED_DIR,
    prefix=PREFIX,
    utility_name="saved",
    max_time_steps=MAX_TIME_STEPS,
)

print("device:", "cuda" if torch.cuda.is_available() else "cpu")
print("context_dim:", data["C_by_time"].shape[1])
print("action_dim:", data["A_examples"].shape[1])
print("times:", len(data["C_by_time"]))
print("examples:", len(data["A_examples"]))
print("actions/time:", data["meta"]["num_actions_per_time"])

device: cuda
context_dim: 118
action_dim: 69
times: 7465
examples: 306065
actions/time: 41

In [5]:
# Compact sweep. Each epoch prints one diagnostics line per active run.
# Utility options supported by the training module:
#   saved, rational, clipped_linear, closest_binary, rank_discount

CONFIGS = [
    TrainConfig(
        run_name="saved_h64_e8",
        utility_name="saved",
        hidden=64,
        emb_dim=8,
        depth=2,
        dropout=0.05,
        combine_mode="mul_only",
        loss_name="mse",
        max_epochs=25,
        patience=8,
        batch_size=2048,
        lr=1e-3,
        weight_decay=1e-4,
        log_every=1,
    ),
    TrainConfig(
        run_name="clip_h64_e8",
        utility_name="clipped_linear",
        utility_kwargs={"utility_radius": 30.0},
        hidden=64,
        emb_dim=8,
        depth=2,
        dropout=0.05,
        combine_mode="mul_only",
        loss_name="mse",
        max_epochs=25,
        patience=8,
        batch_size=2048,
        lr=1e-3,
        weight_decay=1e-4,
        log_every=1,
    ),
    TrainConfig(
        run_name="binary_h64_e8",
        utility_name="closest_binary",
        hidden=64,
        emb_dim=8,
        depth=2,
        dropout=0.05,
        combine_mode="mul_only",
        loss_name="bce",
        max_epochs=25,
        patience=8,
        batch_size=2048,
        lr=1e-3,
        weight_decay=1e-4,
        log_every=1,
    ),
]

results = run_config_grid(
    PROCESSED_DIR,
    CONFIGS,
    prefix=PREFIX,
    max_time_steps=MAX_TIME_STEPS,
)

own_target_summary_df = summarize_results(results)
print("Own-target diagnostics only; use the common-objective table below to compare utilities.")
display(own_target_summary_df)

            saved_h64_e8 ep 001/025* loss=0.03131 val_rmse=0.1479 top1=0.186 top3=0.422 reg=0.0403 rank=6.04 9s
            saved_h64_e8 ep 002/025* loss=0.01700 val_rmse=0.1443 top1=0.172 top3=0.404 reg=0.0370 rank=5.81 17s
            saved_h64_e8 ep 003/025* loss=0.01355 val_rmse=0.1423 top1=0.227 top3=0.438 reg=0.0348 rank=5.65 26s
            saved_h64_e8 ep 004/025  loss=0.01120 val_rmse=0.1404 top1=0.246 top3=0.427 reg=0.0352 rank=5.79 36s
            saved_h64_e8 ep 005/025* loss=0.00962 val_rmse=0.1404 top1=0.268 top3=0.472 reg=0.0318 rank=5.39 45s
            saved_h64_e8 ep 006/025  loss=0.00834 val_rmse=0.1413 top1=0.269 top3=0.455 reg=0.0341 rank=5.72 54s
            saved_h64_e8 ep 007/025* loss=0.00747 val_rmse=0.1381 top1=0.280 top3=0.472 reg=0.0316 rank=5.47 64s
            saved_h64_e8 ep 008/025* loss=0.00677 val_rmse=0.1404 top1=0.302 top3=0.499 reg=0.0302 rank=5.28 73s
            saved_h64_e8 ep 009/025  loss=0.00627 val_rmse=0.1424 top1=0.305 top3=0.488 reg=0.0305 rank=5.36 81s
            saved_h64_e8 ep 010/025  loss=0.00581 val_rmse=0.1399 top1=0.298 top3=0.478 reg=0.0304 rank=5.33 90s
            saved_h64_e8 ep 011/025* loss=0.00541 val_rmse=0.1397 top1=0.297 top3=0.502 reg=0.0294 rank=5.20 99s
            saved_h64_e8 ep 012/025* loss=0.00503 val_rmse=0.1384 top1=0.307 top3=0.506 reg=0.0291 rank=5.14 108s
            saved_h64_e8 ep 013/025  loss=0.00475 val_rmse=0.1391 top1=0.315 top3=0.528 reg=0.0297 rank=5.12 117s
            saved_h64_e8 ep 014/025* loss=0.00446 val_rmse=0.1376 top1=0.322 top3=0.544 reg=0.0275 rank=4.92 125s
            saved_h64_e8 ep 015/025  loss=0.00426 val_rmse=0.1394 top1=0.282 top3=0.511 reg=0.0285 rank=5.10 134s
            saved_h64_e8 ep 016/025  loss=0.00404 val_rmse=0.1385 top1=0.302 top3=0.530 reg=0.0289 rank=5.10 143s
            saved_h64_e8 ep 017/025  loss=0.00389 val_rmse=0.1392 top1=0.297 top3=0.500 reg=0.0289 rank=5.16 152s
            saved_h64_e8 ep 018/025  loss=0.00374 val_rmse=0.1405 top1=0.302 top3=0.526 reg=0.0294 rank=5.12 160s
            saved_h64_e8 ep 019/025  loss=0.00357 val_rmse=0.1412 top1=0.293 top3=0.536 reg=0.0290 rank=5.12 169s
            saved_h64_e8 ep 020/025  loss=0.00347 val_rmse=0.1416 top1=0.318 top3=0.499 reg=0.0302 rank=5.30 178s
            saved_h64_e8 ep 021/025  loss=0.00336 val_rmse=0.1403 top1=0.303 top3=0.523 reg=0.0308 rank=5.25 186s
            saved_h64_e8 ep 022/025  loss=0.00324 val_rmse=0.1415 top1=0.304 top3=0.511 reg=0.0309 rank=5.31 195s
            saved_h64_e8 early stop at ep 022; best ep 014
             clip_h64_e8 ep 001/025* loss=0.05950 val_rmse=0.2164 top1=0.756 top3=0.765 reg=0.0353 rank=2.98 9s
             clip_h64_e8 ep 002/025* loss=0.03699 val_rmse=0.2204 top1=0.762 top3=0.772 reg=0.0318 rank=2.92 17s
             clip_h64_e8 ep 003/025* loss=0.02815 val_rmse=0.2200 top1=0.775 top3=0.782 reg=0.0285 rank=2.80 27s
             clip_h64_e8 ep 004/025* loss=0.02272 val_rmse=0.2167 top1=0.774 top3=0.784 reg=0.0275 rank=2.78 36s
             clip_h64_e8 ep 005/025* loss=0.01902 val_rmse=0.2149 top1=0.775 top3=0.785 reg=0.0261 rank=2.82 45s
             clip_h64_e8 ep 006/025  loss=0.01627 val_rmse=0.2189 top1=0.778 top3=0.789 reg=0.0265 rank=2.81 54s
             clip_h64_e8 ep 007/025* loss=0.01435 val_rmse=0.2127 top1=0.806 top3=0.814 reg=0.0215 rank=2.53 63s
             clip_h64_e8 ep 008/025* loss=0.01294 val_rmse=0.2118 top1=0.819 top3=0.829 reg=0.0210 rank=2.43 73s
             clip_h64_e8 ep 009/025  loss=0.01194 val_rmse=0.2163 top1=0.788 top3=0.798 reg=0.0258 rank=2.74 83s
             clip_h64_e8 ep 010/025  loss=0.01105 val_rmse=0.2167 top1=0.794 top3=0.802 reg=0.0249 rank=2.64 94s
             clip_h64_e8 ep 011/025  loss=0.01033 val_rmse=0.2140 top1=0.805 top3=0.815 reg=0.0238 rank=2.57 104s
             clip_h64_e8 ep 012/025  loss=0.00983 val_rmse=0.2137 top1=0.804 top3=0.814 reg=0.0249 rank=2.64 112s
             clip_h64_e8 ep 013/025  loss=0.00931 val_rmse=0.2163 top1=0.788 top3=0.796 reg=0.0283 rank=2.84 121s
             clip_h64_e8 ep 014/025  loss=0.00875 val_rmse=0.2131 top1=0.814 top3=0.825 reg=0.0232 rank=2.56 130s
             clip_h64_e8 ep 015/025  loss=0.00826 val_rmse=0.2128 top1=0.814 top3=0.825 reg=0.0240 rank=2.63 139s
             clip_h64_e8 ep 016/025  loss=0.00778 val_rmse=0.2176 top1=0.804 top3=0.817 reg=0.0263 rank=2.63 147s
             clip_h64_e8 early stop at ep 016; best ep 008
           binary_h64_e8 ep 001/025* loss=0.52346 val_rmse=0.3819 top1=0.898 top3=0.898 reg=0.1018 rank=2.63 9s
           binary_h64_e8 ep 002/025* loss=0.31655 val_rmse=0.3840 top1=0.924 top3=0.924 reg=0.0764 rank=2.22 18s
           binary_h64_e8 ep 003/025* loss=0.23505 val_rmse=0.3935 top1=0.926 top3=0.926 reg=0.0737 rank=2.18 26s
           binary_h64_e8 ep 004/025  loss=0.18750 val_rmse=0.4049 top1=0.917 top3=0.917 reg=0.0831 rank=2.33 35s
           binary_h64_e8 ep 005/025  loss=0.15603 val_rmse=0.4109 top1=0.914 top3=0.914 reg=0.0857 rank=2.37 45s
           binary_h64_e8 ep 006/025  loss=0.12891 val_rmse=0.4178 top1=0.909 top3=0.909 reg=0.0911 rank=2.46 55s
           binary_h64_e8 ep 007/025  loss=0.10644 val_rmse=0.4203 top1=0.908 top3=0.908 reg=0.0924 rank=2.48 63s
           binary_h64_e8 ep 008/025  loss=0.08921 val_rmse=0.4308 top1=0.892 top3=0.892 reg=0.1078 rank=2.73 72s
           binary_h64_e8 ep 009/025  loss=0.07297 val_rmse=0.4394 top1=0.889 top3=0.889 reg=0.1105 rank=2.77 81s
           binary_h64_e8 ep 010/025  loss=0.05882 val_rmse=0.4398 top1=0.880 top3=0.880 reg=0.1199 rank=2.92 91s
           binary_h64_e8 ep 011/025  loss=0.04537 val_rmse=0.4432 top1=0.875 top3=0.875 reg=0.1246 rank=2.99 102s
           binary_h64_e8 early stop at ep 011; best ep 003
Own-target diagnostics only; use the common-objective table below to compare utilities.

,run_name,utility,hidden,emb_dim,depth,dropout,combine,loss,best_epoch,train_rmse,...,val_avg_regret,val_avg_norm_regret,test_rmse,test_mae,test_r2,test_top1,test_top3,test_mean_rank,test_avg_regret,test_avg_norm_regret
0,clip_h64_e8,clipped_linear,64,8,2,0.05,mul_only,mse,8,0.097192,...,0.020967,0.045176,0.230155,0.154219,0.357555,0.750837,0.760884,3.485599,0.048644,0.094660
1,saved_h64_e8,saved,64,8,2,0.05,mul_only,mse,14,0.054120,...,0.027523,0.059756,0.138637,0.096998,0.514722,0.318151,0.496316,5.026792,0.032868,0.061710
2,binary_h64_e8,closest_binary,64,8,2,0.05,mul_only,bce,3,0.244501,...,0.073677,0.073677,0.405288,0.231275,0.309705,0.884796,0.884796,2.843269,0.115204,0.115204

In [6]:
# Compare every trained run on the same downstream objectives.
# top1: the model-selected subset is truly best for that objective.
# top3: the model-selected subset is within the true top 3 actions.
# mean_rank: the true-utility rank of the model-selected subset.

COMMON_OBJECTIVES = [
    {"name": "contains_closest", "utility_name": "closest_binary", "utility_kwargs": {}},
    {"name": "rank_discount", "utility_name": "rank_discount", "utility_kwargs": {}},
    {"name": "clipped_r30", "utility_name": "clipped_linear", "utility_kwargs": {"utility_radius": 30.0}},
    {"name": "saved_rational", "utility_name": "saved", "utility_kwargs": {}},
]

common_eval_df = compare_on_common_objectives(results, COMMON_OBJECTIVES)
display(common_eval_df)

test_policy_df = (
    common_eval_df[common_eval_df["split"].eq("test")]
    .sort_values(
        ["eval_objective", "top1", "top3", "mean_rank", "avg_norm_regret"],
        ascending=[True, False, False, True, True],
    )
    .reset_index(drop=True)
)
display(test_policy_df)

PRIMARY_OBJECTIVE = "saved_rational"
PRIMARY_SPLIT = "val"
primary_candidates = common_eval_df[
    common_eval_df["eval_objective"].eq(PRIMARY_OBJECTIVE)
    & common_eval_df["split"].eq(PRIMARY_SPLIT)
].copy()

best_row = primary_candidates.sort_values(
    ["top1", "top3", "mean_rank", "avg_norm_regret"],
    ascending=[False, False, True, True],
).iloc[0]
best_name = best_row["run_name"]
best_result = next(result for result in results if result["config"].run_name == best_name)

print("primary objective:", PRIMARY_OBJECTIVE)
print("best run:", best_name)
print("best epoch:", best_result["best_epoch"])
print("validation policy metrics:", best_row[["top1", "top3", "mean_rank", "avg_regret", "avg_norm_regret"]].to_dict())

display(
    common_eval_df[
        common_eval_df["run_name"].eq(best_name)
        & common_eval_df["split"].eq("test")
    ].sort_values("eval_objective")
)
display(best_result["history"].tail(8))

,run_name,train_utility,eval_objective,split,hidden,emb_dim,combine,top1,top3,mean_rank,avg_regret,avg_norm_regret
0,saved_h64_e8,saved,clipped_r30,test,64,8,mul_only,0.793704,0.802411,3.004689,0.039383,0.076319
1,clip_h64_e8,clipped_linear,clipped_r30,test,64,8,mul_only,0.750837,0.760884,3.485599,0.048644,0.094660
2,binary_h64_e8,closest_binary,clipped_r30,test,64,8,mul_only,0.724715,0.735432,3.830543,0.062842,0.111279
3,clip_h64_e8,clipped_linear,clipped_r30,val,64,8,mul_only,0.819156,0.828533,2.427997,0.020967,0.045176
4,saved_h64_e8,saved,clipped_r30,val,64,8,mul_only,0.808439,0.817147,2.515070,0.022956,0.051010
5,binary_h64_e8,closest_binary,clipped_r30,val,64,8,mul_only,0.771601,0.779638,3.123242,0.036830,0.074280
6,saved_h64_e8,saved,contains_closest,test,64,8,mul_only,0.920965,0.920965,2.264568,0.079035,0.079035
7,clip_h64_e8,clipped_linear,contains_closest,test,64,8,mul_only,0.886135,0.886135,2.821835,0.113865,0.113865
8,binary_h64_e8,closest_binary,contains_closest,test,64,8,mul_only,0.884796,0.884796,2.843269,0.115204,0.115204
9,clip_h64_e8,clipped_linear,contains_closest,val,64,8,mul_only,0.940388,0.940388,1.953784,0.059612,0.059612
10,saved_h64_e8,saved,contains_closest,val,64,8,mul_only,0.930342,0.930342,2.114534,0.069658,0.069658
11,binary_h64_e8,closest_binary,contains_closest,val,64,8,mul_only,0.926323,0.926323,2.178835,0.073677,0.073677
12,saved_h64_e8,saved,rank_discount,test,64,8,mul_only,0.920965,0.920965,2.519089,0.043313,0.051976
13,clip_h64_e8,clipped_linear,rank_discount,test,64,8,mul_only,0.886135,0.886135,3.222371,0.062715,0.075258
14,binary_h64_e8,closest_binary,rank_discount,test,64,8,mul_only,0.884796,0.884796,3.359678,0.065171,0.078205
15,clip_h64_e8,clipped_linear,rank_discount,val,64,8,mul_only,0.940388,0.940388,2.217013,0.033691,0.040429
16,saved_h64_e8,saved,rank_discount,val,64,8,mul_only,0.930342,0.930342,2.367046,0.038625,0.046350
17,binary_h64_e8,closest_binary,rank_discount,val,64,8,mul_only,0.926323,0.926323,2.735432,0.044586,0.053503
18,saved_h64_e8,saved,saved_rational,test,64,8,mul_only,0.318151,0.496316,5.026792,0.032868,0.061710
19,clip_h64_e8,clipped_linear,saved_rational,test,64,8,mul_only,0.115874,0.300067,7.737441,0.055021,0.109720
20,binary_h64_e8,closest_binary,saved_rational,test,64,8,mul_only,0.098459,0.267247,9.128600,0.071807,0.140456
21,saved_h64_e8,saved,saved_rational,val,64,8,mul_only,0.322170,0.543871,4.920295,0.027523,0.059756
22,clip_h64_e8,clipped_linear,saved_rational,val,64,8,mul_only,0.228399,0.399866,6.447421,0.037889,0.078841
23,binary_h64_e8,closest_binary,saved_rational,val,64,8,mul_only,0.186872,0.324849,7.937040,0.053330,0.110795

,run_name,train_utility,eval_objective,split,hidden,emb_dim,combine,top1,top3,mean_rank,avg_regret,avg_norm_regret
0,saved_h64_e8,saved,clipped_r30,test,64,8,mul_only,0.793704,0.802411,3.004689,0.039383,0.076319
1,clip_h64_e8,clipped_linear,clipped_r30,test,64,8,mul_only,0.750837,0.760884,3.485599,0.048644,0.094660
2,binary_h64_e8,closest_binary,clipped_r30,test,64,8,mul_only,0.724715,0.735432,3.830543,0.062842,0.111279
3,saved_h64_e8,saved,contains_closest,test,64,8,mul_only,0.920965,0.920965,2.264568,0.079035,0.079035
4,clip_h64_e8,clipped_linear,contains_closest,test,64,8,mul_only,0.886135,0.886135,2.821835,0.113865,0.113865
5,binary_h64_e8,closest_binary,contains_closest,test,64,8,mul_only,0.884796,0.884796,2.843269,0.115204,0.115204
6,saved_h64_e8,saved,rank_discount,test,64,8,mul_only,0.920965,0.920965,2.519089,0.043313,0.051976
7,clip_h64_e8,clipped_linear,rank_discount,test,64,8,mul_only,0.886135,0.886135,3.222371,0.062715,0.075258
8,binary_h64_e8,closest_binary,rank_discount,test,64,8,mul_only,0.884796,0.884796,3.359678,0.065171,0.078205
9,saved_h64_e8,saved,saved_rational,test,64,8,mul_only,0.318151,0.496316,5.026792,0.032868,0.061710
10,clip_h64_e8,clipped_linear,saved_rational,test,64,8,mul_only,0.115874,0.300067,7.737441,0.055021,0.109720
11,binary_h64_e8,closest_binary,saved_rational,test,64,8,mul_only,0.098459,0.267247,9.128600,0.071807,0.140456

primary objective: contains_closest
best run: clip_h64_e8
best epoch: 8
validation policy metrics: {'top1': 0.9403884795713329, 'top3': 0.9403884795713329, 'mean_rank': 1.9537843268586739, 'avg_regret': 0.05961152042866711, 'avg_norm_regret': 0.05961152042866711}

,run_name,train_utility,eval_objective,split,hidden,emb_dim,combine,top1,top3,mean_rank,avg_regret,avg_norm_regret
1,clip_h64_e8,clipped_linear,clipped_r30,test,64,8,mul_only,0.750837,0.760884,3.485599,0.048644,0.094660
7,clip_h64_e8,clipped_linear,contains_closest,test,64,8,mul_only,0.886135,0.886135,2.821835,0.113865,0.113865
13,clip_h64_e8,clipped_linear,rank_discount,test,64,8,mul_only,0.886135,0.886135,3.222371,0.062715,0.075258
19,clip_h64_e8,clipped_linear,saved_rational,test,64,8,mul_only,0.115874,0.300067,7.737441,0.055021,0.109720

,epoch,train_loss,val_rmse,val_mae,val_r2,val_top1,val_top3,val_mean_rank,val_avg_regret,val_avg_norm_regret
8,9,0.011936,0.216345,0.140074,0.393883,0.788346,0.797723,2.737441,0.025847,0.055426
9,10,0.011055,0.216693,0.140147,0.391932,0.793704,0.802411,2.642331,0.024857,0.053172
10,11,0.010327,0.213980,0.138108,0.407059,0.805090,0.815137,2.573342,0.023774,0.050440
11,12,0.009830,0.213730,0.136703,0.408447,0.804421,0.813798,2.643001,0.024942,0.053741
12,13,0.009310,0.216306,0.139520,0.394101,0.787676,0.796383,2.839920,0.028314,0.062765
13,14,0.008746,0.213109,0.137055,0.411880,0.814468,0.824514,2.558607,0.023246,0.053458
14,15,0.008262,0.212849,0.137305,0.413313,0.814468,0.825184,2.633624,0.023977,0.055050
15,16,0.007783,0.217599,0.139071,0.386835,0.804421,0.817147,2.634963,0.026312,0.056491

In [8]:
# Saved-utility width sweep. Depth stays at the TrainConfig default: depth=2.

SAVED_OBJECTIVES = [
    {"name": "saved_rational", "utility_name": "saved", "utility_kwargs": {}},
    {"name": "contains_closest", "utility_name": "closest_binary", "utility_kwargs": {}},
]

HIDDEN_SWEEP_CONFIGS = [
    TrainConfig(
        run_name=f"saved_h{hidden}_d2",
        utility_name="saved",
        hidden=hidden,
        emb_dim=8,
        depth=2,
        dropout=0.05,
        combine_mode="mul_only",
        loss_name="mse",
        max_epochs=50,
        patience=16,
        batch_size=2048,
        lr=1e-3,
        weight_decay=1e-4,
        log_every=1,
    )
    for hidden in [128, 256, 512, 1024]
]

hidden_sweep_results = run_config_grid(
    PROCESSED_DIR,
    HIDDEN_SWEEP_CONFIGS,
    prefix=PREFIX,
    max_time_steps=MAX_TIME_STEPS,
)

hidden_sweep_own_df = summarize_results(hidden_sweep_results)
hidden_sweep_eval_df = compare_on_common_objectives(hidden_sweep_results, SAVED_OBJECTIVES)
hidden_sweep_test_df = (
    hidden_sweep_eval_df[hidden_sweep_eval_df["split"].eq("test")]
    .sort_values(
        ["eval_objective", "top1", "top3", "mean_rank", "avg_norm_regret"],
        ascending=[True, False, False, True, True],
    )
    .reset_index(drop=True)
)

display(hidden_sweep_own_df)
display(hidden_sweep_test_df)

           saved_h128_d2 ep 001/050* loss=0.02948 val_rmse=0.1530 top1=0.143 top3=0.296 reg=0.0484 rank=7.14 10s
           saved_h128_d2 ep 002/050* loss=0.01542 val_rmse=0.1530 top1=0.176 top3=0.354 reg=0.0435 rank=6.51 19s
           saved_h128_d2 ep 003/050* loss=0.01186 val_rmse=0.1470 top1=0.211 top3=0.431 reg=0.0391 rank=6.09 28s
           saved_h128_d2 ep 004/050  loss=0.00960 val_rmse=0.1460 top1=0.203 top3=0.404 reg=0.0412 rank=6.41 37s
           saved_h128_d2 ep 005/050  loss=0.00800 val_rmse=0.1426 top1=0.213 top3=0.417 reg=0.0406 rank=6.39 46s
           saved_h128_d2 ep 006/050  loss=0.00683 val_rmse=0.1421 top1=0.232 top3=0.461 reg=0.0397 rank=6.21 55s
           saved_h128_d2 ep 007/050  loss=0.00587 val_rmse=0.1449 top1=0.258 top3=0.480 reg=0.0396 rank=6.10 65s
           saved_h128_d2 ep 008/050  loss=0.00517 val_rmse=0.1463 top1=0.283 top3=0.520 reg=0.0397 rank=5.97 75s
           saved_h128_d2 ep 009/050  loss=0.00464 val_rmse=0.1444 top1=0.251 top3=0.479 reg=0.0392 rank=6.05 85s
           saved_h128_d2 ep 010/050  loss=0.00420 val_rmse=0.1442 top1=0.265 top3=0.480 reg=0.0406 rank=6.19 94s
           saved_h128_d2 ep 011/050  loss=0.00383 val_rmse=0.1444 top1=0.266 top3=0.505 reg=0.0393 rank=6.02 103s
           saved_h128_d2 ep 012/050  loss=0.00355 val_rmse=0.1440 top1=0.261 top3=0.486 reg=0.0409 rank=6.21 112s
           saved_h128_d2 ep 013/050* loss=0.00328 val_rmse=0.1441 top1=0.242 top3=0.460 reg=0.0375 rank=6.02 121s
           saved_h128_d2 ep 014/050  loss=0.00305 val_rmse=0.1461 top1=0.243 top3=0.478 reg=0.0390 rank=6.12 129s
           saved_h128_d2 ep 015/050* loss=0.00285 val_rmse=0.1442 top1=0.267 top3=0.496 reg=0.0352 rank=5.73 138s
           saved_h128_d2 ep 016/050* loss=0.00269 val_rmse=0.1441 top1=0.273 top3=0.506 reg=0.0348 rank=5.63 147s
           saved_h128_d2 ep 017/050  loss=0.00252 val_rmse=0.1459 top1=0.267 top3=0.501 reg=0.0350 rank=5.71 156s
           saved_h128_d2 ep 018/050* loss=0.00238 val_rmse=0.1469 top1=0.270 top3=0.487 reg=0.0329 rank=5.54 168s
           saved_h128_d2 ep 019/050  loss=0.00228 val_rmse=0.1482 top1=0.254 top3=0.492 reg=0.0339 rank=5.64 177s
           saved_h128_d2 ep 020/050* loss=0.00217 val_rmse=0.1448 top1=0.246 top3=0.476 reg=0.0328 rank=5.58 187s
           saved_h128_d2 ep 021/050  loss=0.00208 val_rmse=0.1451 top1=0.249 top3=0.501 reg=0.0330 rank=5.51 197s
           saved_h128_d2 ep 022/050  loss=0.00198 val_rmse=0.1446 top1=0.267 top3=0.503 reg=0.0345 rank=5.66 209s
           saved_h128_d2 ep 023/050* loss=0.00189 val_rmse=0.1452 top1=0.294 top3=0.510 reg=0.0319 rank=5.41 219s
           saved_h128_d2 ep 024/050  loss=0.00183 val_rmse=0.1476 top1=0.255 top3=0.502 reg=0.0339 rank=5.61 229s
           saved_h128_d2 ep 025/050  loss=0.00176 val_rmse=0.1475 top1=0.243 top3=0.484 reg=0.0361 rank=5.85 239s
           saved_h128_d2 ep 026/050  loss=0.00170 val_rmse=0.1506 top1=0.282 top3=0.505 reg=0.0356 rank=5.73 249s
           saved_h128_d2 ep 027/050  loss=0.00166 val_rmse=0.1488 top1=0.285 top3=0.498 reg=0.0338 rank=5.57 261s
           saved_h128_d2 ep 028/050  loss=0.00162 val_rmse=0.1471 top1=0.267 top3=0.513 reg=0.0335 rank=5.52 272s
           saved_h128_d2 ep 029/050  loss=0.00155 val_rmse=0.1478 top1=0.277 top3=0.512 reg=0.0322 rank=5.41 281s
           saved_h128_d2 ep 030/050  loss=0.00152 val_rmse=0.1496 top1=0.255 top3=0.494 reg=0.0365 rank=5.87 292s
           saved_h128_d2 ep 031/050  loss=0.00148 val_rmse=0.1519 top1=0.311 top3=0.509 reg=0.0349 rank=5.63 305s
           saved_h128_d2 ep 032/050  loss=0.00144 val_rmse=0.1488 top1=0.309 top3=0.537 reg=0.0338 rank=5.50 314s
           saved_h128_d2 ep 033/050  loss=0.00141 val_rmse=0.1486 top1=0.269 top3=0.530 reg=0.0346 rank=5.56 324s
           saved_h128_d2 ep 034/050  loss=0.00137 val_rmse=0.1498 top1=0.301 top3=0.518 reg=0.0361 rank=5.67 333s
           saved_h128_d2 ep 035/050  loss=0.00136 val_rmse=0.1500 top1=0.242 top3=0.495 reg=0.0367 rank=5.94 344s
           saved_h128_d2 ep 036/050  loss=0.00131 val_rmse=0.1490 top1=0.243 top3=0.508 reg=0.0358 rank=5.77 354s
           saved_h128_d2 ep 037/050  loss=0.00129 val_rmse=0.1484 top1=0.269 top3=0.502 reg=0.0354 rank=5.70 365s
           saved_h128_d2 ep 038/050  loss=0.00125 val_rmse=0.1499 top1=0.288 top3=0.515 reg=0.0345 rank=5.62 374s
           saved_h128_d2 ep 039/050  loss=0.00124 val_rmse=0.1493 top1=0.297 top3=0.500 reg=0.0354 rank=5.74 384s
           saved_h128_d2 early stop at ep 039; best ep 023
           saved_h256_d2 ep 001/050* loss=0.02895 val_rmse=0.1484 top1=0.139 top3=0.374 reg=0.0413 rank=6.41 11s
           saved_h256_d2 ep 002/050* loss=0.01362 val_rmse=0.1478 top1=0.201 top3=0.419 reg=0.0395 rank=6.16 22s
           saved_h256_d2 ep 003/050* loss=0.00981 val_rmse=0.1497 top1=0.195 top3=0.438 reg=0.0364 rank=5.87 32s
           saved_h256_d2 ep 004/050  loss=0.00759 val_rmse=0.1469 top1=0.216 top3=0.426 reg=0.0378 rank=5.94 43s
           saved_h256_d2 ep 005/050  loss=0.00610 val_rmse=0.1501 top1=0.240 top3=0.455 reg=0.0371 rank=5.90 54s
           saved_h256_d2 ep 006/050  loss=0.00511 val_rmse=0.1511 top1=0.226 top3=0.433 reg=0.0396 rank=6.12 65s
           saved_h256_d2 ep 007/050  loss=0.00441 val_rmse=0.1488 top1=0.226 top3=0.435 reg=0.0400 rank=6.13 76s
           saved_h256_d2 ep 008/050  loss=0.00389 val_rmse=0.1485 top1=0.236 top3=0.447 reg=0.0399 rank=6.14 87s
           saved_h256_d2 ep 009/050  loss=0.00348 val_rmse=0.1489 top1=0.210 top3=0.406 reg=0.0418 rank=6.46 97s
           saved_h256_d2 ep 010/050  loss=0.00316 val_rmse=0.1486 top1=0.243 top3=0.468 reg=0.0397 rank=6.07 107s
           saved_h256_d2 ep 011/050  loss=0.00290 val_rmse=0.1467 top1=0.269 top3=0.483 reg=0.0392 rank=5.97 119s
           saved_h256_d2 ep 012/050  loss=0.00268 val_rmse=0.1489 top1=0.264 top3=0.476 reg=0.0378 rank=5.98 129s
           saved_h256_d2 ep 013/050  loss=0.00248 val_rmse=0.1489 top1=0.249 top3=0.445 reg=0.0400 rank=6.17 139s
           saved_h256_d2 ep 014/050  loss=0.00228 val_rmse=0.1495 top1=0.282 top3=0.500 reg=0.0382 rank=5.92 150s
           saved_h256_d2 ep 015/050  loss=0.00210 val_rmse=0.1473 top1=0.275 top3=0.477 reg=0.0377 rank=5.90 161s
           saved_h256_d2 ep 016/050  loss=0.00197 val_rmse=0.1476 top1=0.253 top3=0.469 reg=0.0383 rank=6.00 171s
           saved_h256_d2 ep 017/050  loss=0.00182 val_rmse=0.1481 top1=0.275 top3=0.496 reg=0.0396 rank=6.01 183s
           saved_h256_d2 ep 018/050  loss=0.00171 val_rmse=0.1475 top1=0.294 top3=0.492 reg=0.0385 rank=5.87 194s
           saved_h256_d2 ep 019/050  loss=0.00160 val_rmse=0.1480 top1=0.279 top3=0.496 reg=0.0365 rank=5.87 204s
           saved_h256_d2 early stop at ep 019; best ep 003
           saved_h512_d2 ep 001/050* loss=0.02847 val_rmse=0.1472 top1=0.180 top3=0.403 reg=0.0398 rank=5.98 12s
           saved_h512_d2 ep 002/050* loss=0.01253 val_rmse=0.1489 top1=0.221 top3=0.417 reg=0.0341 rank=5.57 24s
           saved_h512_d2 ep 003/050  loss=0.00916 val_rmse=0.1513 top1=0.192 top3=0.411 reg=0.0398 rank=6.10 36s
           saved_h512_d2 ep 004/050  loss=0.00712 val_rmse=0.1495 top1=0.216 top3=0.415 reg=0.0363 rank=5.95 49s
           saved_h512_d2 ep 005/050* loss=0.00575 val_rmse=0.1485 top1=0.243 top3=0.438 reg=0.0327 rank=5.59 62s
           saved_h512_d2 ep 006/050  loss=0.00465 val_rmse=0.1497 top1=0.230 top3=0.420 reg=0.0349 rank=5.82 74s
           saved_h512_d2 ep 007/050  loss=0.00396 val_rmse=0.1495 top1=0.237 top3=0.431 reg=0.0363 rank=5.99 86s
           saved_h512_d2 ep 008/050  loss=0.00341 val_rmse=0.1476 top1=0.244 top3=0.429 reg=0.0343 rank=5.82 98s
           saved_h512_d2 ep 009/050  loss=0.00300 val_rmse=0.1515 top1=0.275 top3=0.450 reg=0.0342 rank=5.79 110s
           saved_h512_d2 ep 010/050  loss=0.00262 val_rmse=0.1463 top1=0.275 top3=0.452 reg=0.0340 rank=5.75 123s
           saved_h512_d2 ep 011/050  loss=0.00236 val_rmse=0.1469 top1=0.277 top3=0.480 reg=0.0358 rank=5.75 136s
           saved_h512_d2 ep 012/050  loss=0.00209 val_rmse=0.1487 top1=0.279 top3=0.496 reg=0.0339 rank=5.55 149s
           saved_h512_d2 ep 013/050  loss=0.00188 val_rmse=0.1477 top1=0.267 top3=0.496 reg=0.0333 rank=5.47 160s
           saved_h512_d2 ep 014/050  loss=0.00170 val_rmse=0.1490 top1=0.285 top3=0.508 reg=0.0333 rank=5.47 171s
           saved_h512_d2 ep 015/050  loss=0.00154 val_rmse=0.1478 top1=0.299 top3=0.518 reg=0.0337 rank=5.55 182s
           saved_h512_d2 ep 016/050  loss=0.00143 val_rmse=0.1481 top1=0.299 top3=0.507 reg=0.0348 rank=5.63 192s
           saved_h512_d2 ep 017/050  loss=0.00130 val_rmse=0.1492 top1=0.273 top3=0.512 reg=0.0370 rank=5.78 203s
           saved_h512_d2 ep 018/050  loss=0.00124 val_rmse=0.1500 top1=0.342 top3=0.538 reg=0.0370 rank=5.79 213s
           saved_h512_d2 ep 019/050  loss=0.00116 val_rmse=0.1509 top1=0.301 top3=0.526 reg=0.0368 rank=5.78 224s
           saved_h512_d2 ep 020/050  loss=0.00108 val_rmse=0.1492 top1=0.330 top3=0.530 reg=0.0359 rank=5.66 235s
           saved_h512_d2 ep 021/050  loss=0.00104 val_rmse=0.1451 top1=0.348 top3=0.548 reg=0.0347 rank=5.52 246s
           saved_h512_d2 early stop at ep 021; best ep 005
          saved_h1024_d2 ep 001/050* loss=0.02397 val_rmse=0.1469 top1=0.137 top3=0.387 reg=0.0380 rank=5.97 11s
          saved_h1024_d2 ep 002/050* loss=0.01017 val_rmse=0.1455 top1=0.208 top3=0.452 reg=0.0314 rank=5.44 21s
          saved_h1024_d2 ep 003/050* loss=0.00684 val_rmse=0.1425 top1=0.222 top3=0.451 reg=0.0301 rank=5.33 32s
          saved_h1024_d2 ep 004/050  loss=0.00515 val_rmse=0.1445 top1=0.224 top3=0.472 reg=0.0316 rank=5.42 43s
          saved_h1024_d2 ep 005/050  loss=0.00412 val_rmse=0.1439 top1=0.218 top3=0.488 reg=0.0332 rank=5.59 54s
          saved_h1024_d2 ep 006/050  loss=0.00336 val_rmse=0.1456 top1=0.196 top3=0.439 reg=0.0330 rank=5.67 65s
          saved_h1024_d2 ep 007/050  loss=0.00278 val_rmse=0.1454 top1=0.214 top3=0.439 reg=0.0336 rank=5.71 76s
          saved_h1024_d2 ep 008/050  loss=0.00236 val_rmse=0.1415 top1=0.226 top3=0.448 reg=0.0327 rank=5.55 87s
          saved_h1024_d2 ep 009/050* loss=0.00199 val_rmse=0.1433 top1=0.240 top3=0.483 reg=0.0295 rank=5.21 98s
          saved_h1024_d2 ep 010/050  loss=0.00171 val_rmse=0.1407 top1=0.264 top3=0.482 reg=0.0315 rank=5.41 108s
          saved_h1024_d2 ep 011/050  loss=0.00148 val_rmse=0.1435 top1=0.274 top3=0.495 reg=0.0327 rank=5.47 119s
          saved_h1024_d2 ep 012/050  loss=0.00131 val_rmse=0.1429 top1=0.255 top3=0.494 reg=0.0330 rank=5.41 129s
          saved_h1024_d2 ep 013/050* loss=0.00121 val_rmse=0.1406 top1=0.320 top3=0.512 reg=0.0289 rank=5.02 139s
          saved_h1024_d2 ep 014/050  loss=0.00109 val_rmse=0.1444 top1=0.304 top3=0.512 reg=0.0316 rank=5.34 150s
          saved_h1024_d2 ep 015/050  loss=0.00101 val_rmse=0.1449 top1=0.318 top3=0.515 reg=0.0307 rank=5.20 160s
          saved_h1024_d2 ep 016/050* loss=0.00093 val_rmse=0.1430 top1=0.319 top3=0.553 reg=0.0286 rank=4.98 171s
          saved_h1024_d2 ep 017/050* loss=0.00089 val_rmse=0.1417 top1=0.321 top3=0.551 reg=0.0286 rank=4.90 182s
          saved_h1024_d2 ep 018/050* loss=0.00083 val_rmse=0.1411 top1=0.311 top3=0.551 reg=0.0280 rank=4.94 192s
          saved_h1024_d2 ep 019/050* loss=0.00079 val_rmse=0.1430 top1=0.366 top3=0.565 reg=0.0264 rank=4.69 202s
          saved_h1024_d2 ep 020/050  loss=0.00074 val_rmse=0.1448 top1=0.309 top3=0.518 reg=0.0303 rank=5.15 213s
          saved_h1024_d2 ep 021/050  loss=0.00074 val_rmse=0.1439 top1=0.378 top3=0.553 reg=0.0275 rank=4.75 224s
          saved_h1024_d2 ep 022/050  loss=0.00072 val_rmse=0.1463 top1=0.346 top3=0.555 reg=0.0295 rank=4.97 235s
          saved_h1024_d2 ep 023/050  loss=0.00069 val_rmse=0.1445 top1=0.308 top3=0.537 reg=0.0293 rank=5.02 245s
          saved_h1024_d2 ep 024/050  loss=0.00062 val_rmse=0.1458 top1=0.368 top3=0.559 reg=0.0281 rank=4.85 256s
          saved_h1024_d2 ep 025/050  loss=0.00064 val_rmse=0.1479 top1=0.316 top3=0.546 reg=0.0311 rank=5.19 268s
          saved_h1024_d2 ep 026/050  loss=0.00060 val_rmse=0.1470 top1=0.356 top3=0.564 reg=0.0296 rank=4.98 278s
          saved_h1024_d2 ep 027/050  loss=0.00058 val_rmse=0.1461 top1=0.344 top3=0.553 reg=0.0286 rank=4.93 289s
          saved_h1024_d2 ep 028/050  loss=0.00064 val_rmse=0.1459 top1=0.344 top3=0.524 reg=0.0300 rank=5.11 300s
          saved_h1024_d2 ep 029/050  loss=0.00054 val_rmse=0.1468 top1=0.352 top3=0.545 reg=0.0309 rank=5.12 311s
          saved_h1024_d2 ep 030/050  loss=0.00053 val_rmse=0.1471 top1=0.369 top3=0.563 reg=0.0280 rank=4.87 322s
          saved_h1024_d2 ep 031/050  loss=0.00053 val_rmse=0.1462 top1=0.362 top3=0.537 reg=0.0299 rank=5.03 335s
          saved_h1024_d2 ep 032/050  loss=0.00050 val_rmse=0.1455 top1=0.363 top3=0.558 reg=0.0278 rank=4.86 347s
          saved_h1024_d2 ep 033/050  loss=0.00055 val_rmse=0.1451 top1=0.372 top3=0.561 reg=0.0276 rank=4.82 358s
          saved_h1024_d2 ep 034/050  loss=0.00050 val_rmse=0.1451 top1=0.362 top3=0.556 reg=0.0295 rank=4.99 370s
          saved_h1024_d2 ep 035/050  loss=0.00048 val_rmse=0.1459 top1=0.369 top3=0.543 reg=0.0294 rank=4.93 380s
          saved_h1024_d2 early stop at ep 035; best ep 019

,run_name,utility,hidden,emb_dim,depth,dropout,combine,loss,best_epoch,train_rmse,...,val_avg_regret,val_avg_norm_regret,test_rmse,test_mae,test_r2,test_top1,test_top3,test_mean_rank,test_avg_regret,test_avg_norm_regret
0,saved_h1024_d2,saved,1024,8,2,0.05,mul_only,mse,19,0.018852,...,0.026392,0.056875,0.136741,0.097498,0.527903,0.346283,0.550569,5.058272,0.037365,0.068837
1,saved_h128_d2,saved,128,8,2,0.05,mul_only,mse,23,0.030477,...,0.031929,0.067503,0.145943,0.104194,0.462229,0.249833,0.472204,5.634963,0.038814,0.075557
2,saved_h512_d2,saved,512,8,2,0.05,mul_only,mse,5,0.058980,...,0.032708,0.069746,0.136276,0.099437,0.531108,0.213664,0.423309,5.402545,0.033447,0.065294
3,saved_h256_d2,saved,256,8,2,0.05,mul_only,mse,3,0.081391,...,0.036389,0.076080,0.141017,0.102714,0.497920,0.172806,0.381782,5.914936,0.037923,0.071975

,run_name,train_utility,eval_objective,split,hidden,emb_dim,combine,top1,top3,mean_rank,avg_regret,avg_norm_regret
0,saved_h512_d2,saved,contains_closest,test,512,8,mul_only,0.919625,0.919625,2.286001,0.080375,0.080375
1,saved_h256_d2,saved,contains_closest,test,256,8,mul_only,0.914267,0.914267,2.371735,0.085733,0.085733
2,saved_h128_d2,saved,contains_closest,test,128,8,mul_only,0.899531,0.899531,2.607502,0.100469,0.100469
3,saved_h1024_d2,saved,contains_closest,test,1024,8,mul_only,0.890824,0.890824,2.746818,0.109176,0.109176
4,saved_h1024_d2,saved,saved_rational,test,1024,8,mul_only,0.346283,0.550569,5.058272,0.037365,0.068837
5,saved_h128_d2,saved,saved_rational,test,128,8,mul_only,0.249833,0.472204,5.634963,0.038814,0.075557
6,saved_h512_d2,saved,saved_rational,test,512,8,mul_only,0.213664,0.423309,5.402545,0.033447,0.065294
7,saved_h256_d2,saved,saved_rational,test,256,8,mul_only,0.172806,0.381782,5.914936,0.037923,0.071975

In [9]:
print(next(results[0]["model"].parameters()).device)
print(torch.cuda.memory_allocated() / 1e9)
print(torch.cuda.memory_reserved() / 1e9)

cuda:0
0.02486272
0.121634816

In [10]:
# Saved-utility depth sweep. Hidden width stays at the TrainConfig default: hidden=64.

DEPTH_SWEEP_CONFIGS = [
    TrainConfig(
        run_name=f"saved_h64_d{depth}",
        utility_name="saved",
        hidden=64,
        emb_dim=8,
        depth=depth,
        dropout=0.05,
        combine_mode="mul_only",
        loss_name="mse",
        max_epochs=50,
        patience=16,
        batch_size=16384,
        lr=1e-3,
        weight_decay=1e-4,
        log_every=1,
    )
    for depth in [3, 4, 5, 6]
]

depth_sweep_results = run_config_grid(
    PROCESSED_DIR,
    DEPTH_SWEEP_CONFIGS,
    prefix=PREFIX,
    max_time_steps=MAX_TIME_STEPS,
)

depth_sweep_own_df = summarize_results(depth_sweep_results)
depth_sweep_eval_df = compare_on_common_objectives(depth_sweep_results, SAVED_OBJECTIVES)
depth_sweep_test_df = (
    depth_sweep_eval_df[depth_sweep_eval_df["split"].eq("test")]
    .sort_values(
        ["eval_objective", "top1", "top3", "mean_rank", "avg_norm_regret"],
        ascending=[True, False, False, True, True],
    )
    .reset_index(drop=True)
)

display(depth_sweep_own_df)
display(depth_sweep_test_df)

            saved_h64_d3 ep 001/050* loss=0.07259 val_rmse=0.1725 top1=0.064 top3=0.206 reg=0.0947 rank=10.37 8s
            saved_h64_d3 ep 002/050* loss=0.03431 val_rmse=0.1665 top1=0.117 top3=0.254 reg=0.0776 rank=8.99 15s
            saved_h64_d3 ep 003/050* loss=0.02903 val_rmse=0.1617 top1=0.174 top3=0.332 reg=0.0616 rank=7.70 22s
            saved_h64_d3 ep 004/050* loss=0.02599 val_rmse=0.1564 top1=0.194 top3=0.382 reg=0.0531 rank=7.11 29s
            saved_h64_d3 ep 005/050* loss=0.02373 val_rmse=0.1543 top1=0.175 top3=0.380 reg=0.0501 rank=7.00 36s
            saved_h64_d3 ep 006/050  loss=0.02187 val_rmse=0.1545 top1=0.150 top3=0.376 reg=0.0508 rank=7.15 44s
            saved_h64_d3 ep 007/050  loss=0.02030 val_rmse=0.1519 top1=0.154 top3=0.391 reg=0.0505 rank=7.04 51s
            saved_h64_d3 ep 008/050* loss=0.01887 val_rmse=0.1509 top1=0.159 top3=0.396 reg=0.0476 rank=6.93 58s
            saved_h64_d3 ep 009/050* loss=0.01770 val_rmse=0.1501 top1=0.151 top3=0.393 reg=0.0472 rank=6.91 66s
            saved_h64_d3 ep 010/050* loss=0.01664 val_rmse=0.1488 top1=0.157 top3=0.392 reg=0.0469 rank=6.92 73s
            saved_h64_d3 ep 011/050* loss=0.01574 val_rmse=0.1487 top1=0.166 top3=0.406 reg=0.0458 rank=6.80 81s
            saved_h64_d3 ep 012/050* loss=0.01491 val_rmse=0.1463 top1=0.166 top3=0.412 reg=0.0431 rank=6.60 89s
            saved_h64_d3 ep 013/050  loss=0.01421 val_rmse=0.1473 top1=0.167 top3=0.409 reg=0.0440 rank=6.67 97s
            saved_h64_d3 ep 014/050  loss=0.01366 val_rmse=0.1473 top1=0.167 top3=0.399 reg=0.0454 rank=6.83 105s
            saved_h64_d3 ep 015/050* loss=0.01311 val_rmse=0.1466 top1=0.171 top3=0.403 reg=0.0430 rank=6.60 112s
            saved_h64_d3 ep 016/050  loss=0.01259 val_rmse=0.1466 top1=0.173 top3=0.411 reg=0.0443 rank=6.72 119s
            saved_h64_d3 ep 017/050* loss=0.01214 val_rmse=0.1443 top1=0.185 top3=0.426 reg=0.0420 rank=6.43 126s
            saved_h64_d3 ep 018/050* loss=0.01161 val_rmse=0.1444 top1=0.185 top3=0.422 reg=0.0413 rank=6.38 134s
            saved_h64_d3 ep 019/050* loss=0.01120 val_rmse=0.1439 top1=0.178 top3=0.418 reg=0.0408 rank=6.42 141s
            saved_h64_d3 ep 020/050* loss=0.01081 val_rmse=0.1441 top1=0.180 top3=0.419 reg=0.0402 rank=6.36 148s
            saved_h64_d3 ep 021/050* loss=0.01048 val_rmse=0.1441 top1=0.184 top3=0.413 reg=0.0397 rank=6.33 155s
            saved_h64_d3 ep 022/050  loss=0.01012 val_rmse=0.1445 top1=0.180 top3=0.413 reg=0.0399 rank=6.35 162s
            saved_h64_d3 ep 023/050  loss=0.00979 val_rmse=0.1448 top1=0.175 top3=0.409 reg=0.0404 rank=6.37 170s
            saved_h64_d3 ep 024/050* loss=0.00942 val_rmse=0.1440 top1=0.175 top3=0.403 reg=0.0392 rank=6.31 177s
            saved_h64_d3 ep 025/050* loss=0.00907 val_rmse=0.1442 top1=0.175 top3=0.407 reg=0.0390 rank=6.32 184s
            saved_h64_d3 ep 026/050* loss=0.00885 val_rmse=0.1441 top1=0.169 top3=0.397 reg=0.0388 rank=6.34 191s
            saved_h64_d3 ep 027/050* loss=0.00860 val_rmse=0.1433 top1=0.173 top3=0.410 reg=0.0372 rank=6.20 198s
            saved_h64_d3 ep 028/050  loss=0.00835 val_rmse=0.1424 top1=0.175 top3=0.409 reg=0.0375 rank=6.23 206s
            saved_h64_d3 ep 029/050  loss=0.00808 val_rmse=0.1445 top1=0.177 top3=0.397 reg=0.0388 rank=6.33 213s
            saved_h64_d3 ep 030/050  loss=0.00790 val_rmse=0.1441 top1=0.186 top3=0.410 reg=0.0381 rank=6.26 220s
            saved_h64_d3 ep 031/050  loss=0.00770 val_rmse=0.1436 top1=0.184 top3=0.413 reg=0.0379 rank=6.29 227s
            saved_h64_d3 ep 032/050  loss=0.00749 val_rmse=0.1441 top1=0.196 top3=0.426 reg=0.0379 rank=6.21 234s
            saved_h64_d3 ep 033/050  loss=0.00734 val_rmse=0.1428 top1=0.187 top3=0.407 reg=0.0376 rank=6.26 241s
            saved_h64_d3 ep 034/050* loss=0.00711 val_rmse=0.1431 top1=0.188 top3=0.411 reg=0.0368 rank=6.23 248s
            saved_h64_d3 ep 035/050* loss=0.00696 val_rmse=0.1430 top1=0.196 top3=0.418 reg=0.0365 rank=6.16 256s
            saved_h64_d3 ep 036/050  loss=0.00678 val_rmse=0.1443 top1=0.188 top3=0.408 reg=0.0378 rank=6.23 263s
            saved_h64_d3 ep 037/050  loss=0.00665 val_rmse=0.1440 top1=0.184 top3=0.395 reg=0.0382 rank=6.33 270s
            saved_h64_d3 ep 038/050  loss=0.00648 val_rmse=0.1442 top1=0.193 top3=0.404 reg=0.0370 rank=6.23 278s
            saved_h64_d3 ep 039/050  loss=0.00635 val_rmse=0.1440 top1=0.194 top3=0.403 reg=0.0370 rank=6.24 285s
            saved_h64_d3 ep 040/050* loss=0.00624 val_rmse=0.1453 top1=0.204 top3=0.413 reg=0.0363 rank=6.10 292s
            saved_h64_d3 ep 041/050  loss=0.00608 val_rmse=0.1462 top1=0.201 top3=0.411 reg=0.0371 rank=6.22 300s
            saved_h64_d3 ep 042/050  loss=0.00597 val_rmse=0.1439 top1=0.207 top3=0.422 reg=0.0363 rank=6.12 307s
            saved_h64_d3 ep 043/050  loss=0.00582 val_rmse=0.1446 top1=0.198 top3=0.415 reg=0.0369 rank=6.18 314s
            saved_h64_d3 ep 044/050  loss=0.00578 val_rmse=0.1445 top1=0.200 top3=0.412 reg=0.0375 rank=6.27 321s
            saved_h64_d3 ep 045/050  loss=0.00564 val_rmse=0.1441 top1=0.212 top3=0.429 reg=0.0366 rank=6.11 328s
            saved_h64_d3 ep 046/050  loss=0.00554 val_rmse=0.1440 top1=0.206 top3=0.429 reg=0.0364 rank=6.10 335s
            saved_h64_d3 ep 047/050  loss=0.00544 val_rmse=0.1455 top1=0.212 top3=0.423 reg=0.0365 rank=6.11 342s
            saved_h64_d3 ep 048/050  loss=0.00538 val_rmse=0.1458 top1=0.221 top3=0.439 reg=0.0365 rank=6.09 350s
            saved_h64_d3 ep 049/050* loss=0.00527 val_rmse=0.1441 top1=0.212 top3=0.435 reg=0.0355 rank=6.03 357s
            saved_h64_d3 ep 050/050  loss=0.00520 val_rmse=0.1459 top1=0.218 top3=0.436 reg=0.0365 rank=6.11 364s
            saved_h64_d4 ep 001/050* loss=0.08404 val_rmse=0.1782 top1=0.060 top3=0.224 reg=0.0973 rank=10.60 7s
            saved_h64_d4 ep 002/050* loss=0.03543 val_rmse=0.1656 top1=0.079 top3=0.271 reg=0.0839 rank=9.65 15s
            saved_h64_d4 ep 003/050* loss=0.03127 val_rmse=0.1620 top1=0.086 top3=0.288 reg=0.0696 rank=8.68 22s
            saved_h64_d4 ep 004/050* loss=0.02872 val_rmse=0.1597 top1=0.105 top3=0.340 reg=0.0546 rank=7.65 29s
            saved_h64_d4 ep 005/050* loss=0.02610 val_rmse=0.1574 top1=0.113 top3=0.320 reg=0.0517 rank=7.37 36s
            saved_h64_d4 ep 006/050* loss=0.02403 val_rmse=0.1559 top1=0.132 top3=0.332 reg=0.0491 rank=7.21 43s
            saved_h64_d4 ep 007/050* loss=0.02238 val_rmse=0.1514 top1=0.156 top3=0.395 reg=0.0453 rank=6.77 50s
            saved_h64_d4 ep 008/050* loss=0.02092 val_rmse=0.1486 top1=0.169 top3=0.409 reg=0.0426 rank=6.46 58s
            saved_h64_d4 ep 009/050* loss=0.01977 val_rmse=0.1477 top1=0.177 top3=0.394 reg=0.0425 rank=6.55 65s
            saved_h64_d4 ep 010/050* loss=0.01876 val_rmse=0.1463 top1=0.180 top3=0.381 reg=0.0424 rank=6.57 72s
            saved_h64_d4 ep 011/050  loss=0.01784 val_rmse=0.1454 top1=0.182 top3=0.383 reg=0.0428 rank=6.71 79s
            saved_h64_d4 ep 012/050  loss=0.01696 val_rmse=0.1465 top1=0.192 top3=0.381 reg=0.0446 rank=6.86 87s
            saved_h64_d4 ep 013/050  loss=0.01620 val_rmse=0.1460 top1=0.198 top3=0.392 reg=0.0444 rank=6.80 94s
            saved_h64_d4 ep 014/050* loss=0.01548 val_rmse=0.1464 top1=0.212 top3=0.400 reg=0.0423 rank=6.60 101s
            saved_h64_d4 ep 015/050  loss=0.01479 val_rmse=0.1465 top1=0.208 top3=0.398 reg=0.0431 rank=6.67 108s
            saved_h64_d4 ep 016/050* loss=0.01422 val_rmse=0.1449 top1=0.202 top3=0.397 reg=0.0416 rank=6.53 115s
            saved_h64_d4 ep 017/050  loss=0.01359 val_rmse=0.1454 top1=0.201 top3=0.395 reg=0.0420 rank=6.60 123s
            saved_h64_d4 ep 018/050* loss=0.01313 val_rmse=0.1449 top1=0.200 top3=0.396 reg=0.0413 rank=6.53 130s
            saved_h64_d4 ep 019/050* loss=0.01264 val_rmse=0.1456 top1=0.200 top3=0.399 reg=0.0412 rank=6.45 137s
            saved_h64_d4 ep 020/050* loss=0.01223 val_rmse=0.1453 top1=0.190 top3=0.399 reg=0.0410 rank=6.46 145s
            saved_h64_d4 ep 021/050* loss=0.01173 val_rmse=0.1457 top1=0.187 top3=0.388 reg=0.0403 rank=6.40 152s
            saved_h64_d4 ep 022/050* loss=0.01130 val_rmse=0.1446 top1=0.192 top3=0.407 reg=0.0390 rank=6.24 160s
            saved_h64_d4 ep 023/050* loss=0.01100 val_rmse=0.1451 top1=0.193 top3=0.397 reg=0.0386 rank=6.20 167s
            saved_h64_d4 ep 024/050* loss=0.01056 val_rmse=0.1430 top1=0.184 top3=0.399 reg=0.0375 rank=6.13 174s
            saved_h64_d4 ep 025/050* loss=0.01025 val_rmse=0.1436 top1=0.200 top3=0.413 reg=0.0368 rank=6.02 181s
            saved_h64_d4 ep 026/050  loss=0.00996 val_rmse=0.1444 top1=0.197 top3=0.409 reg=0.0381 rank=6.14 190s
            saved_h64_d4 ep 027/050* loss=0.00957 val_rmse=0.1426 top1=0.198 top3=0.423 reg=0.0364 rank=5.94 197s
            saved_h64_d4 ep 028/050  loss=0.00926 val_rmse=0.1433 top1=0.204 top3=0.421 reg=0.0371 rank=6.03 204s
            saved_h64_d4 ep 029/050  loss=0.00895 val_rmse=0.1428 top1=0.199 top3=0.410 reg=0.0373 rank=6.03 211s
            saved_h64_d4 ep 030/050* loss=0.00869 val_rmse=0.1426 top1=0.200 top3=0.420 reg=0.0359 rank=5.87 218s
            saved_h64_d4 ep 031/050  loss=0.00843 val_rmse=0.1422 top1=0.192 top3=0.408 reg=0.0366 rank=5.95 226s
            saved_h64_d4 ep 032/050  loss=0.00826 val_rmse=0.1426 top1=0.203 top3=0.411 reg=0.0360 rank=5.90 233s
            saved_h64_d4 ep 033/050  loss=0.00795 val_rmse=0.1431 top1=0.195 top3=0.411 reg=0.0372 rank=6.03 240s
            saved_h64_d4 ep 034/050* loss=0.00779 val_rmse=0.1419 top1=0.204 top3=0.420 reg=0.0357 rank=5.86 247s
            saved_h64_d4 ep 035/050* loss=0.00751 val_rmse=0.1416 top1=0.216 top3=0.445 reg=0.0350 rank=5.77 254s
            saved_h64_d4 ep 036/050* loss=0.00734 val_rmse=0.1419 top1=0.207 top3=0.425 reg=0.0350 rank=5.83 261s
            saved_h64_d4 ep 037/050* loss=0.00713 val_rmse=0.1430 top1=0.220 top3=0.438 reg=0.0342 rank=5.72 268s
            saved_h64_d4 ep 038/050* loss=0.00695 val_rmse=0.1421 top1=0.225 top3=0.440 reg=0.0337 rank=5.71 275s
            saved_h64_d4 ep 039/050  loss=0.00677 val_rmse=0.1420 top1=0.216 top3=0.451 reg=0.0339 rank=5.75 282s
            saved_h64_d4 ep 040/050* loss=0.00664 val_rmse=0.1431 top1=0.214 top3=0.437 reg=0.0333 rank=5.65 289s
            saved_h64_d4 ep 041/050* loss=0.00645 val_rmse=0.1427 top1=0.226 top3=0.466 reg=0.0331 rank=5.59 297s
            saved_h64_d4 ep 042/050  loss=0.00632 val_rmse=0.1430 top1=0.232 top3=0.446 reg=0.0339 rank=5.71 304s
            saved_h64_d4 ep 043/050  loss=0.00620 val_rmse=0.1435 top1=0.237 top3=0.445 reg=0.0353 rank=5.83 311s
            saved_h64_d4 ep 044/050  loss=0.00606 val_rmse=0.1424 top1=0.221 top3=0.450 reg=0.0348 rank=5.82 318s
            saved_h64_d4 ep 045/050  loss=0.00596 val_rmse=0.1442 top1=0.233 top3=0.462 reg=0.0350 rank=5.77 325s
            saved_h64_d4 ep 046/050  loss=0.00588 val_rmse=0.1435 top1=0.229 top3=0.458 reg=0.0336 rank=5.66 332s
            saved_h64_d4 ep 047/050  loss=0.00569 val_rmse=0.1432 top1=0.234 top3=0.463 reg=0.0341 rank=5.72 340s
            saved_h64_d4 ep 048/050  loss=0.00565 val_rmse=0.1435 top1=0.248 top3=0.466 reg=0.0343 rank=5.71 348s
            saved_h64_d4 ep 049/050* loss=0.00555 val_rmse=0.1436 top1=0.250 top3=0.464 reg=0.0330 rank=5.61 355s
            saved_h64_d4 ep 050/050  loss=0.00544 val_rmse=0.1445 top1=0.248 top3=0.464 reg=0.0352 rank=5.78 363s
            saved_h64_d5 ep 001/050* loss=0.06078 val_rmse=0.1801 top1=0.053 top3=0.130 reg=0.1365 rank=13.36 8s
            saved_h64_d5 ep 002/050* loss=0.03285 val_rmse=0.1659 top1=0.074 top3=0.202 reg=0.0983 rank=11.03 15s
            saved_h64_d5 ep 003/050* loss=0.02854 val_rmse=0.1611 top1=0.100 top3=0.244 reg=0.0813 rank=9.65 23s
            saved_h64_d5 ep 004/050* loss=0.02545 val_rmse=0.1553 top1=0.118 top3=0.279 reg=0.0696 rank=8.64 31s
            saved_h64_d5 ep 005/050* loss=0.02309 val_rmse=0.1523 top1=0.127 top3=0.307 reg=0.0566 rank=7.66 38s
            saved_h64_d5 ep 006/050* loss=0.02111 val_rmse=0.1519 top1=0.115 top3=0.303 reg=0.0556 rank=7.65 45s
            saved_h64_d5 ep 007/050* loss=0.01957 val_rmse=0.1520 top1=0.113 top3=0.303 reg=0.0547 rank=7.63 53s
            saved_h64_d5 ep 008/050* loss=0.01813 val_rmse=0.1505 top1=0.117 top3=0.303 reg=0.0538 rank=7.65 60s
            saved_h64_d5 ep 009/050* loss=0.01706 val_rmse=0.1505 top1=0.117 top3=0.308 reg=0.0518 rank=7.40 69s
            saved_h64_d5 ep 010/050* loss=0.01605 val_rmse=0.1496 top1=0.114 top3=0.305 reg=0.0508 rank=7.34 79s
            saved_h64_d5 ep 011/050* loss=0.01507 val_rmse=0.1492 top1=0.118 top3=0.315 reg=0.0502 rank=7.24 87s
            saved_h64_d5 ep 012/050* loss=0.01433 val_rmse=0.1476 top1=0.125 top3=0.323 reg=0.0476 rank=7.02 94s
            saved_h64_d5 ep 013/050* loss=0.01358 val_rmse=0.1479 top1=0.150 top3=0.353 reg=0.0469 rank=6.86 101s
            saved_h64_d5 ep 014/050* loss=0.01304 val_rmse=0.1470 top1=0.159 top3=0.368 reg=0.0449 rank=6.64 108s
            saved_h64_d5 ep 015/050  loss=0.01242 val_rmse=0.1472 top1=0.153 top3=0.353 reg=0.0458 rank=6.73 116s
            saved_h64_d5 ep 016/050  loss=0.01195 val_rmse=0.1479 top1=0.170 top3=0.370 reg=0.0454 rank=6.68 123s
            saved_h64_d5 ep 017/050  loss=0.01146 val_rmse=0.1475 top1=0.175 top3=0.379 reg=0.0461 rank=6.72 130s
            saved_h64_d5 ep 018/050* loss=0.01107 val_rmse=0.1468 top1=0.184 top3=0.386 reg=0.0445 rank=6.61 137s
            saved_h64_d5 ep 019/050  loss=0.01069 val_rmse=0.1481 top1=0.188 top3=0.382 reg=0.0454 rank=6.70 144s
            saved_h64_d5 ep 020/050* loss=0.01040 val_rmse=0.1469 top1=0.192 top3=0.393 reg=0.0436 rank=6.63 152s
            saved_h64_d5 ep 021/050  loss=0.01010 val_rmse=0.1478 top1=0.207 top3=0.415 reg=0.0444 rank=6.59 159s
            saved_h64_d5 ep 022/050  loss=0.00983 val_rmse=0.1494 top1=0.203 top3=0.408 reg=0.0459 rank=6.72 166s
            saved_h64_d5 ep 023/050  loss=0.00951 val_rmse=0.1511 top1=0.202 top3=0.401 reg=0.0440 rank=6.64 173s
            saved_h64_d5 ep 024/050  loss=0.00929 val_rmse=0.1499 top1=0.206 top3=0.419 reg=0.0439 rank=6.57 181s
            saved_h64_d5 ep 025/050* loss=0.00907 val_rmse=0.1482 top1=0.218 top3=0.421 reg=0.0420 rank=6.39 188s
            saved_h64_d5 ep 026/050  loss=0.00880 val_rmse=0.1477 top1=0.210 top3=0.415 reg=0.0421 rank=6.40 195s
            saved_h64_d5 ep 027/050  loss=0.00861 val_rmse=0.1505 top1=0.214 top3=0.413 reg=0.0436 rank=6.55 203s
            saved_h64_d5 ep 028/050* loss=0.00843 val_rmse=0.1483 top1=0.222 top3=0.433 reg=0.0410 rank=6.27 210s
            saved_h64_d5 ep 029/050  loss=0.00822 val_rmse=0.1503 top1=0.212 top3=0.422 reg=0.0427 rank=6.43 217s
            saved_h64_d5 ep 030/050  loss=0.00804 val_rmse=0.1496 top1=0.202 top3=0.409 reg=0.0421 rank=6.43 224s
            saved_h64_d5 ep 031/050  loss=0.00789 val_rmse=0.1493 top1=0.208 top3=0.413 reg=0.0420 rank=6.41 232s
            saved_h64_d5 ep 032/050  loss=0.00765 val_rmse=0.1503 top1=0.206 top3=0.405 reg=0.0417 rank=6.46 239s
            saved_h64_d5 ep 033/050  loss=0.00751 val_rmse=0.1517 top1=0.214 top3=0.417 reg=0.0416 rank=6.35 246s
            saved_h64_d5 ep 034/050  loss=0.00727 val_rmse=0.1508 top1=0.216 top3=0.409 reg=0.0420 rank=6.41 253s
            saved_h64_d5 ep 035/050  loss=0.00715 val_rmse=0.1529 top1=0.207 top3=0.402 reg=0.0437 rank=6.61 261s
            saved_h64_d5 ep 036/050  loss=0.00697 val_rmse=0.1515 top1=0.229 top3=0.427 reg=0.0412 rank=6.36 268s
            saved_h64_d5 ep 037/050  loss=0.00674 val_rmse=0.1525 top1=0.236 top3=0.435 reg=0.0416 rank=6.35 275s
            saved_h64_d5 ep 038/050  loss=0.00660 val_rmse=0.1522 top1=0.224 top3=0.416 reg=0.0412 rank=6.35 283s
            saved_h64_d5 ep 039/050  loss=0.00636 val_rmse=0.1513 top1=0.216 top3=0.419 reg=0.0410 rank=6.38 290s
            saved_h64_d5 ep 040/050  loss=0.00621 val_rmse=0.1526 top1=0.229 top3=0.427 reg=0.0420 rank=6.44 297s
            saved_h64_d5 ep 041/050* loss=0.00605 val_rmse=0.1527 top1=0.236 top3=0.439 reg=0.0405 rank=6.26 304s
            saved_h64_d5 ep 042/050  loss=0.00590 val_rmse=0.1520 top1=0.228 top3=0.423 reg=0.0419 rank=6.48 311s
            saved_h64_d5 ep 043/050  loss=0.00579 val_rmse=0.1524 top1=0.240 top3=0.441 reg=0.0414 rank=6.34 318s
            saved_h64_d5 ep 044/050* loss=0.00563 val_rmse=0.1536 top1=0.248 top3=0.441 reg=0.0401 rank=6.24 326s
            saved_h64_d5 ep 045/050  loss=0.00550 val_rmse=0.1539 top1=0.244 top3=0.437 reg=0.0418 rank=6.37 333s
            saved_h64_d5 ep 046/050  loss=0.00542 val_rmse=0.1541 top1=0.250 top3=0.435 reg=0.0408 rank=6.28 340s
            saved_h64_d5 ep 047/050  loss=0.00527 val_rmse=0.1548 top1=0.249 top3=0.424 reg=0.0422 rank=6.38 347s
            saved_h64_d5 ep 048/050  loss=0.00518 val_rmse=0.1528 top1=0.246 top3=0.430 reg=0.0412 rank=6.31 355s
            saved_h64_d5 ep 049/050  loss=0.00510 val_rmse=0.1542 top1=0.249 top3=0.433 reg=0.0421 rank=6.34 362s
            saved_h64_d5 ep 050/050  loss=0.00495 val_rmse=0.1558 top1=0.237 top3=0.419 reg=0.0434 rank=6.57 369s
            saved_h64_d6 ep 001/050* loss=0.09845 val_rmse=0.1922 top1=0.046 top3=0.146 reg=0.1637 rank=15.46 8s
            saved_h64_d6 ep 002/050* loss=0.03761 val_rmse=0.1665 top1=0.084 top3=0.243 reg=0.0996 rank=10.98 15s
            saved_h64_d6 ep 003/050* loss=0.03251 val_rmse=0.1632 top1=0.125 top3=0.313 reg=0.0856 rank=9.36 22s
            saved_h64_d6 ep 004/050* loss=0.02962 val_rmse=0.1574 top1=0.165 top3=0.365 reg=0.0738 rank=8.56 29s
            saved_h64_d6 ep 005/050* loss=0.02756 val_rmse=0.1547 top1=0.190 top3=0.409 reg=0.0624 rank=7.75 37s
            saved_h64_d6 ep 006/050* loss=0.02572 val_rmse=0.1552 top1=0.200 top3=0.431 reg=0.0547 rank=7.08 44s
            saved_h64_d6 ep 007/050* loss=0.02417 val_rmse=0.1551 top1=0.217 top3=0.455 reg=0.0490 rank=6.58 53s
            saved_h64_d6 ep 008/050* loss=0.02269 val_rmse=0.1546 top1=0.212 top3=0.452 reg=0.0439 rank=6.28 60s
            saved_h64_d6 ep 009/050* loss=0.02138 val_rmse=0.1525 top1=0.205 top3=0.449 reg=0.0419 rank=6.15 67s
            saved_h64_d6 ep 010/050  loss=0.02025 val_rmse=0.1537 top1=0.188 top3=0.427 reg=0.0426 rank=6.30 74s
            saved_h64_d6 ep 011/050  loss=0.01939 val_rmse=0.1530 top1=0.183 top3=0.409 reg=0.0437 rank=6.57 81s
            saved_h64_d6 ep 012/050  loss=0.01830 val_rmse=0.1529 top1=0.191 top3=0.408 reg=0.0464 rank=6.86 88s
            saved_h64_d6 ep 013/050  loss=0.01758 val_rmse=0.1513 top1=0.195 top3=0.399 reg=0.0490 rank=7.10 96s
            saved_h64_d6 ep 014/050  loss=0.01689 val_rmse=0.1521 top1=0.201 top3=0.399 reg=0.0494 rank=7.27 103s
            saved_h64_d6 ep 015/050  loss=0.01618 val_rmse=0.1524 top1=0.202 top3=0.388 reg=0.0529 rank=7.54 110s
            saved_h64_d6 ep 016/050  loss=0.01547 val_rmse=0.1518 top1=0.202 top3=0.393 reg=0.0528 rank=7.55 117s
            saved_h64_d6 ep 017/050  loss=0.01491 val_rmse=0.1538 top1=0.201 top3=0.387 reg=0.0537 rank=7.64 124s
            saved_h64_d6 ep 018/050  loss=0.01440 val_rmse=0.1531 top1=0.212 top3=0.401 reg=0.0511 rank=7.32 132s
            saved_h64_d6 ep 019/050  loss=0.01391 val_rmse=0.1527 top1=0.222 top3=0.409 reg=0.0519 rank=7.35 139s
            saved_h64_d6 ep 020/050  loss=0.01338 val_rmse=0.1509 top1=0.216 top3=0.420 reg=0.0506 rank=7.18 146s
            saved_h64_d6 ep 021/050  loss=0.01284 val_rmse=0.1497 top1=0.208 top3=0.415 reg=0.0490 rank=7.11 153s
            saved_h64_d6 ep 022/050  loss=0.01255 val_rmse=0.1469 top1=0.217 top3=0.431 reg=0.0458 rank=6.82 160s
            saved_h64_d6 ep 023/050  loss=0.01210 val_rmse=0.1492 top1=0.215 top3=0.429 reg=0.0460 rank=6.83 168s
            saved_h64_d6 ep 024/050  loss=0.01173 val_rmse=0.1472 top1=0.212 top3=0.427 reg=0.0451 rank=6.81 175s
            saved_h64_d6 ep 025/050  loss=0.01141 val_rmse=0.1483 top1=0.231 top3=0.429 reg=0.0456 rank=6.78 182s
            saved_h64_d6 early stop at ep 025; best ep 009

,run_name,utility,hidden,emb_dim,depth,dropout,combine,loss,best_epoch,train_rmse,...,val_avg_regret,val_avg_norm_regret,test_rmse,test_mae,test_r2,test_top1,test_top3,test_mean_rank,test_avg_regret,test_avg_norm_regret
0,saved_h64_d4,saved,64,8,4,0.05,mul_only,mse,49,0.055641,...,0.032966,0.070627,0.143397,0.101274,0.480826,0.271266,0.449431,5.716678,0.040112,0.076856
1,saved_h64_d3,saved,64,8,3,0.05,mul_only,mse,49,0.056627,...,0.035475,0.076201,0.143941,0.103108,0.476883,0.237776,0.421299,5.673141,0.036669,0.072332
2,saved_h64_d5,saved,64,8,5,0.05,mul_only,mse,44,0.057085,...,0.040149,0.082697,0.148402,0.105566,0.443949,0.248493,0.430676,5.724046,0.038005,0.073585
3,saved_h64_d6,saved,64,8,6,0.05,mul_only,mse,9,0.130751,...,0.041902,0.084057,0.149039,0.114374,0.439170,0.168788,0.381782,6.995981,0.052599,0.099164

,run_name,train_utility,eval_objective,split,hidden,emb_dim,combine,top1,top3,mean_rank,avg_regret,avg_norm_regret
0,saved_h64_d5,saved,contains_closest,test,64,8,mul_only,0.905559,0.905559,2.511052,0.094441,0.094441
1,saved_h64_d3,saved,contains_closest,test,64,8,mul_only,0.902210,0.902210,2.564635,0.097790,0.097790
2,saved_h64_d4,saved,contains_closest,test,64,8,mul_only,0.896182,0.896182,2.661085,0.103818,0.103818
3,saved_h64_d6,saved,contains_closest,test,64,8,mul_only,0.874079,0.874079,3.014735,0.125921,0.125921
4,saved_h64_d4,saved,saved_rational,test,64,8,mul_only,0.271266,0.449431,5.716678,0.040112,0.076856
5,saved_h64_d5,saved,saved_rational,test,64,8,mul_only,0.248493,0.430676,5.724046,0.038005,0.073585
6,saved_h64_d3,saved,saved_rational,test,64,8,mul_only,0.237776,0.421299,5.673141,0.036669,0.072332
7,saved_h64_d6,saved,saved_rational,test,64,8,mul_only,0.168788,0.381782,6.995981,0.052599,0.099164

In [5]:
# Saved-utility embedding sweep. Hidden/depth stay at TrainConfig defaults: hidden=64, depth=2.
DEVICE = 'cuda'

SAVED_OBJECTIVES = [
    {"name": "saved_rational", "utility_name": "saved", "utility_kwargs": {}},
    {"name": "contains_closest", "utility_name": "closest_binary", "utility_kwargs": {}},
]

EMBEDDING_SWEEP_CONFIGS = [
    TrainConfig(
        run_name=f"saved_h64_d2_e{emb_dim}",
        utility_name="saved",
        hidden=64,
        emb_dim=emb_dim,
        depth=2,
        dropout=0.05,
        combine_mode="mul_only",
        loss_name="mse",
        max_epochs=50,
        patience=16,
        batch_size=8192,
        lr=1e-3,
        weight_decay=1e-4,
        log_every=1,
    )
    for emb_dim in [16, 32, 64, 96]
]

embedding_sweep_results = run_config_grid(
    PROCESSED_DIR,
    EMBEDDING_SWEEP_CONFIGS,
    prefix=PREFIX,
    max_time_steps=MAX_TIME_STEPS,
    device=DEVICE,
)

embedding_sweep_own_df = summarize_results(embedding_sweep_results)
embedding_sweep_eval_df = compare_on_common_objectives(embedding_sweep_results, SAVED_OBJECTIVES)
embedding_sweep_test_df = (
    embedding_sweep_eval_df[embedding_sweep_eval_df["split"].eq("test")]
    .sort_values(
        ["eval_objective", "top1", "top3", "mean_rank", "avg_norm_regret"],
        ascending=[True, False, False, True, True],
    )
    .reset_index(drop=True)
)

display(embedding_sweep_own_df)
display(embedding_sweep_test_df)

        saved_h64_d2_e16 ep 001/050* loss=0.12516 val_rmse=0.1802 top1=0.065 top3=0.224 reg=0.1260 rank=12.21 8s
        saved_h64_d2_e16 ep 002/050* loss=0.03387 val_rmse=0.1655 top1=0.078 top3=0.381 reg=0.0684 rank=8.32 16s
        saved_h64_d2_e16 ep 003/050* loss=0.02722 val_rmse=0.1551 top1=0.096 top3=0.374 reg=0.0497 rank=7.04 24s
        saved_h64_d2_e16 ep 004/050* loss=0.02411 val_rmse=0.1533 top1=0.100 top3=0.368 reg=0.0451 rank=6.69 32s
        saved_h64_d2_e16 ep 005/050* loss=0.02191 val_rmse=0.1502 top1=0.095 top3=0.346 reg=0.0429 rank=6.59 41s
        saved_h64_d2_e16 ep 006/050* loss=0.02026 val_rmse=0.1486 top1=0.105 top3=0.338 reg=0.0422 rank=6.56 49s
        saved_h64_d2_e16 ep 007/050* loss=0.01891 val_rmse=0.1497 top1=0.113 top3=0.330 reg=0.0419 rank=6.50 58s
        saved_h64_d2_e16 ep 008/050* loss=0.01776 val_rmse=0.1466 top1=0.124 top3=0.338 reg=0.0409 rank=6.36 66s
        saved_h64_d2_e16 ep 009/050* loss=0.01678 val_rmse=0.1467 top1=0.130 top3=0.342 reg=0.0406 rank=6.30 73s
        saved_h64_d2_e16 ep 010/050* loss=0.01593 val_rmse=0.1460 top1=0.131 top3=0.348 reg=0.0394 rank=6.20 82s
        saved_h64_d2_e16 ep 011/050* loss=0.01519 val_rmse=0.1462 top1=0.147 top3=0.364 reg=0.0385 rank=6.16 91s
        saved_h64_d2_e16 ep 012/050* loss=0.01443 val_rmse=0.1444 top1=0.158 top3=0.370 reg=0.0378 rank=6.06 101s
        saved_h64_d2_e16 ep 013/050  loss=0.01384 val_rmse=0.1454 top1=0.163 top3=0.378 reg=0.0387 rank=6.10 109s
        saved_h64_d2_e16 ep 014/050* loss=0.01324 val_rmse=0.1440 top1=0.163 top3=0.384 reg=0.0368 rank=5.91 116s
        saved_h64_d2_e16 ep 015/050  loss=0.01269 val_rmse=0.1458 top1=0.172 top3=0.382 reg=0.0375 rank=6.06 125s
        saved_h64_d2_e16 ep 016/050* loss=0.01211 val_rmse=0.1440 top1=0.183 top3=0.401 reg=0.0364 rank=5.89 134s
        saved_h64_d2_e16 ep 017/050  loss=0.01173 val_rmse=0.1447 top1=0.175 top3=0.380 reg=0.0366 rank=5.97 141s
        saved_h64_d2_e16 ep 018/050  loss=0.01127 val_rmse=0.1448 top1=0.178 top3=0.384 reg=0.0379 rank=6.11 149s
        saved_h64_d2_e16 ep 019/050  loss=0.01082 val_rmse=0.1452 top1=0.190 top3=0.394 reg=0.0368 rank=5.98 157s
        saved_h64_d2_e16 ep 020/050* loss=0.01045 val_rmse=0.1440 top1=0.191 top3=0.400 reg=0.0359 rank=5.90 164s
        saved_h64_d2_e16 ep 021/050  loss=0.01004 val_rmse=0.1462 top1=0.196 top3=0.407 reg=0.0359 rank=5.92 172s
        saved_h64_d2_e16 ep 022/050* loss=0.00978 val_rmse=0.1450 top1=0.196 top3=0.400 reg=0.0355 rank=5.88 180s
        saved_h64_d2_e16 ep 023/050  loss=0.00946 val_rmse=0.1456 top1=0.205 top3=0.413 reg=0.0359 rank=5.86 188s
        saved_h64_d2_e16 ep 024/050  loss=0.00918 val_rmse=0.1453 top1=0.199 top3=0.392 reg=0.0357 rank=5.99 195s
        saved_h64_d2_e16 ep 025/050  loss=0.00893 val_rmse=0.1454 top1=0.203 top3=0.392 reg=0.0362 rank=6.01 205s
        saved_h64_d2_e16 ep 026/050* loss=0.00865 val_rmse=0.1454 top1=0.211 top3=0.419 reg=0.0346 rank=5.80 215s
        saved_h64_d2_e16 ep 027/050  loss=0.00840 val_rmse=0.1454 top1=0.198 top3=0.394 reg=0.0356 rank=5.96 223s
        saved_h64_d2_e16 ep 028/050* loss=0.00822 val_rmse=0.1461 top1=0.208 top3=0.413 reg=0.0341 rank=5.81 232s
        saved_h64_d2_e16 ep 029/050  loss=0.00799 val_rmse=0.1476 top1=0.206 top3=0.402 reg=0.0347 rank=5.83 240s
        saved_h64_d2_e16 ep 030/050* loss=0.00778 val_rmse=0.1447 top1=0.222 top3=0.425 reg=0.0326 rank=5.56 248s
        saved_h64_d2_e16 ep 031/050* loss=0.00761 val_rmse=0.1458 top1=0.226 top3=0.427 reg=0.0317 rank=5.50 256s
        saved_h64_d2_e16 ep 032/050  loss=0.00743 val_rmse=0.1474 top1=0.216 top3=0.413 reg=0.0343 rank=5.76 264s
        saved_h64_d2_e16 ep 033/050  loss=0.00720 val_rmse=0.1451 top1=0.221 top3=0.418 reg=0.0338 rank=5.71 272s
        saved_h64_d2_e16 ep 034/050  loss=0.00707 val_rmse=0.1469 top1=0.236 top3=0.437 reg=0.0325 rank=5.55 280s
        saved_h64_d2_e16 ep 035/050  loss=0.00687 val_rmse=0.1447 top1=0.218 top3=0.415 reg=0.0336 rank=5.75 288s
        saved_h64_d2_e16 ep 036/050  loss=0.00674 val_rmse=0.1450 top1=0.233 top3=0.443 reg=0.0326 rank=5.56 296s
        saved_h64_d2_e16 ep 037/050  loss=0.00663 val_rmse=0.1451 top1=0.232 top3=0.428 reg=0.0328 rank=5.65 304s
        saved_h64_d2_e16 ep 038/050  loss=0.00646 val_rmse=0.1469 top1=0.234 top3=0.441 reg=0.0320 rank=5.54 312s
        saved_h64_d2_e16 ep 039/050  loss=0.00632 val_rmse=0.1464 top1=0.230 top3=0.433 reg=0.0329 rank=5.61 319s
        saved_h64_d2_e16 ep 040/050* loss=0.00628 val_rmse=0.1465 top1=0.239 top3=0.445 reg=0.0313 rank=5.46 327s
        saved_h64_d2_e16 ep 041/050* loss=0.00611 val_rmse=0.1457 top1=0.243 top3=0.448 reg=0.0308 rank=5.41 335s
        saved_h64_d2_e16 ep 042/050  loss=0.00602 val_rmse=0.1462 top1=0.225 top3=0.419 reg=0.0334 rank=5.70 342s
        saved_h64_d2_e16 ep 043/050  loss=0.00591 val_rmse=0.1475 top1=0.226 top3=0.419 reg=0.0330 rank=5.64 350s
        saved_h64_d2_e16 ep 044/050  loss=0.00579 val_rmse=0.1466 top1=0.232 top3=0.431 reg=0.0322 rank=5.58 358s
        saved_h64_d2_e16 ep 045/050  loss=0.00570 val_rmse=0.1467 top1=0.230 top3=0.411 reg=0.0334 rank=5.71 365s
        saved_h64_d2_e16 ep 046/050  loss=0.00565 val_rmse=0.1464 top1=0.239 top3=0.426 reg=0.0325 rank=5.56 373s
        saved_h64_d2_e16 ep 047/050  loss=0.00550 val_rmse=0.1472 top1=0.223 top3=0.422 reg=0.0312 rank=5.48 380s
        saved_h64_d2_e16 ep 048/050  loss=0.00540 val_rmse=0.1472 top1=0.217 top3=0.415 reg=0.0320 rank=5.54 388s
        saved_h64_d2_e16 ep 049/050  loss=0.00534 val_rmse=0.1477 top1=0.220 top3=0.421 reg=0.0315 rank=5.53 397s
        saved_h64_d2_e16 ep 050/050  loss=0.00527 val_rmse=0.1487 top1=0.222 top3=0.415 reg=0.0324 rank=5.60 406s
        saved_h64_d2_e32 ep 001/050* loss=0.04618 val_rmse=0.1647 top1=0.198 top3=0.393 reg=0.0655 rank=8.08 9s
        saved_h64_d2_e32 ep 002/050* loss=0.02484 val_rmse=0.1554 top1=0.204 top3=0.407 reg=0.0455 rank=6.59 17s
        saved_h64_d2_e32 ep 003/050  loss=0.02011 val_rmse=0.1530 top1=0.208 top3=0.384 reg=0.0480 rank=6.97 25s
        saved_h64_d2_e32 ep 004/050  loss=0.01732 val_rmse=0.1521 top1=0.200 top3=0.362 reg=0.0456 rank=6.81 33s
        saved_h64_d2_e32 ep 005/050* loss=0.01537 val_rmse=0.1504 top1=0.208 top3=0.383 reg=0.0428 rank=6.47 41s
        saved_h64_d2_e32 ep 006/050* loss=0.01391 val_rmse=0.1483 top1=0.180 top3=0.366 reg=0.0397 rank=6.20 49s
        saved_h64_d2_e32 ep 007/050* loss=0.01273 val_rmse=0.1469 top1=0.187 top3=0.386 reg=0.0365 rank=5.85 58s
        saved_h64_d2_e32 ep 008/050* loss=0.01173 val_rmse=0.1442 top1=0.185 top3=0.392 reg=0.0341 rank=5.71 66s
        saved_h64_d2_e32 ep 009/050* loss=0.01097 val_rmse=0.1450 top1=0.196 top3=0.397 reg=0.0335 rank=5.60 73s
        saved_h64_d2_e32 ep 010/050* loss=0.01024 val_rmse=0.1441 top1=0.190 top3=0.402 reg=0.0328 rank=5.57 81s
        saved_h64_d2_e32 ep 011/050* loss=0.00960 val_rmse=0.1431 top1=0.200 top3=0.416 reg=0.0326 rank=5.52 89s
        saved_h64_d2_e32 ep 012/050* loss=0.00904 val_rmse=0.1400 top1=0.210 top3=0.441 reg=0.0315 rank=5.38 98s
        saved_h64_d2_e32 ep 013/050  loss=0.00855 val_rmse=0.1421 top1=0.206 top3=0.425 reg=0.0323 rank=5.47 106s
        saved_h64_d2_e32 ep 014/050  loss=0.00808 val_rmse=0.1418 top1=0.208 top3=0.429 reg=0.0331 rank=5.60 114s
        saved_h64_d2_e32 ep 015/050  loss=0.00772 val_rmse=0.1411 top1=0.197 top3=0.409 reg=0.0337 rank=5.69 122s
        saved_h64_d2_e32 ep 016/050  loss=0.00733 val_rmse=0.1415 top1=0.203 top3=0.423 reg=0.0340 rank=5.71 130s
        saved_h64_d2_e32 ep 017/050  loss=0.00697 val_rmse=0.1419 top1=0.219 top3=0.430 reg=0.0329 rank=5.59 138s
        saved_h64_d2_e32 ep 018/050  loss=0.00667 val_rmse=0.1410 top1=0.218 top3=0.428 reg=0.0342 rank=5.67 147s
        saved_h64_d2_e32 ep 019/050  loss=0.00636 val_rmse=0.1410 top1=0.203 top3=0.415 reg=0.0360 rank=5.88 155s
        saved_h64_d2_e32 ep 020/050  loss=0.00611 val_rmse=0.1425 top1=0.208 top3=0.409 reg=0.0366 rank=5.93 163s
        saved_h64_d2_e32 ep 021/050  loss=0.00588 val_rmse=0.1435 top1=0.206 top3=0.407 reg=0.0378 rank=6.04 172s
        saved_h64_d2_e32 ep 022/050  loss=0.00569 val_rmse=0.1437 top1=0.200 top3=0.412 reg=0.0380 rank=6.07 180s
        saved_h64_d2_e32 ep 023/050  loss=0.00550 val_rmse=0.1414 top1=0.210 top3=0.415 reg=0.0362 rank=5.94 187s
        saved_h64_d2_e32 ep 024/050  loss=0.00533 val_rmse=0.1437 top1=0.206 top3=0.401 reg=0.0385 rank=6.08 195s
        saved_h64_d2_e32 ep 025/050  loss=0.00515 val_rmse=0.1449 top1=0.222 top3=0.412 reg=0.0362 rank=5.90 203s
        saved_h64_d2_e32 ep 026/050  loss=0.00500 val_rmse=0.1450 top1=0.210 top3=0.409 reg=0.0371 rank=6.01 211s
        saved_h64_d2_e32 ep 027/050  loss=0.00484 val_rmse=0.1455 top1=0.204 top3=0.412 reg=0.0367 rank=5.99 219s
        saved_h64_d2_e32 ep 028/050  loss=0.00470 val_rmse=0.1440 top1=0.204 top3=0.408 reg=0.0364 rank=5.95 226s
        saved_h64_d2_e32 early stop at ep 028; best ep 012
        saved_h64_d2_e64 ep 001/050* loss=0.06005 val_rmse=0.1708 top1=0.086 top3=0.232 reg=0.0987 rank=11.42 8s
        saved_h64_d2_e64 ep 002/050* loss=0.02589 val_rmse=0.1634 top1=0.068 top3=0.228 reg=0.0707 rank=9.41 15s
        saved_h64_d2_e64 ep 003/050* loss=0.02078 val_rmse=0.1575 top1=0.082 top3=0.273 reg=0.0615 rank=8.49 23s
        saved_h64_d2_e64 ep 004/050* loss=0.01812 val_rmse=0.1551 top1=0.100 top3=0.303 reg=0.0561 rank=8.04 31s
        saved_h64_d2_e64 ep 005/050* loss=0.01612 val_rmse=0.1526 top1=0.109 top3=0.327 reg=0.0512 rank=7.44 39s
        saved_h64_d2_e64 ep 006/050* loss=0.01467 val_rmse=0.1501 top1=0.111 top3=0.342 reg=0.0488 rank=7.17 46s
        saved_h64_d2_e64 ep 007/050* loss=0.01341 val_rmse=0.1486 top1=0.128 top3=0.368 reg=0.0461 rank=6.86 54s
        saved_h64_d2_e64 ep 008/050* loss=0.01230 val_rmse=0.1472 top1=0.141 top3=0.384 reg=0.0433 rank=6.59 62s
        saved_h64_d2_e64 ep 009/050* loss=0.01143 val_rmse=0.1460 top1=0.159 top3=0.388 reg=0.0424 rank=6.50 70s
        saved_h64_d2_e64 ep 010/050* loss=0.01068 val_rmse=0.1447 top1=0.158 top3=0.395 reg=0.0405 rank=6.42 77s
        saved_h64_d2_e64 ep 011/050  loss=0.01002 val_rmse=0.1451 top1=0.159 top3=0.398 reg=0.0407 rank=6.42 85s
        saved_h64_d2_e64 ep 012/050* loss=0.00946 val_rmse=0.1442 top1=0.153 top3=0.396 reg=0.0403 rank=6.45 93s
        saved_h64_d2_e64 ep 013/050* loss=0.00891 val_rmse=0.1425 top1=0.163 top3=0.398 reg=0.0390 rank=6.34 101s
        saved_h64_d2_e64 ep 014/050* loss=0.00846 val_rmse=0.1443 top1=0.162 top3=0.401 reg=0.0381 rank=6.24 109s
        saved_h64_d2_e64 ep 015/050* loss=0.00803 val_rmse=0.1428 top1=0.165 top3=0.398 reg=0.0381 rank=6.25 117s
        saved_h64_d2_e64 ep 016/050* loss=0.00769 val_rmse=0.1407 top1=0.165 top3=0.400 reg=0.0368 rank=6.08 125s
        saved_h64_d2_e64 ep 017/050* loss=0.00735 val_rmse=0.1425 top1=0.180 top3=0.401 reg=0.0366 rank=6.14 133s
        saved_h64_d2_e64 ep 018/050* loss=0.00705 val_rmse=0.1409 top1=0.183 top3=0.402 reg=0.0354 rank=5.96 141s
        saved_h64_d2_e64 ep 019/050* loss=0.00676 val_rmse=0.1434 top1=0.173 top3=0.403 reg=0.0354 rank=5.96 149s
        saved_h64_d2_e64 ep 020/050  loss=0.00656 val_rmse=0.1421 top1=0.159 top3=0.393 reg=0.0355 rank=6.03 158s
        saved_h64_d2_e64 ep 021/050  loss=0.00631 val_rmse=0.1435 top1=0.162 top3=0.392 reg=0.0361 rank=6.10 165s
        saved_h64_d2_e64 ep 022/050  loss=0.00612 val_rmse=0.1421 top1=0.178 top3=0.392 reg=0.0355 rank=6.03 174s
        saved_h64_d2_e64 ep 023/050  loss=0.00590 val_rmse=0.1424 top1=0.156 top3=0.372 reg=0.0361 rank=6.20 182s
        saved_h64_d2_e64 ep 024/050  loss=0.00572 val_rmse=0.1425 top1=0.177 top3=0.392 reg=0.0355 rank=6.06 191s
        saved_h64_d2_e64 ep 025/050* loss=0.00554 val_rmse=0.1412 top1=0.186 top3=0.413 reg=0.0345 rank=5.98 199s
        saved_h64_d2_e64 ep 026/050  loss=0.00537 val_rmse=0.1422 top1=0.187 top3=0.415 reg=0.0346 rank=5.95 208s
        saved_h64_d2_e64 ep 027/050  loss=0.00521 val_rmse=0.1439 top1=0.167 top3=0.390 reg=0.0358 rank=6.14 216s
        saved_h64_d2_e64 ep 028/050  loss=0.00507 val_rmse=0.1412 top1=0.185 top3=0.425 reg=0.0347 rank=5.94 224s
        saved_h64_d2_e64 ep 029/050  loss=0.00493 val_rmse=0.1421 top1=0.189 top3=0.399 reg=0.0355 rank=6.07 231s
        saved_h64_d2_e64 ep 030/050  loss=0.00482 val_rmse=0.1441 top1=0.173 top3=0.398 reg=0.0367 rank=6.21 239s
        saved_h64_d2_e64 ep 031/050  loss=0.00472 val_rmse=0.1433 top1=0.169 top3=0.388 reg=0.0376 rank=6.28 247s
        saved_h64_d2_e64 ep 032/050  loss=0.00460 val_rmse=0.1428 top1=0.182 top3=0.411 reg=0.0368 rank=6.18 255s
        saved_h64_d2_e64 ep 033/050  loss=0.00449 val_rmse=0.1443 top1=0.181 top3=0.409 reg=0.0360 rank=6.09 264s
        saved_h64_d2_e64 ep 034/050  loss=0.00441 val_rmse=0.1424 top1=0.190 top3=0.417 reg=0.0370 rank=6.18 272s
        saved_h64_d2_e64 ep 035/050  loss=0.00430 val_rmse=0.1442 top1=0.182 top3=0.404 reg=0.0372 rank=6.19 280s
        saved_h64_d2_e64 ep 036/050  loss=0.00420 val_rmse=0.1444 top1=0.194 top3=0.401 reg=0.0359 rank=6.14 288s
        saved_h64_d2_e64 ep 037/050  loss=0.00411 val_rmse=0.1449 top1=0.215 top3=0.432 reg=0.0358 rank=6.04 296s
        saved_h64_d2_e64 ep 038/050  loss=0.00404 val_rmse=0.1426 top1=0.185 top3=0.397 reg=0.0365 rank=6.18 304s
        saved_h64_d2_e64 ep 039/050  loss=0.00394 val_rmse=0.1445 top1=0.196 top3=0.419 reg=0.0369 rank=6.20 312s
        saved_h64_d2_e64 ep 040/050  loss=0.00389 val_rmse=0.1446 top1=0.196 top3=0.429 reg=0.0362 rank=6.11 320s
        saved_h64_d2_e64 ep 041/050  loss=0.00381 val_rmse=0.1453 top1=0.189 top3=0.405 reg=0.0376 rank=6.28 328s
        saved_h64_d2_e64 early stop at ep 041; best ep 025
        saved_h64_d2_e96 ep 001/050* loss=0.06833 val_rmse=0.1695 top1=0.137 top3=0.322 reg=0.0870 rank=10.26 8s
        saved_h64_d2_e96 ep 002/050* loss=0.02621 val_rmse=0.1579 top1=0.153 top3=0.350 reg=0.0578 rank=7.77 16s
        saved_h64_d2_e96 ep 003/050* loss=0.02149 val_rmse=0.1560 top1=0.142 top3=0.334 reg=0.0568 rank=7.82 24s
        saved_h64_d2_e96 ep 004/050* loss=0.01873 val_rmse=0.1544 top1=0.151 top3=0.356 reg=0.0509 rank=7.21 32s
        saved_h64_d2_e96 ep 005/050* loss=0.01666 val_rmse=0.1536 top1=0.165 top3=0.374 reg=0.0477 rank=6.92 40s
        saved_h64_d2_e96 ep 006/050* loss=0.01513 val_rmse=0.1519 top1=0.174 top3=0.388 reg=0.0453 rank=6.70 49s
        saved_h64_d2_e96 ep 007/050* loss=0.01376 val_rmse=0.1491 top1=0.173 top3=0.379 reg=0.0408 rank=6.35 57s
        saved_h64_d2_e96 ep 008/050* loss=0.01269 val_rmse=0.1482 top1=0.169 top3=0.388 reg=0.0399 rank=6.32 65s
        saved_h64_d2_e96 ep 009/050* loss=0.01181 val_rmse=0.1453 top1=0.163 top3=0.394 reg=0.0371 rank=6.07 73s
        saved_h64_d2_e96 ep 010/050* loss=0.01099 val_rmse=0.1448 top1=0.175 top3=0.403 reg=0.0370 rank=6.04 82s
        saved_h64_d2_e96 ep 011/050* loss=0.01038 val_rmse=0.1440 top1=0.166 top3=0.399 reg=0.0365 rank=6.02 90s
        saved_h64_d2_e96 ep 012/050* loss=0.00974 val_rmse=0.1448 top1=0.171 top3=0.406 reg=0.0362 rank=6.01 99s
        saved_h64_d2_e96 ep 013/050  loss=0.00926 val_rmse=0.1432 top1=0.159 top3=0.403 reg=0.0362 rank=6.04 107s
        saved_h64_d2_e96 ep 014/050  loss=0.00875 val_rmse=0.1447 top1=0.162 top3=0.399 reg=0.0366 rank=6.09 116s
        saved_h64_d2_e96 ep 015/050  loss=0.00830 val_rmse=0.1437 top1=0.152 top3=0.380 reg=0.0371 rank=6.25 124s
        saved_h64_d2_e96 ep 016/050  loss=0.00786 val_rmse=0.1436 top1=0.159 top3=0.403 reg=0.0384 rank=6.27 133s
        saved_h64_d2_e96 ep 017/050  loss=0.00751 val_rmse=0.1445 top1=0.167 top3=0.401 reg=0.0378 rank=6.21 142s
        saved_h64_d2_e96 ep 018/050  loss=0.00718 val_rmse=0.1435 top1=0.177 top3=0.403 reg=0.0384 rank=6.23 150s
        saved_h64_d2_e96 ep 019/050  loss=0.00691 val_rmse=0.1446 top1=0.173 top3=0.385 reg=0.0399 rank=6.43 158s
        saved_h64_d2_e96 ep 020/050  loss=0.00662 val_rmse=0.1443 top1=0.173 top3=0.409 reg=0.0392 rank=6.33 167s
        saved_h64_d2_e96 ep 021/050  loss=0.00634 val_rmse=0.1446 top1=0.180 top3=0.406 reg=0.0389 rank=6.33 175s
        saved_h64_d2_e96 ep 022/050  loss=0.00612 val_rmse=0.1453 top1=0.190 top3=0.409 reg=0.0384 rank=6.27 183s
        saved_h64_d2_e96 ep 023/050  loss=0.00594 val_rmse=0.1444 top1=0.177 top3=0.408 reg=0.0396 rank=6.37 191s
        saved_h64_d2_e96 ep 024/050  loss=0.00571 val_rmse=0.1454 top1=0.190 top3=0.413 reg=0.0395 rank=6.33 199s
        saved_h64_d2_e96 ep 025/050  loss=0.00554 val_rmse=0.1457 top1=0.182 top3=0.397 reg=0.0400 rank=6.44 208s
        saved_h64_d2_e96 ep 026/050  loss=0.00536 val_rmse=0.1465 top1=0.173 top3=0.401 reg=0.0399 rank=6.41 217s
        saved_h64_d2_e96 ep 027/050  loss=0.00518 val_rmse=0.1458 top1=0.189 top3=0.403 reg=0.0393 rank=6.37 225s
        saved_h64_d2_e96 ep 028/050  loss=0.00506 val_rmse=0.1459 top1=0.197 top3=0.406 reg=0.0386 rank=6.29 234s
        saved_h64_d2_e96 early stop at ep 028; best ep 012

NameError: name 'SAVED_OBJECTIVES' is not defined

In [6]:
SAVED_OBJECTIVES = [
    {"name": "saved_rational", "utility_name": "saved", "utility_kwargs": {}},
    {"name": "contains_closest", "utility_name": "closest_binary", "utility_kwargs": {}},
]

embedding_sweep_own_df = summarize_results(embedding_sweep_results)
embedding_sweep_eval_df = compare_on_common_objectives(
    embedding_sweep_results,
    SAVED_OBJECTIVES,
)

embedding_sweep_test_df = (
    embedding_sweep_eval_df[embedding_sweep_eval_df["split"].eq("test")]
    .sort_values(
        ["eval_objective", "top1", "top3", "mean_rank", "avg_norm_regret"],
        ascending=[True, False, False, True, True],
    )
    .reset_index(drop=True)
)

display(embedding_sweep_own_df)
display(embedding_sweep_test_df)

,run_name,utility,hidden,emb_dim,depth,dropout,combine,loss,best_epoch,train_rmse,...,val_avg_regret,val_avg_norm_regret,test_rmse,test_mae,test_r2,test_top1,test_top3,test_mean_rank,test_avg_regret,test_avg_norm_regret
0,saved_h64_d2_e16,saved,64,16,2,0.05,mul_only,mse,41,0.064033,...,0.030820,0.065023,0.144651,0.104246,0.471710,0.251172,0.445412,5.501674,0.036026,0.071060
1,saved_h64_d2_e32,saved,64,32,2,0.05,mul_only,mse,12,0.084477,...,0.031475,0.065655,0.141825,0.103295,0.492150,0.207636,0.418620,5.637642,0.036882,0.069524
2,saved_h64_d2_e64,saved,64,64,2,0.05,mul_only,mse,25,0.060218,...,0.034535,0.073889,0.142028,0.100700,0.490691,0.131279,0.344943,6.019424,0.042712,0.079012
3,saved_h64_d2_e96,saved,64,96,2,0.05,mul_only,mse,12,0.087122,...,0.036180,0.075328,0.142927,0.104996,0.484226,0.149364,0.356999,6.079035,0.036553,0.073278

,run_name,train_utility,eval_objective,split,hidden,emb_dim,combine,top1,top3,mean_rank,avg_regret,avg_norm_regret
0,saved_h64_d2_e32,saved,contains_closest,test,64,32,mul_only,0.924313,0.924313,2.210985,0.075687,0.075687
1,saved_h64_d2_e96,saved,contains_closest,test,64,96,mul_only,0.918955,0.918955,2.296718,0.081045,0.081045
2,saved_h64_d2_e64,saved,contains_closest,test,64,64,mul_only,0.905559,0.905559,2.511052,0.094441,0.094441
3,saved_h64_d2_e16,saved,contains_closest,test,64,16,mul_only,0.902210,0.902210,2.564635,0.097790,0.097790
4,saved_h64_d2_e16,saved,saved_rational,test,64,16,mul_only,0.251172,0.445412,5.501674,0.036026,0.071060
5,saved_h64_d2_e32,saved,saved_rational,test,64,32,mul_only,0.207636,0.418620,5.637642,0.036882,0.069524
6,saved_h64_d2_e96,saved,saved_rational,test,64,96,mul_only,0.149364,0.356999,6.079035,0.036553,0.073278
7,saved_h64_d2_e64,saved,saved_rational,test,64,64,mul_only,0.131279,0.344943,6.019424,0.042712,0.079012

In [8]:
# Saved-utility stability sweep. Compare the simple baseline against the strongest width candidate.
# This keeps the utility fixed and checks whether architecture differences survive seed variation.

SAVED_OBJECTIVES = [
    {"name": "saved_rational", "utility_name": "saved", "utility_kwargs": {}},
    {"name": "contains_closest", "utility_name": "closest_binary", "utility_kwargs": {}},
]

SEEDS = [11, 22, 33, 44, 55]
SEED_SWEEP_CONFIGS = []

for seed in SEEDS:
    SEED_SWEEP_CONFIGS.append(
        TrainConfig(
            run_name=f"saved_h64_d2_e8_seed{seed}",
            utility_name="saved",
            hidden=64,
            emb_dim=8,
            depth=2,
            dropout=0.05,
            combine_mode="mul_only",
            loss_name="mse",
            max_epochs=50,
            patience=16,
            batch_size=8192,
            lr=1e-3,
            weight_decay=1e-4,
            seed=seed,
            log_every=1,
        )
    )
    SEED_SWEEP_CONFIGS.append(
        TrainConfig(
            run_name=f"saved_h512_d2_e8_seed{seed}",
            utility_name="saved",
            hidden=512,
            emb_dim=8,
            depth=2,
            dropout=0.05,
            combine_mode="mul_only",
            loss_name="mse",
            max_epochs=50,
            patience=16,
            batch_size=8192,
            lr=1e-3,
            weight_decay=1e-4,
            seed=seed,
            log_every=1,
        )
    )

seed_sweep_results = run_config_grid(
    PROCESSED_DIR,
    SEED_SWEEP_CONFIGS,
    prefix=PREFIX,
    max_time_steps=MAX_TIME_STEPS,
    device=DEVICE,
)

seed_sweep_own_df = summarize_results(seed_sweep_results)
seed_sweep_eval_df = compare_on_common_objectives(seed_sweep_results, SAVED_OBJECTIVES)

seed_sweep_test_df = (
    seed_sweep_eval_df[seed_sweep_eval_df["split"].eq("test")]
    .sort_values(
        ["eval_objective", "top1", "top3", "mean_rank", "avg_norm_regret"],
        ascending=[True, False, False, True, True],
    )
    .reset_index(drop=True)
)

seed_sweep_summary_df = (
    seed_sweep_eval_df[seed_sweep_eval_df["split"].eq("test")]
    .assign(architecture=lambda df: df["hidden"].astype(str).radd("h") + "_e" + df["emb_dim"].astype(str))
    .groupby(["eval_objective", "architecture"], as_index=False)
    .agg(
        top1_mean=("top1", "mean"),
        top1_std=("top1", "std"),
        top3_mean=("top3", "mean"),
        top3_std=("top3", "std"),
        mean_rank_mean=("mean_rank", "mean"),
        mean_rank_std=("mean_rank", "std"),
        avg_regret_mean=("avg_regret", "mean"),
        avg_regret_std=("avg_regret", "std"),
        avg_norm_regret_mean=("avg_norm_regret", "mean"),
        avg_norm_regret_std=("avg_norm_regret", "std"),
    )
    .sort_values(["eval_objective", "avg_norm_regret_mean", "mean_rank_mean"])
    .reset_index(drop=True)
)

display(seed_sweep_own_df)
display(seed_sweep_test_df)
display(seed_sweep_summary_df)

  saved_h64_d2_e8_seed11 ep 001/050* loss=0.07894 val_rmse=0.1678 top1=0.116 top3=0.242 reg=0.1037 rank=10.60 10s
  saved_h64_d2_e8_seed11 ep 002/050* loss=0.03131 val_rmse=0.1575 top1=0.205 top3=0.374 reg=0.0681 rank=8.09 19s
  saved_h64_d2_e8_seed11 ep 003/050* loss=0.02538 val_rmse=0.1505 top1=0.190 top3=0.384 reg=0.0549 rank=7.36 28s
  saved_h64_d2_e8_seed11 ep 004/050* loss=0.02235 val_rmse=0.1489 top1=0.186 top3=0.395 reg=0.0505 rank=7.14 37s
  saved_h64_d2_e8_seed11 ep 005/050* loss=0.02031 val_rmse=0.1465 top1=0.190 top3=0.407 reg=0.0467 rank=6.81 45s
  saved_h64_d2_e8_seed11 ep 006/050* loss=0.01878 val_rmse=0.1455 top1=0.196 top3=0.417 reg=0.0451 rank=6.70 53s
  saved_h64_d2_e8_seed11 ep 007/050* loss=0.01738 val_rmse=0.1445 top1=0.182 top3=0.417 reg=0.0440 rank=6.63 61s
  saved_h64_d2_e8_seed11 ep 008/050* loss=0.01619 val_rmse=0.1440 top1=0.173 top3=0.416 reg=0.0426 rank=6.52 69s
  saved_h64_d2_e8_seed11 ep 009/050* loss=0.01521 val_rmse=0.1429 top1=0.175 top3=0.409 reg=0.0407 rank=6.42 77s
  saved_h64_d2_e8_seed11 ep 010/050* loss=0.01434 val_rmse=0.1428 top1=0.188 top3=0.429 reg=0.0392 rank=6.16 85s
  saved_h64_d2_e8_seed11 ep 011/050* loss=0.01351 val_rmse=0.1415 top1=0.187 top3=0.433 reg=0.0359 rank=5.86 92s
  saved_h64_d2_e8_seed11 ep 012/050  loss=0.01283 val_rmse=0.1423 top1=0.180 top3=0.413 reg=0.0361 rank=5.97 100s
  saved_h64_d2_e8_seed11 ep 013/050* loss=0.01218 val_rmse=0.1418 top1=0.180 top3=0.418 reg=0.0340 rank=5.77 108s
  saved_h64_d2_e8_seed11 ep 014/050* loss=0.01161 val_rmse=0.1430 top1=0.180 top3=0.423 reg=0.0336 rank=5.71 116s
  saved_h64_d2_e8_seed11 ep 015/050* loss=0.01107 val_rmse=0.1410 top1=0.172 top3=0.423 reg=0.0333 rank=5.69 125s
  saved_h64_d2_e8_seed11 ep 016/050  loss=0.01059 val_rmse=0.1416 top1=0.160 top3=0.413 reg=0.0345 rank=5.84 133s
  saved_h64_d2_e8_seed11 ep 017/050  loss=0.01013 val_rmse=0.1412 top1=0.171 top3=0.429 reg=0.0336 rank=5.73 141s
  saved_h64_d2_e8_seed11 ep 018/050  loss=0.00973 val_rmse=0.1414 top1=0.158 top3=0.416 reg=0.0334 rank=5.79 149s
  saved_h64_d2_e8_seed11 ep 019/050  loss=0.00936 val_rmse=0.1425 top1=0.158 top3=0.412 reg=0.0343 rank=5.87 157s
  saved_h64_d2_e8_seed11 ep 020/050* loss=0.00902 val_rmse=0.1396 top1=0.176 top3=0.425 reg=0.0324 rank=5.67 165s
  saved_h64_d2_e8_seed11 ep 021/050  loss=0.00873 val_rmse=0.1407 top1=0.184 top3=0.425 reg=0.0331 rank=5.70 173s
  saved_h64_d2_e8_seed11 ep 022/050  loss=0.00845 val_rmse=0.1409 top1=0.189 top3=0.417 reg=0.0326 rank=5.63 181s
  saved_h64_d2_e8_seed11 ep 023/050  loss=0.00819 val_rmse=0.1400 top1=0.190 top3=0.401 reg=0.0327 rank=5.69 188s
  saved_h64_d2_e8_seed11 ep 024/050  loss=0.00799 val_rmse=0.1395 top1=0.183 top3=0.405 reg=0.0340 rank=5.84 197s
  saved_h64_d2_e8_seed11 ep 025/050* loss=0.00777 val_rmse=0.1393 top1=0.204 top3=0.422 reg=0.0316 rank=5.54 206s
  saved_h64_d2_e8_seed11 ep 026/050  loss=0.00754 val_rmse=0.1383 top1=0.188 top3=0.405 reg=0.0323 rank=5.65 214s
  saved_h64_d2_e8_seed11 ep 027/050* loss=0.00735 val_rmse=0.1374 top1=0.202 top3=0.407 reg=0.0313 rank=5.51 224s
  saved_h64_d2_e8_seed11 ep 028/050  loss=0.00715 val_rmse=0.1384 top1=0.187 top3=0.419 reg=0.0330 rank=5.67 232s
  saved_h64_d2_e8_seed11 ep 029/050  loss=0.00696 val_rmse=0.1372 top1=0.196 top3=0.419 reg=0.0314 rank=5.54 240s
  saved_h64_d2_e8_seed11 ep 030/050* loss=0.00679 val_rmse=0.1386 top1=0.214 top3=0.439 reg=0.0313 rank=5.48 248s
  saved_h64_d2_e8_seed11 ep 031/050  loss=0.00668 val_rmse=0.1381 top1=0.203 top3=0.429 reg=0.0320 rank=5.60 256s
  saved_h64_d2_e8_seed11 ep 032/050  loss=0.00652 val_rmse=0.1383 top1=0.212 top3=0.435 reg=0.0324 rank=5.62 264s
  saved_h64_d2_e8_seed11 ep 033/050  loss=0.00637 val_rmse=0.1381 top1=0.224 top3=0.443 reg=0.0320 rank=5.56 272s
  saved_h64_d2_e8_seed11 ep 034/050  loss=0.00628 val_rmse=0.1376 top1=0.229 top3=0.456 reg=0.0321 rank=5.51 280s
  saved_h64_d2_e8_seed11 ep 035/050* loss=0.00612 val_rmse=0.1386 top1=0.235 top3=0.461 reg=0.0310 rank=5.37 288s
  saved_h64_d2_e8_seed11 ep 036/050  loss=0.00602 val_rmse=0.1371 top1=0.235 top3=0.461 reg=0.0316 rank=5.49 296s
  saved_h64_d2_e8_seed11 ep 037/050  loss=0.00589 val_rmse=0.1369 top1=0.230 top3=0.459 reg=0.0327 rank=5.63 303s
  saved_h64_d2_e8_seed11 ep 038/050  loss=0.00581 val_rmse=0.1398 top1=0.232 top3=0.461 reg=0.0325 rank=5.59 311s
  saved_h64_d2_e8_seed11 ep 039/050  loss=0.00572 val_rmse=0.1390 top1=0.230 top3=0.455 reg=0.0334 rank=5.69 319s
  saved_h64_d2_e8_seed11 ep 040/050  loss=0.00564 val_rmse=0.1391 top1=0.242 top3=0.460 reg=0.0332 rank=5.69 326s
  saved_h64_d2_e8_seed11 ep 041/050  loss=0.00554 val_rmse=0.1400 top1=0.232 top3=0.454 reg=0.0338 rank=5.77 334s
  saved_h64_d2_e8_seed11 ep 042/050  loss=0.00544 val_rmse=0.1397 top1=0.232 top3=0.449 reg=0.0341 rank=5.80 343s
  saved_h64_d2_e8_seed11 ep 043/050  loss=0.00535 val_rmse=0.1391 top1=0.240 top3=0.443 reg=0.0338 rank=5.74 350s
  saved_h64_d2_e8_seed11 ep 044/050  loss=0.00529 val_rmse=0.1395 top1=0.247 top3=0.452 reg=0.0334 rank=5.68 358s
  saved_h64_d2_e8_seed11 ep 045/050  loss=0.00519 val_rmse=0.1391 top1=0.258 top3=0.458 reg=0.0328 rank=5.61 367s
  saved_h64_d2_e8_seed11 ep 046/050  loss=0.00511 val_rmse=0.1400 top1=0.236 top3=0.457 reg=0.0343 rank=5.76 375s
  saved_h64_d2_e8_seed11 ep 047/050  loss=0.00505 val_rmse=0.1410 top1=0.233 top3=0.447 reg=0.0348 rank=5.83 383s
  saved_h64_d2_e8_seed11 ep 048/050  loss=0.00499 val_rmse=0.1406 top1=0.251 top3=0.455 reg=0.0343 rank=5.78 391s
  saved_h64_d2_e8_seed11 ep 049/050  loss=0.00489 val_rmse=0.1407 top1=0.240 top3=0.455 reg=0.0348 rank=5.81 398s
  saved_h64_d2_e8_seed11 ep 050/050  loss=0.00484 val_rmse=0.1397 top1=0.247 top3=0.471 reg=0.0335 rank=5.67 406s
 saved_h512_d2_e8_seed11 ep 001/050* loss=0.05052 val_rmse=0.1603 top1=0.105 top3=0.366 reg=0.0607 rank=7.91 9s
 saved_h512_d2_e8_seed11 ep 002/050* loss=0.02243 val_rmse=0.1470 top1=0.083 top3=0.322 reg=0.0505 rank=7.18 17s
 saved_h512_d2_e8_seed11 ep 003/050* loss=0.01719 val_rmse=0.1460 top1=0.113 top3=0.345 reg=0.0450 rank=6.77 27s
 saved_h512_d2_e8_seed11 ep 004/050* loss=0.01417 val_rmse=0.1472 top1=0.124 top3=0.337 reg=0.0413 rank=6.55 37s
 saved_h512_d2_e8_seed11 ep 005/050* loss=0.01205 val_rmse=0.1475 top1=0.138 top3=0.371 reg=0.0390 rank=6.31 46s
 saved_h512_d2_e8_seed11 ep 006/050* loss=0.01040 val_rmse=0.1457 top1=0.159 top3=0.406 reg=0.0349 rank=5.87 54s
 saved_h512_d2_e8_seed11 ep 007/050  loss=0.00917 val_rmse=0.1455 top1=0.153 top3=0.400 reg=0.0351 rank=5.92 63s
 saved_h512_d2_e8_seed11 ep 008/050* loss=0.00821 val_rmse=0.1435 top1=0.165 top3=0.419 reg=0.0344 rank=5.77 71s
 saved_h512_d2_e8_seed11 ep 009/050* loss=0.00743 val_rmse=0.1431 top1=0.183 top3=0.434 reg=0.0324 rank=5.54 82s
 saved_h512_d2_e8_seed11 ep 010/050  loss=0.00679 val_rmse=0.1454 top1=0.194 top3=0.461 reg=0.0326 rank=5.43 92s
 saved_h512_d2_e8_seed11 ep 011/050* loss=0.00629 val_rmse=0.1439 top1=0.205 top3=0.447 reg=0.0322 rank=5.46 102s
 saved_h512_d2_e8_seed11 ep 012/050  loss=0.00586 val_rmse=0.1453 top1=0.219 top3=0.460 reg=0.0325 rank=5.46 111s
 saved_h512_d2_e8_seed11 ep 013/050* loss=0.00550 val_rmse=0.1418 top1=0.235 top3=0.472 reg=0.0306 rank=5.24 120s
 saved_h512_d2_e8_seed11 ep 014/050  loss=0.00519 val_rmse=0.1434 top1=0.220 top3=0.453 reg=0.0317 rank=5.43 129s
 saved_h512_d2_e8_seed11 ep 015/050  loss=0.00489 val_rmse=0.1474 top1=0.240 top3=0.451 reg=0.0331 rank=5.53 139s
 saved_h512_d2_e8_seed11 ep 016/050  loss=0.00463 val_rmse=0.1440 top1=0.231 top3=0.461 reg=0.0317 rank=5.48 147s
 saved_h512_d2_e8_seed11 ep 017/050  loss=0.00443 val_rmse=0.1452 top1=0.235 top3=0.443 reg=0.0318 rank=5.48 157s
 saved_h512_d2_e8_seed11 ep 018/050  loss=0.00421 val_rmse=0.1469 top1=0.240 top3=0.459 reg=0.0307 rank=5.37 166s
 saved_h512_d2_e8_seed11 ep 019/050  loss=0.00403 val_rmse=0.1471 top1=0.239 top3=0.457 reg=0.0308 rank=5.45 175s
 saved_h512_d2_e8_seed11 ep 020/050* loss=0.00385 val_rmse=0.1458 top1=0.253 top3=0.470 reg=0.0298 rank=5.32 184s
 saved_h512_d2_e8_seed11 ep 021/050  loss=0.00371 val_rmse=0.1453 top1=0.243 top3=0.455 reg=0.0318 rank=5.53 192s
 saved_h512_d2_e8_seed11 ep 022/050* loss=0.00358 val_rmse=0.1443 top1=0.255 top3=0.476 reg=0.0292 rank=5.22 201s
 saved_h512_d2_e8_seed11 ep 023/050  loss=0.00345 val_rmse=0.1458 top1=0.231 top3=0.453 reg=0.0315 rank=5.51 211s
 saved_h512_d2_e8_seed11 ep 024/050  loss=0.00328 val_rmse=0.1451 top1=0.236 top3=0.467 reg=0.0293 rank=5.25 220s
 saved_h512_d2_e8_seed11 ep 025/050  loss=0.00319 val_rmse=0.1435 top1=0.251 top3=0.478 reg=0.0294 rank=5.26 228s
 saved_h512_d2_e8_seed11 ep 026/050  loss=0.00307 val_rmse=0.1438 top1=0.246 top3=0.476 reg=0.0299 rank=5.29 237s
 saved_h512_d2_e8_seed11 ep 027/050  loss=0.00296 val_rmse=0.1446 top1=0.250 top3=0.485 reg=0.0299 rank=5.26 246s
 saved_h512_d2_e8_seed11 ep 028/050  loss=0.00288 val_rmse=0.1451 top1=0.247 top3=0.482 reg=0.0305 rank=5.27 255s
 saved_h512_d2_e8_seed11 ep 029/050  loss=0.00279 val_rmse=0.1436 top1=0.254 top3=0.482 reg=0.0294 rank=5.19 264s
 saved_h512_d2_e8_seed11 ep 030/050  loss=0.00269 val_rmse=0.1432 top1=0.256 top3=0.490 reg=0.0295 rank=5.19 273s
 saved_h512_d2_e8_seed11 ep 031/050  loss=0.00261 val_rmse=0.1449 top1=0.245 top3=0.478 reg=0.0306 rank=5.36 281s
 saved_h512_d2_e8_seed11 ep 032/050  loss=0.00254 val_rmse=0.1446 top1=0.229 top3=0.463 reg=0.0305 rank=5.35 289s
 saved_h512_d2_e8_seed11 ep 033/050  loss=0.00245 val_rmse=0.1431 top1=0.253 top3=0.477 reg=0.0297 rank=5.20 298s
 saved_h512_d2_e8_seed11 ep 034/050  loss=0.00239 val_rmse=0.1466 top1=0.242 top3=0.471 reg=0.0307 rank=5.35 307s
 saved_h512_d2_e8_seed11 ep 035/050* loss=0.00230 val_rmse=0.1436 top1=0.271 top3=0.510 reg=0.0275 rank=4.98 317s
 saved_h512_d2_e8_seed11 ep 036/050  loss=0.00224 val_rmse=0.1427 top1=0.259 top3=0.500 reg=0.0295 rank=5.23 327s
 saved_h512_d2_e8_seed11 ep 037/050  loss=0.00217 val_rmse=0.1443 top1=0.256 top3=0.490 reg=0.0308 rank=5.28 336s
 saved_h512_d2_e8_seed11 ep 038/050  loss=0.00209 val_rmse=0.1449 top1=0.265 top3=0.505 reg=0.0295 rank=5.19 345s
 saved_h512_d2_e8_seed11 ep 039/050  loss=0.00204 val_rmse=0.1455 top1=0.260 top3=0.489 reg=0.0315 rank=5.33 355s
 saved_h512_d2_e8_seed11 ep 040/050  loss=0.00197 val_rmse=0.1445 top1=0.255 top3=0.484 reg=0.0304 rank=5.29 365s
 saved_h512_d2_e8_seed11 ep 041/050  loss=0.00189 val_rmse=0.1422 top1=0.266 top3=0.498 reg=0.0293 rank=5.12 373s
 saved_h512_d2_e8_seed11 ep 042/050  loss=0.00183 val_rmse=0.1458 top1=0.262 top3=0.492 reg=0.0308 rank=5.34 381s
 saved_h512_d2_e8_seed11 ep 043/050  loss=0.00177 val_rmse=0.1452 top1=0.269 top3=0.497 reg=0.0313 rank=5.31 391s
 saved_h512_d2_e8_seed11 ep 044/050  loss=0.00174 val_rmse=0.1437 top1=0.274 top3=0.496 reg=0.0315 rank=5.28 399s
 saved_h512_d2_e8_seed11 ep 045/050  loss=0.00169 val_rmse=0.1434 top1=0.275 top3=0.500 reg=0.0310 rank=5.28 409s
 saved_h512_d2_e8_seed11 ep 046/050  loss=0.00163 val_rmse=0.1433 top1=0.298 top3=0.522 reg=0.0299 rank=5.14 417s
 saved_h512_d2_e8_seed11 ep 047/050  loss=0.00159 val_rmse=0.1442 top1=0.257 top3=0.490 reg=0.0326 rank=5.45 427s
 saved_h512_d2_e8_seed11 ep 048/050  loss=0.00156 val_rmse=0.1441 top1=0.266 top3=0.494 reg=0.0311 rank=5.33 435s
 saved_h512_d2_e8_seed11 ep 049/050  loss=0.00152 val_rmse=0.1435 top1=0.291 top3=0.518 reg=0.0299 rank=5.19 444s
 saved_h512_d2_e8_seed11 ep 050/050  loss=0.00147 val_rmse=0.1440 top1=0.263 top3=0.490 reg=0.0309 rank=5.31 453s
  saved_h64_d2_e8_seed22 ep 001/050* loss=0.05257 val_rmse=0.1707 top1=0.177 top3=0.382 reg=0.0686 rank=8.33 8s
  saved_h64_d2_e8_seed22 ep 002/050* loss=0.02687 val_rmse=0.1550 top1=0.226 top3=0.441 reg=0.0415 rank=6.16 17s
  saved_h64_d2_e8_seed22 ep 003/050* loss=0.02241 val_rmse=0.1501 top1=0.215 top3=0.442 reg=0.0403 rank=6.00 25s
  saved_h64_d2_e8_seed22 ep 004/050  loss=0.01974 val_rmse=0.1485 top1=0.182 top3=0.421 reg=0.0420 rank=6.18 33s
  saved_h64_d2_e8_seed22 ep 005/050* loss=0.01775 val_rmse=0.1480 top1=0.193 top3=0.429 reg=0.0393 rank=5.92 41s
  saved_h64_d2_e8_seed22 ep 006/050* loss=0.01631 val_rmse=0.1459 top1=0.196 top3=0.423 reg=0.0375 rank=5.80 49s
  saved_h64_d2_e8_seed22 ep 007/050* loss=0.01510 val_rmse=0.1436 top1=0.200 top3=0.413 reg=0.0368 rank=5.80 58s
  saved_h64_d2_e8_seed22 ep 008/050  loss=0.01417 val_rmse=0.1450 top1=0.214 top3=0.420 reg=0.0370 rank=5.82 66s
  saved_h64_d2_e8_seed22 ep 009/050* loss=0.01330 val_rmse=0.1440 top1=0.219 top3=0.421 reg=0.0366 rank=5.79 74s
  saved_h64_d2_e8_seed22 ep 010/050* loss=0.01253 val_rmse=0.1444 top1=0.228 top3=0.427 reg=0.0358 rank=5.73 82s
  saved_h64_d2_e8_seed22 ep 011/050  loss=0.01186 val_rmse=0.1427 top1=0.223 top3=0.417 reg=0.0379 rank=6.01 90s
  saved_h64_d2_e8_seed22 ep 012/050  loss=0.01113 val_rmse=0.1427 top1=0.220 top3=0.403 reg=0.0377 rank=6.07 99s
  saved_h64_d2_e8_seed22 ep 013/050  loss=0.01060 val_rmse=0.1423 top1=0.233 top3=0.418 reg=0.0365 rank=5.89 107s
  saved_h64_d2_e8_seed22 ep 014/050* loss=0.01003 val_rmse=0.1409 top1=0.244 top3=0.425 reg=0.0352 rank=5.82 117s
  saved_h64_d2_e8_seed22 ep 015/050* loss=0.00954 val_rmse=0.1404 top1=0.249 top3=0.435 reg=0.0344 rank=5.75 125s
  saved_h64_d2_e8_seed22 ep 016/050  loss=0.00909 val_rmse=0.1407 top1=0.261 top3=0.443 reg=0.0351 rank=5.80 134s
  saved_h64_d2_e8_seed22 ep 017/050* loss=0.00870 val_rmse=0.1382 top1=0.274 top3=0.461 reg=0.0318 rank=5.49 142s
  saved_h64_d2_e8_seed22 ep 018/050* loss=0.00831 val_rmse=0.1382 top1=0.291 top3=0.466 reg=0.0307 rank=5.38 151s
  saved_h64_d2_e8_seed22 ep 019/050* loss=0.00803 val_rmse=0.1390 top1=0.293 top3=0.478 reg=0.0304 rank=5.29 162s
  saved_h64_d2_e8_seed22 ep 020/050* loss=0.00771 val_rmse=0.1387 top1=0.298 top3=0.497 reg=0.0294 rank=5.21 173s
  saved_h64_d2_e8_seed22 ep 021/050  loss=0.00744 val_rmse=0.1381 top1=0.308 top3=0.498 reg=0.0302 rank=5.29 183s
  saved_h64_d2_e8_seed22 ep 022/050  loss=0.00720 val_rmse=0.1384 top1=0.311 top3=0.506 reg=0.0297 rank=5.21 191s
  saved_h64_d2_e8_seed22 ep 023/050  loss=0.00694 val_rmse=0.1390 top1=0.308 top3=0.496 reg=0.0303 rank=5.31 201s
  saved_h64_d2_e8_seed22 ep 024/050* loss=0.00674 val_rmse=0.1382 top1=0.314 top3=0.491 reg=0.0292 rank=5.22 210s
  saved_h64_d2_e8_seed22 ep 025/050  loss=0.00653 val_rmse=0.1392 top1=0.301 top3=0.491 reg=0.0306 rank=5.35 219s
  saved_h64_d2_e8_seed22 ep 026/050  loss=0.00631 val_rmse=0.1397 top1=0.315 top3=0.496 reg=0.0295 rank=5.25 227s
  saved_h64_d2_e8_seed22 ep 027/050  loss=0.00615 val_rmse=0.1381 top1=0.320 top3=0.500 reg=0.0295 rank=5.24 235s
  saved_h64_d2_e8_seed22 ep 028/050* loss=0.00601 val_rmse=0.1380 top1=0.332 top3=0.506 reg=0.0284 rank=5.12 244s
  saved_h64_d2_e8_seed22 ep 029/050  loss=0.00582 val_rmse=0.1391 top1=0.322 top3=0.504 reg=0.0299 rank=5.21 252s
  saved_h64_d2_e8_seed22 ep 030/050  loss=0.00567 val_rmse=0.1392 top1=0.313 top3=0.494 reg=0.0293 rank=5.24 261s
  saved_h64_d2_e8_seed22 ep 031/050  loss=0.00556 val_rmse=0.1381 top1=0.315 top3=0.502 reg=0.0297 rank=5.29 269s
  saved_h64_d2_e8_seed22 ep 032/050  loss=0.00541 val_rmse=0.1396 top1=0.318 top3=0.518 reg=0.0292 rank=5.18 277s
  saved_h64_d2_e8_seed22 ep 033/050  loss=0.00526 val_rmse=0.1395 top1=0.320 top3=0.508 reg=0.0289 rank=5.16 286s
  saved_h64_d2_e8_seed22 ep 034/050  loss=0.00515 val_rmse=0.1394 top1=0.307 top3=0.497 reg=0.0294 rank=5.23 294s
  saved_h64_d2_e8_seed22 ep 035/050  loss=0.00503 val_rmse=0.1394 top1=0.324 top3=0.506 reg=0.0293 rank=5.15 302s
  saved_h64_d2_e8_seed22 ep 036/050  loss=0.00488 val_rmse=0.1389 top1=0.318 top3=0.508 reg=0.0295 rank=5.17 310s
  saved_h64_d2_e8_seed22 ep 037/050  loss=0.00480 val_rmse=0.1389 top1=0.322 top3=0.513 reg=0.0292 rank=5.17 318s
  saved_h64_d2_e8_seed22 ep 038/050  loss=0.00470 val_rmse=0.1386 top1=0.302 top3=0.482 reg=0.0307 rank=5.33 327s
  saved_h64_d2_e8_seed22 ep 039/050  loss=0.00462 val_rmse=0.1398 top1=0.299 top3=0.503 reg=0.0295 rank=5.20 335s
  saved_h64_d2_e8_seed22 ep 040/050  loss=0.00454 val_rmse=0.1392 top1=0.312 top3=0.510 reg=0.0291 rank=5.18 343s
  saved_h64_d2_e8_seed22 ep 041/050  loss=0.00446 val_rmse=0.1398 top1=0.317 top3=0.524 reg=0.0288 rank=5.03 352s
  saved_h64_d2_e8_seed22 ep 042/050  loss=0.00436 val_rmse=0.1397 top1=0.338 top3=0.529 reg=0.0287 rank=5.05 360s
  saved_h64_d2_e8_seed22 ep 043/050  loss=0.00426 val_rmse=0.1408 top1=0.324 top3=0.536 reg=0.0284 rank=5.02 369s
  saved_h64_d2_e8_seed22 ep 044/050  loss=0.00419 val_rmse=0.1408 top1=0.311 top3=0.522 reg=0.0285 rank=5.07 377s
  saved_h64_d2_e8_seed22 early stop at ep 044; best ep 028
 saved_h512_d2_e8_seed22 ep 001/050* loss=0.05532 val_rmse=0.1516 top1=0.186 top3=0.384 reg=0.0543 rank=7.40 9s
 saved_h512_d2_e8_seed22 ep 002/050* loss=0.02229 val_rmse=0.1470 top1=0.139 top3=0.338 reg=0.0461 rank=6.79 18s
 saved_h512_d2_e8_seed22 ep 003/050* loss=0.01735 val_rmse=0.1471 top1=0.149 top3=0.368 reg=0.0428 rank=6.43 28s
 saved_h512_d2_e8_seed22 ep 004/050* loss=0.01476 val_rmse=0.1472 top1=0.166 top3=0.378 reg=0.0415 rank=6.27 36s
 saved_h512_d2_e8_seed22 ep 005/050* loss=0.01294 val_rmse=0.1480 top1=0.185 top3=0.402 reg=0.0392 rank=6.01 45s
 saved_h512_d2_e8_seed22 ep 006/050* loss=0.01155 val_rmse=0.1497 top1=0.216 top3=0.435 reg=0.0366 rank=5.74 54s
 saved_h512_d2_e8_seed22 ep 007/050* loss=0.01042 val_rmse=0.1491 top1=0.211 top3=0.429 reg=0.0364 rank=5.74 63s
 saved_h512_d2_e8_seed22 ep 008/050* loss=0.00950 val_rmse=0.1474 top1=0.208 top3=0.439 reg=0.0345 rank=5.59 72s
 saved_h512_d2_e8_seed22 ep 009/050* loss=0.00869 val_rmse=0.1471 top1=0.216 top3=0.435 reg=0.0331 rank=5.54 81s
 saved_h512_d2_e8_seed22 ep 010/050  loss=0.00801 val_rmse=0.1498 top1=0.224 top3=0.444 reg=0.0334 rank=5.48 90s
 saved_h512_d2_e8_seed22 ep 011/050  loss=0.00743 val_rmse=0.1512 top1=0.216 top3=0.427 reg=0.0352 rank=5.81 99s
 saved_h512_d2_e8_seed22 ep 012/050  loss=0.00697 val_rmse=0.1515 top1=0.220 top3=0.426 reg=0.0348 rank=5.76 107s
 saved_h512_d2_e8_seed22 ep 013/050  loss=0.00650 val_rmse=0.1508 top1=0.221 top3=0.418 reg=0.0355 rank=5.83 116s
 saved_h512_d2_e8_seed22 ep 014/050  loss=0.00608 val_rmse=0.1500 top1=0.235 top3=0.426 reg=0.0348 rank=5.74 125s
 saved_h512_d2_e8_seed22 ep 015/050  loss=0.00576 val_rmse=0.1541 top1=0.222 top3=0.408 reg=0.0339 rank=5.75 134s
 saved_h512_d2_e8_seed22 ep 016/050  loss=0.00540 val_rmse=0.1530 top1=0.217 top3=0.399 reg=0.0351 rank=5.93 143s
 saved_h512_d2_e8_seed22 ep 017/050* loss=0.00509 val_rmse=0.1493 top1=0.262 top3=0.451 reg=0.0322 rank=5.53 152s
 saved_h512_d2_e8_seed22 ep 018/050  loss=0.00480 val_rmse=0.1500 top1=0.238 top3=0.412 reg=0.0341 rank=5.74 162s
 saved_h512_d2_e8_seed22 ep 019/050  loss=0.00458 val_rmse=0.1500 top1=0.245 top3=0.431 reg=0.0338 rank=5.69 171s
 saved_h512_d2_e8_seed22 ep 020/050  loss=0.00436 val_rmse=0.1477 top1=0.246 top3=0.439 reg=0.0332 rank=5.64 179s
 saved_h512_d2_e8_seed22 ep 021/050  loss=0.00414 val_rmse=0.1495 top1=0.228 top3=0.412 reg=0.0333 rank=5.72 188s
 saved_h512_d2_e8_seed22 ep 022/050  loss=0.00395 val_rmse=0.1478 top1=0.242 top3=0.415 reg=0.0330 rank=5.71 197s
 saved_h512_d2_e8_seed22 ep 023/050  loss=0.00377 val_rmse=0.1477 top1=0.251 top3=0.451 reg=0.0326 rank=5.66 206s
 saved_h512_d2_e8_seed22 ep 024/050  loss=0.00361 val_rmse=0.1490 top1=0.246 top3=0.426 reg=0.0339 rank=5.72 215s
 saved_h512_d2_e8_seed22 ep 025/050  loss=0.00344 val_rmse=0.1493 top1=0.247 top3=0.430 reg=0.0335 rank=5.72 224s
 saved_h512_d2_e8_seed22 ep 026/050  loss=0.00330 val_rmse=0.1488 top1=0.243 top3=0.425 reg=0.0332 rank=5.75 232s
 saved_h512_d2_e8_seed22 ep 027/050* loss=0.00317 val_rmse=0.1490 top1=0.253 top3=0.434 reg=0.0321 rank=5.54 241s
 saved_h512_d2_e8_seed22 ep 028/050  loss=0.00305 val_rmse=0.1496 top1=0.240 top3=0.423 reg=0.0343 rank=5.74 250s
 saved_h512_d2_e8_seed22 ep 029/050  loss=0.00293 val_rmse=0.1491 top1=0.254 top3=0.441 reg=0.0330 rank=5.63 259s
 saved_h512_d2_e8_seed22 ep 030/050  loss=0.00281 val_rmse=0.1485 top1=0.249 top3=0.427 reg=0.0337 rank=5.74 268s
 saved_h512_d2_e8_seed22 ep 031/050  loss=0.00271 val_rmse=0.1493 top1=0.251 top3=0.413 reg=0.0343 rank=5.75 277s

,run_name,utility,hidden,emb_dim,depth,dropout,combine,loss,best_epoch,train_rmse,...,val_avg_regret,val_avg_norm_regret,test_rmse,test_mae,test_r2,test_top1,test_top3,test_mean_rank,test_avg_regret,test_avg_norm_regret
0,saved_h512_d2_e8_seed11,saved,512,8,2,0.05,mul_only,mse,35,0.033868,...,0.027523,0.060771,0.140221,0.100297,0.503570,0.262559,0.470194,5.296718,0.037829,0.070760
1,saved_h64_d2_e8_seed22,saved,64,8,2,0.05,mul_only,mse,28,0.065148,...,0.028372,0.061452,0.137434,0.098280,0.523109,0.308104,0.460817,5.182184,0.032348,0.061981
2,saved_h64_d2_e8_seed11,saved,64,8,2,0.05,mul_only,mse,35,0.065579,...,0.031021,0.064959,0.140620,0.101201,0.500741,0.183523,0.406564,5.776959,0.038139,0.074261
3,saved_h512_d2_e8_seed44,saved,512,8,2,0.05,mul_only,mse,7,0.081699,...,0.031890,0.066005,0.142707,0.105567,0.485813,0.158071,0.398526,5.570663,0.033920,0.066559
4,saved_h64_d2_e8_seed44,saved,64,8,2,0.05,mul_only,mse,49,0.054820,...,0.031993,0.069547,0.139696,0.099810,0.507278,0.248493,0.462827,5.746149,0.040587,0.078086
5,saved_h512_d2_e8_seed22,saved,512,8,2,0.05,mul_only,mse,27,0.041826,...,0.032077,0.066986,0.138532,0.099658,0.515453,0.237776,0.447421,5.308774,0.033974,0.065375
6,saved_h512_d2_e8_seed55,saved,512,8,2,0.05,mul_only,mse,7,0.080270,...,0.032193,0.067174,0.138647,0.102510,0.514653,0.155392,0.385131,5.773610,0.036228,0.070815
7,saved_h64_d2_e8_seed33,saved,64,8,2,0.05,mul_only,mse,47,0.059334,...,0.032260,0.068749,0.138139,0.099659,0.518204,0.292699,0.498995,5.163429,0.031643,0.062075
8,saved_h512_d2_e8_seed33,saved,512,8,2,0.05,mul_only,mse,18,0.053185,...,0.033694,0.069860,0.138144,0.100665,0.518166,0.207636,0.444742,5.352311,0.034415,0.067061
9,saved_h64_d2_e8_seed55,saved,64,8,2,0.05,mul_only,mse,31,0.069340,...,0.034894,0.074090,0.141327,0.104547,0.495705,0.183523,0.421969,5.820496,0.037913,0.073786

,run_name,train_utility,eval_objective,split,hidden,emb_dim,combine,top1,top3,mean_rank,avg_regret,avg_norm_regret
0,saved_h512_d2_e8_seed44,saved,contains_closest,test,512,8,mul_only,0.929002,0.929002,2.135968,0.070998,0.070998
1,saved_h64_d2_e8_seed22,saved,contains_closest,test,64,8,mul_only,0.926993,0.926993,2.168118,0.073007,0.073007
2,saved_h64_d2_e8_seed33,saved,contains_closest,test,64,8,mul_only,0.922304,0.922304,2.243135,0.077696,0.077696
3,saved_h512_d2_e8_seed22,saved,contains_closest,test,512,8,mul_only,0.918955,0.918955,2.296718,0.081045,0.081045
4,saved_h512_d2_e8_seed55,saved,contains_closest,test,512,8,mul_only,0.917616,0.917616,2.318151,0.082384,0.082384
5,saved_h512_d2_e8_seed33,saved,contains_closest,test,512,8,mul_only,0.916276,0.916276,2.339585,0.083724,0.083724
6,saved_h64_d2_e8_seed55,saved,contains_closest,test,64,8,mul_only,0.908908,0.908908,2.457468,0.091092,0.091092
7,saved_h64_d2_e8_seed11,saved,contains_closest,test,64,8,mul_only,0.904889,0.904889,2.521768,0.095111,0.095111
8,saved_h512_d2_e8_seed11,saved,contains_closest,test,512,8,mul_only,0.901541,0.901541,2.575352,0.098459,0.098459
9,saved_h64_d2_e8_seed44,saved,contains_closest,test,64,8,mul_only,0.886135,0.886135,2.821835,0.113865,0.113865
10,saved_h64_d2_e8_seed22,saved,saved_rational,test,64,8,mul_only,0.308104,0.460817,5.182184,0.032348,0.061981
11,saved_h64_d2_e8_seed33,saved,saved_rational,test,64,8,mul_only,0.292699,0.498995,5.163429,0.031643,0.062075
12,saved_h512_d2_e8_seed11,saved,saved_rational,test,512,8,mul_only,0.262559,0.470194,5.296718,0.037829,0.070760
13,saved_h64_d2_e8_seed44,saved,saved_rational,test,64,8,mul_only,0.248493,0.462827,5.746149,0.040587,0.078086
14,saved_h512_d2_e8_seed22,saved,saved_rational,test,512,8,mul_only,0.237776,0.447421,5.308774,0.033974,0.065375
15,saved_h512_d2_e8_seed33,saved,saved_rational,test,512,8,mul_only,0.207636,0.444742,5.352311,0.034415,0.067061
16,saved_h64_d2_e8_seed55,saved,saved_rational,test,64,8,mul_only,0.183523,0.421969,5.820496,0.037913,0.073786
17,saved_h64_d2_e8_seed11,saved,saved_rational,test,64,8,mul_only,0.183523,0.406564,5.776959,0.038139,0.074261
18,saved_h512_d2_e8_seed44,saved,saved_rational,test,512,8,mul_only,0.158071,0.398526,5.570663,0.033920,0.066559
19,saved_h512_d2_e8_seed55,saved,saved_rational,test,512,8,mul_only,0.155392,0.385131,5.773610,0.036228,0.070815

,eval_objective,architecture,top1_mean,top1_std,top3_mean,top3_std,mean_rank_mean,mean_rank_std,avg_regret_mean,avg_regret_std,avg_norm_regret_mean,avg_norm_regret_std
0,contains_closest,h512_e8,0.916678,0.009839,0.916678,0.009839,2.333155,0.157429,0.083322,0.009839,0.083322,0.009839
1,contains_closest,h64_e8,0.909846,0.016100,0.909846,0.016100,2.442465,0.257602,0.090154,0.016100,0.090154,0.016100
2,saved_rational,h512_e8,0.204287,0.047579,0.429203,0.035837,5.460415,0.207198,0.035273,0.001710,0.068114,0.002516
3,saved_rational,h64_e8,0.243269,0.058765,0.450234,0.036586,5.537843,0.334342,0.036126,0.003922,0.070038,0.007500

In [9]:
# Pick the best saved-utility architecture from whichever sweeps have been run.

SAVED_OBJECTIVES = [
    {"name": "saved_rational", "utility_name": "saved", "utility_kwargs": {}},
    {"name": "contains_closest", "utility_name": "closest_binary", "utility_kwargs": {}},
]

saved_arch_results = []
for result_var in [
    "hidden_sweep_results",
    "depth_sweep_results",
    "embedding_sweep_results",
    "seed_sweep_results",
]:
    saved_arch_results.extend(globals().get(result_var, []))

if not saved_arch_results:
    raise RuntimeError("Run at least one saved-utility sweep before picking a best architecture.")

saved_arch_eval_df = compare_on_common_objectives(saved_arch_results, SAVED_OBJECTIVES)

saved_arch_val_df = saved_arch_eval_df[
    saved_arch_eval_df["split"].eq("val")
    & saved_arch_eval_df["eval_objective"].eq("saved_rational")
].copy()

best_arch_row = saved_arch_val_df.sort_values(
    ["avg_norm_regret", "mean_rank", "top3", "top1"],
    ascending=[True, True, False, False],
).iloc[0]
best_saved_arch_name = best_arch_row["run_name"]
best_saved_arch_result = next(
    result for result in saved_arch_results
    if result["config"].run_name == best_saved_arch_name
)

print("best saved-utility architecture:", best_saved_arch_name)
print("validation saved metrics:", best_arch_row[["top1", "top3", "mean_rank", "avg_regret", "avg_norm_regret"]].to_dict())

display(
    saved_arch_eval_df[saved_arch_eval_df["split"].eq("test")]
    .sort_values(["eval_objective", "avg_norm_regret", "mean_rank"])
    .reset_index(drop=True)
)

best saved-utility architecture: saved_h512_d2_e8_seed11
validation saved metrics: {'top1': 0.27059611520428667, 'top3': 0.5097119892833222, 'mean_rank': 4.983255190890824, 'avg_regret': 0.027523223328175198, 'avg_norm_regret': 0.060770917688785696}

,run_name,train_utility,eval_objective,split,hidden,emb_dim,combine,top1,top3,mean_rank,avg_regret,avg_norm_regret
0,saved_h512_d2_e8_seed44,saved,contains_closest,test,512,8,mul_only,0.929002,0.929002,2.135968,0.070998,0.070998
1,saved_h64_d2_e8_seed22,saved,contains_closest,test,64,8,mul_only,0.926993,0.926993,2.168118,0.073007,0.073007
2,saved_h64_d2_e32,saved,contains_closest,test,64,32,mul_only,0.924313,0.924313,2.210985,0.075687,0.075687
3,saved_h64_d2_e8_seed33,saved,contains_closest,test,64,8,mul_only,0.922304,0.922304,2.243135,0.077696,0.077696
4,saved_h64_d2_e96,saved,contains_closest,test,64,96,mul_only,0.918955,0.918955,2.296718,0.081045,0.081045
5,saved_h512_d2_e8_seed22,saved,contains_closest,test,512,8,mul_only,0.918955,0.918955,2.296718,0.081045,0.081045
6,saved_h512_d2_e8_seed55,saved,contains_closest,test,512,8,mul_only,0.917616,0.917616,2.318151,0.082384,0.082384
7,saved_h512_d2_e8_seed33,saved,contains_closest,test,512,8,mul_only,0.916276,0.916276,2.339585,0.083724,0.083724
8,saved_h64_d2_e8_seed55,saved,contains_closest,test,64,8,mul_only,0.908908,0.908908,2.457468,0.091092,0.091092
9,saved_h64_d2_e64,saved,contains_closest,test,64,64,mul_only,0.905559,0.905559,2.511052,0.094441,0.094441
10,saved_h64_d2_e8_seed11,saved,contains_closest,test,64,8,mul_only,0.904889,0.904889,2.521768,0.095111,0.095111
11,saved_h64_d2_e16,saved,contains_closest,test,64,16,mul_only,0.902210,0.902210,2.564635,0.097790,0.097790
12,saved_h512_d2_e8_seed11,saved,contains_closest,test,512,8,mul_only,0.901541,0.901541,2.575352,0.098459,0.098459
13,saved_h64_d2_e8_seed44,saved,contains_closest,test,64,8,mul_only,0.886135,0.886135,2.821835,0.113865,0.113865
14,saved_h64_d2_e8_seed22,saved,saved_rational,test,64,8,mul_only,0.308104,0.460817,5.182184,0.032348,0.061981
15,saved_h64_d2_e8_seed33,saved,saved_rational,test,64,8,mul_only,0.292699,0.498995,5.163429,0.031643,0.062075
16,saved_h512_d2_e8_seed22,saved,saved_rational,test,512,8,mul_only,0.237776,0.447421,5.308774,0.033974,0.065375
17,saved_h512_d2_e8_seed44,saved,saved_rational,test,512,8,mul_only,0.158071,0.398526,5.570663,0.033920,0.066559
18,saved_h512_d2_e8_seed33,saved,saved_rational,test,512,8,mul_only,0.207636,0.444742,5.352311,0.034415,0.067061
19,saved_h64_d2_e32,saved,saved_rational,test,64,32,mul_only,0.207636,0.418620,5.637642,0.036882,0.069524
20,saved_h512_d2_e8_seed11,saved,saved_rational,test,512,8,mul_only,0.262559,0.470194,5.296718,0.037829,0.070760
21,saved_h512_d2_e8_seed55,saved,saved_rational,test,512,8,mul_only,0.155392,0.385131,5.773610,0.036228,0.070815
22,saved_h64_d2_e16,saved,saved_rational,test,64,16,mul_only,0.251172,0.445412,5.501674,0.036026,0.071060
23,saved_h64_d2_e96,saved,saved_rational,test,64,96,mul_only,0.149364,0.356999,6.079035,0.036553,0.073278
24,saved_h64_d2_e8_seed55,saved,saved_rational,test,64,8,mul_only,0.183523,0.421969,5.820496,0.037913,0.073786
25,saved_h64_d2_e8_seed11,saved,saved_rational,test,64,8,mul_only,0.183523,0.406564,5.776959,0.038139,0.074261
26,saved_h64_d2_e8_seed44,saved,saved_rational,test,64,8,mul_only,0.248493,0.462827,5.746149,0.040587,0.078086
27,saved_h64_d2_e64,saved,saved_rational,test,64,64,mul_only,0.131279,0.344943,6.019424,0.042712,0.079012

In [ ]:
# Save the trained towers, standardizers, and frozen embeddings for fast scoring.
# The embeddings file includes context embeddings by time and action embeddings by example.

export_result = globals().get("best_saved_arch_result", best_result)

paths = export_frozen_embeddings(
    export_result,
    output_dir=RUN_DIR,
    prefix=export_result["config"].run_name,
)

manifest = pd.DataFrame(
    [{"artifact": key, "path": str(path)} for key, path in paths.items()]
)
display(manifest)