In [1]:
from pathlib import Path
import importlib
import sys

import numpy as np
import pandas as pd
import torch

PROJECT_ROOT = Path.cwd()
if PROJECT_ROOT.name == "notebooks":
    PROJECT_ROOT = PROJECT_ROOT.parent

SCRIPTS_DIR = PROJECT_ROOT / "scripts"
if str(SCRIPTS_DIR) not in sys.path:
    sys.path.append(str(SCRIPTS_DIR))

import dataloader
import audio_feature_dataloader
import processed_feature_builder
importlib.reload(dataloader)
importlib.reload(audio_feature_dataloader)
importlib.reload(processed_feature_builder)

from dataloader import load_data
from audio_feature_dataloader import build_audio_feature_dataset
from processed_feature_builder import build_processed_two_tower_data, save_processed_two_tower_data

DATA_DIR = PROJECT_ROOT / "data" / "raw"
PROCESSED_DIR = PROJECT_ROOT / "data" / "processed"
SENSOR_CSV = DATA_DIR / "wp_node_gps.csv"
GPS_CSV = DATA_DIR / "20260416_150152_gps2_gps.csv"

SAMPLE_MS = 200
RESAMPLE_RATE = f"{SAMPLE_MS}ms"
CHUNK_MS = 10
EXPANDED_PREFIX = "vehicle_sensor_subset_200ms_expanded_features"

context_audio_features = [
    "rms_db", "spectral_centroid_hz", "spectral_flatness",
    "band_20_120_ratio", "band_120_500_ratio", "band_500_2000_ratio",
    "low_to_voice_db", "mid_to_voice_db", "rms_delta_db", "centroid_delta_hz",
    "peak_db", "crest_factor_db", "zcr", "spectral_bandwidth_hz",
    "spectral_rolloff85_hz", "spectral_entropy", "band_20_120_db",
    "band_120_500_db", "band_500_2000_db", "band_2000_6000_db",
    "band_2000_6000_ratio", "flatness_delta",
]

action_audio_features = [
    "rms_db", "spectral_centroid_hz", "spectral_flatness",
    "band_20_120_ratio", "band_120_500_ratio", "low_to_voice_db",
    "band_500_2000_ratio", "mid_to_voice_db", "crest_factor_db", "zcr",
    "spectral_bandwidth_hz", "spectral_rolloff85_hz", "spectral_entropy",
    "band_2000_6000_ratio", "flatness_delta",
]

per_node_required = [
    "rssi_median", "rssi_mad", "rssi_iqr", "rssi_trimmed_mean",
    "rssi_persistence_top3", "rssi_persistence_top5",
    "vehicle_like_score", "construction_like_score", "vehicle_minus_construction_score",
]
global_required = [
    "rssi_top1_top3_gap", "rssi_top1_top5_gap", "global_rssi_mean",
    "global_rssi_std", "global_rssi_range",
] + [
    f"global_{stat}_{feature}"
    for feature in [
        "construction_like_score", "vehicle_like_score", "spectral_entropy",
        "crest_factor_db", "band_2000_6000_ratio",
    ]
    for stat in ["mean", "max", "std", "range"]
]
action_subset_required = [
    "subset_centroid_minus_acoustic_com_x",
    "subset_centroid_minus_acoustic_com_y",
    "subset_centroid_to_acoustic_com_dist",
    "num_signal_top2_in_subset", "num_signal_top3_in_subset", "num_signal_top5_in_subset",
    "best_signal_rank_in_subset", "mean_signal_rank_in_subset", "worst_signal_rank_in_subset",
    "median_rssi", "mad_rssi", "iqr_rssi", "range_rssi",
]
audio_agg_required = [
    f"{stat}_audio_{feature}"
    for feature in action_audio_features
    for stat in ["mean", "max", "min", "std", "range"]
]
score_agg_required = [
    f"{stat}_{feature}"
    for feature in ["construction_like_score", "vehicle_like_score", "vehicle_minus_construction_score"]
    for stat in ["mean", "max", "std"]
]

node_list = sorted(pd.read_csv(SENSOR_CSV)["Node #"].astype(int).tolist())
gdf_cleaned, normalized_cleaned, valid_indices, gdf_nodes = load_data(
    data_dir=DATA_DIR,
    sensor_csv=SENSOR_CSV,
    gps_csv=GPS_CSV,
    node_list=node_list,
    chunk_ms=CHUNK_MS,
    sample_ms=SAMPLE_MS,
    resample_rate=RESAMPLE_RATE,
    plot_gaps=False,
    interpolate_gps=True,
)
audio_feature_df, audio_feature_long, audio_gdf_nodes = build_audio_feature_dataset(
    data_dir=DATA_DIR,
    sensor_csv=SENSOR_CSV,
    node_list=node_list,
    sample_ms=SAMPLE_MS,
    add_cross_sensor=True,
)

expanded_processed = build_processed_two_tower_data(
    gdf_cleaned=gdf_cleaned,
    gdf_nodes=gdf_nodes,
    valid_indices=valid_indices,
    node_list=node_list,
    audio_feature_long=audio_feature_long,
    history_steps=5,
    max_subset_size=3,
    utility_second_weight=0.45,
    utility_third_weight=0.20,
    softmax_temperature=4.0,
    context_audio_features=context_audio_features,
    action_audio_features=action_audio_features,
    include_audio_derived_features=True,
    verbose=True,
    progress_every=1500,
)
expanded_paths = save_processed_two_tower_data(
    expanded_processed,
    processed_dir=PROCESSED_DIR,
    prefix=EXPANDED_PREFIX,
)

meta = expanded_processed["meta"]
missing_context_audio = sorted(set(context_audio_features) - set(meta["context_audio_features"]))
missing_action_audio = sorted(set(action_audio_features) - set(meta["action_audio_features"]))
assert not missing_context_audio, missing_context_audio
assert not missing_action_audio, missing_action_audio

context_names = set(meta["context_feature_names"])
node_feature_cols = set(expanded_processed["node_feature_df"].columns)
feature_wide_cols = set(expanded_processed["feature_wide_df"].columns)
for node in meta["ordered_nodes"]:
    for feature in per_node_required:
        assert feature in node_feature_cols, f"missing node_feature_df column: {feature}"
        assert f"n{node}_{feature}" in context_names, f"missing context feature: n{node}_{feature}"
        assert f"n{node}_{feature}" in feature_wide_cols, f"missing feature_wide column: n{node}_{feature}"
    for feature in context_audio_features:
        assert f"n{node}_audio_{feature}" in context_names, f"missing context audio: n{node}_audio_{feature}"

global_names = set(meta["global_feature_names"])
for feature in global_required:
    assert feature in global_names, f"missing global context feature: {feature}"
    assert feature in feature_wide_cols, f"missing feature_wide global column: {feature}"

action_names = set(meta["action_feature_names"])
for feature in action_subset_required + audio_agg_required + score_agg_required:
    assert feature in action_names, f"missing action feature: {feature}"

arrays = np.load(expanded_paths["arrays_npz"])
assert arrays["C_by_time"].shape[1] == meta["context_dim"] == len(meta["context_feature_names"])
assert arrays["A_examples"].shape[1] == meta["action_raw_dim"] == len(meta["action_feature_names"])

leak_tokens = ("distance_to", "vehicle_x", "vehicle_y", "latitude", "longitude")
feature_names = list(meta["context_feature_names"]) + list(meta["action_feature_names"])
leaky_features = [name for name in feature_names if any(tok in name.lower() for tok in leak_tokens)]
assert not leaky_features, leaky_features[:20]

print("expanded processed prefix:", EXPANDED_PREFIX)
print("context_dim:", meta["context_dim"])
print("action_dim:", meta["action_raw_dim"])
print("times/examples:", meta["num_times"], meta["num_examples"])
print("all requested expanded features are present; no feature-side vehicle coordinate leakage detected")
display(pd.DataFrame([{"artifact": k, "path": str(v)} for k, v in expanded_paths.items()]))

Loaded FLAC: d:\2023-2028_UCLA_Research_Projects\IoBT\17-5-26- MILCOM Attempt\data\raw\20260416_150152_dvpg_gq_orin_11_respeaker.flac
Loaded FLAC: d:\2023-2028_UCLA_Research_Projects\IoBT\17-5-26- MILCOM Attempt\data\raw\20260416_150152_dvpg_gq_orin_12_respeaker.flac
Loaded FLAC: d:\2023-2028_UCLA_Research_Projects\IoBT\17-5-26- MILCOM Attempt\data\raw\20260416_150152_dvpg_gq_orin_13_respeaker.flac
Loaded FLAC: d:\2023-2028_UCLA_Research_Projects\IoBT\17-5-26- MILCOM Attempt\data\raw\20260416_150152_dvpg_gq_orin_14_respeaker.flac
Loaded FLAC: d:\2023-2028_UCLA_Research_Projects\IoBT\17-5-26- MILCOM Attempt\data\raw\20260416_150152_dvpg_gq_orin_15_respeaker.flac
Loaded FLAC: d:\2023-2028_UCLA_Research_Projects\IoBT\17-5-26- MILCOM Attempt\data\raw\20260416_150152_dvpg_gq_orin_16_respeaker.flac
Node 11: 155480 rows loaded, time range: 2026-04-16 15:01:52 to 2026-04-16 15:27:46.790000
Node 12: 155490 rows loaded, time range: 2026-04-16 15:01:52 to 2026-04-16 15:27:46.890000
Node 13: 155490 rows loaded, time range: 2026-04-16 15:01:52 to 2026-04-16 15:27:46.890000
Node 14: 155480 rows loaded, time range: 2026-04-16 15:01:52 to 2026-04-16 15:27:46.790000
Node 15: 155480 rows loaded, time range: 2026-04-16 15:01:52 to 2026-04-16 15:27:46.790000
Node 16: 155480 rows loaded, time range: 2026-04-16 15:01:52 to 2026-04-16 15:27:46.790000

Final Cleaned DataFrames Summary
Using nodes: [11, 12, 13, 14, 15, 16]
Dropped nodes: []
Local projected CRS: EPSG:32618
gdf_cleaned: 7766 rows, columns: ['rpi11', 'rpi12', 'rpi13', 'rpi14', 'rpi15', 'rpi16', 'geometry', 'distance_to_11', 'distance_to_12', 'distance_to_13', 'distance_to_14', 'distance_to_15', 'distance_to_16']
normalized_cleaned: 7766 rows, columns: ['rpi11', 'rpi12', 'rpi13', 'rpi14', 'rpi15', 'rpi16', 'Latitude', 'Longitude', 'distance_to_11', 'distance_to_12', 'distance_to_13', 'distance_to_14', 'distance_to_15', 'distance_to_16']

Valid time indices: 7465 out of 7766 total
First 10 valid indices: [136, 137, 138, 139, 140, 141, 142, 143, 144, 145]
Loaded audio features: node 11, 20260416_150152_dvpg_gq_orin_11_respeaker.flac, 7774 rows at 200 ms
Loaded audio features: node 12, 20260416_150152_dvpg_gq_orin_12_respeaker.flac, 7774 rows at 200 ms
Loaded audio features: node 13, 20260416_150152_dvpg_gq_orin_13_respeaker.flac, 7774 rows at 200 ms
Loaded audio features: node 14, 20260416_150152_dvpg_gq_orin_14_respeaker.flac, 7774 rows at 200 ms
Loaded audio features: node 15, 20260416_150152_dvpg_gq_orin_15_respeaker.flac, 7774 rows at 200 ms
Loaded audio features: node 16, 20260416_150152_dvpg_gq_orin_16_respeaker.flac, 7774 rows at 200 ms
valid timesteps: 7465
ordered nodes: [11, 12, 13, 14, 15, 16]
temporal features: 1/7465
temporal features: 1500/7465
temporal features: 3000/7465
temporal features: 4500/7465
temporal features: 6000/7465
temporal features: 7465/7465
node rows: 1/7465
node rows: 1500/7465
node rows: 3000/7465
node rows: 4500/7465
node rows: 6000/7465
node rows: 7465/7465
action rows: 1/7465
action rows: 1500/7465
action rows: 3000/7465
action rows: 4500/7465
action rows: 6000/7465
action rows: 7465/7465
processed two-tower data ready
sequence_df: (7465, 5)
examples_df: (306065, 15)
context_dim: 269
action_raw_dim: 214
expanded processed prefix: vehicle_sensor_subset_200ms_expanded_features
context_dim: 269
action_dim: 214
times/examples: 7465 306065
all requested expanded features are present; no feature-side vehicle coordinate leakage detected

                   artifact                                               path
0          feature_wide_csv  d:\2023-2028_UCLA_Research_Projects\IoBT\17-5-...
1         node_features_csv  d:\2023-2028_UCLA_Research_Projects\IoBT\17-5-...
2    ground_truth_nodes_csv  d:\2023-2028_UCLA_Research_Projects\IoBT\17-5-...
3  ground_truth_vehicle_csv  d:\2023-2028_UCLA_Research_Projects\IoBT\17-5-...
4       sensor_geometry_csv  d:\2023-2028_UCLA_Research_Projects\IoBT\17-5-...
5              sequence_pkl  d:\2023-2028_UCLA_Research_Projects\IoBT\17-5-...
6              examples_pkl  d:\2023-2028_UCLA_Research_Projects\IoBT\17-5-...
7        examples_index_csv  d:\2023-2028_UCLA_Research_Projects\IoBT\17-5-...
8                arrays_npz  d:\2023-2028_UCLA_Research_Projects\IoBT\17-5-...
9                 meta_json  d:\2023-2028_UCLA_Research_Projects\IoBT\17-5-...

In [2]:
import importlib
import two_tower_training
importlib.reload(two_tower_training)

from two_tower_training import TrainConfig, compare_on_common_objectives, run_config_grid, summarize_results

DEVICE = "cuda" if torch.cuda.is_available() else "cpu"
SAVED_OBJECTIVES = [
    {"name": "saved_rational", "utility_name": "saved", "utility_kwargs": {}},
    {"name": "contains_closest", "utility_name": "closest_binary", "utility_kwargs": {}},
]

expanded_h512_config = TrainConfig(
    run_name="expanded_saved_h512_d2_e8",
    utility_name="saved",
    hidden=512,
    emb_dim=8,
    depth=2,
    dropout=0.05,
    combine_mode="mul_only",
    loss_name="mse",
    max_epochs=50,
    patience=16,
    batch_size=8192,
    lr=1e-3,
    weight_decay=1e-4,
    seed=22,
    log_every=1,
)

expanded_results = run_config_grid(
    PROCESSED_DIR,
    [expanded_h512_config],
    prefix=EXPANDED_PREFIX,
    device=DEVICE,
)
expanded_summary_df = summarize_results(expanded_results)
expanded_common_eval_df = compare_on_common_objectives(expanded_results, SAVED_OBJECTIVES)
display(expanded_summary_df)
display(expanded_common_eval_df[expanded_common_eval_df["split"].eq("test")].reset_index(drop=True))

expanded_saved_h512_d2_e8 ep 001/050* loss=0.04510 val_rmse=0.1434 top1=0.238 top3=0.449 reg=0.0357 rank=5.98 11s
expanded_saved_h512_d2_e8 ep 002/050  loss=0.01762 val_rmse=0.1354 top1=0.147 top3=0.391 reg=0.0406 rank=6.46 22s
expanded_saved_h512_d2_e8 ep 003/050  loss=0.01254 val_rmse=0.1297 top1=0.162 top3=0.385 reg=0.0362 rank=6.03 33s
expanded_saved_h512_d2_e8 ep 004/050* loss=0.00994 val_rmse=0.1244 top1=0.161 top3=0.419 reg=0.0315 rank=5.53 44s
expanded_saved_h512_d2_e8 ep 005/050* loss=0.00827 val_rmse=0.1247 top1=0.185 top3=0.453 reg=0.0289 rank=5.23 55s
expanded_saved_h512_d2_e8 ep 006/050* loss=0.00705 val_rmse=0.1262 top1=0.203 top3=0.466 reg=0.0287 rank=5.20 66s
expanded_saved_h512_d2_e8 ep 007/050* loss=0.00613 val_rmse=0.1244 top1=0.213 top3=0.487 reg=0.0281 rank=5.14 77s
expanded_saved_h512_d2_e8 ep 008/050* loss=0.00544 val_rmse=0.1261 top1=0.243 top3=0.500 reg=0.0274 rank=5.05 90s
expanded_saved_h512_d2_e8 ep 009/050* loss=0.00490 val_rmse=0.1221 top1=0.238 top3=0.508 reg=0.0262 rank=4.97 100s
expanded_saved_h512_d2_e8 ep 010/050* loss=0.00449 val_rmse=0.1240 top1=0.248 top3=0.506 reg=0.0260 rank=4.90 113s
expanded_saved_h512_d2_e8 ep 011/050  loss=0.00411 val_rmse=0.1255 top1=0.248 top3=0.487 reg=0.0278 rank=5.11 125s
expanded_saved_h512_d2_e8 ep 012/050  loss=0.00379 val_rmse=0.1243 top1=0.249 top3=0.512 reg=0.0270 rank=5.00 137s
expanded_saved_h512_d2_e8 ep 013/050  loss=0.00352 val_rmse=0.1201 top1=0.273 top3=0.530 reg=0.0261 rank=4.87 149s
expanded_saved_h512_d2_e8 ep 014/050* loss=0.00332 val_rmse=0.1217 top1=0.269 top3=0.522 reg=0.0249 rank=4.80 160s
expanded_saved_h512_d2_e8 ep 015/050  loss=0.00309 val_rmse=0.1198 top1=0.272 top3=0.532 reg=0.0254 rank=4.82 171s
expanded_saved_h512_d2_e8 ep 016/050  loss=0.00293 val_rmse=0.1223 top1=0.255 top3=0.494 reg=0.0269 rank=5.03 183s
expanded_saved_h512_d2_e8 ep 017/050  loss=0.00274 val_rmse=0.1246 top1=0.275 top3=0.522 reg=0.0253 rank=4.84 195s
expanded_saved_h512_d2_e8 ep 018/050  loss=0.00261 val_rmse=0.1229 top1=0.259 top3=0.498 reg=0.0258 rank=4.92 206s
expanded_saved_h512_d2_e8 ep 019/050  loss=0.00247 val_rmse=0.1215 top1=0.277 top3=0.514 reg=0.0253 rank=4.80 217s
expanded_saved_h512_d2_e8 ep 020/050  loss=0.00236 val_rmse=0.1206 top1=0.259 top3=0.533 reg=0.0255 rank=4.87 229s
expanded_saved_h512_d2_e8 ep 021/050* loss=0.00224 val_rmse=0.1220 top1=0.270 top3=0.518 reg=0.0244 rank=4.75 241s
expanded_saved_h512_d2_e8 ep 022/050  loss=0.00213 val_rmse=0.1235 top1=0.267 top3=0.505 reg=0.0268 rank=5.01 252s
expanded_saved_h512_d2_e8 ep 023/050  loss=0.00203 val_rmse=0.1216 top1=0.254 top3=0.511 reg=0.0248 rank=4.76 263s
expanded_saved_h512_d2_e8 ep 024/050  loss=0.00192 val_rmse=0.1232 top1=0.277 top3=0.517 reg=0.0252 rank=4.85 274s
expanded_saved_h512_d2_e8 ep 025/050  loss=0.00186 val_rmse=0.1245 top1=0.269 top3=0.509 reg=0.0256 rank=4.87 286s
expanded_saved_h512_d2_e8 ep 026/050  loss=0.00178 val_rmse=0.1219 top1=0.271 top3=0.523 reg=0.0248 rank=4.74 297s
expanded_saved_h512_d2_e8 ep 027/050  loss=0.00171 val_rmse=0.1215 top1=0.262 top3=0.500 reg=0.0256 rank=4.91 308s
expanded_saved_h512_d2_e8 ep 028/050  loss=0.00164 val_rmse=0.1236 top1=0.261 top3=0.502 reg=0.0257 rank=4.93 321s
expanded_saved_h512_d2_e8 ep 029/050  loss=0.00159 val_rmse=0.1229 top1=0.286 top3=0.517 reg=0.0251 rank=4.78 332s
expanded_saved_h512_d2_e8 ep 030/050* loss=0.00151 val_rmse=0.1219 top1=0.294 top3=0.533 reg=0.0240 rank=4.71 344s
expanded_saved_h512_d2_e8 ep 031/050  loss=0.00146 val_rmse=0.1219 top1=0.273 top3=0.510 reg=0.0247 rank=4.78 355s
expanded_saved_h512_d2_e8 ep 032/050  loss=0.00141 val_rmse=0.1247 top1=0.271 top3=0.496 reg=0.0257 rank=4.91 367s
expanded_saved_h512_d2_e8 ep 033/050  loss=0.00136 val_rmse=0.1240 top1=0.287 top3=0.506 reg=0.0253 rank=4.87 378s
expanded_saved_h512_d2_e8 ep 034/050  loss=0.00130 val_rmse=0.1237 top1=0.267 top3=0.495 reg=0.0255 rank=4.88 389s
expanded_saved_h512_d2_e8 ep 035/050  loss=0.00126 val_rmse=0.1247 top1=0.262 top3=0.503 reg=0.0248 rank=4.82 400s
expanded_saved_h512_d2_e8 ep 036/050  loss=0.00121 val_rmse=0.1235 top1=0.295 top3=0.530 reg=0.0243 rank=4.70 411s
expanded_saved_h512_d2_e8 ep 037/050  loss=0.00117 val_rmse=0.1232 top1=0.283 top3=0.524 reg=0.0244 rank=4.70 423s
expanded_saved_h512_d2_e8 ep 038/050  loss=0.00114 val_rmse=0.1246 top1=0.285 top3=0.523 reg=0.0247 rank=4.72 435s
expanded_saved_h512_d2_e8 ep 039/050  loss=0.00111 val_rmse=0.1239 top1=0.262 top3=0.506 reg=0.0252 rank=4.83 446s
expanded_saved_h512_d2_e8 ep 040/050  loss=0.00107 val_rmse=0.1256 top1=0.263 top3=0.504 reg=0.0249 rank=4.81 457s
expanded_saved_h512_d2_e8 ep 041/050* loss=0.00103 val_rmse=0.1241 top1=0.297 top3=0.520 reg=0.0229 rank=4.55 468s
expanded_saved_h512_d2_e8 ep 042/050  loss=0.00099 val_rmse=0.1257 top1=0.263 top3=0.508 reg=0.0249 rank=4.79 479s
expanded_saved_h512_d2_e8 ep 043/050  loss=0.00097 val_rmse=0.1257 top1=0.280 top3=0.531 reg=0.0246 rank=4.67 492s
expanded_saved_h512_d2_e8 ep 044/050  loss=0.00095 val_rmse=0.1247 top1=0.295 top3=0.532 reg=0.0240 rank=4.63 504s
expanded_saved_h512_d2_e8 ep 045/050  loss=0.00093 val_rmse=0.1238 top1=0.289 top3=0.513 reg=0.0247 rank=4.72 515s
expanded_saved_h512_d2_e8 ep 046/050  loss=0.00090 val_rmse=0.1238 top1=0.279 top3=0.511 reg=0.0239 rank=4.65 526s
expanded_saved_h512_d2_e8 ep 047/050  loss=0.00087 val_rmse=0.1235 top1=0.309 top3=0.528 reg=0.0231 rank=4.54 537s
expanded_saved_h512_d2_e8 ep 048/050  loss=0.00084 val_rmse=0.1254 top1=0.303 top3=0.537 reg=0.0238 rank=4.57 548s
expanded_saved_h512_d2_e8 ep 049/050  loss=0.00082 val_rmse=0.1256 top1=0.293 top3=0.525 reg=0.0237 rank=4.57 559s
expanded_saved_h512_d2_e8 ep 050/050  loss=0.00080 val_rmse=0.1265 top1=0.293 top3=0.528 reg=0.0240 rank=4.64 570s

,run_name,utility,hidden,emb_dim,depth,dropout,combine,loss,best_epoch,train_rmse,...,val_avg_regret,val_avg_norm_regret,test_rmse,test_mae,test_r2,test_top1,test_top3,test_mean_rank,test_avg_regret,test_avg_norm_regret
0,expanded_saved_h512_d2_e8,saved,512,8,2,0.05,mul_only,mse,41,0.019546,...,0.022904,0.050454,0.116675,0.083843,0.656293,0.283322,0.544541,4.425318,0.023707,0.047672

,run_name,train_utility,eval_objective,split,hidden,emb_dim,combine,top1,top3,mean_rank,avg_regret,avg_norm_regret
0,expanded_saved_h512_d2_e8,saved,contains_closest,test,512,8,mul_only,0.943068,0.943068,1.910918,0.056932,0.056932
1,expanded_saved_h512_d2_e8,saved,saved_rational,test,512,8,mul_only,0.283322,0.544541,4.425318,0.023707,0.047672

In [4]:
# Same model and saved utility, but no waveform/frequency features beyond RSSI-derived features.
# Sensor GPS geometry and RSSI history/rank/persistence features remain available.

RSSI_GEOMETRY_PREFIX = "vehicle_sensor_subset_200ms_rssi_geometry_only"

rssi_geometry_processed = build_processed_two_tower_data(
    gdf_cleaned=gdf_cleaned,
    gdf_nodes=gdf_nodes,
    valid_indices=valid_indices,
    node_list=node_list,
    audio_feature_long=None,
    history_steps=5,
    max_subset_size=3,
    utility_second_weight=0.45,
    utility_third_weight=0.20,
    softmax_temperature=4.0,
    context_audio_features=[],
    action_audio_features=[],
    include_audio_derived_features=False,
    verbose=True,
    progress_every=1500,
)
rssi_geometry_paths = save_processed_two_tower_data(
    rssi_geometry_processed,
    processed_dir=PROCESSED_DIR,
    prefix=RSSI_GEOMETRY_PREFIX,
)

rssi_meta = rssi_geometry_processed["meta"]
assert rssi_meta["context_audio_features"] == []
assert rssi_meta["action_audio_features"] == []
assert rssi_meta["derived_audio_score_features"] == []
assert not [name for name in rssi_meta["context_feature_names"] if "audio_" in name]
assert not [name for name in rssi_meta["action_feature_names"] if "audio_" in name]

rssi_geometry_h512_config = TrainConfig(
    run_name="rssi_geometry_saved_h512_d2_e8",
    utility_name="saved",
    hidden=512,
    emb_dim=8,
    depth=2,
    dropout=0.05,
    combine_mode="mul_only",
    loss_name="mse",
    max_epochs=50,
    patience=16,
    batch_size=8192,
    lr=1e-3,
    weight_decay=1e-4,
    seed=22,
    log_every=1,
)

rssi_geometry_results = run_config_grid(
    PROCESSED_DIR,
    [rssi_geometry_h512_config],
    prefix=RSSI_GEOMETRY_PREFIX,
    device=DEVICE,
)
rssi_geometry_summary_df = summarize_results(rssi_geometry_results)
rssi_geometry_common_eval_df = compare_on_common_objectives(rssi_geometry_results, SAVED_OBJECTIVES)

display(rssi_geometry_summary_df)
display(rssi_geometry_common_eval_df[rssi_geometry_common_eval_df["split"].eq("test")].reset_index(drop=True))

if "expanded_results" in globals():
    ablation_eval_df = compare_on_common_objectives(
        expanded_results + rssi_geometry_results,
        SAVED_OBJECTIVES,
    )
    display(
        ablation_eval_df[ablation_eval_df["split"].eq("test")]
        .sort_values(["eval_objective", "avg_norm_regret", "mean_rank"])
        .reset_index(drop=True)
    )

valid timesteps: 7465
ordered nodes: [11, 12, 13, 14, 15, 16]
temporal features: 1/7465
temporal features: 1500/7465
temporal features: 3000/7465
temporal features: 4500/7465
temporal features: 6000/7465
temporal features: 7465/7465
node rows: 1/7465
node rows: 1500/7465
node rows: 3000/7465
node rows: 4500/7465
node rows: 6000/7465
node rows: 7465/7465
action rows: 1/7465
action rows: 1500/7465
action rows: 3000/7465
action rows: 4500/7465
action rows: 6000/7465
action rows: 7465/7465
processed two-tower data ready
sequence_df: (7465, 5)
examples_df: (306065, 15)
context_dim: 99
action_raw_dim: 76
rssi_geometry_saved_h512_d2_e8 ep 001/050* loss=0.04696 val_rmse=0.1697 top1=0.204 top3=0.352 reg=0.0712 rank=8.17 11s
rssi_geometry_saved_h512_d2_e8 ep 002/050* loss=0.02651 val_rmse=0.1692 top1=0.173 top3=0.293 reg=0.0678 rank=8.62 22s
rssi_geometry_saved_h512_d2_e8 ep 003/050  loss=0.02266 val_rmse=0.1787 top1=0.175 top3=0.281 reg=0.0820 rank=9.99 33s
rssi_geometry_saved_h512_d2_e8 ep 004/050  loss=0.01997 val_rmse=0.1847 top1=0.162 top3=0.268 reg=0.0861 rank=10.24 44s
rssi_geometry_saved_h512_d2_e8 ep 005/050  loss=0.01774 val_rmse=0.1830 top1=0.159 top3=0.293 reg=0.0789 rank=9.41 55s
rssi_geometry_saved_h512_d2_e8 ep 006/050  loss=0.01581 val_rmse=0.1869 top1=0.136 top3=0.269 reg=0.0790 rank=9.53 65s
rssi_geometry_saved_h512_d2_e8 ep 007/050  loss=0.01408 val_rmse=0.1897 top1=0.154 top3=0.301 reg=0.0803 rank=9.42 75s
rssi_geometry_saved_h512_d2_e8 ep 008/050  loss=0.01262 val_rmse=0.1905 top1=0.159 top3=0.297 reg=0.0834 rank=9.71 87s
rssi_geometry_saved_h512_d2_e8 ep 009/050  loss=0.01142 val_rmse=0.1899 top1=0.172 top3=0.310 reg=0.0847 rank=9.67 97s
rssi_geometry_saved_h512_d2_e8 ep 010/050  loss=0.01043 val_rmse=0.1931 top1=0.145 top3=0.286 reg=0.0927 rank=10.24 108s
rssi_geometry_saved_h512_d2_e8 ep 011/050  loss=0.00962 val_rmse=0.1911 top1=0.157 top3=0.302 reg=0.0889 rank=9.86 120s
rssi_geometry_saved_h512_d2_e8 ep 012/050  loss=0.00885 val_rmse=0.1929 top1=0.148 top3=0.295 reg=0.0856 rank=9.72 131s
rssi_geometry_saved_h512_d2_e8 ep 013/050  loss=0.00822 val_rmse=0.1912 top1=0.153 top3=0.285 reg=0.0859 rank=9.70 142s
rssi_geometry_saved_h512_d2_e8 ep 014/050  loss=0.00767 val_rmse=0.1891 top1=0.164 top3=0.307 reg=0.0855 rank=9.57 153s
rssi_geometry_saved_h512_d2_e8 ep 015/050  loss=0.00719 val_rmse=0.1904 top1=0.159 top3=0.311 reg=0.0865 rank=9.68 163s
rssi_geometry_saved_h512_d2_e8 ep 016/050  loss=0.00675 val_rmse=0.1912 top1=0.173 top3=0.322 reg=0.0866 rank=9.51 174s
rssi_geometry_saved_h512_d2_e8 ep 017/050  loss=0.00636 val_rmse=0.1888 top1=0.168 top3=0.306 reg=0.0873 rank=9.68 186s
rssi_geometry_saved_h512_d2_e8 ep 018/050  loss=0.00595 val_rmse=0.1900 top1=0.157 top3=0.299 reg=0.0876 rank=9.75 199s
rssi_geometry_saved_h512_d2_e8 early stop at ep 018; best ep 002

,run_name,utility,hidden,emb_dim,depth,dropout,combine,loss,best_epoch,train_rmse,...,val_avg_regret,val_avg_norm_regret,test_rmse,test_mae,test_r2,test_top1,test_top3,test_mean_rank,test_avg_regret,test_avg_norm_regret
0,rssi_geometry_saved_h512_d2_e8,saved,512,8,2,0.05,mul_only,mse,2,0.149376,...,0.067825,0.135486,0.160671,0.123608,0.348208,0.22639,0.330208,8.073677,0.072984,0.134118

,run_name,train_utility,eval_objective,split,hidden,emb_dim,combine,top1,top3,mean_rank,avg_regret,avg_norm_regret
0,rssi_geometry_saved_h512_d2_e8,saved,contains_closest,test,512,8,mul_only,0.77361,0.773610,4.622237,0.226390,0.226390
1,rssi_geometry_saved_h512_d2_e8,saved,saved_rational,test,512,8,mul_only,0.22639,0.330208,8.073677,0.072984,0.134118

,run_name,train_utility,eval_objective,split,hidden,emb_dim,combine,top1,top3,mean_rank,avg_regret,avg_norm_regret
0,expanded_saved_h512_d2_e8,saved,contains_closest,test,512,8,mul_only,0.943068,0.943068,1.910918,0.056932,0.056932
1,rssi_geometry_saved_h512_d2_e8,saved,contains_closest,test,512,8,mul_only,0.773610,0.773610,4.622237,0.226390,0.226390
2,expanded_saved_h512_d2_e8,saved,saved_rational,test,512,8,mul_only,0.283322,0.544541,4.425318,0.023707,0.047672
3,rssi_geometry_saved_h512_d2_e8,saved,saved_rational,test,512,8,mul_only,0.226390,0.330208,8.073677,0.072984,0.134118

In [5]:
import importlib
import pandas as pd
from dataclasses import replace

import two_tower_training
importlib.reload(two_tower_training)

from two_tower_training import (
    TrainConfig,
    compare_on_common_objectives,
    run_config_grid,
    summarize_results,
)

DEVICE = "cuda" if torch.cuda.is_available() else "cpu"

SAVED_OBJECTIVES = [
    {"name": "saved_rational", "utility_name": "saved", "utility_kwargs": {}},
    {"name": "contains_closest", "utility_name": "closest_binary", "utility_kwargs": {}},
]

# Your current expanded baseline.
base_config = TrainConfig(
    run_name="expanded_saved_h512_d2_e8",
    utility_name="saved",
    hidden=512,
    emb_dim=8,
    depth=2,
    dropout=0.05,
    combine_mode="mul_only",
    loss_name="mse",
    max_epochs=50,
    patience=16,
    batch_size=8192,
    lr=1e-3,
    weight_decay=1e-4,
    seed=22,
    log_every=1,
)

# One-change-at-a-time configs around the baseline.
one_change_configs = [
    # 1. Main bottleneck test: 8 -> 16 embedding.
    replace(
        base_config,
        run_name="expanded_saved_h512_d2_e16",
        emb_dim=16,
    ),

    # 2. Stronger bottleneck test: 8 -> 24 embedding.
    # Still not insane for the later linearized bandit: d = 1 + 3*24 = 73.
    replace(
        base_config,
        run_name="expanded_saved_h512_d2_e24",
        emb_dim=24,
    ),

    # 3. Dropout regularization test.
    replace(
        base_config,
        run_name="expanded_saved_h512_d2_e8_drop010",
        dropout=0.10,
    ),

    # 4. Weight-decay regularization test.
    replace(
        base_config,
        run_name="expanded_saved_h512_d2_e8_wd5e4",
        weight_decay=5e-4,
    ),

    # 5. Noisy-label robustness test.
    replace(
        base_config,
        run_name="expanded_saved_h512_d2_e8_smoothl1",
        loss_name="smooth_l1",
    ),
]

one_change_results = run_config_grid(
    PROCESSED_DIR,
    one_change_configs,
    prefix=EXPANDED_PREFIX,
    device=DEVICE,
)

one_change_summary_df = summarize_results(one_change_results)

one_change_common_eval_df = compare_on_common_objectives(
    one_change_results,
    SAVED_OBJECTIVES,
)

display(one_change_summary_df)

display(
    one_change_common_eval_df[
        one_change_common_eval_df["split"].eq("test")
    ].reset_index(drop=True)
)

expanded_saved_h512_d2_e16 ep 001/050* loss=0.04178 val_rmse=0.1456 top1=0.217 top3=0.395 reg=0.0408 rank=6.45 12s
expanded_saved_h512_d2_e16 ep 002/050* loss=0.01627 val_rmse=0.1311 top1=0.172 top3=0.376 reg=0.0354 rank=6.07 23s
expanded_saved_h512_d2_e16 ep 003/050* loss=0.01144 val_rmse=0.1313 top1=0.168 top3=0.376 reg=0.0352 rank=6.04 35s
expanded_saved_h512_d2_e16 ep 004/050* loss=0.00891 val_rmse=0.1335 top1=0.200 top3=0.405 reg=0.0339 rank=5.81 47s
expanded_saved_h512_d2_e16 ep 005/050* loss=0.00730 val_rmse=0.1322 top1=0.202 top3=0.420 reg=0.0325 rank=5.67 59s
expanded_saved_h512_d2_e16 ep 006/050* loss=0.00617 val_rmse=0.1306 top1=0.223 top3=0.440 reg=0.0298 rank=5.37 71s
expanded_saved_h512_d2_e16 ep 007/050* loss=0.00532 val_rmse=0.1275 top1=0.228 top3=0.433 reg=0.0296 rank=5.34 83s
expanded_saved_h512_d2_e16 ep 008/050* loss=0.00470 val_rmse=0.1253 top1=0.228 top3=0.453 reg=0.0273 rank=5.09 95s
expanded_saved_h512_d2_e16 ep 009/050* loss=0.00422 val_rmse=0.1266 top1=0.262 top3=0.472 reg=0.0261 rank=4.93 108s
expanded_saved_h512_d2_e16 ep 010/050  loss=0.00384 val_rmse=0.1265 top1=0.240 top3=0.451 reg=0.0268 rank=5.02 120s
expanded_saved_h512_d2_e16 ep 011/050  loss=0.00351 val_rmse=0.1275 top1=0.243 top3=0.465 reg=0.0262 rank=4.93 133s
expanded_saved_h512_d2_e16 ep 012/050* loss=0.00323 val_rmse=0.1249 top1=0.235 top3=0.445 reg=0.0260 rank=4.92 145s
expanded_saved_h512_d2_e16 ep 013/050* loss=0.00301 val_rmse=0.1246 top1=0.257 top3=0.464 reg=0.0256 rank=4.85 159s
expanded_saved_h512_d2_e16 ep 014/050* loss=0.00281 val_rmse=0.1244 top1=0.255 top3=0.471 reg=0.0256 rank=4.87 171s
expanded_saved_h512_d2_e16 ep 015/050  loss=0.00261 val_rmse=0.1266 top1=0.240 top3=0.457 reg=0.0263 rank=5.01 183s
expanded_saved_h512_d2_e16 ep 016/050* loss=0.00246 val_rmse=0.1248 top1=0.275 top3=0.471 reg=0.0254 rank=4.87 195s
expanded_saved_h512_d2_e16 ep 017/050* loss=0.00232 val_rmse=0.1257 top1=0.252 top3=0.472 reg=0.0246 rank=4.78 207s
expanded_saved_h512_d2_e16 ep 018/050* loss=0.00219 val_rmse=0.1216 top1=0.276 top3=0.488 reg=0.0235 rank=4.61 219s
expanded_saved_h512_d2_e16 ep 019/050  loss=0.00207 val_rmse=0.1235 top1=0.260 top3=0.472 reg=0.0245 rank=4.76 231s
expanded_saved_h512_d2_e16 ep 020/050  loss=0.00195 val_rmse=0.1242 top1=0.282 top3=0.472 reg=0.0247 rank=4.76 244s
expanded_saved_h512_d2_e16 ep 021/050  loss=0.00184 val_rmse=0.1219 top1=0.271 top3=0.469 reg=0.0249 rank=4.82 257s
expanded_saved_h512_d2_e16 ep 022/050  loss=0.00178 val_rmse=0.1242 top1=0.291 top3=0.496 reg=0.0240 rank=4.67 269s
expanded_saved_h512_d2_e16 ep 023/050  loss=0.00169 val_rmse=0.1256 top1=0.261 top3=0.491 reg=0.0246 rank=4.74 281s
expanded_saved_h512_d2_e16 ep 024/050  loss=0.00160 val_rmse=0.1252 top1=0.288 top3=0.490 reg=0.0243 rank=4.70 293s
expanded_saved_h512_d2_e16 ep 025/050  loss=0.00154 val_rmse=0.1234 top1=0.267 top3=0.486 reg=0.0237 rank=4.69 304s
expanded_saved_h512_d2_e16 ep 026/050* loss=0.00147 val_rmse=0.1231 top1=0.294 top3=0.510 reg=0.0234 rank=4.62 316s
expanded_saved_h512_d2_e16 ep 027/050  loss=0.00140 val_rmse=0.1248 top1=0.271 top3=0.501 reg=0.0236 rank=4.64 328s
expanded_saved_h512_d2_e16 ep 028/050* loss=0.00136 val_rmse=0.1232 top1=0.282 top3=0.514 reg=0.0228 rank=4.54 339s
expanded_saved_h512_d2_e16 ep 029/050  loss=0.00130 val_rmse=0.1251 top1=0.300 top3=0.508 reg=0.0234 rank=4.60 350s
expanded_saved_h512_d2_e16 ep 030/050* loss=0.00125 val_rmse=0.1225 top1=0.281 top3=0.540 reg=0.0220 rank=4.47 361s
expanded_saved_h512_d2_e16 ep 031/050  loss=0.00122 val_rmse=0.1242 top1=0.291 top3=0.514 reg=0.0234 rank=4.59 373s
expanded_saved_h512_d2_e16 ep 032/050  loss=0.00116 val_rmse=0.1223 top1=0.324 top3=0.537 reg=0.0223 rank=4.44 383s
expanded_saved_h512_d2_e16 ep 033/050  loss=0.00113 val_rmse=0.1228 top1=0.293 top3=0.508 reg=0.0233 rank=4.62 394s
expanded_saved_h512_d2_e16 ep 034/050  loss=0.00109 val_rmse=0.1231 top1=0.301 top3=0.534 reg=0.0224 rank=4.48 405s
expanded_saved_h512_d2_e16 ep 035/050  loss=0.00105 val_rmse=0.1227 top1=0.315 top3=0.540 reg=0.0221 rank=4.43 416s
expanded_saved_h512_d2_e16 ep 036/050  loss=0.00102 val_rmse=0.1237 top1=0.287 top3=0.549 reg=0.0221 rank=4.48 427s
expanded_saved_h512_d2_e16 ep 037/050  loss=0.00098 val_rmse=0.1253 top1=0.293 top3=0.523 reg=0.0240 rank=4.62 437s
expanded_saved_h512_d2_e16 ep 038/050  loss=0.00097 val_rmse=0.1239 top1=0.279 top3=0.519 reg=0.0246 rank=4.72 449s
expanded_saved_h512_d2_e16 ep 039/050  loss=0.00093 val_rmse=0.1247 top1=0.309 top3=0.537 reg=0.0226 rank=4.47 460s
expanded_saved_h512_d2_e16 ep 040/050  loss=0.00091 val_rmse=0.1249 top1=0.333 top3=0.558 reg=0.0230 rank=4.45 471s
expanded_saved_h512_d2_e16 ep 041/050  loss=0.00088 val_rmse=0.1237 top1=0.317 top3=0.552 reg=0.0223 rank=4.42 483s
expanded_saved_h512_d2_e16 ep 042/050* loss=0.00086 val_rmse=0.1231 top1=0.328 top3=0.559 reg=0.0220 rank=4.40 494s
expanded_saved_h512_d2_e16 ep 043/050  loss=0.00083 val_rmse=0.1231 top1=0.324 top3=0.543 reg=0.0240 rank=4.60 505s
expanded_saved_h512_d2_e16 ep 044/050  loss=0.00081 val_rmse=0.1237 top1=0.309 top3=0.557 reg=0.0231 rank=4.48 516s
expanded_saved_h512_d2_e16 ep 045/050  loss=0.00080 val_rmse=0.1261 top1=0.310 top3=0.549 reg=0.0235 rank=4.55 527s
expanded_saved_h512_d2_e16 ep 046/050  loss=0.00078 val_rmse=0.1237 top1=0.324 top3=0.567 reg=0.0223 rank=4.41 537s
expanded_saved_h512_d2_e16 ep 047/050  loss=0.00076 val_rmse=0.1246 top1=0.307 top3=0.568 reg=0.0229 rank=4.48 547s
expanded_saved_h512_d2_e16 ep 048/050  loss=0.00074 val_rmse=0.1228 top1=0.335 top3=0.563 reg=0.0228 rank=4.52 557s
expanded_saved_h512_d2_e16 ep 049/050* loss=0.00072 val_rmse=0.1233 top1=0.340 top3=0.569 reg=0.0216 rank=4.35 567s
expanded_saved_h512_d2_e16 ep 050/050  loss=0.00071 val_rmse=0.1247 top1=0.337 top3=0.575 reg=0.0216 rank=4.35 576s
expanded_saved_h512_d2_e24 ep 001/050* loss=0.04627 val_rmse=0.1492 top1=0.206 top3=0.391 reg=0.0425 rank=6.49 10s
expanded_saved_h512_d2_e24 ep 002/050* loss=0.01564 val_rmse=0.1344 top1=0.151 top3=0.352 reg=0.0419 rank=6.65 20s
expanded_saved_h512_d2_e24 ep 003/050* loss=0.01074 val_rmse=0.1285 top1=0.216 top3=0.407 reg=0.0347 rank=5.68 31s
expanded_saved_h512_d2_e24 ep 004/050* loss=0.00841 val_rmse=0.1292 top1=0.190 top3=0.398 reg=0.0321 rank=5.51 41s
expanded_saved_h512_d2_e24 ep 005/050  loss=0.00694 val_rmse=0.1297 top1=0.205 top3=0.401 reg=0.0322 rank=5.51 52s
expanded_saved_h512_d2_e24 ep 006/050* loss=0.00592 val_rmse=0.1259 top1=0.202 top3=0.402 reg=0.0306 rank=5.38 63s
expanded_saved_h512_d2_e24 ep 007/050* loss=0.00516 val_rmse=0.1254 top1=0.217 top3=0.415 reg=0.0287 rank=5.19 73s
expanded_saved_h512_d2_e24 ep 008/050  loss=0.00456 val_rmse=0.1293 top1=0.214 top3=0.392 reg=0.0299 rank=5.32 84s
expanded_saved_h512_d2_e24 ep 009/050* loss=0.00411 val_rmse=0.1266 top1=0.216 top3=0.415 reg=0.0280 rank=5.10 94s
expanded_saved_h512_d2_e24 ep 010/050* loss=0.00370 val_rmse=0.1260 top1=0.226 top3=0.425 reg=0.0267 rank=5.01 105s
expanded_saved_h512_d2_e24 ep 011/050  loss=0.00340 val_rmse=0.1267 top1=0.217 top3=0.399 reg=0.0290 rank=5.24 113s
expanded_saved_h512_d2_e24 ep 012/050* loss=0.00314 val_rmse=0.1252 top1=0.217 top3=0.408 reg=0.0265 rank=5.03 122s
expanded_saved_h512_d2_e24 ep 013/050  loss=0.00290 val_rmse=0.1277 top1=0.214 top3=0.419 reg=0.0268 rank=5.02 131s
expanded_saved_h512_d2_e24 ep 014/050  loss=0.00270 val_rmse=0.1258 top1=0.214 top3=0.408 reg=0.0282 rank=5.16 139s
expanded_saved_h512_d2_e24 ep 015/050* loss=0.00251 val_rmse=0.1231 top1=0.229 top3=0.428 reg=0.0252 rank=4.89 148s
expanded_saved_h512_d2_e24 ep 016/050  loss=0.00236 val_rmse=0.1235 top1=0.220 top3=0.422 reg=0.0255 rank=4.91 158s
expanded_saved_h512_d2_e24 ep 017/050* loss=0.00222 val_rmse=0.1242 top1=0.231 top3=0.435 reg=0.0252 rank=4.89 166s
expanded_saved_h512_d2_e24 ep 018/050  loss=0.00210 val_rmse=0.1233 top1=0.210 top3=0.425 reg=0.0256 rank=4.95 174s
expanded_saved_h512_d2_e24 ep 019/050* loss=0.00198 val_rmse=0.1231 top1=0.248 top3=0.446 reg=0.0247 rank=4.80 183s
expanded_saved_h512_d2_e24 ep 020/050  loss=0.00189 val_rmse=0.1252 top1=0.239 top3=0.443 reg=0.0251 rank=4.84 191s
expanded_saved_h512_d2_e24 ep 021/050  loss=0.00178 val_rmse=0.1236 top1=0.222 top3=0.431 reg=0.0251 rank=4.88 200s
expanded_saved_h512_d2_e24 ep 022/050* loss=0.00170 val_rmse=0.1256 top1=0.268 top3=0.463 reg=0.0245 rank=4.75 209s
expanded_saved_h512_d2_e24 ep 023/050* loss=0.00162 val_rmse=0.1243 top1=0.271 top3=0.459 reg=0.0239 rank=4.71 218s
expanded_saved_h512_d2_e24 ep 024/050  loss=0.00155 val_rmse=0.1238 top1=0.238 top3=0.451 reg=0.0245 rank=4.79 227s
expanded_saved_h512_d2_e24 ep 025/050  loss=0.00148 val_rmse=0.1237 top1=0.272 top3=0.449 reg=0.0247 rank=4.81 236s
expanded_saved_h512_d2_e24 ep 026/050  loss=0.00142 val_rmse=0.1249 top1=0.251 top3=0.452 reg=0.0252 rank=4.83 244s
expanded_saved_h512_d2_e24 ep 027/050  loss=0.00138 val_rmse=0.1241 top1=0.270 top3=0.463 reg=0.0244 rank=4.75 253s
expanded_saved_h512_d2_e24 ep 028/050* loss=0.00132 val_rmse=0.1245 top1=0.267 top3=0.451 reg=0.0239 rank=4.70 263s
expanded_saved_h512_d2_e24 ep 029/050  loss=0.00129 val_rmse=0.1255 top1=0.253 top3=0.453 reg=0.0249 rank=4.82 274s
expanded_saved_h512_d2_e24 ep 030/050  loss=0.00123 val_rmse=0.1250 top1=0.261 top3=0.456 reg=0.0247 rank=4.78 285s
expanded_saved_h512_d2_e24 ep 031/050  loss=0.00118 val_rmse=0.1253 top1=0.265 top3=0.449 reg=0.0247 rank=4.79 296s
expanded_saved_h512_d2_e24 ep 032/050  loss=0.00115 val_rmse=0.1265 top1=0.265 top3=0.444 reg=0.0253 rank=4.84 307s
expanded_saved_h512_d2_e24 ep 033/050  loss=0.00111 val_rmse=0.1270 top1=0.293 top3=0.471 reg=0.0246 rank=4.72 318s
expanded_saved_h512_d2_e24 ep 034/050  loss=0.00108 val_rmse=0.1241 top1=0.267 top3=0.460 reg=0.0247 rank=4.78 329s
expanded_saved_h512_d2_e24 ep 035/050  loss=0.00105 val_rmse=0.1252 top1=0.281 top3=0.454 reg=0.0243 rank=4.72 340s
expanded_saved_h512_d2_e24 ep 036/050  loss=0.00103 val_rmse=0.1242 top1=0.281 top3=0.472 reg=0.0247 rank=4.79 350s
expanded_saved_h512_d2_e24 ep 037/050  loss=0.00100 val_rmse=0.1272 top1=0.283 top3=0.474 reg=0.0260 rank=4.90 361s
expanded_saved_h512_d2_e24 ep 038/050  loss=0.00097 val_rmse=0.1235 top1=0.291 top3=0.474 reg=0.0243 rank=4.72 371s
expanded_saved_h512_d2_e24 ep 039/050  loss=0.00093 val_rmse=0.1251 top1=0.293 top3=0.483 reg=0.0246 rank=4.74 382s
expanded_saved_h512_d2_e24 ep 040/050  loss=0.00092 val_rmse=0.1264 top1=0.284 top3=0.459 reg=0.0256 rank=4.84 393s
expanded_saved_h512_d2_e24 ep 041/050  loss=0.00089 val_rmse=0.1245 top1=0.288 top3=0.484 reg=0.0243 rank=4.74 403s
expanded_saved_h512_d2_e24 ep 042/050  loss=0.00087 val_rmse=0.1249 top1=0.277 top3=0.468 reg=0.0254 rank=4.82 411s
expanded_saved_h512_d2_e24 ep 043/050  loss=0.00086 val_rmse=0.1247 top1=0.277 top3=0.472 reg=0.0251 rank=4.83 420s
expanded_saved_h512_d2_e24 ep 044/050  loss=0.00083 val_rmse=0.1263 top1=0.284 top3=0.466 reg=0.0245 rank=4.74 429s
expanded_saved_h512_d2_e24 early stop at ep 044; best ep 028
expanded_saved_h512_d2_e8_drop010 ep 001/050* loss=0.04736 val_rmse=0.1417 top1=0.225 top3=0.463 reg=0.0342 rank=5.83 8s
expanded_saved_h512_d2_e8_drop010 ep 002/050  loss=0.01941 val_rmse=0.1363 top1=0.136 top3=0.386 reg=0.0385 rank=6.30 17s
expanded_saved_h512_d2_e8_drop010 ep 003/050* loss=0.01400 val_rmse=0.1287 top1=0.180 top3=0.401 reg=0.0339 rank=5.77 26s
expanded_saved_h512_d2_e8_drop010 ep 004/050* loss=0.01132 val_rmse=0.1248 top1=0.201 top3=0.441 reg=0.0286 rank=5.21 34s
expanded_saved_h512_d2_e8_drop010 ep 005/050* loss=0.00963 val_rmse=0.1241 top1=0.232 top3=0.480 reg=0.0266 rank=4.93 43s
expanded_saved_h512_d2_e8_drop010 ep 006/050  loss=0.00835 val_rmse=0.1244 top1=0.231 top3=0.484 reg=0.0267 rank=4.97 52s
expanded_saved_h512_d2_e8_drop010 ep 007/050* loss=0.00739 val_rmse=0.1228 top1=0.246 top3=0.490 reg=0.0254 rank=4.82 60s
expanded_saved_h512_d2_e8_drop010 ep 008/050  loss=0.00660 val_rmse=0.1254 top1=0.269 top3=0.496 reg=0.0259 rank=4.88 69s
expanded_saved_h512_d2_e8_drop010 ep 009/050* loss=0.00607 val_rmse=0.1220 top1=0.259 top3=0.506 reg=0.0248 rank=4.76 77s
expanded_saved_h512_d2_e8_drop010 ep 010/050* loss=0.00557 val_rmse=0.1210 top1=0.266 top3=0.518 reg=0.0239 rank=4.69 86s
expanded_saved_h512_d2_e8_drop010 ep 011/050  loss=0.00513 val_rmse=0.1239 top1=0.271 top3=0.477 reg=0.0263 rank=4.97 95s
expanded_saved_h512_d2_e8_drop010 ep 012/050  loss=0.00477 val_rmse=0.1226 top1=0.271 top3=0.490 reg=0.0256 rank=4.93 103s
expanded_saved_h512_d2_e8_drop010 ep 013/050  loss=0.00444 val_rmse=0.1215 top1=0.273 top3=0.499 reg=0.0251 rank=4.87 112s
expanded_saved_h512_d2_e8_drop010 ep 014/050  loss=0.00417 val_rmse=0.1231 top1=0.258 top3=0.504 reg=0.0243 rank=4.78 121s
expanded_saved_h512_d2_e8_drop010 ep 015/050  loss=0.00390 val_rmse=0.1224 top1=0.271 top3=0.516 reg=0.0241 rank=4.74 130s
expanded_saved_h512_d2_e8_drop010 ep 016/050  loss=0.00372 val_rmse=0.1200 top1=0.273 top3=0.498 reg=0.0247 rank=4.79 138s
expanded_saved_h512_d2_e8_drop010 ep 017/050  loss=0.00347 val_rmse=0.1236 top1=0.266 top3=0.502 reg=0.0258 rank=4.90 147s
expanded_saved_h512_d2_e8_drop010 ep 018/050  loss=0.00332 val_rmse=0.1229 top1=0.269 top3=0.497 reg=0.0248 rank=4.79 155s
expanded_saved_h512_d2_e8_drop010 ep 019/050  loss=0.00313 val_rmse=0.1215 top1=0.296 top3=0.510 reg=0.0243 rank=4.73 164s
expanded_saved_h512_d2_e8_drop010 ep 020/050* loss=0.00301 val_rmse=0.1210 top1=0.287 top3=0.526 reg=0.0237 rank=4.66 173s
expanded_saved_h512_d2_e8_drop010 ep 021/050  loss=0.00284 val_rmse=0.1209 top1=0.279 top3=0.490 reg=0.0242 rank=4.80 181s
expanded_saved_h512_d2_e8_drop010 ep 022/050  loss=0.00272 val_rmse=0.1230 top1=0.306 top3=0.518 reg=0.0248 rank=4.71 190s
expanded_saved_h512_d2_e8_drop010 ep 023/050  loss=0.00260 val_rmse=0.1214 top1=0.261 top3=0.512 reg=0.0237 rank=4.67 198s
expanded_saved_h512_d2_e8_drop010 ep 024/050  loss=0.00249 val_rmse=0.1219 top1=0.270 top3=0.510 reg=0.0244 rank=4.72 207s
expanded_saved_h512_d2_e8_drop010 ep 025/050  loss=0.00240 val_rmse=0.1250 top1=0.262 top3=0.498 reg=0.0247 rank=4.75 215s
expanded_saved_h512_d2_e8_drop010 ep 026/050* loss=0.00229 val_rmse=0.1225 top1=0.271 top3=0.519 reg=0.0235 rank=4.62 224s
expanded_saved_h512_d2_e8_drop010 ep 027/050  loss=0.00222 val_rmse=0.1232 top1=0.238 top3=0.493 reg=0.0250 rank=4.85 232s
expanded_saved_h512_d2_e8_drop010 ep 028/050* loss=0.00214 val_rmse=0.1217 top1=0.288 top3=0.527 reg=0.0234 rank=4.57 241s
expanded_saved_h512_d2_e8_drop010 ep 029/050  loss=0.00206 val_rmse=0.1215 top1=0.271 top3=0.506 reg=0.0240 rank=4.70 249s
expanded_saved_h512_d2_e8_drop010 ep 030/050* loss=0.00199 val_rmse=0.1207 top1=0.279 top3=0.526 reg=0.0228 rank=4.57 258s
expanded_saved_h512_d2_e8_drop010 ep 031/050  loss=0.00191 val_rmse=0.1212 top1=0.266 top3=0.508 reg=0.0241 rank=4.70 266s
expanded_saved_h512_d2_e8_drop010 ep 032/050  loss=0.00184 val_rmse=0.1237 top1=0.254 top3=0.484 reg=0.0251 rank=4.83 275s
expanded_saved_h512_d2_e8_drop010 ep 033/050  loss=0.00178 val_rmse=0.1234 top1=0.281 top3=0.495 reg=0.0250 rank=4.80 283s
expanded_saved_h512_d2_e8_drop010 ep 034/050  loss=0.00172 val_rmse=0.1211 top1=0.251 top3=0.482 reg=0.0249 rank=4.81 292s
expanded_saved_h512_d2_e8_drop010 ep 035/050  loss=0.00166 val_rmse=0.1223 top1=0.271 top3=0.516 reg=0.0240 rank=4.68 301s
expanded_saved_h512_d2_e8_drop010 ep 036/050  loss=0.00161 val_rmse=0.1205 top1=0.266 top3=0.512 reg=0.0234 rank=4.63 309s
expanded_saved_h512_d2_e8_drop010 ep 037/050  loss=0.00156 val_rmse=0.1221 top1=0.267 top3=0.505 reg=0.0238 rank=4.68 318s
expanded_saved_h512_d2_e8_drop010 ep 038/050  loss=0.00152 val_rmse=0.1248 top1=0.256 top3=0.500 reg=0.0250 rank=4.82 326s
expanded_saved_h512_d2_e8_drop010 ep 039/050  loss=0.00149 val_rmse=0.1233 top1=0.251 top3=0.492 reg=0.0259 rank=4.93 335s
expanded_saved_h512_d2_e8_drop010 ep 040/050  loss=0.00142 val_rmse=0.1218 top1=0.245 top3=0.496 reg=0.0243 rank=4.77 343s
expanded_saved_h512_d2_e8_drop010 ep 041/050  loss=0.00139 val_rmse=0.1226 top1=0.257 top3=0.492 reg=0.0242 rank=4.76 352s
expanded_saved_h512_d2_e8_drop010 ep 042/050  loss=0.00133 val_rmse=0.1236 top1=0.238 top3=0.458 reg=0.0263 rank=5.01 360s
expanded_saved_h512_d2_e8_drop010 ep 043/050  loss=0.00131 val_rmse=0.1238 top1=0.259 top3=0.503 reg=0.0245 rank=4.73 368s
expanded_saved_h512_d2_e8_drop010 ep 044/050  loss=0.00126 val_rmse=0.1235 top1=0.271 top3=0.479 reg=0.0248 rank=4.78 377s
expanded_saved_h512_d2_e8_drop010 ep 045/050  loss=0.00125 val_rmse=0.1230 top1=0.267 top3=0.487 reg=0.0257 rank=4.86 386s
expanded_saved_h512_d2_e8_drop010 ep 046/050  loss=0.00120 val_rmse=0.1232 top1=0.255 top3=0.487 reg=0.0244 rank=4.76 394s
expanded_saved_h512_d2_e8_drop010 early stop at ep 046; best ep 030
expanded_saved_h512_d2_e8_wd5e4 ep 001/050* loss=0.04510 val_rmse=0.1434 top1=0.238 top3=0.448 reg=0.0359 rank=5.99 9s
expanded_saved_h512_d2_e8_wd5e4 ep 002/050  loss=0.01762 val_rmse=0.1354 top1=0.150 top3=0.391 reg=0.0408 rank=6.48 17s
expanded_saved_h512_d2_e8_wd5e4 ep 003/050  loss=0.01255 val_rmse=0.1297 top1=0.162 top3=0.384 reg=0.0364 rank=6.06 26s
expanded_saved_h512_d2_e8_wd5e4 ep 004/050* loss=0.00994 val_rmse=0.1244 top1=0.158 top3=0.419 reg=0.0316 rank=5.56 35s
expanded_saved_h512_d2_e8_wd5e4 ep 005/050* loss=0.00827 val_rmse=0.1246 top1=0.188 top3=0.457 reg=0.0286 rank=5.20 44s
expanded_saved_h512_d2_e8_wd5e4 ep 006/050  loss=0.00705 val_rmse=0.1262 top1=0.200 top3=0.463 reg=0.0287 rank=5.22 52s
expanded_saved_h512_d2_e8_wd5e4 ep 007/050* loss=0.00613 val_rmse=0.1244 top1=0.216 top3=0.489 reg=0.0280 rank=5.14 61s
expanded_saved_h512_d2_e8_wd5e4 ep 008/050* loss=0.00544 val_rmse=0.1262 top1=0.244 top3=0.498 reg=0.0273 rank=5.07 69s
expanded_saved_h512_d2_e8_wd5e4 ep 009/050* loss=0.00489 val_rmse=0.1221 top1=0.242 top3=0.510 reg=0.0263 rank=4.96 78s
expanded_saved_h512_d2_e8_wd5e4 ep 010/050* loss=0.00449 val_rmse=0.1238 top1=0.253 top3=0.506 reg=0.0259 rank=4.91 87s
expanded_saved_h512_d2_e8_wd5e4 ep 011/050  loss=0.00411 val_rmse=0.1253 top1=0.255 top3=0.490 reg=0.0276 rank=5.10 95s
expanded_saved_h512_d2_e8_wd5e4 ep 012/050  loss=0.00379 val_rmse=0.1240 top1=0.254 top3=0.512 reg=0.0267 rank=5.00 104s
expanded_saved_h512_d2_e8_wd5e4 ep 013/050  loss=0.00352 val_rmse=0.1201 top1=0.272 top3=0.528 reg=0.0261 rank=4.88 113s
expanded_saved_h512_d2_e8_wd5e4 ep 014/050* loss=0.00332 val_rmse=0.1219 top1=0.269 top3=0.522 reg=0.0250 rank=4.81 122s
expanded_saved_h512_d2_e8_wd5e4 ep 015/050  loss=0.00309 val_rmse=0.1197 top1=0.271 top3=0.534 reg=0.0255 rank=4.83 130s
expanded_saved_h512_d2_e8_wd5e4 ep 016/050  loss=0.00293 val_rmse=0.1218 top1=0.259 top3=0.504 reg=0.0264 rank=4.98 139s
expanded_saved_h512_d2_e8_wd5e4 ep 017/050  loss=0.00274 val_rmse=0.1247 top1=0.271 top3=0.522 reg=0.0256 rank=4.87 147s
expanded_saved_h512_d2_e8_wd5e4 ep 018/050  loss=0.00261 val_rmse=0.1231 top1=0.262 top3=0.501 reg=0.0263 rank=4.97 156s
expanded_saved_h512_d2_e8_wd5e4 ep 019/050* loss=0.00246 val_rmse=0.1217 top1=0.277 top3=0.514 reg=0.0247 rank=4.75 166s
expanded_saved_h512_d2_e8_wd5e4 ep 020/050* loss=0.00235 val_rmse=0.1205 top1=0.261 top3=0.534 reg=0.0246 rank=4.76 175s
expanded_saved_h512_d2_e8_wd5e4 ep 021/050  loss=0.00223 val_rmse=0.1218 top1=0.265 top3=0.512 reg=0.0249 rank=4.82 185s
expanded_saved_h512_d2_e8_wd5e4 ep 022/050  loss=0.00212 val_rmse=0.1236 top1=0.263 top3=0.502 reg=0.0268 rank=5.01 194s
expanded_saved_h512_d2_e8_wd5e4 ep 023/050* loss=0.00202 val_rmse=0.1215 top1=0.259 top3=0.518 reg=0.0245 rank=4.74 202s
expanded_saved_h512_d2_e8_wd5e4 ep 024/050  loss=0.00192 val_rmse=0.1233 top1=0.273 top3=0.516 reg=0.0251 rank=4.85 211s
expanded_saved_h512_d2_e8_wd5e4 ep 025/050  loss=0.00185 val_rmse=0.1243 top1=0.270 top3=0.516 reg=0.0254 rank=4.88 220s
expanded_saved_h512_d2_e8_wd5e4 ep 026/050  loss=0.00177 val_rmse=0.1221 top1=0.268 top3=0.528 reg=0.0246 rank=4.73 228s
expanded_saved_h512_d2_e8_wd5e4 ep 027/050  loss=0.00171 val_rmse=0.1217 top1=0.263 top3=0.507 reg=0.0256 rank=4.91 237s

,run_name,utility,hidden,emb_dim,depth,dropout,combine,loss,best_epoch,train_rmse,...,val_avg_regret,val_avg_norm_regret,test_rmse,test_mae,test_r2,test_top1,test_top3,test_mean_rank,test_avg_regret,test_avg_norm_regret
0,expanded_saved_h512_d2_e16,saved,512,16,2,0.05,mul_only,mse,49,0.015718,...,0.021587,0.047695,0.117341,0.084514,0.652360,0.358339,0.606162,4.034159,0.021643,0.042809
1,expanded_saved_h512_d2_e8_smoothl1,saved,512,8,2,0.05,mul_only,smooth_l1,8,0.045941,...,0.022192,0.048724,0.119032,0.088301,0.642266,0.215673,0.482920,4.508372,0.023325,0.046852
2,expanded_saved_h512_d2_e8_drop010,saved,512,8,2,0.10,mul_only,mse,30,0.029872,...,0.022825,0.050606,0.118083,0.085402,0.647949,0.279303,0.535164,4.306095,0.023078,0.045778
3,expanded_saved_h512_d2_e8_wd5e4,saved,512,8,2,0.05,mul_only,mse,41,0.019413,...,0.022854,0.050628,0.115975,0.083389,0.660402,0.282652,0.549230,4.342264,0.023081,0.046444
4,expanded_saved_h512_d2_e24,saved,512,24,2,0.05,mul_only,mse,28,0.024481,...,0.023883,0.049692,0.123081,0.090066,0.617515,0.249163,0.459478,4.718687,0.025646,0.050379

,run_name,train_utility,eval_objective,split,hidden,emb_dim,combine,top1,top3,mean_rank,avg_regret,avg_norm_regret
0,expanded_saved_h512_d2_e8_smoothl1,saved,contains_closest,test,512,8,mul_only,0.957803,0.957803,1.675151,0.042197,0.042197
1,expanded_saved_h512_d2_e8_drop010,saved,contains_closest,test,512,8,mul_only,0.950435,0.950435,1.793034,0.049565,0.049565
2,expanded_saved_h512_d2_e8_wd5e4,saved,contains_closest,test,512,8,mul_only,0.945747,0.945747,1.868051,0.054253,0.054253
3,expanded_saved_h512_d2_e16,saved,contains_closest,test,512,16,mul_only,0.945077,0.945077,1.878768,0.054923,0.054923
4,expanded_saved_h512_d2_e24,saved,contains_closest,test,512,24,mul_only,0.942398,0.942398,1.921634,0.057602,0.057602
5,expanded_saved_h512_d2_e16,saved,saved_rational,test,512,16,mul_only,0.358339,0.606162,4.034159,0.021643,0.042809
6,expanded_saved_h512_d2_e8_drop010,saved,saved_rational,test,512,8,mul_only,0.279303,0.535164,4.306095,0.023078,0.045778
7,expanded_saved_h512_d2_e8_wd5e4,saved,saved_rational,test,512,8,mul_only,0.282652,0.549230,4.342264,0.023081,0.046444
8,expanded_saved_h512_d2_e8_smoothl1,saved,saved_rational,test,512,8,mul_only,0.215673,0.482920,4.508372,0.023325,0.046852
9,expanded_saved_h512_d2_e24,saved,saved_rational,test,512,24,mul_only,0.249163,0.459478,4.718687,0.025646,0.050379

In [7]:
import importlib
import pandas as pd
from dataclasses import replace

import two_tower_training
importlib.reload(two_tower_training)

from two_tower_training import (
    TrainConfig,
    compare_on_common_objectives,
    run_config_grid,
    summarize_results,
)

DEVICE = "cuda" if torch.cuda.is_available() else "cpu"

SAVED_OBJECTIVES = [
    {"name": "saved_rational", "utility_name": "saved", "utility_kwargs": {}},
    {"name": "contains_closest", "utility_name": "closest_binary", "utility_kwargs": {}},
]

# New baseline: best from the previous batch.
base_e16_config = TrainConfig(
    run_name="expanded_saved_h512_d2_e16",
    utility_name="saved",
    hidden=512,
    emb_dim=16,
    depth=2,
    dropout=0.05,
    combine_mode="mul_only",
    loss_name="mse",
    max_epochs=50,
    patience=16,
    batch_size=8192,
    lr=1e-3,
    weight_decay=1e-4,
    seed=22,
    log_every=1,
)

e16_probe_configs = [
    # 1. Smaller embedding near the winner.
    replace(
        base_e16_config,
        run_name="expanded_saved_h512_d2_e12",
        emb_dim=12,
    ),

    # 2. Larger embedding near the winner, but below the bad e24 case.
    replace(
        base_e16_config,
        run_name="expanded_saved_h512_d2_e20",
        emb_dim=20,
    ),

    # 3. More dropout around e16.
    replace(
        base_e16_config,
        run_name="expanded_saved_h512_d2_e16_drop010",
        dropout=0.10,
    ),

    # 4. More weight decay around e16.
    replace(
        base_e16_config,
        run_name="expanded_saved_h512_d2_e16_wd5e4",
        weight_decay=5e-4,
    ),

    # 5. Lower learning rate around e16.
    replace(
        base_e16_config,
        run_name="expanded_saved_h512_d2_e16_lr5e4",
        lr=5e-4,
    ),
]

e16_probe_results = run_config_grid(
    PROCESSED_DIR,
    e16_probe_configs,
    prefix=EXPANDED_PREFIX,
    device=DEVICE,
)

e16_probe_summary_df = summarize_results(e16_probe_results)

e16_probe_common_eval_df = compare_on_common_objectives(
    e16_probe_results,
    SAVED_OBJECTIVES,
)

display(e16_probe_summary_df)

display(
    e16_probe_common_eval_df[
        e16_probe_common_eval_df["split"].eq("test")
    ].reset_index(drop=True)
)

expanded_saved_h512_d2_e12 ep 001/050* loss=0.05611 val_rmse=0.1463 top1=0.152 top3=0.393 reg=0.0432 rank=6.77 13s
expanded_saved_h512_d2_e12 ep 002/050* loss=0.01861 val_rmse=0.1312 top1=0.126 top3=0.354 reg=0.0378 rank=6.30 23s
expanded_saved_h512_d2_e12 ep 003/050* loss=0.01319 val_rmse=0.1313 top1=0.123 top3=0.386 reg=0.0348 rank=6.06 34s
expanded_saved_h512_d2_e12 ep 004/050* loss=0.01049 val_rmse=0.1302 top1=0.167 top3=0.420 reg=0.0306 rank=5.56 44s
expanded_saved_h512_d2_e12 ep 005/050* loss=0.00875 val_rmse=0.1312 top1=0.210 top3=0.475 reg=0.0278 rank=5.17 55s
expanded_saved_h512_d2_e12 ep 006/050* loss=0.00746 val_rmse=0.1302 top1=0.217 top3=0.497 reg=0.0260 rank=4.93 65s
expanded_saved_h512_d2_e12 ep 007/050* loss=0.00656 val_rmse=0.1310 top1=0.220 top3=0.491 reg=0.0255 rank=4.89 75s
expanded_saved_h512_d2_e12 ep 008/050  loss=0.00583 val_rmse=0.1304 top1=0.222 top3=0.490 reg=0.0258 rank=4.94 85s
expanded_saved_h512_d2_e12 ep 009/050* loss=0.00520 val_rmse=0.1314 top1=0.236 top3=0.494 reg=0.0242 rank=4.72 96s
expanded_saved_h512_d2_e12 ep 010/050  loss=0.00475 val_rmse=0.1309 top1=0.216 top3=0.480 reg=0.0251 rank=4.86 106s
expanded_saved_h512_d2_e12 ep 011/050* loss=0.00435 val_rmse=0.1309 top1=0.254 top3=0.504 reg=0.0236 rank=4.64 116s
expanded_saved_h512_d2_e12 ep 012/050  loss=0.00403 val_rmse=0.1296 top1=0.222 top3=0.467 reg=0.0250 rank=4.88 126s
expanded_saved_h512_d2_e12 ep 013/050* loss=0.00372 val_rmse=0.1284 top1=0.248 top3=0.510 reg=0.0230 rank=4.62 135s
expanded_saved_h512_d2_e12 ep 014/050  loss=0.00348 val_rmse=0.1278 top1=0.234 top3=0.469 reg=0.0239 rank=4.73 144s
expanded_saved_h512_d2_e12 ep 015/050  loss=0.00326 val_rmse=0.1300 top1=0.230 top3=0.478 reg=0.0251 rank=4.82 153s
expanded_saved_h512_d2_e12 ep 016/050  loss=0.00305 val_rmse=0.1301 top1=0.251 top3=0.509 reg=0.0241 rank=4.67 162s
expanded_saved_h512_d2_e12 ep 017/050  loss=0.00288 val_rmse=0.1286 top1=0.242 top3=0.469 reg=0.0255 rank=4.87 171s
expanded_saved_h512_d2_e12 ep 018/050  loss=0.00273 val_rmse=0.1282 top1=0.265 top3=0.502 reg=0.0239 rank=4.64 180s
expanded_saved_h512_d2_e12 ep 019/050  loss=0.00257 val_rmse=0.1290 top1=0.249 top3=0.494 reg=0.0249 rank=4.80 190s
expanded_saved_h512_d2_e12 ep 020/050  loss=0.00245 val_rmse=0.1299 top1=0.237 top3=0.488 reg=0.0242 rank=4.73 199s
expanded_saved_h512_d2_e12 ep 021/050  loss=0.00230 val_rmse=0.1280 top1=0.259 top3=0.500 reg=0.0248 rank=4.73 208s
expanded_saved_h512_d2_e12 ep 022/050  loss=0.00218 val_rmse=0.1278 top1=0.261 top3=0.498 reg=0.0232 rank=4.62 217s
expanded_saved_h512_d2_e12 ep 023/050  loss=0.00207 val_rmse=0.1290 top1=0.255 top3=0.497 reg=0.0246 rank=4.74 227s
expanded_saved_h512_d2_e12 ep 024/050  loss=0.00200 val_rmse=0.1266 top1=0.269 top3=0.510 reg=0.0237 rank=4.64 236s
expanded_saved_h512_d2_e12 ep 025/050  loss=0.00189 val_rmse=0.1271 top1=0.257 top3=0.496 reg=0.0251 rank=4.77 245s
expanded_saved_h512_d2_e12 ep 026/050  loss=0.00180 val_rmse=0.1296 top1=0.252 top3=0.479 reg=0.0270 rank=5.03 254s
expanded_saved_h512_d2_e12 ep 027/050  loss=0.00172 val_rmse=0.1271 top1=0.269 top3=0.505 reg=0.0239 rank=4.69 264s
expanded_saved_h512_d2_e12 ep 028/050  loss=0.00166 val_rmse=0.1285 top1=0.250 top3=0.489 reg=0.0260 rank=4.90 273s
expanded_saved_h512_d2_e12 ep 029/050  loss=0.00158 val_rmse=0.1276 top1=0.271 top3=0.501 reg=0.0256 rank=4.81 282s
expanded_saved_h512_d2_e12 early stop at ep 029; best ep 013
expanded_saved_h512_d2_e20 ep 001/050* loss=0.04459 val_rmse=0.1493 top1=0.159 top3=0.362 reg=0.0476 rank=7.29 10s
expanded_saved_h512_d2_e20 ep 002/050* loss=0.01586 val_rmse=0.1368 top1=0.125 top3=0.338 reg=0.0437 rank=6.77 20s
expanded_saved_h512_d2_e20 ep 003/050* loss=0.01086 val_rmse=0.1334 top1=0.157 top3=0.404 reg=0.0333 rank=5.70 29s
expanded_saved_h512_d2_e20 ep 004/050* loss=0.00838 val_rmse=0.1327 top1=0.184 top3=0.413 reg=0.0316 rank=5.57 37s
expanded_saved_h512_d2_e20 ep 005/050  loss=0.00684 val_rmse=0.1317 top1=0.169 top3=0.403 reg=0.0334 rank=5.75 46s
expanded_saved_h512_d2_e20 ep 006/050* loss=0.00577 val_rmse=0.1289 top1=0.190 top3=0.413 reg=0.0315 rank=5.54 56s
expanded_saved_h512_d2_e20 ep 007/050* loss=0.00500 val_rmse=0.1286 top1=0.190 top3=0.415 reg=0.0305 rank=5.45 64s
expanded_saved_h512_d2_e20 ep 008/050  loss=0.00443 val_rmse=0.1340 top1=0.197 top3=0.402 reg=0.0330 rank=5.73 73s
expanded_saved_h512_d2_e20 ep 009/050  loss=0.00399 val_rmse=0.1309 top1=0.196 top3=0.418 reg=0.0305 rank=5.45 82s
expanded_saved_h512_d2_e20 ep 010/050  loss=0.00360 val_rmse=0.1297 top1=0.192 top3=0.395 reg=0.0338 rank=5.82 90s
expanded_saved_h512_d2_e20 ep 011/050  loss=0.00335 val_rmse=0.1298 top1=0.186 top3=0.393 reg=0.0324 rank=5.69 99s
expanded_saved_h512_d2_e20 ep 012/050  loss=0.00308 val_rmse=0.1266 top1=0.229 top3=0.434 reg=0.0318 rank=5.54 108s
expanded_saved_h512_d2_e20 ep 013/050  loss=0.00283 val_rmse=0.1303 top1=0.198 top3=0.397 reg=0.0334 rank=5.75 116s
expanded_saved_h512_d2_e20 ep 014/050  loss=0.00267 val_rmse=0.1297 top1=0.218 top3=0.427 reg=0.0320 rank=5.51 125s
expanded_saved_h512_d2_e20 ep 015/050  loss=0.00249 val_rmse=0.1291 top1=0.206 top3=0.408 reg=0.0335 rank=5.74 134s
expanded_saved_h512_d2_e20 ep 016/050* loss=0.00231 val_rmse=0.1284 top1=0.236 top3=0.445 reg=0.0304 rank=5.33 142s
expanded_saved_h512_d2_e20 ep 017/050  loss=0.00218 val_rmse=0.1291 top1=0.225 top3=0.435 reg=0.0318 rank=5.52 151s
expanded_saved_h512_d2_e20 ep 018/050  loss=0.00207 val_rmse=0.1301 top1=0.246 top3=0.425 reg=0.0328 rank=5.59 160s
expanded_saved_h512_d2_e20 ep 019/050  loss=0.00194 val_rmse=0.1308 top1=0.220 top3=0.420 reg=0.0332 rank=5.64 168s
expanded_saved_h512_d2_e20 ep 020/050* loss=0.00185 val_rmse=0.1270 top1=0.258 top3=0.467 reg=0.0291 rank=5.19 177s
expanded_saved_h512_d2_e20 ep 021/050  loss=0.00175 val_rmse=0.1273 top1=0.242 top3=0.440 reg=0.0321 rank=5.54 185s
expanded_saved_h512_d2_e20 ep 022/050  loss=0.00164 val_rmse=0.1279 top1=0.235 top3=0.438 reg=0.0315 rank=5.46 194s
expanded_saved_h512_d2_e20 ep 023/050  loss=0.00157 val_rmse=0.1293 top1=0.250 top3=0.450 reg=0.0318 rank=5.46 203s
expanded_saved_h512_d2_e20 ep 024/050  loss=0.00150 val_rmse=0.1283 top1=0.279 top3=0.467 reg=0.0306 rank=5.30 212s
expanded_saved_h512_d2_e20 ep 025/050  loss=0.00143 val_rmse=0.1283 top1=0.236 top3=0.440 reg=0.0310 rank=5.42 220s
expanded_saved_h512_d2_e20 ep 026/050  loss=0.00138 val_rmse=0.1271 top1=0.259 top3=0.459 reg=0.0295 rank=5.20 229s
expanded_saved_h512_d2_e20 ep 027/050  loss=0.00132 val_rmse=0.1268 top1=0.253 top3=0.470 reg=0.0296 rank=5.20 237s
expanded_saved_h512_d2_e20 ep 028/050  loss=0.00127 val_rmse=0.1281 top1=0.273 top3=0.466 reg=0.0301 rank=5.23 246s
expanded_saved_h512_d2_e20 ep 029/050  loss=0.00122 val_rmse=0.1269 top1=0.289 top3=0.480 reg=0.0291 rank=5.12 255s
expanded_saved_h512_d2_e20 ep 030/050  loss=0.00117 val_rmse=0.1263 top1=0.285 top3=0.494 reg=0.0294 rank=5.08 264s
expanded_saved_h512_d2_e20 ep 031/050  loss=0.00111 val_rmse=0.1271 top1=0.261 top3=0.481 reg=0.0294 rank=5.15 273s
expanded_saved_h512_d2_e20 ep 032/050  loss=0.00108 val_rmse=0.1288 top1=0.289 top3=0.480 reg=0.0312 rank=5.27 282s
expanded_saved_h512_d2_e20 ep 033/050* loss=0.00105 val_rmse=0.1264 top1=0.297 top3=0.498 reg=0.0287 rank=5.03 291s
expanded_saved_h512_d2_e20 ep 034/050  loss=0.00101 val_rmse=0.1278 top1=0.282 top3=0.486 reg=0.0311 rank=5.30 300s
expanded_saved_h512_d2_e20 ep 035/050* loss=0.00098 val_rmse=0.1256 top1=0.301 top3=0.510 reg=0.0273 rank=4.84 309s
expanded_saved_h512_d2_e20 ep 036/050  loss=0.00095 val_rmse=0.1259 top1=0.265 top3=0.498 reg=0.0287 rank=5.05 317s
expanded_saved_h512_d2_e20 ep 037/050  loss=0.00093 val_rmse=0.1258 top1=0.301 top3=0.509 reg=0.0275 rank=4.90 326s
expanded_saved_h512_d2_e20 ep 038/050  loss=0.00090 val_rmse=0.1254 top1=0.293 top3=0.512 reg=0.0273 rank=4.88 335s
expanded_saved_h512_d2_e20 ep 039/050* loss=0.00087 val_rmse=0.1256 top1=0.291 top3=0.524 reg=0.0270 rank=4.84 343s
expanded_saved_h512_d2_e20 ep 040/050* loss=0.00084 val_rmse=0.1250 top1=0.322 top3=0.531 reg=0.0267 rank=4.80 352s
expanded_saved_h512_d2_e20 ep 041/050* loss=0.00082 val_rmse=0.1237 top1=0.303 top3=0.526 reg=0.0262 rank=4.77 361s
expanded_saved_h512_d2_e20 ep 042/050  loss=0.00080 val_rmse=0.1250 top1=0.295 top3=0.518 reg=0.0263 rank=4.79 369s
expanded_saved_h512_d2_e20 ep 043/050  loss=0.00078 val_rmse=0.1254 top1=0.295 top3=0.531 reg=0.0263 rank=4.75 378s
expanded_saved_h512_d2_e20 ep 044/050  loss=0.00076 val_rmse=0.1252 top1=0.295 top3=0.524 reg=0.0270 rank=4.84 386s
expanded_saved_h512_d2_e20 ep 045/050* loss=0.00075 val_rmse=0.1231 top1=0.317 top3=0.543 reg=0.0255 rank=4.67 395s
expanded_saved_h512_d2_e20 ep 046/050  loss=0.00072 val_rmse=0.1249 top1=0.309 top3=0.529 reg=0.0266 rank=4.82 404s
expanded_saved_h512_d2_e20 ep 047/050* loss=0.00070 val_rmse=0.1242 top1=0.321 top3=0.532 reg=0.0254 rank=4.67 412s
expanded_saved_h512_d2_e20 ep 048/050* loss=0.00069 val_rmse=0.1250 top1=0.328 top3=0.539 reg=0.0254 rank=4.68 421s
expanded_saved_h512_d2_e20 ep 049/050  loss=0.00067 val_rmse=0.1252 top1=0.296 top3=0.548 reg=0.0258 rank=4.69 430s
expanded_saved_h512_d2_e20 ep 050/050* loss=0.00067 val_rmse=0.1232 top1=0.316 top3=0.561 reg=0.0245 rank=4.54 439s
expanded_saved_h512_d2_e16_drop010 ep 001/050* loss=0.04365 val_rmse=0.1451 top1=0.203 top3=0.384 reg=0.0418 rank=6.50 9s
expanded_saved_h512_d2_e16_drop010 ep 002/050* loss=0.01797 val_rmse=0.1309 top1=0.150 top3=0.365 reg=0.0362 rank=6.25 18s
expanded_saved_h512_d2_e16_drop010 ep 003/050* loss=0.01291 val_rmse=0.1305 top1=0.165 top3=0.379 reg=0.0337 rank=5.89 26s
expanded_saved_h512_d2_e16_drop010 ep 004/050* loss=0.01037 val_rmse=0.1326 top1=0.196 top3=0.420 reg=0.0308 rank=5.52 35s
expanded_saved_h512_d2_e16_drop010 ep 005/050  loss=0.00870 val_rmse=0.1322 top1=0.196 top3=0.423 reg=0.0319 rank=5.63 44s
expanded_saved_h512_d2_e16_drop010 ep 006/050* loss=0.00750 val_rmse=0.1285 top1=0.216 top3=0.458 reg=0.0278 rank=5.18 53s
expanded_saved_h512_d2_e16_drop010 ep 007/050* loss=0.00657 val_rmse=0.1262 top1=0.228 top3=0.441 reg=0.0272 rank=5.10 62s
expanded_saved_h512_d2_e16_drop010 ep 008/050* loss=0.00589 val_rmse=0.1261 top1=0.210 top3=0.447 reg=0.0272 rank=5.05 71s
expanded_saved_h512_d2_e16_drop010 ep 009/050* loss=0.00531 val_rmse=0.1296 top1=0.239 top3=0.471 reg=0.0260 rank=4.94 79s
expanded_saved_h512_d2_e16_drop010 ep 010/050  loss=0.00489 val_rmse=0.1256 top1=0.230 top3=0.455 reg=0.0261 rank=4.95 89s
expanded_saved_h512_d2_e16_drop010 ep 011/050* loss=0.00448 val_rmse=0.1255 top1=0.248 top3=0.466 reg=0.0253 rank=4.79 98s
expanded_saved_h512_d2_e16_drop010 ep 012/050  loss=0.00412 val_rmse=0.1268 top1=0.232 top3=0.464 reg=0.0258 rank=4.87 107s
expanded_saved_h512_d2_e16_drop010 ep 013/050* loss=0.00383 val_rmse=0.1266 top1=0.253 top3=0.466 reg=0.0247 rank=4.77 117s
expanded_saved_h512_d2_e16_drop010 ep 014/050* loss=0.00360 val_rmse=0.1238 top1=0.273 top3=0.500 reg=0.0242 rank=4.69 127s
expanded_saved_h512_d2_e16_drop010 ep 015/050  loss=0.00336 val_rmse=0.1263 top1=0.247 top3=0.490 reg=0.0243 rank=4.77 136s
expanded_saved_h512_d2_e16_drop010 ep 016/050  loss=0.00312 val_rmse=0.1261 top1=0.281 top3=0.480 reg=0.0254 rank=4.86 146s
expanded_saved_h512_d2_e16_drop010 ep 017/050* loss=0.00294 val_rmse=0.1246 top1=0.277 top3=0.484 reg=0.0240 rank=4.73 155s
expanded_saved_h512_d2_e16_drop010 ep 018/050  loss=0.00281 val_rmse=0.1259 top1=0.271 top3=0.496 reg=0.0247 rank=4.77 166s
expanded_saved_h512_d2_e16_drop010 ep 019/050* loss=0.00265 val_rmse=0.1233 top1=0.278 top3=0.492 reg=0.0239 rank=4.73 176s
expanded_saved_h512_d2_e16_drop010 ep 020/050  loss=0.00250 val_rmse=0.1244 top1=0.311 top3=0.491 reg=0.0250 rank=4.78 185s
expanded_saved_h512_d2_e16_drop010 ep 021/050  loss=0.00235 val_rmse=0.1238 top1=0.251 top3=0.479 reg=0.0252 rank=4.87 193s
expanded_saved_h512_d2_e16_drop010 ep 022/050* loss=0.00223 val_rmse=0.1249 top1=0.273 top3=0.522 reg=0.0236 rank=4.64 201s
expanded_saved_h512_d2_e16_drop010 ep 023/050  loss=0.00214 val_rmse=0.1242 top1=0.281 top3=0.494 reg=0.0239 rank=4.69 210s
expanded_saved_h512_d2_e16_drop010 ep 024/050  loss=0.00203 val_rmse=0.1261 top1=0.292 top3=0.482 reg=0.0247 rank=4.75 218s
expanded_saved_h512_d2_e16_drop010 ep 025/050  loss=0.00196 val_rmse=0.1245 top1=0.278 top3=0.487 reg=0.0243 rank=4.77 228s
expanded_saved_h512_d2_e16_drop010 ep 026/050  loss=0.00187 val_rmse=0.1250 top1=0.303 top3=0.492 reg=0.0240 rank=4.73 236s
expanded_saved_h512_d2_e16_drop010 ep 027/050  loss=0.00180 val_rmse=0.1262 top1=0.271 top3=0.494 reg=0.0250 rank=4.80 244s
expanded_saved_h512_d2_e16_drop010 ep 028/050  loss=0.00173 val_rmse=0.1253 top1=0.289 top3=0.507 reg=0.0242 rank=4.68 253s
expanded_saved_h512_d2_e16_drop010 ep 029/050  loss=0.00164 val_rmse=0.1273 top1=0.270 top3=0.500 reg=0.0253 rank=4.85 262s
expanded_saved_h512_d2_e16_drop010 ep 030/050* loss=0.00159 val_rmse=0.1230 top1=0.309 top3=0.528 reg=0.0229 rank=4.57 271s
expanded_saved_h512_d2_e16_drop010 ep 031/050  loss=0.00155 val_rmse=0.1268 top1=0.296 top3=0.520 reg=0.0240 rank=4.69 280s
expanded_saved_h512_d2_e16_drop010 ep 032/050  loss=0.00148 val_rmse=0.1270 top1=0.315 top3=0.514 reg=0.0245 rank=4.74 288s
expanded_saved_h512_d2_e16_drop010 ep 033/050  loss=0.00144 val_rmse=0.1279 top1=0.284 top3=0.506 reg=0.0247 rank=4.79 296s
expanded_saved_h512_d2_e16_drop010 ep 034/050  loss=0.00140 val_rmse=0.1234 top1=0.266 top3=0.520 reg=0.0248 rank=4.78 305s
expanded_saved_h512_d2_e16_drop010 ep 035/050  loss=0.00135 val_rmse=0.1255 top1=0.309 top3=0.522 reg=0.0246 rank=4.73 313s
expanded_saved_h512_d2_e16_drop010 ep 036/050  loss=0.00130 val_rmse=0.1264 top1=0.287 top3=0.518 reg=0.0255 rank=4.85 322s
expanded_saved_h512_d2_e16_drop010 ep 037/050  loss=0.00127 val_rmse=0.1261 top1=0.299 top3=0.530 reg=0.0245 rank=4.70 330s
expanded_saved_h512_d2_e16_drop010 ep 038/050  loss=0.00124 val_rmse=0.1228 top1=0.301 top3=0.533 reg=0.0244 rank=4.67 338s
expanded_saved_h512_d2_e16_drop010 ep 039/050  loss=0.00121 val_rmse=0.1264 top1=0.269 top3=0.521 reg=0.0241 rank=4.73 348s
expanded_saved_h512_d2_e16_drop010 ep 040/050  loss=0.00117 val_rmse=0.1274 top1=0.305 top3=0.510 reg=0.0253 rank=4.81 356s
expanded_saved_h512_d2_e16_drop010 ep 041/050  loss=0.00114 val_rmse=0.1277 top1=0.291 top3=0.532 reg=0.0245 rank=4.71 365s
expanded_saved_h512_d2_e16_drop010 ep 042/050  loss=0.00112 val_rmse=0.1249 top1=0.310 top3=0.545 reg=0.0235 rank=4.59 373s
expanded_saved_h512_d2_e16_drop010 ep 043/050  loss=0.00108 val_rmse=0.1253 top1=0.344 top3=0.548 reg=0.0232 rank=4.52 382s
expanded_saved_h512_d2_e16_drop010 ep 044/050  loss=0.00106 val_rmse=0.1266 top1=0.313 top3=0.550 reg=0.0235 rank=4.58 390s
expanded_saved_h512_d2_e16_drop010 ep 045/050  loss=0.00103 val_rmse=0.1267 top1=0.316 top3=0.549 reg=0.0230 rank=4.53 399s
expanded_saved_h512_d2_e16_drop010 ep 046/050  loss=0.00103 val_rmse=0.1266 top1=0.320 top3=0.553 reg=0.0248 rank=4.62 408s
expanded_saved_h512_d2_e16_drop010 early stop at ep 046; best ep 030
expanded_saved_h512_d2_e16_wd5e4 ep 001/050* loss=0.04178 val_rmse=0.1456 top1=0.217 top3=0.396 reg=0.0408 rank=6.43 9s
expanded_saved_h512_d2_e16_wd5e4 ep 002/050* loss=0.01627 val_rmse=0.1310 top1=0.173 top3=0.372 reg=0.0355 rank=6.08 17s
expanded_saved_h512_d2_e16_wd5e4 ep 003/050* loss=0.01144 val_rmse=0.1312 top1=0.171 top3=0.376 reg=0.0350 rank=6.00 26s
expanded_saved_h512_d2_e16_wd5e4 ep 004/050* loss=0.00891 val_rmse=0.1336 top1=0.202 top3=0.406 reg=0.0336 rank=5.78 35s
expanded_saved_h512_d2_e16_wd5e4 ep 005/050* loss=0.00730 val_rmse=0.1323 top1=0.203 top3=0.423 reg=0.0324 rank=5.63 43s
expanded_saved_h512_d2_e16_wd5e4 ep 006/050* loss=0.00616 val_rmse=0.1307 top1=0.222 top3=0.445 reg=0.0297 rank=5.34 52s
expanded_saved_h512_d2_e16_wd5e4 ep 007/050* loss=0.00532 val_rmse=0.1277 top1=0.231 top3=0.438 reg=0.0296 rank=5.32 61s
expanded_saved_h512_d2_e16_wd5e4 ep 008/050* loss=0.00470 val_rmse=0.1255 top1=0.228 top3=0.450 reg=0.0275 rank=5.08 69s
expanded_saved_h512_d2_e16_wd5e4 ep 009/050* loss=0.00422 val_rmse=0.1265 top1=0.260 top3=0.474 reg=0.0260 rank=4.90 78s
expanded_saved_h512_d2_e16_wd5e4 ep 010/050  loss=0.00384 val_rmse=0.1265 top1=0.244 top3=0.459 reg=0.0267 rank=5.00 86s
expanded_saved_h512_d2_e16_wd5e4 ep 011/050  loss=0.00351 val_rmse=0.1274 top1=0.246 top3=0.471 reg=0.0262 rank=4.92 95s
expanded_saved_h512_d2_e16_wd5e4 ep 012/050  loss=0.00322 val_rmse=0.1253 top1=0.235 top3=0.451 reg=0.0263 rank=4.94 103s
expanded_saved_h512_d2_e16_wd5e4 ep 013/050* loss=0.00301 val_rmse=0.1251 top1=0.255 top3=0.466 reg=0.0259 rank=4.87 111s
expanded_saved_h512_d2_e16_wd5e4 ep 014/050* loss=0.00281 val_rmse=0.1247 top1=0.260 top3=0.474 reg=0.0251 rank=4.81 119s
expanded_saved_h512_d2_e16_wd5e4 ep 015/050  loss=0.00260 val_rmse=0.1267 top1=0.241 top3=0.462 reg=0.0265 rank=5.02 127s
expanded_saved_h512_d2_e16_wd5e4 ep 016/050  loss=0.00246 val_rmse=0.1251 top1=0.276 top3=0.476 reg=0.0254 rank=4.85 135s
expanded_saved_h512_d2_e16_wd5e4 ep 017/050* loss=0.00232 val_rmse=0.1258 top1=0.264 top3=0.478 reg=0.0248 rank=4.78 144s
expanded_saved_h512_d2_e16_wd5e4 ep 018/050* loss=0.00219 val_rmse=0.1217 top1=0.281 top3=0.492 reg=0.0235 rank=4.61 152s
expanded_saved_h512_d2_e16_wd5e4 ep 019/050  loss=0.00207 val_rmse=0.1236 top1=0.263 top3=0.475 reg=0.0240 rank=4.70 160s
expanded_saved_h512_d2_e16_wd5e4 ep 020/050  loss=0.00195 val_rmse=0.1243 top1=0.284 top3=0.479 reg=0.0247 rank=4.73 168s
expanded_saved_h512_d2_e16_wd5e4 ep 021/050  loss=0.00184 val_rmse=0.1222 top1=0.263 top3=0.463 reg=0.0250 rank=4.82 177s
expanded_saved_h512_d2_e16_wd5e4 ep 022/050  loss=0.00178 val_rmse=0.1247 top1=0.289 top3=0.498 reg=0.0241 rank=4.66 185s
expanded_saved_h512_d2_e16_wd5e4 ep 023/050  loss=0.00169 val_rmse=0.1260 top1=0.259 top3=0.494 reg=0.0245 rank=4.73 194s
expanded_saved_h512_d2_e16_wd5e4 ep 024/050  loss=0.00160 val_rmse=0.1256 top1=0.292 top3=0.491 reg=0.0243 rank=4.72 202s
expanded_saved_h512_d2_e16_wd5e4 ep 025/050  loss=0.00154 val_rmse=0.1235 top1=0.265 top3=0.477 reg=0.0245 rank=4.76 212s
expanded_saved_h512_d2_e16_wd5e4 ep 026/050  loss=0.00147 val_rmse=0.1236 top1=0.300 top3=0.506 reg=0.0238 rank=4.66 220s
expanded_saved_h512_d2_e16_wd5e4 ep 027/050* loss=0.00140 val_rmse=0.1252 top1=0.269 top3=0.500 reg=0.0234 rank=4.63 229s
expanded_saved_h512_d2_e16_wd5e4 ep 028/050* loss=0.00136 val_rmse=0.1237 top1=0.287 top3=0.512 reg=0.0230 rank=4.56 237s
expanded_saved_h512_d2_e16_wd5e4 ep 029/050  loss=0.00130 val_rmse=0.1255 top1=0.294 top3=0.508 reg=0.0234 rank=4.62 246s
expanded_saved_h512_d2_e16_wd5e4 ep 030/050* loss=0.00125 val_rmse=0.1231 top1=0.280 top3=0.545 reg=0.0221 rank=4.45 255s
expanded_saved_h512_d2_e16_wd5e4 ep 031/050  loss=0.00122 val_rmse=0.1251 top1=0.293 top3=0.509 reg=0.0243 rank=4.67 263s
expanded_saved_h512_d2_e16_wd5e4 ep 032/050  loss=0.00116 val_rmse=0.1228 top1=0.319 top3=0.532 reg=0.0231 rank=4.54 271s
expanded_saved_h512_d2_e16_wd5e4 ep 033/050  loss=0.00113 val_rmse=0.1232 top1=0.289 top3=0.509 reg=0.0235 rank=4.64 280s
expanded_saved_h512_d2_e16_wd5e4 ep 034/050  loss=0.00109 val_rmse=0.1235 top1=0.294 top3=0.529 reg=0.0227 rank=4.51 288s
expanded_saved_h512_d2_e16_wd5e4 ep 035/050  loss=0.00105 val_rmse=0.1233 top1=0.312 top3=0.547 reg=0.0227 rank=4.48 297s
expanded_saved_h512_d2_e16_wd5e4 ep 036/050* loss=0.00102 val_rmse=0.1242 top1=0.297 top3=0.552 reg=0.0218 rank=4.43 305s
expanded_saved_h512_d2_e16_wd5e4 ep 037/050  loss=0.00098 val_rmse=0.1259 top1=0.292 top3=0.530 reg=0.0239 rank=4.61 314s
expanded_saved_h512_d2_e16_wd5e4 ep 038/050  loss=0.00097 val_rmse=0.1249 top1=0.280 top3=0.522 reg=0.0242 rank=4.68 322s
expanded_saved_h512_d2_e16_wd5e4 ep 039/050  loss=0.00093 val_rmse=0.1254 top1=0.309 top3=0.539 reg=0.0224 rank=4.46 330s
expanded_saved_h512_d2_e16_wd5e4 ep 040/050  loss=0.00090 val_rmse=0.1257 top1=0.326 top3=0.556 reg=0.0229 rank=4.46 339s
expanded_saved_h512_d2_e16_wd5e4 ep 041/050  loss=0.00088 val_rmse=0.1242 top1=0.317 top3=0.552 reg=0.0223 rank=4.45 348s

,run_name,utility,hidden,emb_dim,depth,dropout,combine,loss,best_epoch,train_rmse,...,val_avg_regret,val_avg_norm_regret,test_rmse,test_mae,test_r2,test_top1,test_top3,test_mean_rank,test_avg_regret,test_avg_norm_regret
0,expanded_saved_h512_d2_e16_wd5e4,saved,512,16,2,0.05,mul_only,mse,36,0.018505,...,0.021825,0.048203,0.118466,0.086326,0.645658,0.316812,0.589417,4.198928,0.022763,0.045469
1,expanded_saved_h512_d2_e16_drop010,saved,512,16,2,0.10,mul_only,mse,30,0.023312,...,0.022876,0.049997,0.115619,0.083909,0.662486,0.358339,0.584059,4.152043,0.022200,0.044528
2,expanded_saved_h512_d2_e16_lr5e4,saved,512,16,2,0.05,mul_only,mse,34,0.026671,...,0.023013,0.048286,0.116906,0.086559,0.654928,0.290690,0.531815,4.434025,0.023385,0.046734
3,expanded_saved_h512_d2_e12,saved,512,12,2,0.05,mul_only,mse,13,0.045883,...,0.023032,0.048745,0.119445,0.089894,0.639781,0.221701,0.486269,4.837910,0.026475,0.052236
4,expanded_saved_h512_d2_e20,saved,512,20,2,0.05,mul_only,mse,50,0.014085,...,0.024476,0.051506,0.117138,0.085308,0.653557,0.313463,0.604823,4.383121,0.024184,0.048838

,run_name,train_utility,eval_objective,split,hidden,emb_dim,combine,top1,top3,mean_rank,avg_regret,avg_norm_regret
0,expanded_saved_h512_d2_e16_lr5e4,saved,contains_closest,test,512,16,mul_only,0.947756,0.947756,1.835901,0.052244,0.052244
1,expanded_saved_h512_d2_e16_drop010,saved,contains_closest,test,512,16,mul_only,0.945077,0.945077,1.878768,0.054923,0.054923
2,expanded_saved_h512_d2_e12,saved,contains_closest,test,512,12,mul_only,0.943737,0.943737,1.900201,0.056263,0.056263
3,expanded_saved_h512_d2_e16_wd5e4,saved,contains_closest,test,512,16,mul_only,0.941058,0.941058,1.943068,0.058942,0.058942
4,expanded_saved_h512_d2_e20,saved,contains_closest,test,512,20,mul_only,0.933691,0.933691,2.060951,0.066309,0.066309
5,expanded_saved_h512_d2_e16_drop010,saved,saved_rational,test,512,16,mul_only,0.358339,0.584059,4.152043,0.022200,0.044528
6,expanded_saved_h512_d2_e16_wd5e4,saved,saved_rational,test,512,16,mul_only,0.316812,0.589417,4.198928,0.022763,0.045469
7,expanded_saved_h512_d2_e16_lr5e4,saved,saved_rational,test,512,16,mul_only,0.290690,0.531815,4.434025,0.023385,0.046734
8,expanded_saved_h512_d2_e20,saved,saved_rational,test,512,20,mul_only,0.313463,0.604823,4.383121,0.024184,0.048838
9,expanded_saved_h512_d2_e12,saved,saved_rational,test,512,12,mul_only,0.221701,0.486269,4.837910,0.026475,0.052236

In [10]:
import numpy as np
import pandas as pd

from two_tower_training import (
    predict_scores,
    build_utility_labels,
)

def per_time_decisions(result, utility_name="saved", utility_kwargs=None, split_name="test"):
    """
    Returns one row per timestep:
    top1, top3, rank, regret, norm_regret, selected_value, best_value.
    """
    utility_kwargs = utility_kwargs or {}

    model = result["model"]
    prepared = result["prepared"]
    config = result["config"]
    device = result["device"]

    indices = prepared["split"][split_name]
    time_id = prepared["example_time_id"][indices]

    y_eval = build_utility_labels(
        examples_index=prepared["examples_index"],
        saved_y=prepared["saved_y_examples"],
        meta=prepared["meta"],
        utility_name=utility_name,
        utility_kwargs=utility_kwargs,
    ).astype(np.float32)[indices]

    scores = predict_scores(
        model,
        prepared,
        indices,
        config.batch_size * 2,
        device,
    )

    rows = []
    df = pd.DataFrame({
        "time_id": time_id,
        "y_true": y_eval,
        "score": scores,
    })

    for tid, g in df.groupby("time_id", sort=False):
        yt = g["y_true"].to_numpy(dtype=float)
        sc = g["score"].to_numpy(dtype=float)

        pred_idx = int(np.argmax(sc))
        selected_value = float(yt[pred_idx])
        best_value = float(np.max(yt))
        worst_value = float(np.min(yt))

        rank = int(np.sum(yt > selected_value + 1e-10)) + 1
        regret = best_value - selected_value
        denom = best_value - worst_value
        norm_regret = 0.0 if denom <= 1e-12 else regret / denom

        rows.append({
            "time_id": tid,
            "top1": float(rank == 1),
            "top3": float(rank <= 3),
            "rank": float(rank),
            "regret": regret,
            "norm_regret": norm_regret,
            "selected_value": selected_value,
            "best_value": best_value,
        })

    return pd.DataFrame(rows)


def paired_block_bootstrap(df_a, df_b, metric, higher_is_better=True, block_len=25, B=3000, seed=0):
    """
    Paired block bootstrap over consecutive time steps.
    Positive diff means A is better than B.
    """
    rng = np.random.default_rng(seed)

    a = df_a.sort_values("time_id")[metric].to_numpy()
    b = df_b.sort_values("time_id")[metric].to_numpy()

    assert len(a) == len(b), "A/B must have same number of timesteps."

    if higher_is_better:
        diff = a - b
    else:
        diff = b - a

    n = len(diff)
    starts = np.arange(0, max(1, n - block_len + 1))

    boot = []
    for _ in range(B):
        sampled = []
        while len(sampled) < n:
            s = int(rng.choice(starts))
            sampled.extend(diff[s:s + block_len])
        sampled = np.asarray(sampled[:n])
        boot.append(sampled.mean())

    boot = np.asarray(boot)

    return {
        "metric": metric,
        "A_mean": float(a.mean()),
        "B_mean": float(b.mean()),
        "A_minus_B_oriented": float(diff.mean()),
        "ci_low": float(np.quantile(boot, 0.025)),
        "ci_high": float(np.quantile(boot, 0.975)),
        "p_A_better": float(np.mean(boot > 0.0)),
    }


def compare_two_results_bootstrap(
    result_a,
    result_b,
    name_a,
    name_b,
    utility_name="saved",
    utility_kwargs=None,
    split_name="test",
    block_len=25,
):
    df_a = per_time_decisions(result_a, utility_name, utility_kwargs, split_name)
    df_b = per_time_decisions(result_b, utility_name, utility_kwargs, split_name)

    rows = []
    rows.append(paired_block_bootstrap(df_a, df_b, "top1", higher_is_better=True, block_len=block_len))
    rows.append(paired_block_bootstrap(df_a, df_b, "top3", higher_is_better=True, block_len=block_len))
    rows.append(paired_block_bootstrap(df_a, df_b, "rank", higher_is_better=False, block_len=block_len))
    rows.append(paired_block_bootstrap(df_a, df_b, "norm_regret", higher_is_better=False, block_len=block_len))
    rows.append(paired_block_bootstrap(df_a, df_b, "regret", higher_is_better=False, block_len=block_len))

    out = pd.DataFrame(rows)
    out.insert(0, "A", name_a)
    out.insert(1, "B", name_b)
    out.insert(2, "utility", utility_name)
    return out

# Build a name -> result dictionary from all result lists you still have.
all_results = []
for obj in [
    globals().get("expanded_results", []),
    globals().get("one_change_results", []),
    globals().get("e16_probe_results", []),
]:
    all_results.extend(obj)

result_by_name = {r["config"].run_name: r for r in all_results}

plain = result_by_name["expanded_saved_h512_d2_e16"]
drop = result_by_name["expanded_saved_h512_d2_e16_drop010"]
smooth = result_by_name["expanded_saved_h512_d2_e8_smoothl1"]

# Saved-rational comparison.
display(compare_two_results_bootstrap(
    plain,
    drop,
    "plain_e16",
    "e16_drop010",
    utility_name="saved",
    split_name="test",
    block_len=25,
))

# Contains-closest comparison.
display(compare_two_results_bootstrap(
    smooth,
    plain,
    "smoothl1_e8",
    "plain_e16",
    utility_name="closest_binary",
    split_name="test",
    block_len=25,
))

,A,B,utility,metric,A_mean,B_mean,A_minus_B_oriented,ci_low,ci_high,p_A_better
0,plain_e16,e16_drop010,saved,top1,0.358339,0.358339,0.000000,-0.024799,0.032150,0.586000
1,plain_e16,e16_drop010,saved,top3,0.606162,0.584059,0.022103,0.000000,0.050904,0.974000
2,plain_e16,e16_drop010,saved,rank,4.034159,4.152043,0.117883,-0.099866,0.352328,0.866000
3,plain_e16,e16_drop010,saved,norm_regret,0.042809,0.044528,0.001719,-0.002121,0.005784,0.818000
4,plain_e16,e16_drop010,saved,regret,0.021643,0.022200,0.000557,-0.001208,0.002376,0.758333

,A,B,utility,metric,A_mean,B_mean,A_minus_B_oriented,ci_low,ci_high,p_A_better
0,smoothl1_e8,plain_e16,closest_binary,top1,0.957803,0.945077,0.012726,-0.005358,0.033490,0.902333
1,smoothl1_e8,plain_e16,closest_binary,top3,0.957803,0.945077,0.012726,-0.005358,0.033490,0.902333
2,smoothl1_e8,plain_e16,closest_binary,rank,1.675151,1.878768,0.203617,-0.085733,0.535834,0.902333
3,smoothl1_e8,plain_e16,closest_binary,norm_regret,0.042197,0.054923,0.012726,-0.005358,0.033490,0.902333
4,smoothl1_e8,plain_e16,closest_binary,regret,0.042197,0.054923,0.012726,-0.005358,0.033490,0.902333