# m02 Multi-Vehicle RSSI Utility Search

Build exact-5 multi-vehicle subset examples from `data/interim`, then train the v3-style two-tower architecture on candidate utility functions. This notebook intentionally uses only normalized sensor coordinates and RSSI dB, so it is the RSSI-only ablation for the multi-vehicle setting.

In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
from pathlib import Path
import sys

PROJECT_ROOT = Path.cwd()
if PROJECT_ROOT.name == "notebooks":
    PROJECT_ROOT = PROJECT_ROOT.parent

SCRIPTS_DIR = PROJECT_ROOT / "scripts"
if str(SCRIPTS_DIR) not in sys.path:
    sys.path.insert(0, str(SCRIPTS_DIR))

from multi_vehicle_utility_search import build_eq5_rssi_static_examples

build_summary_df, build_paths_df = build_eq5_rssi_static_examples(PROJECT_ROOT)
display(build_summary_df)
display(build_paths_df)

Interim source: d:\2023-2028_UCLA_Research_Projects\IoBT\17-5-26-MILCOMAttempt\data\interim\20250815_0900_multi_vehicle
valid timestamps=6625, nodes=10, vehicles=['vehicle1', 'vehicle2'], exact subset size=5
rho=10.222 m
Saved processed artifact: m02_multi_vehicle_eq5_rssi_static
Elapsed: 0.7 min

,prefix,times,actions_per_time,examples,context_dim,action_dim,mean_contains_fraction_all_actions,both_rate_all_actions,elapsed_min
0,m02_multi_vehicle_eq5_rssi_static,6625,252,1669500,30,21,0.5,0.245493,0.74452

              artifact                                               path
0           arrays_npz  d:\2023-2028_UCLA_Research_Projects\IoBT\17-5-...
1   examples_index_csv  d:\2023-2028_UCLA_Research_Projects\IoBT\17-5-...
2     feature_wide_csv  d:\2023-2028_UCLA_Research_Projects\IoBT\17-5-...
3  sensor_geometry_csv  d:\2023-2028_UCLA_Research_Projects\IoBT\17-5-...
4            meta_json  d:\2023-2028_UCLA_Research_Projects\IoBT\17-5-...

In [5]:
from pathlib import Path
import sys

PROJECT_ROOT = Path.cwd()
if PROJECT_ROOT.name == "notebooks":
    PROJECT_ROOT = PROJECT_ROOT.parent

SCRIPTS_DIR = PROJECT_ROOT / "scripts"
if str(SCRIPTS_DIR) not in sys.path:
    sys.path.insert(0, str(SCRIPTS_DIR))

import importlib
import multi_vehicle_utility_search as mv_utils

mv_utils = importlib.reload(mv_utils)
from multi_vehicle_utility_search import SECOND_SWEEP_CANDIDATES, run_rssi_utility_search

summary_df, utility_results = run_rssi_utility_search(
    PROJECT_ROOT,
    model_tag="multi_vehicle_rssi_utility_search_eq5_second_sweep",
    max_epochs=150,
    patience=150,
    log_every=5,
    batch_size=8192,
    time_batch_size=256,
    utility_candidates=SECOND_SWEEP_CANDIDATES,
)

vehicle_cols = [col for col in summary_df.columns if col.startswith("test_contains_vehicle")]
display_cols = [
    "utility",
    "best_epoch",
    "val_contains_closest_fraction",
    "val_contains_closest_all",
    "val_dominance_gap",
    "test_contains_closest_fraction",
    "test_contains_closest_all",
    "test_one_closest_rate",
    "test_neither_closest_rate",
    "test_dominance_gap",
    *vehicle_cols,
    "test_mean_worst_vehicle_rank",
    "test_mean_abs_vehicle_rank_gap",
    "test_avg_regret",
]
display(summary_df[[col for col in display_cols if col in summary_df.columns]])

Dense cache is missing requested utility targets; rebuilding with 12 utility matrices.
Building dense train cache from m02_multi_vehicle_eq5_rssi_static_examples_index.csv ...
Saved dense train cache: d:\2023-2028_UCLA_Research_Projects\IoBT\17-5-26-MILCOMAttempt\data\processed\m02_multi_vehicle_eq5_rssi_static_dense_train_cache.npz
PROJECT_ROOT: d:\2023-2028_UCLA_Research_Projects\IoBT\17-5-26-MILCOMAttempt
DEVICE: cuda
data: times=6625, actions/time=252, examples=1,669,500, context_dim=30, action_dim=21
dense cache: d:\2023-2028_UCLA_Research_Projects\IoBT\17-5-26-MILCOMAttempt\data\processed\m02_multi_vehicle_eq5_rssi_static_dense_train_cache.npz
utilities: ['softmin_d1_beta5', 'softmin_d1_beta10', 'sum_plus_softmin_beta10_lam05', 'sum_plus_softmin_beta10_lam10', 'harmonic_d1', 'sum_d1_minus_gap_lam025', 'top2_d1_alpha02']

=== softmin_d1_beta5 === Smooth min over per-vehicle d1 utilities with beta=5.
softmin_d1_beta5 ep 001/150* loss=0.04217 val_acc=0.601 both=0.326 one=0.550 gap=0.022 vehicle1=0.612 vehicle2=0.590 wrank=2.30 reg=0.0678 1s
softmin_d1_beta5 ep 002/150* loss=0.01223 val_acc=0.651 both=0.398 one=0.505 gap=0.070 vehicle1=0.686 vehicle2=0.616 wrank=1.96 reg=0.0546 1s
softmin_d1_beta5 ep 004/150* loss=0.00809 val_acc=0.661 both=0.454 one=0.414 gap=0.011 vehicle1=0.666 vehicle2=0.656 wrank=1.75 reg=0.0453 2s
softmin_d1_beta5 ep 005/150* loss=0.00744 val_acc=0.682 both=0.489 one=0.385 gap=0.002 vehicle1=0.682 vehicle2=0.681 wrank=1.65 reg=0.0408 3s
softmin_d1_beta5 ep 006/150* loss=0.00692 val_acc=0.711 both=0.531 one=0.360 gap=0.005 vehicle1=0.708 vehicle2=0.713 wrank=1.61 reg=0.0366 3s
softmin_d1_beta5 ep 007/150* loss=0.00652 val_acc=0.719 both=0.546 one=0.347 gap=0.008 vehicle1=0.715 vehicle2=0.723 wrank=1.57 reg=0.0357 4s
softmin_d1_beta5 ep 010/150  loss=0.00578 val_acc=0.689 both=0.503 one=0.372 gap=0.055 vehicle1=0.661 vehicle2=0.716 wrank=1.61 reg=0.0400 5s
softmin_d1_beta5 ep 011/150* loss=0.00564 val_acc=0.721 both=0.546 one=0.349 gap=0.032 vehicle1=0.705 vehicle2=0.737 wrank=1.54 reg=0.0361 6s
softmin_d1_beta5 ep 015/150  loss=0.00516 val_acc=0.714 both=0.526 one=0.377 gap=0.034 vehicle1=0.697 vehicle2=0.731 wrank=1.61 reg=0.0384 8s
softmin_d1_beta5 ep 016/150* loss=0.00503 val_acc=0.725 both=0.534 one=0.381 gap=0.016 vehicle1=0.717 vehicle2=0.733 wrank=1.62 reg=0.0389 8s
softmin_d1_beta5 ep 019/150* loss=0.00482 val_acc=0.729 both=0.537 one=0.384 gap=0.004 vehicle1=0.728 vehicle2=0.731 wrank=1.63 reg=0.0389 9s
softmin_d1_beta5 ep 020/150* loss=0.00472 val_acc=0.734 both=0.546 one=0.377 gap=0.012 vehicle1=0.728 vehicle2=0.740 wrank=1.62 reg=0.0382 10s
softmin_d1_beta5 ep 022/150* loss=0.00457 val_acc=0.738 both=0.548 one=0.381 gap=0.014 vehicle1=0.731 vehicle2=0.746 wrank=1.61 reg=0.0370 11s
softmin_d1_beta5 ep 023/150* loss=0.00453 val_acc=0.749 both=0.568 one=0.362 gap=0.008 vehicle1=0.745 vehicle2=0.753 wrank=1.56 reg=0.0344 11s
softmin_d1_beta5 ep 025/150* loss=0.00444 val_acc=0.753 both=0.565 one=0.376 gap=0.014 vehicle1=0.746 vehicle2=0.760 wrank=1.59 reg=0.0350 12s
softmin_d1_beta5 ep 027/150* loss=0.00428 val_acc=0.762 both=0.581 one=0.362 gap=0.017 vehicle1=0.754 vehicle2=0.771 wrank=1.55 reg=0.0326 13s
softmin_d1_beta5 ep 030/150* loss=0.00417 val_acc=0.766 both=0.582 one=0.369 gap=0.029 vehicle1=0.752 vehicle2=0.781 wrank=1.55 reg=0.0315 15s
softmin_d1_beta5 ep 031/150* loss=0.00408 val_acc=0.798 both=0.626 one=0.345 gap=0.040 vehicle1=0.778 vehicle2=0.818 wrank=1.49 reg=0.0277 15s
softmin_d1_beta5 ep 035/150  loss=0.00391 val_acc=0.791 both=0.616 one=0.350 gap=0.030 vehicle1=0.776 vehicle2=0.806 wrank=1.48 reg=0.0293 17s
softmin_d1_beta5 ep 036/150* loss=0.00387 val_acc=0.803 both=0.629 one=0.346 gap=0.073 vehicle1=0.766 vehicle2=0.839 wrank=1.49 reg=0.0275 18s
softmin_d1_beta5 ep 040/150  loss=0.00376 val_acc=0.786 both=0.611 one=0.351 gap=0.057 vehicle1=0.758 vehicle2=0.814 wrank=1.48 reg=0.0290 20s
softmin_d1_beta5 ep 045/150  loss=0.00356 val_acc=0.773 both=0.593 one=0.360 gap=0.049 vehicle1=0.749 vehicle2=0.798 wrank=1.51 reg=0.0321 22s
softmin_d1_beta5 ep 050/150  loss=0.00337 val_acc=0.794 both=0.620 one=0.348 gap=0.057 vehicle1=0.766 vehicle2=0.823 wrank=1.43 reg=0.0267 24s
softmin_d1_beta5 ep 053/150* loss=0.00329 val_acc=0.813 both=0.651 one=0.324 gap=0.057 vehicle1=0.785 vehicle2=0.842 wrank=1.41 reg=0.0250 26s
softmin_d1_beta5 ep 055/150  loss=0.00326 val_acc=0.776 both=0.600 one=0.352 gap=0.069 vehicle1=0.741 vehicle2=0.811 wrank=1.49 reg=0.0310 27s
softmin_d1_beta5 ep 060/150* loss=0.00310 val_acc=0.817 both=0.668 one=0.299 gap=0.050 vehicle1=0.792 vehicle2=0.842 wrank=1.39 reg=0.0244 29s
softmin_d1_beta5 ep 065/150  loss=0.00301 val_acc=0.780 both=0.614 one=0.332 gap=0.069 vehicle1=0.745 vehicle2=0.814 wrank=1.45 reg=0.0299 32s
softmin_d1_beta5 ep 067/150* loss=0.00298 val_acc=0.820 both=0.670 one=0.300 gap=0.042 vehicle1=0.799 vehicle2=0.842 wrank=1.40 reg=0.0239 33s
softmin_d1_beta5 ep 070/150  loss=0.00289 val_acc=0.776 both=0.605 one=0.342 gap=0.040 vehicle1=0.756 vehicle2=0.796 wrank=1.47 reg=0.0306 34s
softmin_d1_beta5 ep 071/150* loss=0.00291 val_acc=0.827 both=0.686 one=0.282 gap=0.066 vehicle1=0.794 vehicle2=0.860 wrank=1.38 reg=0.0225 34s
softmin_d1_beta5 ep 075/150  loss=0.00279 val_acc=0.795 both=0.635 one=0.320 gap=0.048 vehicle1=0.771 vehicle2=0.819 wrank=1.43 reg=0.0275 36s
softmin_d1_beta5 ep 079/150* loss=0.00273 val_acc=0.832 both=0.690 one=0.285 gap=0.050 vehicle1=0.808 vehicle2=0.857 wrank=1.38 reg=0.0221 38s
softmin_d1_beta5 ep 080/150* loss=0.00271 val_acc=0.841 both=0.711 one=0.260 gap=0.053 vehicle1=0.814 vehicle2=0.867 wrank=1.36 reg=0.0206 39s
softmin_d1_beta5 ep 085/150  loss=0.00261 val_acc=0.823 both=0.677 one=0.292 gap=0.007 vehicle1=0.820 vehicle2=0.826 wrank=1.38 reg=0.0245 41s
softmin_d1_beta5 ep 086/150* loss=0.00261 val_acc=0.845 both=0.710 one=0.269 gap=0.029 vehicle1=0.830 vehicle2=0.859 wrank=1.33 reg=0.0197 42s
softmin_d1_beta5 ep 090/150  loss=0.00253 val_acc=0.843 both=0.706 one=0.275 gap=0.046 vehicle1=0.820 vehicle2=0.866 wrank=1.36 reg=0.0206 44s
softmin_d1_beta5 ep 092/150* loss=0.00253 val_acc=0.851 both=0.718 one=0.266 gap=0.015 vehicle1=0.843 vehicle2=0.858 wrank=1.32 reg=0.0198 44s
softmin_d1_beta5 ep 095/150  loss=0.00250 val_acc=0.834 both=0.700 one=0.268 gap=0.029 vehicle1=0.820 vehicle2=0.849 wrank=1.35 reg=0.0215 46s
softmin_d1_beta5 ep 100/150  loss=0.00242 val_acc=0.822 both=0.691 one=0.263 gap=0.048 vehicle1=0.798 vehicle2=0.846 wrank=1.38 reg=0.0236 48s
softmin_d1_beta5 ep 102/150* loss=0.00236 val_acc=0.853 both=0.732 one=0.242 gap=0.024 vehicle1=0.841 vehicle2=0.865 wrank=1.31 reg=0.0192 49s
softmin_d1_beta5 ep 104/150* loss=0.00235 val_acc=0.857 both=0.741 one=0.231 gap=0.012 vehicle1=0.851 vehicle2=0.863 wrank=1.30 reg=0.0189 50s
softmin_d1_beta5 ep 105/150  loss=0.00234 val_acc=0.839 both=0.703 one=0.273 gap=0.026 vehicle1=0.826 vehicle2=0.852 wrank=1.34 reg=0.0211 51s
softmin_d1_beta5 ep 109/150* loss=0.00225 val_acc=0.860 both=0.740 one=0.239 gap=0.016 vehicle1=0.852 vehicle2=0.868 wrank=1.34 reg=0.0185 53s
softmin_d1_beta5 ep 110/150  loss=0.00227 val_acc=0.848 both=0.719 one=0.258 gap=0.042 vehicle1=0.827 vehicle2=0.869 wrank=1.33 reg=0.0203 53s
softmin_d1_beta5 ep 111/150* loss=0.00230 val_acc=0.874 both=0.760 one=0.227 gap=0.045 vehicle1=0.851 vehicle2=0.896 wrank=1.32 reg=0.0169 54s
softmin_d1_beta5 ep 115/150  loss=0.00224 val_acc=0.836 both=0.703 one=0.267 gap=0.029 vehicle1=0.822 vehicle2=0.851 wrank=1.35 reg=0.0225 55s
softmin_d1_beta5 ep 120/150  loss=0.00216 val_acc=0.826 both=0.688 one=0.276 gap=0.036 vehicle1=0.808 vehicle2=0.845 wrank=1.38 reg=0.0235 58s
softmin_d1_beta5 ep 125/150  loss=0.00211 val_acc=0.825 both=0.685 one=0.280 gap=0.023 vehicle1=0.813 vehicle2=0.836 wrank=1.38 reg=0.0252 60s
softmin_d1_beta5 ep 130/150  loss=0.00206 val_acc=0.858 both=0.735 one=0.246 gap=0.009 vehicle1=0.854 vehicle2=0.863 wrank=1.31 reg=0.0196 63s
softmin_d1_beta5 ep 135/150  loss=0.00203 val_acc=0.851 both=0.723 one=0.257 gap=0.026 vehicle1=0.838 vehicle2=0.864 wrank=1.35 reg=0.0212 65s
softmin_d1_beta5 ep 140/150  loss=0.00197 val_acc=0.846 both=0.715 one=0.260 gap=0.020 vehicle1=0.835 vehicle2=0.856 wrank=1.35 reg=0.0214 67s
softmin_d1_beta5 ep 145/150  loss=0.00193 val_acc=0.848 both=0.718 one=0.260 gap=0.030 vehicle1=0.833 vehicle2=0.863 wrank=1.36 reg=0.0221 70s
softmin_d1_beta5 ep 150/150  loss=0.00189 val_acc=0.843 both=0.712 one=0.262 gap=0.031 vehicle1=0.827 vehicle2=0.858 wrank=1.35 reg=0.0221 72s

=== softmin_d1_beta10 === Sharper smooth min over per-vehicle d1 utilities with beta=10.
softmin_d1_beta10 ep 001/150* loss=0.03997 val_acc=0.613 both=0.343 one=0.540 gap=0.022 vehicle1=0.624 vehicle2=0.602 wrank=2.22 reg=0.0670 0s
softmin_d1_beta10 ep 002/150* loss=0.01282 val_acc=0.673 both=0.429 one=0.488 gap=0.068 vehicle1=0.707 vehicle2=0.639 wrank=1.89 reg=0.0516 1s
softmin_d1_beta10 ep 005/150* loss=0.00818 val_acc=0.708 both=0.528 one=0.361 gap=0.006 vehicle1=0.705 vehicle2=0.711 wrank=1.59 reg=0.0375 2s
softmin_d1_beta10 ep 006/150* loss=0.00765 val_acc=0.726 both=0.550 one=0.352 gap=0.009 vehicle1=0.722 vehicle2=0.731 wrank=1.56 reg=0.0351 3s
softmin_d1_beta10 ep 007/150* loss=0.00727 val_acc=0.731 both=0.554 one=0.354 gap=0.011 vehicle1=0.725 vehicle2=0.737 wrank=1.52 reg=0.0337 3s
softmin_d1_beta10 ep 010/150  loss=0.00654 val_acc=0.698 both=0.513 one=0.371 gap=0.040 vehicle1=0.678 vehicle2=0.718 wrank=1.58 reg=0.0385 5s
softmin_d1_beta10 ep 011/150* loss=0.00639 val_acc=0.735 both=0.559 one=0.352 gap=0.026 vehicle1=0.722 vehicle2=0.748 wrank=1.52 reg=0.0340 5s
softmin_d1_beta10 ep 015/150* loss=0.00588 val_acc=0.738 both=0.555 one=0.366 gap=0.013 vehicle1=0.731 vehicle2=0.744 wrank=1.57 reg=0.0374 7s
softmin_d1_beta10 ep 016/150* loss=0.00573 val_acc=0.745 both=0.561 one=0.369 gap=0.008 vehicle1=0.741 vehicle2=0.749 wrank=1.57 reg=0.0380 8s
softmin_d1_beta10 ep 020/150  loss=0.00539 val_acc=0.730 both=0.545 one=0.371 gap=0.005 vehicle1=0.733 vehicle2=0.728 wrank=1.59 reg=0.0397 10s
softmin_d1_beta10 ep 023/150* loss=0.00517 val_acc=0.752 both=0.575 one=0.353 gap=0.003 vehicle1=0.750 vehicle2=0.753 wrank=1.53 reg=0.0363 11s
softmin_d1_beta10 ep 025/150* loss=0.00508 val_acc=0.758 both=0.580 one=0.358 gap=0.015 vehicle1=0.751 vehicle2=0.766 wrank=1.54 reg=0.0358 12s
softmin_d1_beta10 ep 027/150* loss=0.00488 val_acc=0.765 both=0.586 one=0.358 gap=0.012 vehicle1=0.759 vehicle2=0.771 wrank=1.53 reg=0.0343 13s
softmin_d1_beta10 ep 028/150* loss=0.00489 val_acc=0.766 both=0.586 one=0.358 gap=0.017 vehicle1=0.757 vehicle2=0.774 wrank=1.53 reg=0.0349 13s
softmin_d1_beta10 ep 030/150* loss=0.00477 val_acc=0.770 both=0.589 one=0.361 gap=0.018 vehicle1=0.761 vehicle2=0.779 wrank=1.52 reg=0.0338 14s
softmin_d1_beta10 ep 031/150* loss=0.00467 val_acc=0.811 both=0.645 one=0.331 gap=0.027 vehicle1=0.797 vehicle2=0.824 wrank=1.44 reg=0.0280 15s
softmin_d1_beta10 ep 035/150  loss=0.00448 val_acc=0.807 both=0.655 one=0.304 gap=0.023 vehicle1=0.795 vehicle2=0.819 wrank=1.41 reg=0.0279 17s
softmin_d1_beta10 ep 036/150* loss=0.00443 val_acc=0.814 both=0.649 one=0.331 gap=0.044 vehicle1=0.792 vehicle2=0.836 wrank=1.44 reg=0.0275 17s
softmin_d1_beta10 ep 040/150  loss=0.00430 val_acc=0.804 both=0.642 one=0.325 gap=0.057 vehicle1=0.775 vehicle2=0.832 wrank=1.42 reg=0.0287 19s
softmin_d1_beta10 ep 045/150  loss=0.00409 val_acc=0.797 both=0.638 one=0.316 gap=0.035 vehicle1=0.779 vehicle2=0.814 wrank=1.42 reg=0.0306 22s
softmin_d1_beta10 ep 050/150  loss=0.00388 val_acc=0.803 both=0.642 one=0.323 gap=0.036 vehicle1=0.785 vehicle2=0.821 wrank=1.40 reg=0.0295 24s
softmin_d1_beta10 ep 053/150* loss=0.00379 val_acc=0.824 both=0.672 one=0.304 gap=0.058 vehicle1=0.795 vehicle2=0.853 wrank=1.37 reg=0.0250 25s
softmin_d1_beta10 ep 055/150  loss=0.00375 val_acc=0.782 both=0.614 one=0.337 gap=0.028 vehicle1=0.768 vehicle2=0.796 wrank=1.45 reg=0.0317 26s
softmin_d1_beta10 ep 060/150  loss=0.00358 val_acc=0.812 both=0.664 one=0.295 gap=0.064 vehicle1=0.780 vehicle2=0.844 wrank=1.39 reg=0.0264 29s
softmin_d1_beta10 ep 065/150  loss=0.00349 val_acc=0.794 both=0.634 one=0.321 gap=0.072 vehicle1=0.758 vehicle2=0.830 wrank=1.43 reg=0.0289 31s
softmin_d1_beta10 ep 067/150* loss=0.00345 val_acc=0.829 both=0.685 one=0.289 gap=0.045 vehicle1=0.807 vehicle2=0.851 wrank=1.38 reg=0.0237 32s
softmin_d1_beta10 ep 070/150  loss=0.00335 val_acc=0.763 both=0.586 one=0.354 gap=0.049 vehicle1=0.739 vehicle2=0.788 wrank=1.47 reg=0.0336 34s
softmin_d1_beta10 ep 075/150  loss=0.00324 val_acc=0.788 both=0.625 one=0.325 gap=0.042 vehicle1=0.767 vehicle2=0.808 wrank=1.44 reg=0.0301 36s
softmin_d1_beta10 ep 080/150* loss=0.00314 val_acc=0.840 both=0.714 one=0.252 gap=0.036 vehicle1=0.822 vehicle2=0.858 wrank=1.36 reg=0.0222 38s
softmin_d1_beta10 ep 085/150  loss=0.00305 val_acc=0.825 both=0.688 one=0.275 gap=0.002 vehicle1=0.826 vehicle2=0.824 wrank=1.37 reg=0.0257 41s
softmin_d1_beta10 ep 090/150  loss=0.00294 val_acc=0.829 both=0.690 one=0.278 gap=0.042 vehicle1=0.808 vehicle2=0.850 wrank=1.38 reg=0.0236 43s
softmin_d1_beta10 ep 092/150* loss=0.00294 val_acc=0.847 both=0.716 one=0.262 gap=0.007 vehicle1=0.851 vehicle2=0.844 wrank=1.34 reg=0.0222 44s
softmin_d1_beta10 ep 093/150* loss=0.00291 val_acc=0.848 both=0.727 one=0.243 gap=0.018 vehicle1=0.839 vehicle2=0.857 wrank=1.32 reg=0.0211 45s
softmin_d1_beta10 ep 095/150  loss=0.00289 val_acc=0.836 both=0.703 one=0.266 gap=0.019 vehicle1=0.826 vehicle2=0.845 wrank=1.36 reg=0.0238 45s
softmin_d1_beta10 ep 100/150  loss=0.00280 val_acc=0.829 both=0.695 one=0.268 gap=0.038 vehicle1=0.810 vehicle2=0.848 wrank=1.37 reg=0.0242 48s
softmin_d1_beta10 ep 101/150* loss=0.00276 val_acc=0.867 both=0.749 one=0.237 gap=0.027 vehicle1=0.854 vehicle2=0.881 wrank=1.29 reg=0.0185 48s
softmin_d1_beta10 ep 105/150  loss=0.00272 val_acc=0.835 both=0.697 one=0.276 gap=0.012 vehicle1=0.829 vehicle2=0.841 wrank=1.36 reg=0.0250 50s
softmin_d1_beta10 ep 110/150  loss=0.00266 val_acc=0.855 both=0.729 one=0.252 gap=0.012 vehicle1=0.849 vehicle2=0.861 wrank=1.33 reg=0.0210 53s
softmin_d1_beta10 ep 115/150  loss=0.00261 val_acc=0.839 both=0.715 one=0.249 gap=0.003 vehicle1=0.841 vehicle2=0.838 wrank=1.34 reg=0.0247 55s
softmin_d1_beta10 ep 119/150* loss=0.00255 val_acc=0.870 both=0.757 one=0.226 gap=0.020 vehicle1=0.860 vehicle2=0.880 wrank=1.30 reg=0.0179 57s
softmin_d1_beta10 ep 120/150  loss=0.00252 val_acc=0.831 both=0.698 one=0.266 gap=0.035 vehicle1=0.814 vehicle2=0.848 wrank=1.38 reg=0.0245 57s
softmin_d1_beta10 ep 125/150  loss=0.00246 val_acc=0.816 both=0.668 one=0.297 gap=0.017 vehicle1=0.808 vehicle2=0.825 wrank=1.40 reg=0.0284 60s
softmin_d1_beta10 ep 130/150  loss=0.00241 val_acc=0.869 both=0.752 one=0.232 gap=0.009 vehicle1=0.873 vehicle2=0.864 wrank=1.28 reg=0.0184 62s
softmin_d1_beta10 ep 135/150  loss=0.00235 val_acc=0.832 both=0.694 one=0.275 gap=0.008 vehicle1=0.828 vehicle2=0.835 wrank=1.39 reg=0.0272 65s
softmin_d1_beta10 ep 140/150  loss=0.00229 val_acc=0.816 both=0.672 one=0.288 gap=0.029 vehicle1=0.802 vehicle2=0.831 wrank=1.40 reg=0.0283 67s
softmin_d1_beta10 ep 145/150  loss=0.00225 val_acc=0.846 both=0.722 one=0.248 gap=0.019 vehicle1=0.837 vehicle2=0.856 wrank=1.34 reg=0.0230 69s
softmin_d1_beta10 ep 150/150  loss=0.00222 val_acc=0.842 both=0.708 one=0.268 gap=0.022 vehicle1=0.831 vehicle2=0.853 wrank=1.34 reg=0.0238 72s

=== sum_plus_softmin_beta10_lam05 === mean(d1 utilities) + 0.5 * softmin_beta10(d1 utilities).
sum_plus_softmin_beta10_lam05 ep 001/150* loss=0.10673 val_acc=0.574 both=0.299 one=0.550 gap=0.010 vehicle1=0.579 vehicle2=0.569 wrank=2.38 reg=0.1082 0s
sum_plus_softmin_beta10_lam05 ep 002/150* loss=0.02467 val_acc=0.599 both=0.339 one=0.520 gap=0.034 vehicle1=0.582 vehicle2=0.616 wrank=2.20 reg=0.0910 1s
sum_plus_softmin_beta10_lam05 ep 003/150* loss=0.01797 val_acc=0.615 both=0.392 one=0.446 gap=0.013 vehicle1=0.609 vehicle2=0.622 wrank=1.92 reg=0.0815 1s
sum_plus_softmin_beta10_lam05 ep 004/150* loss=0.01544 val_acc=0.622 both=0.394 one=0.457 gap=0.010 vehicle1=0.617 vehicle2=0.627 wrank=1.87 reg=0.0797 2s
sum_plus_softmin_beta10_lam05 ep 005/150* loss=0.01414 val_acc=0.650 both=0.422 one=0.456 gap=0.014 vehicle1=0.657 vehicle2=0.643 wrank=1.78 reg=0.0723 2s
sum_plus_softmin_beta10_lam05 ep 006/150* loss=0.01314 val_acc=0.674 both=0.457 one=0.434 gap=0.005 vehicle1=0.671 vehicle2=0.676 wrank=1.72 reg=0.0655 3s
sum_plus_softmin_beta10_lam05 ep 007/150* loss=0.01213 val_acc=0.706 both=0.518 one=0.374 gap=0.000 vehicle1=0.706 vehicle2=0.706 wrank=1.64 reg=0.0555 3s
sum_plus_softmin_beta10_lam05 ep 010/150  loss=0.01017 val_acc=0.668 both=0.479 one=0.377 gap=0.019 vehicle1=0.658 vehicle2=0.677 wrank=1.70 reg=0.0647 5s
sum_plus_softmin_beta10_lam05 ep 015/150  loss=0.00885 val_acc=0.701 both=0.515 one=0.371 gap=0.034 vehicle1=0.684 vehicle2=0.718 wrank=1.66 reg=0.0612 7s
sum_plus_softmin_beta10_lam05 ep 019/150* loss=0.00825 val_acc=0.706 both=0.515 one=0.381 gap=0.023 vehicle1=0.694 vehicle2=0.718 wrank=1.65 reg=0.0595 9s
sum_plus_softmin_beta10_lam05 ep 020/150* loss=0.00808 val_acc=0.712 both=0.522 one=0.380 gap=0.003 vehicle1=0.711 vehicle2=0.714 wrank=1.66 reg=0.0599 10s
sum_plus_softmin_beta10_lam05 ep 022/150* loss=0.00778 val_acc=0.730 both=0.540 one=0.381 gap=0.005 vehicle1=0.728 vehicle2=0.733 wrank=1.64 reg=0.0560 11s
sum_plus_softmin_beta10_lam05 ep 023/150* loss=0.00775 val_acc=0.745 both=0.563 one=0.364 gap=0.009 vehicle1=0.740 vehicle2=0.749 wrank=1.58 reg=0.0506 11s
sum_plus_softmin_beta10_lam05 ep 025/150  loss=0.00757 val_acc=0.736 both=0.545 one=0.383 gap=0.010 vehicle1=0.731 vehicle2=0.741 wrank=1.63 reg=0.0549 12s
sum_plus_softmin_beta10_lam05 ep 030/150  loss=0.00707 val_acc=0.740 both=0.552 one=0.375 gap=0.008 vehicle1=0.744 vehicle2=0.736 wrank=1.61 reg=0.0546 14s
sum_plus_softmin_beta10_lam05 ep 031/150* loss=0.00691 val_acc=0.765 both=0.570 one=0.389 gap=0.003 vehicle1=0.766 vehicle2=0.763 wrank=1.59 reg=0.0474 15s
sum_plus_softmin_beta10_lam05 ep 035/150* loss=0.00668 val_acc=0.774 both=0.597 one=0.354 gap=0.026 vehicle1=0.787 vehicle2=0.761 wrank=1.56 reg=0.0466 17s
sum_plus_softmin_beta10_lam05 ep 037/150* loss=0.00652 val_acc=0.777 both=0.592 one=0.368 gap=0.006 vehicle1=0.774 vehicle2=0.780 wrank=1.52 reg=0.0438 18s
sum_plus_softmin_beta10_lam05 ep 040/150  loss=0.00642 val_acc=0.773 both=0.589 one=0.367 gap=0.002 vehicle1=0.772 vehicle2=0.774 wrank=1.55 reg=0.0464 19s
sum_plus_softmin_beta10_lam05 ep 042/150* loss=0.00620 val_acc=0.779 both=0.601 one=0.357 gap=0.007 vehicle1=0.783 vehicle2=0.776 wrank=1.53 reg=0.0453 20s
sum_plus_softmin_beta10_lam05 ep 045/150* loss=0.00607 val_acc=0.798 both=0.628 one=0.340 gap=0.005 vehicle1=0.801 vehicle2=0.795 wrank=1.50 reg=0.0426 22s
sum_plus_softmin_beta10_lam05 ep 049/150* loss=0.00582 val_acc=0.809 both=0.653 one=0.312 gap=0.006 vehicle1=0.812 vehicle2=0.806 wrank=1.45 reg=0.0388 23s
sum_plus_softmin_beta10_lam05 ep 050/150  loss=0.00574 val_acc=0.774 both=0.604 one=0.340 gap=0.002 vehicle1=0.774 vehicle2=0.773 wrank=1.50 reg=0.0454 24s
sum_plus_softmin_beta10_lam05 ep 051/150* loss=0.00575 val_acc=0.809 both=0.647 one=0.325 gap=0.011 vehicle1=0.804 vehicle2=0.815 wrank=1.44 reg=0.0378 24s
sum_plus_softmin_beta10_lam05 ep 053/150* loss=0.00560 val_acc=0.817 both=0.666 one=0.303 gap=0.026 vehicle1=0.805 vehicle2=0.830 wrank=1.42 reg=0.0364 25s
sum_plus_softmin_beta10_lam05 ep 055/150  loss=0.00559 val_acc=0.784 both=0.626 one=0.315 gap=0.012 vehicle1=0.778 vehicle2=0.790 wrank=1.47 reg=0.0440 26s
sum_plus_softmin_beta10_lam05 ep 059/150* loss=0.00535 val_acc=0.821 both=0.669 one=0.303 gap=0.032 vehicle1=0.805 vehicle2=0.837 wrank=1.41 reg=0.0351 28s
sum_plus_softmin_beta10_lam05 ep 060/150  loss=0.00532 val_acc=0.797 both=0.642 one=0.309 gap=0.017 vehicle1=0.788 vehicle2=0.805 wrank=1.45 reg=0.0405 29s
sum_plus_softmin_beta10_lam05 ep 065/150  loss=0.00518 val_acc=0.785 both=0.623 one=0.324 gap=0.035 vehicle1=0.767 vehicle2=0.802 wrank=1.45 reg=0.0430 31s

,utility,best_epoch,val_contains_closest_fraction,val_contains_closest_all,val_dominance_gap,test_contains_closest_fraction,test_contains_closest_all,test_one_closest_rate,test_neither_closest_rate,test_dominance_gap,test_contains_vehicle1,test_contains_vehicle2,test_mean_worst_vehicle_rank,test_mean_abs_vehicle_rank_gap,test_avg_regret
0,softmin_d1_beta5,111,0.873585,0.760000,0.044528,0.869057,0.753208,0.231698,0.015094,0.000755,0.869434,0.868679,1.282264,0.267170,0.018317
1,sum_plus_softmin_beta10_lam10,150,0.877358,0.763019,0.024906,0.868302,0.761509,0.213585,0.024906,0.035472,0.886038,0.850566,1.265660,0.235472,0.032461
2,sum_d1_minus_gap_lam025,150,0.849811,0.713208,0.004528,0.866038,0.762264,0.207547,0.030189,0.038491,0.885283,0.846792,1.271698,0.233962,0.031175
3,top2_d1_alpha02,107,0.866038,0.761509,0.012830,0.866038,0.749434,0.233208,0.017358,0.059623,0.895849,0.836226,1.342641,0.325283,0.035205
4,sum_plus_softmin_beta10_lam05,118,0.857736,0.733585,0.015849,0.861887,0.738868,0.246038,0.015094,0.031698,0.877736,0.846038,1.303396,0.286792,0.027098
5,harmonic_d1,118,0.860377,0.737359,0.022642,0.848679,0.720755,0.255849,0.023396,0.030943,0.864151,0.833208,1.311698,0.286792,0.020767
6,softmin_d1_beta10,119,0.869811,0.756981,0.020377,0.846415,0.715472,0.261887,0.022642,0.033962,0.863396,0.829434,1.325283,0.299623,0.023069

In [6]:
# Re-run the original utility set for 150 epochs without overwriting earlier sweeps.
from pathlib import Path
import sys

PROJECT_ROOT = Path.cwd()
if PROJECT_ROOT.name == "notebooks":
    PROJECT_ROOT = PROJECT_ROOT.parent

SCRIPTS_DIR = PROJECT_ROOT / "scripts"
if str(SCRIPTS_DIR) not in sys.path:
    sys.path.insert(0, str(SCRIPTS_DIR))

import importlib
import multi_vehicle_utility_search as mv_utils

mv_utils = importlib.reload(mv_utils)
from multi_vehicle_utility_search import UTILITY_CANDIDATES, run_rssi_utility_search

original_summary_df, original_utility_results = run_rssi_utility_search(
    PROJECT_ROOT,
    model_tag="multi_vehicle_rssi_utility_search_eq5_original_sweep_150ep",
    max_epochs=150,
    patience=150,
    log_every=5,
    batch_size=8192,
    time_batch_size=256,
    utility_candidates=UTILITY_CANDIDATES,
)

vehicle_cols = [col for col in original_summary_df.columns if col.startswith("test_contains_vehicle")]
display_cols = [
    "utility",
    "best_epoch",
    "val_contains_closest_fraction",
    "val_contains_closest_all",
    "val_dominance_gap",
    "test_contains_closest_fraction",
    "test_contains_closest_all",
    "test_one_closest_rate",
    "test_neither_closest_rate",
    "test_dominance_gap",
    *vehicle_cols,
    "test_mean_worst_vehicle_rank",
    "test_mean_abs_vehicle_rank_gap",
    "test_avg_regret",
]
display(original_summary_df[[col for col in display_cols if col in original_summary_df.columns]])

PROJECT_ROOT: d:\2023-2028_UCLA_Research_Projects\IoBT\17-5-26-MILCOMAttempt
DEVICE: cuda
data: times=6625, actions/time=252, examples=1,669,500, context_dim=30, action_dim=21
dense cache: d:\2023-2028_UCLA_Research_Projects\IoBT\17-5-26-MILCOMAttempt\data\processed\m02_multi_vehicle_eq5_rssi_static_dense_train_cache.npz
utilities: ['sum_full', 'sum_d1_only', 'min_d1_only', 'balanced_d1', 'balanced_full']

=== sum_full === u1_full + u2_full, where full uses d1/d2/d3 terms.
        sum_full ep 001/150* loss=0.50005 val_acc=0.570 both=0.289 one=0.562 gap=0.003 vehicle1=0.568 vehicle2=0.571 wrank=2.33 reg=0.1929 1s
        sum_full ep 002/150* loss=0.07388 val_acc=0.625 both=0.375 one=0.499 gap=0.008 vehicle1=0.620 vehicle2=0.629 wrank=2.14 reg=0.1754 1s
        sum_full ep 004/150* loss=0.03757 val_acc=0.640 both=0.435 one=0.410 gap=0.042 vehicle1=0.620 vehicle2=0.661 wrank=1.77 reg=0.1410 2s
        sum_full ep 005/150* loss=0.03351 val_acc=0.682 both=0.482 one=0.401 gap=0.008 vehicle1=0.678 vehicle2=0.686 wrank=1.72 reg=0.1247 3s
        sum_full ep 006/150* loss=0.03091 val_acc=0.710 both=0.514 one=0.392 gap=0.014 vehicle1=0.703 vehicle2=0.717 wrank=1.70 reg=0.1153 3s
        sum_full ep 007/150* loss=0.02854 val_acc=0.730 both=0.544 one=0.372 gap=0.028 vehicle1=0.716 vehicle2=0.744 wrank=1.67 reg=0.1105 4s
        sum_full ep 008/150* loss=0.02678 val_acc=0.735 both=0.546 one=0.377 gap=0.026 vehicle1=0.722 vehicle2=0.748 wrank=1.67 reg=0.1080 4s
        sum_full ep 009/150* loss=0.02468 val_acc=0.748 both=0.565 one=0.368 gap=0.007 vehicle1=0.745 vehicle2=0.752 wrank=1.64 reg=0.1014 5s
        sum_full ep 010/150  loss=0.02335 val_acc=0.743 both=0.557 one=0.372 gap=0.007 vehicle1=0.740 vehicle2=0.746 wrank=1.65 reg=0.1024 5s
        sum_full ep 012/150* loss=0.02139 val_acc=0.754 both=0.577 one=0.354 gap=0.020 vehicle1=0.743 vehicle2=0.764 wrank=1.64 reg=0.1000 6s
        sum_full ep 013/150* loss=0.02074 val_acc=0.760 both=0.583 one=0.352 gap=0.005 vehicle1=0.757 vehicle2=0.762 wrank=1.61 reg=0.0990 7s
        sum_full ep 014/150* loss=0.02021 val_acc=0.773 both=0.602 one=0.341 gap=0.008 vehicle1=0.777 vehicle2=0.769 wrank=1.58 reg=0.0920 7s
        sum_full ep 015/150* loss=0.01950 val_acc=0.789 both=0.620 one=0.339 gap=0.007 vehicle1=0.786 vehicle2=0.792 wrank=1.54 reg=0.0842 8s
        sum_full ep 017/150* loss=0.01888 val_acc=0.790 both=0.618 one=0.344 gap=0.009 vehicle1=0.795 vehicle2=0.786 wrank=1.54 reg=0.0830 9s
        sum_full ep 019/150* loss=0.01800 val_acc=0.795 both=0.622 one=0.346 gap=0.002 vehicle1=0.794 vehicle2=0.796 wrank=1.53 reg=0.0795 10s
        sum_full ep 020/150* loss=0.01756 val_acc=0.798 both=0.629 one=0.339 gap=0.013 vehicle1=0.805 vehicle2=0.792 wrank=1.53 reg=0.0785 10s
        sum_full ep 021/150* loss=0.01740 val_acc=0.813 both=0.648 one=0.331 gap=0.008 vehicle1=0.817 vehicle2=0.809 wrank=1.49 reg=0.0728 11s
        sum_full ep 022/150* loss=0.01691 val_acc=0.816 both=0.655 one=0.322 gap=0.002 vehicle1=0.815 vehicle2=0.817 wrank=1.47 reg=0.0715 11s
        sum_full ep 023/150* loss=0.01687 val_acc=0.822 both=0.674 one=0.296 gap=0.014 vehicle1=0.815 vehicle2=0.829 wrank=1.44 reg=0.0690 12s
        sum_full ep 025/150  loss=0.01634 val_acc=0.816 both=0.662 one=0.309 gap=0.013 vehicle1=0.810 vehicle2=0.823 wrank=1.47 reg=0.0722 13s
        sum_full ep 026/150* loss=0.01607 val_acc=0.825 both=0.672 one=0.304 gap=0.016 vehicle1=0.817 vehicle2=0.832 wrank=1.43 reg=0.0684 13s
        sum_full ep 027/150* loss=0.01574 val_acc=0.836 both=0.688 one=0.297 gap=0.008 vehicle1=0.832 vehicle2=0.840 wrank=1.41 reg=0.0633 14s
        sum_full ep 029/150* loss=0.01533 val_acc=0.836 both=0.691 one=0.291 gap=0.006 vehicle1=0.833 vehicle2=0.839 wrank=1.40 reg=0.0634 15s
        sum_full ep 030/150  loss=0.01517 val_acc=0.821 both=0.663 one=0.315 gap=0.005 vehicle1=0.818 vehicle2=0.823 wrank=1.44 reg=0.0696 15s
        sum_full ep 032/150* loss=0.01474 val_acc=0.845 both=0.705 one=0.279 gap=0.009 vehicle1=0.849 vehicle2=0.840 wrank=1.37 reg=0.0604 16s
        sum_full ep 035/150* loss=0.01429 val_acc=0.850 both=0.707 one=0.285 gap=0.006 vehicle1=0.853 vehicle2=0.847 wrank=1.39 reg=0.0580 18s
        sum_full ep 040/150  loss=0.01355 val_acc=0.831 both=0.678 one=0.304 gap=0.013 vehicle1=0.824 vehicle2=0.837 wrank=1.42 reg=0.0665 20s
        sum_full ep 045/150  loss=0.01301 val_acc=0.845 both=0.701 one=0.288 gap=0.026 vehicle1=0.832 vehicle2=0.858 wrank=1.39 reg=0.0609 22s
        sum_full ep 050/150  loss=0.01217 val_acc=0.822 both=0.666 one=0.312 gap=0.008 vehicle1=0.818 vehicle2=0.826 wrank=1.42 reg=0.0724 25s
        sum_full ep 051/150* loss=0.01241 val_acc=0.862 both=0.734 one=0.256 gap=0.022 vehicle1=0.851 vehicle2=0.873 wrank=1.33 reg=0.0544 25s
        sum_full ep 055/150  loss=0.01190 val_acc=0.844 both=0.700 one=0.287 gap=0.027 vehicle1=0.830 vehicle2=0.857 wrank=1.37 reg=0.0630 27s
        sum_full ep 060/150  loss=0.01130 val_acc=0.840 both=0.700 one=0.280 gap=0.010 vehicle1=0.835 vehicle2=0.845 wrank=1.38 reg=0.0643 30s
        sum_full ep 065/150  loss=0.01088 val_acc=0.844 both=0.707 one=0.273 gap=0.023 vehicle1=0.832 vehicle2=0.855 wrank=1.36 reg=0.0644 32s
        sum_full ep 067/150* loss=0.01077 val_acc=0.874 both=0.758 one=0.230 gap=0.014 vehicle1=0.866 vehicle2=0.881 wrank=1.29 reg=0.0513 33s
        sum_full ep 070/150  loss=0.01055 val_acc=0.816 both=0.673 one=0.285 gap=0.008 vehicle1=0.812 vehicle2=0.820 wrank=1.41 reg=0.0760 34s
        sum_full ep 075/150  loss=0.01032 val_acc=0.838 both=0.708 one=0.260 gap=0.003 vehicle1=0.836 vehicle2=0.839 wrank=1.35 reg=0.0682 37s
        sum_full ep 080/150  loss=0.00982 val_acc=0.846 both=0.718 one=0.256 gap=0.007 vehicle1=0.843 vehicle2=0.850 wrank=1.33 reg=0.0646 39s
        sum_full ep 085/150  loss=0.00957 val_acc=0.834 both=0.705 one=0.259 gap=0.013 vehicle1=0.841 vehicle2=0.828 wrank=1.35 reg=0.0690 42s
        sum_full ep 090/150  loss=0.00933 val_acc=0.828 both=0.694 one=0.268 gap=0.001 vehicle1=0.829 vehicle2=0.828 wrank=1.36 reg=0.0718 44s
        sum_full ep 095/150  loss=0.00902 val_acc=0.840 both=0.719 one=0.241 gap=0.002 vehicle1=0.841 vehicle2=0.838 wrank=1.33 reg=0.0683 46s
        sum_full ep 100/150  loss=0.00916 val_acc=0.840 both=0.715 one=0.249 gap=0.003 vehicle1=0.838 vehicle2=0.842 wrank=1.32 reg=0.0694 49s
        sum_full ep 105/150  loss=0.00864 val_acc=0.860 both=0.749 one=0.223 gap=0.003 vehicle1=0.862 vehicle2=0.859 wrank=1.30 reg=0.0594 51s
        sum_full ep 110/150  loss=0.00847 val_acc=0.839 both=0.718 one=0.242 gap=0.028 vehicle1=0.825 vehicle2=0.853 wrank=1.32 reg=0.0670 54s
        sum_full ep 115/150  loss=0.00837 val_acc=0.813 both=0.674 one=0.278 gap=0.008 vehicle1=0.809 vehicle2=0.817 wrank=1.38 reg=0.0792 56s
        sum_full ep 120/150  loss=0.00843 val_acc=0.844 both=0.727 one=0.234 gap=0.008 vehicle1=0.840 vehicle2=0.848 wrank=1.32 reg=0.0683 58s
        sum_full ep 125/150  loss=0.00803 val_acc=0.825 both=0.695 one=0.260 gap=0.003 vehicle1=0.823 vehicle2=0.826 wrank=1.33 reg=0.0762 61s
        sum_full ep 130/150  loss=0.00795 val_acc=0.840 both=0.724 one=0.232 gap=0.032 vehicle1=0.823 vehicle2=0.856 wrank=1.31 reg=0.0661 63s
        sum_full ep 135/150  loss=0.00773 val_acc=0.829 both=0.705 one=0.248 gap=0.017 vehicle1=0.820 vehicle2=0.837 wrank=1.33 reg=0.0723 66s
        sum_full ep 140/150  loss=0.00745 val_acc=0.842 both=0.725 one=0.235 gap=0.011 vehicle1=0.836 vehicle2=0.848 wrank=1.31 reg=0.0676 68s
        sum_full ep 145/150  loss=0.00738 val_acc=0.838 both=0.716 one=0.245 gap=0.032 vehicle1=0.823 vehicle2=0.854 wrank=1.31 reg=0.0689 70s
        sum_full ep 150/150  loss=0.00723 val_acc=0.842 both=0.722 one=0.241 gap=0.013 vehicle1=0.835 vehicle2=0.848 wrank=1.31 reg=0.0671 73s

=== sum_d1_only === f(d1_vehicle1) + f(d1_vehicle2).
     sum_d1_only ep 001/150* loss=0.22614 val_acc=0.609 both=0.340 one=0.538 gap=0.017 vehicle1=0.617 vehicle2=0.600 wrank=2.25 reg=0.1137 0s
     sum_d1_only ep 003/150* loss=0.03306 val_acc=0.618 both=0.395 one=0.446 gap=0.007 vehicle1=0.614 vehicle2=0.621 wrank=1.83 reg=0.1064 1s
     sum_d1_only ep 005/150* loss=0.02523 val_acc=0.655 both=0.423 one=0.464 gap=0.013 vehicle1=0.661 vehicle2=0.648 wrank=1.77 reg=0.0905 2s
     sum_d1_only ep 006/150* loss=0.02331 val_acc=0.677 both=0.454 one=0.448 gap=0.001 vehicle1=0.677 vehicle2=0.678 wrank=1.73 reg=0.0836 3s
     sum_d1_only ep 007/150* loss=0.02139 val_acc=0.693 both=0.481 one=0.425 gap=0.022 vehicle1=0.682 vehicle2=0.704 wrank=1.70 reg=0.0792 3s
     sum_d1_only ep 008/150* loss=0.01982 val_acc=0.704 both=0.506 one=0.395 gap=0.011 vehicle1=0.699 vehicle2=0.709 wrank=1.67 reg=0.0753 4s
     sum_d1_only ep 009/150* loss=0.01823 val_acc=0.730 both=0.552 one=0.355 gap=0.012 vehicle1=0.724 vehicle2=0.736 wrank=1.64 reg=0.0689 4s
     sum_d1_only ep 010/150  loss=0.01730 val_acc=0.695 both=0.503 one=0.385 gap=0.033 vehicle1=0.678 vehicle2=0.712 wrank=1.70 reg=0.0780 5s
     sum_d1_only ep 013/150* loss=0.01552 val_acc=0.735 both=0.552 one=0.365 gap=0.017 vehicle1=0.726 vehicle2=0.743 wrank=1.63 reg=0.0675 6s
     sum_d1_only ep 014/150* loss=0.01516 val_acc=0.743 both=0.562 one=0.362 gap=0.005 vehicle1=0.740 vehicle2=0.745 wrank=1.60 reg=0.0643 7s
     sum_d1_only ep 015/150* loss=0.01460 val_acc=0.755 both=0.571 one=0.369 gap=0.005 vehicle1=0.752 vehicle2=0.758 wrank=1.59 reg=0.0609 7s
     sum_d1_only ep 017/150* loss=0.01413 val_acc=0.763 both=0.575 one=0.377 gap=0.001 vehicle1=0.763 vehicle2=0.764 wrank=1.57 reg=0.0588 8s
     sum_d1_only ep 019/150* loss=0.01352 val_acc=0.765 both=0.573 one=0.384 gap=0.008 vehicle1=0.761 vehicle2=0.769 wrank=1.55 reg=0.0567 9s
     sum_d1_only ep 020/150* loss=0.01322 val_acc=0.770 both=0.583 one=0.374 gap=0.002 vehicle1=0.769 vehicle2=0.771 wrank=1.55 reg=0.0567 10s
     sum_d1_only ep 022/150* loss=0.01269 val_acc=0.784 both=0.602 one=0.363 gap=0.008 vehicle1=0.788 vehicle2=0.780 wrank=1.50 reg=0.0508 11s
     sum_d1_only ep 023/150* loss=0.01264 val_acc=0.790 both=0.620 one=0.340 gap=0.014 vehicle1=0.783 vehicle2=0.797 wrank=1.46 reg=0.0474 11s
     sum_d1_only ep 025/150  loss=0.01231 val_acc=0.780 both=0.599 one=0.362 gap=0.008 vehicle1=0.777 vehicle2=0.784 wrank=1.51 reg=0.0514 12s
     sum_d1_only ep 030/150  loss=0.01145 val_acc=0.764 both=0.581 one=0.365 gap=0.009 vehicle1=0.759 vehicle2=0.768 wrank=1.51 reg=0.0575 15s
     sum_d1_only ep 032/150* loss=0.01111 val_acc=0.794 both=0.631 one=0.327 gap=0.002 vehicle1=0.795 vehicle2=0.793 wrank=1.42 reg=0.0474 16s
     sum_d1_only ep 035/150  loss=0.01081 val_acc=0.794 both=0.628 one=0.332 gap=0.009 vehicle1=0.789 vehicle2=0.798 wrank=1.45 reg=0.0468 17s
     sum_d1_only ep 040/150  loss=0.01038 val_acc=0.784 both=0.612 one=0.343 gap=0.004 vehicle1=0.782 vehicle2=0.786 wrank=1.46 reg=0.0520 20s
     sum_d1_only ep 045/150* loss=0.00983 val_acc=0.799 both=0.642 one=0.313 gap=0.026 vehicle1=0.786 vehicle2=0.812 wrank=1.44 reg=0.0500 22s
     sum_d1_only ep 049/150* loss=0.00943 val_acc=0.825 both=0.682 one=0.285 gap=0.012 vehicle1=0.819 vehicle2=0.831 wrank=1.36 reg=0.0419 24s
     sum_d1_only ep 050/150  loss=0.00934 val_acc=0.794 both=0.645 one=0.298 gap=0.008 vehicle1=0.790 vehicle2=0.798 wrank=1.40 reg=0.0543 24s
     sum_d1_only ep 053/150* loss=0.00906 val_acc=0.825 both=0.703 one=0.243 gap=0.017 vehicle1=0.817 vehicle2=0.833 wrank=1.35 reg=0.0417 26s
     sum_d1_only ep 055/150  loss=0.00905 val_acc=0.810 both=0.657 one=0.306 gap=0.008 vehicle1=0.806 vehicle2=0.814 wrank=1.38 reg=0.0473 27s
     sum_d1_only ep 056/150* loss=0.00894 val_acc=0.826 both=0.688 one=0.277 gap=0.008 vehicle1=0.822 vehicle2=0.830 wrank=1.37 reg=0.0424 27s
     sum_d1_only ep 059/150* loss=0.00871 val_acc=0.837 both=0.705 one=0.263 gap=0.013 vehicle1=0.830 vehicle2=0.843 wrank=1.34 reg=0.0376 29s
     sum_d1_only ep 060/150  loss=0.00864 val_acc=0.809 both=0.672 one=0.275 gap=0.007 vehicle1=0.813 vehicle2=0.806 wrank=1.39 reg=0.0466 29s
     sum_d1_only ep 064/150* loss=0.00839 val_acc=0.837 both=0.721 one=0.232 gap=0.017 vehicle1=0.828 vehicle2=0.845 wrank=1.34 reg=0.0405 31s
     sum_d1_only ep 065/150  loss=0.00838 val_acc=0.826 both=0.689 one=0.273 gap=0.015 vehicle1=0.818 vehicle2=0.833 wrank=1.36 reg=0.0417 32s
     sum_d1_only ep 067/150* loss=0.00832 val_acc=0.838 both=0.712 one=0.251 gap=0.008 vehicle1=0.834 vehicle2=0.842 wrank=1.36 reg=0.0371 33s
     sum_d1_only ep 070/150  loss=0.00807 val_acc=0.786 both=0.635 one=0.302 gap=0.024 vehicle1=0.774 vehicle2=0.798 wrank=1.45 reg=0.0543 34s
     sum_d1_only ep 075/150  loss=0.00781 val_acc=0.815 both=0.675 one=0.280 gap=0.025 vehicle1=0.803 vehicle2=0.828 wrank=1.38 reg=0.0483 36s
     sum_d1_only ep 080/150  loss=0.00753 val_acc=0.831 both=0.698 one=0.266 gap=0.024 vehicle1=0.819 vehicle2=0.843 wrank=1.35 reg=0.0437 39s
     sum_d1_only ep 082/150* loss=0.00760 val_acc=0.851 both=0.730 one=0.243 gap=0.005 vehicle1=0.854 vehicle2=0.849 wrank=1.30 reg=0.0348 40s
     sum_d1_only ep 085/150  loss=0.00732 val_acc=0.817 both=0.677 one=0.280 gap=0.011 vehicle1=0.811 vehicle2=0.823 wrank=1.38 reg=0.0476 41s
     sum_d1_only ep 090/150  loss=0.00713 val_acc=0.811 both=0.673 one=0.275 gap=0.020 vehicle1=0.801 vehicle2=0.821 wrank=1.40 reg=0.0497 44s
     sum_d1_only ep 092/150* loss=0.00707 val_acc=0.855 both=0.736 one=0.239 gap=0.022 vehicle1=0.845 vehicle2=0.866 wrank=1.29 reg=0.0343 45s
     sum_d1_only ep 095/150  loss=0.00706 val_acc=0.825 both=0.692 one=0.265 gap=0.029 vehicle1=0.810 vehicle2=0.839 wrank=1.35 reg=0.0441 46s
     sum_d1_only ep 100/150  loss=0.00689 val_acc=0.805 both=0.667 one=0.275 gap=0.028 vehicle1=0.791 vehicle2=0.819 wrank=1.38 reg=0.0530 49s
     sum_d1_only ep 105/150  loss=0.00667 val_acc=0.832 both=0.698 one=0.267 gap=0.000 vehicle1=0.832 vehicle2=0.832 wrank=1.34 reg=0.0409 51s
     sum_d1_only ep 110/150  loss=0.00649 val_acc=0.832 both=0.702 one=0.260 gap=0.046 vehicle1=0.809 vehicle2=0.855 wrank=1.34 reg=0.0421 53s
     sum_d1_only ep 115/150  loss=0.00641 val_acc=0.796 both=0.642 one=0.309 gap=0.020 vehicle1=0.786 vehicle2=0.806 wrank=1.40 reg=0.0530 56s
     sum_d1_only ep 120/150  loss=0.00630 val_acc=0.813 both=0.675 one=0.275 gap=0.021 vehicle1=0.802 vehicle2=0.823 wrank=1.37 reg=0.0508 58s
     sum_d1_only ep 125/150  loss=0.00610 val_acc=0.788 both=0.635 one=0.306 gap=0.001 vehicle1=0.787 vehicle2=0.788 wrank=1.41 reg=0.0587 61s
     sum_d1_only ep 130/150  loss=0.00600 val_acc=0.832 both=0.706 one=0.253 gap=0.034 vehicle1=0.815 vehicle2=0.849 wrank=1.34 reg=0.0423 63s
     sum_d1_only ep 135/150  loss=0.00605 val_acc=0.824 both=0.693 one=0.262 gap=0.038 vehicle1=0.805 vehicle2=0.843 wrank=1.34 reg=0.0486 65s
     sum_d1_only ep 140/150  loss=0.00572 val_acc=0.811 both=0.673 one=0.276 gap=0.030 vehicle1=0.796 vehicle2=0.826 wrank=1.38 reg=0.0511 68s
     sum_d1_only ep 145/150  loss=0.00563 val_acc=0.814 both=0.675 one=0.278 gap=0.017 vehicle1=0.805 vehicle2=0.822 wrank=1.36 reg=0.0503 70s
     sum_d1_only ep 150/150  loss=0.00562 val_acc=0.828 both=0.700 one=0.255 gap=0.017 vehicle1=0.820 vehicle2=0.836 wrank=1.35 reg=0.0465 73s

=== min_d1_only === min(f(d1_vehicle1), f(d1_vehicle2)); protects the worse-covered vehicle.
     min_d1_only ep 001/150* loss=0.03700 val_acc=0.604 both=0.337 one=0.535 gap=0.020 vehicle1=0.614 vehicle2=0.594 wrank=2.20 reg=0.0677 0s
     min_d1_only ep 002/150* loss=0.01236 val_acc=0.680 both=0.438 one=0.484 gap=0.096 vehicle1=0.728 vehicle2=0.632 wrank=1.84 reg=0.0511 1s
     min_d1_only ep 004/150* loss=0.00857 val_acc=0.680 both=0.490 one=0.381 gap=0.014 vehicle1=0.688 vehicle2=0.673 wrank=1.66 reg=0.0417 2s
     min_d1_only ep 005/150* loss=0.00791 val_acc=0.718 both=0.542 one=0.352 gap=0.008 vehicle1=0.722 vehicle2=0.714 wrank=1.55 reg=0.0364 2s
     min_d1_only ep 006/150* loss=0.00738 val_acc=0.725 both=0.550 one=0.349 gap=0.004 vehicle1=0.723 vehicle2=0.727 wrank=1.54 reg=0.0360 3s
     min_d1_only ep 007/150* loss=0.00701 val_acc=0.726 both=0.552 one=0.347 gap=0.014 vehicle1=0.719 vehicle2=0.733 wrank=1.52 reg=0.0348 3s
     min_d1_only ep 010/150  loss=0.00633 val_acc=0.694 both=0.504 one=0.379 gap=0.038 vehicle1=0.675 vehicle2=0.712 wrank=1.60 reg=0.0401 5s
     min_d1_only ep 011/150* loss=0.00618 val_acc=0.730 both=0.556 one=0.348 gap=0.022 vehicle1=0.719 vehicle2=0.741 wrank=1.53 reg=0.0355 5s
     min_d1_only ep 015/150* loss=0.00570 val_acc=0.734 both=0.553 one=0.361 gap=0.009 vehicle1=0.729 vehicle2=0.738 wrank=1.57 reg=0.0382 7s
     min_d1_only ep 016/150* loss=0.00555 val_acc=0.744 both=0.565 one=0.359 gap=0.002 vehicle1=0.745 vehicle2=0.743 wrank=1.56 reg=0.0379 8s
     min_d1_only ep 020/150  loss=0.00523 val_acc=0.739 both=0.562 one=0.353 gap=0.006 vehicle1=0.736 vehicle2=0.742 wrank=1.56 reg=0.0384 10s
     min_d1_only ep 022/150* loss=0.00507 val_acc=0.747 both=0.574 one=0.346 gap=0.008 vehicle1=0.743 vehicle2=0.751 wrank=1.54 reg=0.0375 11s
     min_d1_only ep 023/150* loss=0.00502 val_acc=0.761 both=0.592 one=0.338 gap=0.005 vehicle1=0.758 vehicle2=0.763 wrank=1.51 reg=0.0344 11s
     min_d1_only ep 025/150* loss=0.00493 val_acc=0.767 both=0.595 one=0.343 gap=0.017 vehicle1=0.758 vehicle2=0.776 wrank=1.51 reg=0.0341 12s
     min_d1_only ep 027/150* loss=0.00474 val_acc=0.783 both=0.617 one=0.332 gap=0.026 vehicle1=0.771 vehicle2=0.796 wrank=1.47 reg=0.0313 13s
     min_d1_only ep 030/150  loss=0.00463 val_acc=0.778 both=0.608 one=0.340 gap=0.031 vehicle1=0.763 vehicle2=0.794 wrank=1.49 reg=0.0312 14s
     min_d1_only ep 031/150* loss=0.00455 val_acc=0.817 both=0.657 one=0.318 gap=0.036 vehicle1=0.798 vehicle2=0.835 wrank=1.41 reg=0.0269 15s
     min_d1_only ep 035/150  loss=0.00436 val_acc=0.814 both=0.662 one=0.303 gap=0.041 vehicle1=0.793 vehicle2=0.834 wrank=1.38 reg=0.0264 17s
     min_d1_only ep 040/150  loss=0.00418 val_acc=0.800 both=0.639 one=0.322 gap=0.059 vehicle1=0.771 vehicle2=0.829 wrank=1.42 reg=0.0294 19s
     min_d1_only ep 045/150  loss=0.00398 val_acc=0.806 both=0.654 one=0.304 gap=0.049 vehicle1=0.781 vehicle2=0.830 wrank=1.40 reg=0.0291 22s
     min_d1_only ep 049/150* loss=0.00382 val_acc=0.828 both=0.680 one=0.295 gap=0.055 vehicle1=0.800 vehicle2=0.855 wrank=1.39 reg=0.0253 24s
     min_d1_only ep 050/150  loss=0.00377 val_acc=0.820 both=0.668 one=0.304 gap=0.046 vehicle1=0.797 vehicle2=0.843 wrank=1.37 reg=0.0260 24s
     min_d1_only ep 055/150  loss=0.00365 val_acc=0.798 both=0.638 one=0.318 gap=0.042 vehicle1=0.777 vehicle2=0.819 wrank=1.42 reg=0.0290 27s
     min_d1_only ep 060/150  loss=0.00349 val_acc=0.826 both=0.686 one=0.281 gap=0.045 vehicle1=0.804 vehicle2=0.849 wrank=1.37 reg=0.0240 29s
     min_d1_only ep 065/150  loss=0.00340 val_acc=0.801 both=0.645 one=0.312 gap=0.060 vehicle1=0.771 vehicle2=0.831 wrank=1.42 reg=0.0272 31s
     min_d1_only ep 070/150  loss=0.00326 val_acc=0.778 both=0.606 one=0.345 gap=0.049 vehicle1=0.754 vehicle2=0.803 wrank=1.46 reg=0.0304 34s
     min_d1_only ep 075/150  loss=0.00314 val_acc=0.783 both=0.626 one=0.315 gap=0.036 vehicle1=0.765 vehicle2=0.802 wrank=1.45 reg=0.0295 36s
     min_d1_only ep 080/150* loss=0.00305 val_acc=0.829 both=0.700 one=0.260 gap=0.035 vehicle1=0.812 vehicle2=0.847 wrank=1.38 reg=0.0226 39s
     min_d1_only ep 085/150  loss=0.00297 val_acc=0.822 both=0.680 one=0.285 gap=0.002 vehicle1=0.821 vehicle2=0.823 wrank=1.37 reg=0.0255 41s
     min_d1_only ep 087/150* loss=0.00294 val_acc=0.834 both=0.702 one=0.264 gap=0.035 vehicle1=0.817 vehicle2=0.851 wrank=1.35 reg=0.0206 42s
     min_d1_only ep 090/150  loss=0.00286 val_acc=0.820 both=0.674 one=0.291 gap=0.048 vehicle1=0.795 vehicle2=0.844 wrank=1.39 reg=0.0243 43s
     min_d1_only ep 095/150  loss=0.00283 val_acc=0.831 both=0.691 one=0.281 gap=0.033 vehicle1=0.814 vehicle2=0.848 wrank=1.36 reg=0.0235 46s
     min_d1_only ep 100/150  loss=0.00273 val_acc=0.818 both=0.678 one=0.279 gap=0.048 vehicle1=0.794 vehicle2=0.842 wrank=1.38 reg=0.0249 48s

,utility,best_epoch,val_contains_closest_fraction,val_contains_closest_all,val_dominance_gap,test_contains_closest_fraction,test_contains_closest_all,test_one_closest_rate,test_neither_closest_rate,test_dominance_gap,test_contains_vehicle1,test_contains_vehicle2,test_mean_worst_vehicle_rank,test_mean_abs_vehicle_rank_gap,test_avg_regret
0,balanced_full,132,0.869434,0.755472,0.016604,0.856226,0.723774,0.264906,0.011321,0.038491,0.875472,0.836981,1.384906,0.373585,0.034979
1,sum_d1_only,92,0.855472,0.735849,0.021887,0.852830,0.731321,0.243019,0.025660,0.019623,0.862642,0.843019,1.323019,0.295094,0.031356
2,balanced_d1,135,0.864528,0.744151,0.029434,0.850943,0.718491,0.264906,0.016604,0.033962,0.867925,0.833962,1.320000,0.302642,0.019514
3,sum_full,67,0.873585,0.758491,0.014340,0.850566,0.728302,0.244528,0.027170,0.048302,0.874717,0.826415,1.409057,0.379623,0.057036
4,min_d1_only,129,0.868302,0.753208,0.038491,0.837736,0.700377,0.274717,0.024906,0.037736,0.856604,0.818868,1.368302,0.341887,0.024701

In [7]:
# Softmin-utility parameter sweep: vary beta and lambda around the current best setting.
from pathlib import Path
import sys

PROJECT_ROOT = Path.cwd()
if PROJECT_ROOT.name == "notebooks":
    PROJECT_ROOT = PROJECT_ROOT.parent

SCRIPTS_DIR = PROJECT_ROOT / "scripts"
if str(SCRIPTS_DIR) not in sys.path:
    sys.path.insert(0, str(SCRIPTS_DIR))

import importlib
import multi_vehicle_utility_search as mv_utils

mv_utils = importlib.reload(mv_utils)
from multi_vehicle_utility_search import run_rssi_utility_search

# Default setting is beta=10, lambda=1.0. In the labels, lam05=0.5, lam10=1.0, lam20=2.0.
SOFTMIN_PARAM_SWEEP_CANDIDATES = [
    {
        "name": "sum_plus_softmin_beta5_lam10",
        "column": "derived_sum_plus_softmin_beta5_lam10",
        "description": "mean(d1 utilities) + 1.0 * softmin_beta5(d1 utilities).",
        "kind": "sum_plus_softmin_d1",
        "beta": 5.0,
        "lam": 1.0,
    },
    {
        "name": "sum_plus_softmin_beta20_lam10",
        "column": "derived_sum_plus_softmin_beta20_lam10",
        "description": "mean(d1 utilities) + 1.0 * softmin_beta20(d1 utilities).",
        "kind": "sum_plus_softmin_d1",
        "beta": 20.0,
        "lam": 1.0,
    },
    {
        "name": "sum_plus_softmin_beta10_lam05",
        "column": "derived_sum_plus_softmin_beta10_lam05",
        "description": "mean(d1 utilities) + 0.5 * softmin_beta10(d1 utilities).",
        "kind": "sum_plus_softmin_d1",
        "beta": 10.0,
        "lam": 0.5,
    },
    {
        "name": "sum_plus_softmin_beta10_lam20",
        "column": "derived_sum_plus_softmin_beta10_lam20",
        "description": "mean(d1 utilities) + 2.0 * softmin_beta10(d1 utilities).",
        "kind": "sum_plus_softmin_d1",
        "beta": 10.0,
        "lam": 2.0,
    },
]

softmin_param_summary_df, softmin_param_results = run_rssi_utility_search(
    PROJECT_ROOT,
    model_tag="multi_vehicle_rssi_softmin_param_sweep_eq5_150ep",
    max_epochs=150,
    patience=150,
    log_every=5,
    batch_size=8192,
    time_batch_size=256,
    utility_candidates=SOFTMIN_PARAM_SWEEP_CANDIDATES,
)

vehicle_cols = [col for col in softmin_param_summary_df.columns if col.startswith("test_contains_vehicle")]
display_cols = [
    "utility",
    "best_epoch",
    "val_contains_closest_fraction",
    "val_contains_closest_all",
    "val_dominance_gap",
    "test_contains_closest_fraction",
    "test_contains_closest_all",
    "test_one_closest_rate",
    "test_neither_closest_rate",
    "test_dominance_gap",
    *vehicle_cols,
    "test_mean_worst_vehicle_rank",
    "test_mean_abs_vehicle_rank_gap",
    "test_avg_regret",
]
display(softmin_param_summary_df[[col for col in display_cols if col in softmin_param_summary_df.columns]])

Dense cache is missing requested utility targets; rebuilding with 15 utility matrices.
Building dense train cache from m02_multi_vehicle_eq5_rssi_static_examples_index.csv ...
Saved dense train cache: d:\2023-2028_UCLA_Research_Projects\IoBT\17-5-26-MILCOMAttempt\data\processed\m02_multi_vehicle_eq5_rssi_static_dense_train_cache.npz
PROJECT_ROOT: d:\2023-2028_UCLA_Research_Projects\IoBT\17-5-26-MILCOMAttempt
DEVICE: cuda
data: times=6625, actions/time=252, examples=1,669,500, context_dim=30, action_dim=21
dense cache: d:\2023-2028_UCLA_Research_Projects\IoBT\17-5-26-MILCOMAttempt\data\processed\m02_multi_vehicle_eq5_rssi_static_dense_train_cache.npz
utilities: ['sum_plus_softmin_beta5_lam10', 'sum_plus_softmin_beta20_lam10', 'sum_plus_softmin_beta10_lam05', 'sum_plus_softmin_beta10_lam20']

=== sum_plus_softmin_beta5_lam10 === mean(d1 utilities) + 1.0 * softmin_beta5(d1 utilities).
sum_plus_softmin_beta5_lam10 ep 001/150* loss=0.20403 val_acc=0.611 both=0.340 one=0.543 gap=0.009 vehicle1=0.616 vehicle2=0.607 wrank=2.24 reg=0.1209 1s
sum_plus_softmin_beta5_lam10 ep 003/150* loss=0.03145 val_acc=0.620 both=0.398 one=0.445 gap=0.013 vehicle1=0.614 vehicle2=0.626 wrank=1.81 reg=0.1053 2s
sum_plus_softmin_beta5_lam10 ep 004/150* loss=0.02675 val_acc=0.621 both=0.395 one=0.452 gap=0.019 vehicle1=0.611 vehicle2=0.630 wrank=1.79 reg=0.1036 2s
sum_plus_softmin_beta5_lam10 ep 005/150* loss=0.02431 val_acc=0.657 both=0.432 one=0.451 gap=0.002 vehicle1=0.657 vehicle2=0.658 wrank=1.75 reg=0.0935 3s
sum_plus_softmin_beta5_lam10 ep 006/150* loss=0.02261 val_acc=0.666 both=0.442 one=0.448 gap=0.018 vehicle1=0.657 vehicle2=0.675 wrank=1.74 reg=0.0908 3s
sum_plus_softmin_beta5_lam10 ep 007/150* loss=0.02093 val_acc=0.687 both=0.479 one=0.415 gap=0.023 vehicle1=0.675 vehicle2=0.698 wrank=1.68 reg=0.0839 4s
sum_plus_softmin_beta5_lam10 ep 008/150* loss=0.01951 val_acc=0.688 both=0.490 one=0.397 gap=0.015 vehicle1=0.681 vehicle2=0.696 wrank=1.67 reg=0.0818 4s
sum_plus_softmin_beta5_lam10 ep 009/150* loss=0.01809 val_acc=0.727 both=0.546 one=0.363 gap=0.016 vehicle1=0.719 vehicle2=0.735 wrank=1.64 reg=0.0738 5s
sum_plus_softmin_beta5_lam10 ep 010/150  loss=0.01731 val_acc=0.700 both=0.511 one=0.377 gap=0.035 vehicle1=0.682 vehicle2=0.717 wrank=1.68 reg=0.0810 5s
sum_plus_softmin_beta5_lam10 ep 011/150* loss=0.01672 val_acc=0.729 both=0.544 one=0.371 gap=0.025 vehicle1=0.717 vehicle2=0.742 wrank=1.64 reg=0.0751 6s
sum_plus_softmin_beta5_lam10 ep 012/150* loss=0.01622 val_acc=0.732 both=0.547 one=0.370 gap=0.012 vehicle1=0.726 vehicle2=0.738 wrank=1.64 reg=0.0726 6s
sum_plus_softmin_beta5_lam10 ep 013/150* loss=0.01576 val_acc=0.733 both=0.542 one=0.382 gap=0.014 vehicle1=0.726 vehicle2=0.740 wrank=1.63 reg=0.0729 7s
sum_plus_softmin_beta5_lam10 ep 014/150* loss=0.01546 val_acc=0.746 both=0.569 one=0.354 gap=0.001 vehicle1=0.746 vehicle2=0.746 wrank=1.60 reg=0.0688 7s
sum_plus_softmin_beta5_lam10 ep 015/150* loss=0.01498 val_acc=0.746 both=0.564 one=0.365 gap=0.006 vehicle1=0.743 vehicle2=0.749 wrank=1.61 reg=0.0701 7s
sum_plus_softmin_beta5_lam10 ep 020/150  loss=0.01369 val_acc=0.731 both=0.545 one=0.372 gap=0.016 vehicle1=0.739 vehicle2=0.723 wrank=1.62 reg=0.0731 10s
sum_plus_softmin_beta5_lam10 ep 023/150* loss=0.01319 val_acc=0.759 both=0.588 one=0.343 gap=0.029 vehicle1=0.774 vehicle2=0.745 wrank=1.54 reg=0.0621 11s
sum_plus_softmin_beta5_lam10 ep 025/150  loss=0.01290 val_acc=0.741 both=0.552 one=0.377 gap=0.010 vehicle1=0.746 vehicle2=0.736 wrank=1.61 reg=0.0696 12s
sum_plus_softmin_beta5_lam10 ep 029/150* loss=0.01221 val_acc=0.769 both=0.587 one=0.363 gap=0.007 vehicle1=0.765 vehicle2=0.772 wrank=1.56 reg=0.0620 14s
sum_plus_softmin_beta5_lam10 ep 030/150  loss=0.01204 val_acc=0.747 both=0.556 one=0.381 gap=0.014 vehicle1=0.740 vehicle2=0.754 wrank=1.60 reg=0.0684 15s
sum_plus_softmin_beta5_lam10 ep 031/150* loss=0.01176 val_acc=0.791 both=0.622 one=0.338 gap=0.006 vehicle1=0.788 vehicle2=0.794 wrank=1.49 reg=0.0537 15s
sum_plus_softmin_beta5_lam10 ep 034/150* loss=0.01147 val_acc=0.794 both=0.628 one=0.333 gap=0.026 vehicle1=0.781 vehicle2=0.808 wrank=1.48 reg=0.0541 17s
sum_plus_softmin_beta5_lam10 ep 035/150* loss=0.01134 val_acc=0.798 both=0.633 one=0.330 gap=0.008 vehicle1=0.794 vehicle2=0.802 wrank=1.49 reg=0.0540 17s
sum_plus_softmin_beta5_lam10 ep 037/150* loss=0.01112 val_acc=0.799 both=0.635 one=0.329 gap=0.041 vehicle1=0.779 vehicle2=0.820 wrank=1.45 reg=0.0524 18s
sum_plus_softmin_beta5_lam10 ep 040/150  loss=0.01095 val_acc=0.793 both=0.626 one=0.334 gap=0.027 vehicle1=0.780 vehicle2=0.807 wrank=1.47 reg=0.0530 20s
sum_plus_softmin_beta5_lam10 ep 045/150* loss=0.01036 val_acc=0.802 both=0.642 one=0.322 gap=0.039 vehicle1=0.783 vehicle2=0.822 wrank=1.45 reg=0.0528 22s
sum_plus_softmin_beta5_lam10 ep 049/150* loss=0.00993 val_acc=0.840 both=0.712 one=0.256 gap=0.016 vehicle1=0.832 vehicle2=0.848 wrank=1.37 reg=0.0423 24s
sum_plus_softmin_beta5_lam10 ep 050/150  loss=0.00982 val_acc=0.802 both=0.660 one=0.285 gap=0.014 vehicle1=0.795 vehicle2=0.809 wrank=1.43 reg=0.0536 24s
sum_plus_softmin_beta5_lam10 ep 055/150  loss=0.00956 val_acc=0.793 both=0.639 one=0.307 gap=0.010 vehicle1=0.788 vehicle2=0.798 wrank=1.42 reg=0.0551 27s
sum_plus_softmin_beta5_lam10 ep 060/150  loss=0.00907 val_acc=0.806 both=0.665 one=0.282 gap=0.024 vehicle1=0.794 vehicle2=0.818 wrank=1.39 reg=0.0507 29s
sum_plus_softmin_beta5_lam10 ep 065/150  loss=0.00881 val_acc=0.817 both=0.678 one=0.277 gap=0.034 vehicle1=0.800 vehicle2=0.834 wrank=1.38 reg=0.0489 32s
sum_plus_softmin_beta5_lam10 ep 067/150* loss=0.00871 val_acc=0.847 both=0.711 one=0.272 gap=0.023 vehicle1=0.835 vehicle2=0.858 wrank=1.32 reg=0.0384 32s
sum_plus_softmin_beta5_lam10 ep 070/150  loss=0.00847 val_acc=0.783 both=0.625 one=0.315 gap=0.038 vehicle1=0.764 vehicle2=0.802 wrank=1.45 reg=0.0570 34s
sum_plus_softmin_beta5_lam10 ep 075/150  loss=0.00825 val_acc=0.832 both=0.692 one=0.281 gap=0.032 vehicle1=0.817 vehicle2=0.848 wrank=1.35 reg=0.0418 36s
sum_plus_softmin_beta5_lam10 ep 080/150  loss=0.00797 val_acc=0.841 both=0.704 one=0.273 gap=0.020 vehicle1=0.831 vehicle2=0.851 wrank=1.33 reg=0.0394 39s
sum_plus_softmin_beta5_lam10 ep 082/150* loss=0.00802 val_acc=0.849 both=0.714 one=0.271 gap=0.029 vehicle1=0.835 vehicle2=0.864 wrank=1.31 reg=0.0364 40s
sum_plus_softmin_beta5_lam10 ep 083/150* loss=0.00789 val_acc=0.850 both=0.719 one=0.262 gap=0.017 vehicle1=0.842 vehicle2=0.859 wrank=1.32 reg=0.0375 40s
sum_plus_softmin_beta5_lam10 ep 085/150  loss=0.00777 val_acc=0.817 both=0.663 one=0.306 gap=0.018 vehicle1=0.808 vehicle2=0.826 wrank=1.39 reg=0.0479 41s
sum_plus_softmin_beta5_lam10 ep 090/150  loss=0.00755 val_acc=0.824 both=0.682 one=0.285 gap=0.037 vehicle1=0.805 vehicle2=0.842 wrank=1.36 reg=0.0451 44s
sum_plus_softmin_beta5_lam10 ep 092/150* loss=0.00751 val_acc=0.859 both=0.734 one=0.251 gap=0.007 vehicle1=0.856 vehicle2=0.863 wrank=1.29 reg=0.0317 44s
sum_plus_softmin_beta5_lam10 ep 095/150  loss=0.00747 val_acc=0.830 both=0.688 one=0.285 gap=0.016 vehicle1=0.822 vehicle2=0.838 wrank=1.35 reg=0.0428 46s
sum_plus_softmin_beta5_lam10 ep 100/150  loss=0.00730 val_acc=0.848 both=0.713 one=0.270 gap=0.035 vehicle1=0.831 vehicle2=0.866 wrank=1.31 reg=0.0355 48s
sum_plus_softmin_beta5_lam10 ep 105/150  loss=0.00701 val_acc=0.831 both=0.693 one=0.277 gap=0.019 vehicle1=0.822 vehicle2=0.841 wrank=1.36 reg=0.0430 51s
sum_plus_softmin_beta5_lam10 ep 110/150  loss=0.00681 val_acc=0.848 both=0.706 one=0.282 gap=0.048 vehicle1=0.823 vehicle2=0.872 wrank=1.31 reg=0.0347 53s
sum_plus_softmin_beta5_lam10 ep 115/150  loss=0.00677 val_acc=0.839 both=0.697 one=0.284 gap=0.045 vehicle1=0.817 vehicle2=0.862 wrank=1.33 reg=0.0391 56s
sum_plus_softmin_beta5_lam10 ep 120/150  loss=0.00655 val_acc=0.826 both=0.685 one=0.284 gap=0.030 vehicle1=0.811 vehicle2=0.842 wrank=1.36 reg=0.0448 58s
sum_plus_softmin_beta5_lam10 ep 125/150  loss=0.00637 val_acc=0.835 both=0.693 one=0.285 gap=0.048 vehicle1=0.811 vehicle2=0.860 wrank=1.33 reg=0.0406 60s
sum_plus_softmin_beta5_lam10 ep 130/150  loss=0.00636 val_acc=0.853 both=0.723 one=0.260 gap=0.016 vehicle1=0.845 vehicle2=0.861 wrank=1.31 reg=0.0339 63s
sum_plus_softmin_beta5_lam10 ep 135/150  loss=0.00621 val_acc=0.852 both=0.718 one=0.267 gap=0.047 vehicle1=0.829 vehicle2=0.875 wrank=1.30 reg=0.0340 65s
sum_plus_softmin_beta5_lam10 ep 140/150  loss=0.00598 val_acc=0.836 both=0.694 one=0.285 gap=0.015 vehicle1=0.829 vehicle2=0.844 wrank=1.38 reg=0.0417 68s
sum_plus_softmin_beta5_lam10 ep 145/150  loss=0.00585 val_acc=0.840 both=0.699 one=0.282 gap=0.037 vehicle1=0.821 vehicle2=0.858 wrank=1.35 reg=0.0382 70s
sum_plus_softmin_beta5_lam10 ep 150/150* loss=0.00579 val_acc=0.862 both=0.734 one=0.256 gap=0.016 vehicle1=0.854 vehicle2=0.869 wrank=1.30 reg=0.0328 73s

=== sum_plus_softmin_beta20_lam10 === mean(d1 utilities) + 1.0 * softmin_beta20(d1 utilities).
sum_plus_softmin_beta20_lam10 ep 001/150* loss=0.18978 val_acc=0.614 both=0.341 one=0.545 gap=0.009 vehicle1=0.618 vehicle2=0.609 wrank=2.24 reg=0.1246 0s
sum_plus_softmin_beta20_lam10 ep 003/150* loss=0.03157 val_acc=0.622 both=0.401 one=0.442 gap=0.020 vehicle1=0.612 vehicle2=0.632 wrank=1.82 reg=0.1067 1s
sum_plus_softmin_beta20_lam10 ep 004/150* loss=0.02707 val_acc=0.625 both=0.398 one=0.454 gap=0.023 vehicle1=0.614 vehicle2=0.637 wrank=1.78 reg=0.1039 2s
sum_plus_softmin_beta20_lam10 ep 005/150* loss=0.02473 val_acc=0.653 both=0.426 one=0.455 gap=0.005 vehicle1=0.651 vehicle2=0.656 wrank=1.76 reg=0.0972 2s
sum_plus_softmin_beta20_lam10 ep 006/150* loss=0.02307 val_acc=0.666 both=0.445 one=0.442 gap=0.018 vehicle1=0.657 vehicle2=0.675 wrank=1.74 reg=0.0935 3s
sum_plus_softmin_beta20_lam10 ep 007/150* loss=0.02143 val_acc=0.686 both=0.482 one=0.408 gap=0.024 vehicle1=0.674 vehicle2=0.698 wrank=1.68 reg=0.0845 3s
sum_plus_softmin_beta20_lam10 ep 008/150* loss=0.02007 val_acc=0.689 both=0.494 one=0.389 gap=0.005 vehicle1=0.687 vehicle2=0.691 wrank=1.66 reg=0.0814 4s
sum_plus_softmin_beta20_lam10 ep 009/150* loss=0.01869 val_acc=0.722 both=0.542 one=0.360 gap=0.010 vehicle1=0.717 vehicle2=0.727 wrank=1.63 reg=0.0754 4s
sum_plus_softmin_beta20_lam10 ep 010/150  loss=0.01794 val_acc=0.692 both=0.501 one=0.383 gap=0.037 vehicle1=0.674 vehicle2=0.711 wrank=1.69 reg=0.0829 5s
sum_plus_softmin_beta20_lam10 ep 011/150* loss=0.01738 val_acc=0.727 both=0.546 one=0.363 gap=0.020 vehicle1=0.717 vehicle2=0.737 wrank=1.63 reg=0.0759 5s
sum_plus_softmin_beta20_lam10 ep 012/150* loss=0.01691 val_acc=0.727 both=0.548 one=0.358 gap=0.013 vehicle1=0.721 vehicle2=0.734 wrank=1.62 reg=0.0731 6s
sum_plus_softmin_beta20_lam10 ep 013/150* loss=0.01646 val_acc=0.728 both=0.539 one=0.377 gap=0.002 vehicle1=0.727 vehicle2=0.728 wrank=1.62 reg=0.0751 6s
sum_plus_softmin_beta20_lam10 ep 014/150* loss=0.01616 val_acc=0.744 both=0.567 one=0.354 gap=0.002 vehicle1=0.743 vehicle2=0.745 wrank=1.59 reg=0.0697 7s
sum_plus_softmin_beta20_lam10 ep 015/150* loss=0.01568 val_acc=0.745 both=0.564 one=0.363 gap=0.002 vehicle1=0.746 vehicle2=0.744 wrank=1.61 reg=0.0726 7s
sum_plus_softmin_beta20_lam10 ep 018/150* loss=0.01501 val_acc=0.748 both=0.577 one=0.343 gap=0.013 vehicle1=0.755 vehicle2=0.742 wrank=1.56 reg=0.0689 9s
sum_plus_softmin_beta20_lam10 ep 020/150  loss=0.01437 val_acc=0.729 both=0.540 one=0.377 gap=0.010 vehicle1=0.734 vehicle2=0.724 wrank=1.62 reg=0.0779 10s
sum_plus_softmin_beta20_lam10 ep 023/150* loss=0.01386 val_acc=0.761 both=0.591 one=0.340 gap=0.028 vehicle1=0.775 vehicle2=0.747 wrank=1.53 reg=0.0652 11s
sum_plus_softmin_beta20_lam10 ep 025/150  loss=0.01357 val_acc=0.742 both=0.556 one=0.372 gap=0.011 vehicle1=0.748 vehicle2=0.737 wrank=1.61 reg=0.0736 12s
sum_plus_softmin_beta20_lam10 ep 029/150* loss=0.01287 val_acc=0.784 both=0.614 one=0.340 gap=0.015 vehicle1=0.777 vehicle2=0.792 wrank=1.52 reg=0.0611 14s
sum_plus_softmin_beta20_lam10 ep 030/150  loss=0.01272 val_acc=0.742 both=0.546 one=0.390 gap=0.026 vehicle1=0.728 vehicle2=0.755 wrank=1.61 reg=0.0740 15s
sum_plus_softmin_beta20_lam10 ep 031/150* loss=0.01241 val_acc=0.802 both=0.641 one=0.323 gap=0.011 vehicle1=0.797 vehicle2=0.808 wrank=1.47 reg=0.0552 15s
sum_plus_softmin_beta20_lam10 ep 035/150* loss=0.01200 val_acc=0.803 both=0.641 one=0.325 gap=0.011 vehicle1=0.798 vehicle2=0.809 wrank=1.49 reg=0.0563 17s
sum_plus_softmin_beta20_lam10 ep 040/150  loss=0.01157 val_acc=0.793 both=0.630 one=0.325 gap=0.042 vehicle1=0.772 vehicle2=0.814 wrank=1.47 reg=0.0561 19s
sum_plus_softmin_beta20_lam10 ep 045/150  loss=0.01097 val_acc=0.791 both=0.626 one=0.329 gap=0.041 vehicle1=0.771 vehicle2=0.811 wrank=1.48 reg=0.0606 22s
sum_plus_softmin_beta20_lam10 ep 049/150* loss=0.01052 val_acc=0.830 both=0.699 one=0.263 gap=0.024 vehicle1=0.818 vehicle2=0.842 wrank=1.40 reg=0.0474 24s
sum_plus_softmin_beta20_lam10 ep 050/150  loss=0.01039 val_acc=0.798 both=0.653 one=0.290 gap=0.021 vehicle1=0.787 vehicle2=0.808 wrank=1.45 reg=0.0577 24s
sum_plus_softmin_beta20_lam10 ep 051/150* loss=0.01038 val_acc=0.841 both=0.708 one=0.266 gap=0.035 vehicle1=0.823 vehicle2=0.858 wrank=1.35 reg=0.0431 25s
sum_plus_softmin_beta20_lam10 ep 055/150  loss=0.01013 val_acc=0.780 both=0.621 one=0.317 gap=0.021 vehicle1=0.769 vehicle2=0.790 wrank=1.47 reg=0.0615 27s
sum_plus_softmin_beta20_lam10 ep 059/150* loss=0.00968 val_acc=0.841 both=0.709 one=0.265 gap=0.034 vehicle1=0.824 vehicle2=0.858 wrank=1.34 reg=0.0433 29s
sum_plus_softmin_beta20_lam10 ep 060/150  loss=0.00963 val_acc=0.808 both=0.669 one=0.278 gap=0.021 vehicle1=0.798 vehicle2=0.819 wrank=1.40 reg=0.0531 29s
sum_plus_softmin_beta20_lam10 ep 065/150  loss=0.00935 val_acc=0.814 both=0.673 one=0.282 gap=0.045 vehicle1=0.792 vehicle2=0.837 wrank=1.42 reg=0.0518 32s
sum_plus_softmin_beta20_lam10 ep 067/150* loss=0.00925 val_acc=0.846 both=0.710 one=0.272 gap=0.038 vehicle1=0.827 vehicle2=0.865 wrank=1.32 reg=0.0420 33s
sum_plus_softmin_beta20_lam10 ep 070/150  loss=0.00898 val_acc=0.802 both=0.649 one=0.306 gap=0.053 vehicle1=0.776 vehicle2=0.829 wrank=1.44 reg=0.0540 34s
sum_plus_softmin_beta20_lam10 ep 071/150* loss=0.00906 val_acc=0.857 both=0.729 one=0.256 gap=0.042 vehicle1=0.836 vehicle2=0.878 wrank=1.30 reg=0.0374 34s
sum_plus_softmin_beta20_lam10 ep 073/150* loss=0.00888 val_acc=0.866 both=0.744 one=0.243 gap=0.036 vehicle1=0.848 vehicle2=0.884 wrank=1.29 reg=0.0352 35s
sum_plus_softmin_beta20_lam10 ep 075/150  loss=0.00875 val_acc=0.849 both=0.716 one=0.265 gap=0.040 vehicle1=0.829 vehicle2=0.869 wrank=1.33 reg=0.0391 36s
sum_plus_softmin_beta20_lam10 ep 080/150* loss=0.00849 val_acc=0.873 both=0.759 one=0.227 gap=0.026 vehicle1=0.860 vehicle2=0.886 wrank=1.28 reg=0.0331 39s
sum_plus_softmin_beta20_lam10 ep 082/150* loss=0.00854 val_acc=0.875 both=0.757 one=0.235 gap=0.042 vehicle1=0.854 vehicle2=0.896 wrank=1.27 reg=0.0315 40s
sum_plus_softmin_beta20_lam10 ep 085/150  loss=0.00824 val_acc=0.842 both=0.710 one=0.263 gap=0.025 vehicle1=0.829 vehicle2=0.854 wrank=1.33 reg=0.0423 41s
sum_plus_softmin_beta20_lam10 ep 090/150  loss=0.00800 val_acc=0.848 both=0.720 one=0.255 gap=0.044 vehicle1=0.826 vehicle2=0.869 wrank=1.32 reg=0.0391 44s
sum_plus_softmin_beta20_lam10 ep 091/150* loss=0.00794 val_acc=0.877 both=0.768 one=0.219 gap=0.018 vehicle1=0.868 vehicle2=0.886 wrank=1.26 reg=0.0307 44s
sum_plus_softmin_beta20_lam10 ep 095/150  loss=0.00794 val_acc=0.855 both=0.734 one=0.244 gap=0.013 vehicle1=0.849 vehicle2=0.862 wrank=1.30 reg=0.0359 46s
sum_plus_softmin_beta20_lam10 ep 100/150  loss=0.00774 val_acc=0.872 both=0.755 one=0.235 gap=0.035 vehicle1=0.855 vehicle2=0.890 wrank=1.27 reg=0.0321 49s
sum_plus_softmin_beta20_lam10 ep 105/150  loss=0.00746 val_acc=0.849 both=0.725 one=0.249 gap=0.024 vehicle1=0.837 vehicle2=0.861 wrank=1.32 reg=0.0403 51s
sum_plus_softmin_beta20_lam10 ep 110/150  loss=0.00725 val_acc=0.870 both=0.748 one=0.244 gap=0.055 vehicle1=0.842 vehicle2=0.897 wrank=1.28 reg=0.0318 54s
sum_plus_softmin_beta20_lam10 ep 115/150  loss=0.00717 val_acc=0.873 both=0.753 one=0.240 gap=0.050 vehicle1=0.848 vehicle2=0.898 wrank=1.26 reg=0.0310 56s
sum_plus_softmin_beta20_lam10 ep 120/150  loss=0.00696 val_acc=0.853 both=0.728 one=0.249 gap=0.020 vehicle1=0.843 vehicle2=0.863 wrank=1.32 reg=0.0398 58s
sum_plus_softmin_beta20_lam10 ep 125/150  loss=0.00675 val_acc=0.858 both=0.728 one=0.260 gap=0.055 vehicle1=0.830 vehicle2=0.885 wrank=1.31 reg=0.0365 61s
sum_plus_softmin_beta20_lam10 ep 130/150  loss=0.00677 val_acc=0.862 both=0.740 one=0.242 gap=0.011 vehicle1=0.856 vehicle2=0.867 wrank=1.30 reg=0.0357 63s
sum_plus_softmin_beta20_lam10 ep 135/150  loss=0.00661 val_acc=0.871 both=0.752 one=0.238 gap=0.051 vehicle1=0.845 vehicle2=0.896 wrank=1.28 reg=0.0309 66s
sum_plus_softmin_beta20_lam10 ep 140/150  loss=0.00635 val_acc=0.849 both=0.715 one=0.268 gap=0.029 vehicle1=0.834 vehicle2=0.863 wrank=1.34 reg=0.0418 68s
sum_plus_softmin_beta20_lam10 ep 145/150  loss=0.00626 val_acc=0.861 both=0.737 one=0.249 gap=0.035 vehicle1=0.844 vehicle2=0.878 wrank=1.30 reg=0.0373 70s
sum_plus_softmin_beta20_lam10 ep 150/150* loss=0.00618 val_acc=0.878 both=0.762 one=0.231 gap=0.032 vehicle1=0.862 vehicle2=0.894 wrank=1.27 reg=0.0329 73s

=== sum_plus_softmin_beta10_lam05 === mean(d1 utilities) + 0.5 * softmin_beta10(d1 utilities).
sum_plus_softmin_beta10_lam05 ep 001/150* loss=0.10673 val_acc=0.574 both=0.299 one=0.550 gap=0.010 vehicle1=0.579 vehicle2=0.569 wrank=2.38 reg=0.1082 0s
sum_plus_softmin_beta10_lam05 ep 002/150* loss=0.02467 val_acc=0.599 both=0.339 one=0.520 gap=0.034 vehicle1=0.582 vehicle2=0.616 wrank=2.20 reg=0.0910 1s
sum_plus_softmin_beta10_lam05 ep 003/150* loss=0.01797 val_acc=0.615 both=0.392 one=0.446 gap=0.013 vehicle1=0.609 vehicle2=0.622 wrank=1.92 reg=0.0815 1s
sum_plus_softmin_beta10_lam05 ep 004/150* loss=0.01544 val_acc=0.622 both=0.394 one=0.457 gap=0.010 vehicle1=0.617 vehicle2=0.627 wrank=1.87 reg=0.0797 2s
sum_plus_softmin_beta10_lam05 ep 005/150* loss=0.01414 val_acc=0.650 both=0.422 one=0.456 gap=0.014 vehicle1=0.657 vehicle2=0.643 wrank=1.78 reg=0.0723 2s
sum_plus_softmin_beta10_lam05 ep 006/150* loss=0.01314 val_acc=0.674 both=0.457 one=0.434 gap=0.005 vehicle1=0.671 vehicle2=0.676 wrank=1.72 reg=0.0655 3s
sum_plus_softmin_beta10_lam05 ep 007/150* loss=0.01213 val_acc=0.706 both=0.518 one=0.374 gap=0.000 vehicle1=0.706 vehicle2=0.706 wrank=1.64 reg=0.0555 3s
sum_plus_softmin_beta10_lam05 ep 010/150  loss=0.01017 val_acc=0.668 both=0.479 one=0.377 gap=0.019 vehicle1=0.658 vehicle2=0.677 wrank=1.70 reg=0.0647 5s
sum_plus_softmin_beta10_lam05 ep 015/150  loss=0.00885 val_acc=0.701 both=0.515 one=0.371 gap=0.034 vehicle1=0.684 vehicle2=0.718 wrank=1.66 reg=0.0612 7s
sum_plus_softmin_beta10_lam05 ep 019/150* loss=0.00825 val_acc=0.706 both=0.515 one=0.381 gap=0.023 vehicle1=0.694 vehicle2=0.718 wrank=1.65 reg=0.0595 9s
sum_plus_softmin_beta10_lam05 ep 020/150* loss=0.00808 val_acc=0.712 both=0.522 one=0.380 gap=0.003 vehicle1=0.711 vehicle2=0.714 wrank=1.66 reg=0.0599 10s
sum_plus_softmin_beta10_lam05 ep 022/150* loss=0.00778 val_acc=0.730 both=0.540 one=0.381 gap=0.005 vehicle1=0.728 vehicle2=0.733 wrank=1.64 reg=0.0560 11s
sum_plus_softmin_beta10_lam05 ep 023/150* loss=0.00775 val_acc=0.745 both=0.563 one=0.364 gap=0.009 vehicle1=0.740 vehicle2=0.749 wrank=1.58 reg=0.0506 11s
sum_plus_softmin_beta10_lam05 ep 025/150  loss=0.00757 val_acc=0.736 both=0.545 one=0.383 gap=0.010 vehicle1=0.731 vehicle2=0.741 wrank=1.63 reg=0.0549 12s
sum_plus_softmin_beta10_lam05 ep 030/150  loss=0.00707 val_acc=0.740 both=0.552 one=0.375 gap=0.008 vehicle1=0.744 vehicle2=0.736 wrank=1.61 reg=0.0546 15s
sum_plus_softmin_beta10_lam05 ep 031/150* loss=0.00691 val_acc=0.765 both=0.570 one=0.389 gap=0.003 vehicle1=0.766 vehicle2=0.763 wrank=1.59 reg=0.0474 15s
sum_plus_softmin_beta10_lam05 ep 035/150* loss=0.00668 val_acc=0.774 both=0.597 one=0.354 gap=0.026 vehicle1=0.787 vehicle2=0.761 wrank=1.56 reg=0.0466 17s

,utility,best_epoch,val_contains_closest_fraction,val_contains_closest_all,val_dominance_gap,test_contains_closest_fraction,test_contains_closest_all,test_one_closest_rate,test_neither_closest_rate,test_dominance_gap,test_contains_vehicle1,test_contains_vehicle2,test_mean_worst_vehicle_rank,test_mean_abs_vehicle_rank_gap,test_avg_regret
0,sum_plus_softmin_beta5_lam10,150,0.861509,0.733585,0.015849,0.871321,0.763774,0.215094,0.021132,0.021887,0.882264,0.860377,1.267170,0.245283,0.028979
1,sum_plus_softmin_beta20_lam10,150,0.877736,0.762264,0.031698,0.863396,0.751698,0.223396,0.024906,0.039245,0.883019,0.843774,1.283019,0.251321,0.037159
2,sum_plus_softmin_beta10_lam05,118,0.857736,0.733585,0.015849,0.861887,0.738868,0.246038,0.015094,0.031698,0.877736,0.846038,1.303396,0.286792,0.027098
3,sum_plus_softmin_beta10_lam20,113,0.851698,0.720000,0.002264,0.833585,0.701887,0.263396,0.034717,0.041509,0.854340,0.812830,1.391698,0.354717,0.067709

In [8]:
# Softmin-only utility sweep: choose beta for the clean multi-vehicle objective.
from pathlib import Path
import sys

PROJECT_ROOT = Path.cwd()
if PROJECT_ROOT.name == "notebooks":
    PROJECT_ROOT = PROJECT_ROOT.parent

SCRIPTS_DIR = PROJECT_ROOT / "scripts"
if str(SCRIPTS_DIR) not in sys.path:
    sys.path.insert(0, str(SCRIPTS_DIR))

import importlib
import multi_vehicle_utility_search as mv_utils

mv_utils = importlib.reload(mv_utils)
from multi_vehicle_utility_search import run_rssi_utility_search

SOFTMIN_D1_BETA_SWEEP_CANDIDATES = []
for beta in [0.1, 1.0, 5.0, 20.0, 100.0]:
    beta_token = str(beta).replace(".", "p")
    SOFTMIN_D1_BETA_SWEEP_CANDIDATES.append(
        {
            "name": f"softmin_d1_beta{beta_token}",
            "column": f"derived_softmin_d1_beta{beta_token}",
            "description": f"Smooth min over per-vehicle d1 utilities with beta={beta}.",
            "kind": "softmin_d1",
            "beta": float(beta),
        }
    )

softmin_beta_summary_df, softmin_beta_results = run_rssi_utility_search(
    PROJECT_ROOT,
    model_tag="multi_vehicle_rssi_softmin_d1_beta_sweep_eq5_150ep",
    max_epochs=150,
    patience=150,
    log_every=5,
    batch_size=8192,
    time_batch_size=256,
    utility_candidates=SOFTMIN_D1_BETA_SWEEP_CANDIDATES,
)

vehicle_cols = [col for col in softmin_beta_summary_df.columns if col.startswith("test_contains_vehicle")]
display_cols = [
    "utility",
    "best_epoch",
    "val_contains_closest_fraction",
    "val_contains_closest_all",
    "val_dominance_gap",
    "test_contains_closest_fraction",
    "test_contains_closest_all",
    "test_one_closest_rate",
    "test_neither_closest_rate",
    "test_dominance_gap",
    *vehicle_cols,
    "test_mean_worst_vehicle_rank",
    "test_mean_abs_vehicle_rank_gap",
    "test_avg_regret",
]
display(softmin_beta_summary_df[[col for col in display_cols if col in softmin_beta_summary_df.columns]])

Dense cache is missing requested utility targets; rebuilding with 17 utility matrices.
Building dense train cache from m02_multi_vehicle_eq5_rssi_static_examples_index.csv ...
Saved dense train cache: d:\2023-2028_UCLA_Research_Projects\IoBT\17-5-26-MILCOMAttempt\data\processed\m02_multi_vehicle_eq5_rssi_static_dense_train_cache.npz
PROJECT_ROOT: d:\2023-2028_UCLA_Research_Projects\IoBT\17-5-26-MILCOMAttempt
DEVICE: cuda
data: times=6625, actions/time=252, examples=1,669,500, context_dim=30, action_dim=21
dense cache: d:\2023-2028_UCLA_Research_Projects\IoBT\17-5-26-MILCOMAttempt\data\processed\m02_multi_vehicle_eq5_rssi_static_dense_train_cache.npz
utilities: ['softmin_d1_beta0p1', 'softmin_d1_beta1p0', 'softmin_d1_beta5p0', 'softmin_d1_beta20p0', 'softmin_d1_beta100p0']

=== softmin_d1_beta0p1 === Smooth min over per-vehicle d1 utilities with beta=0.1.
softmin_d1_beta0p1 ep 001/150* loss=0.04869 val_acc=0.577 both=0.295 one=0.565 gap=0.003 vehicle1=0.576 vehicle2=0.579 wrank=2.45 reg=0.0741 1s
softmin_d1_beta0p1 ep 002/150* loss=0.01230 val_acc=0.623 both=0.368 one=0.511 gap=0.072 vehicle1=0.659 vehicle2=0.587 wrank=2.09 reg=0.0547 1s
softmin_d1_beta0p1 ep 004/150* loss=0.00764 val_acc=0.627 both=0.403 one=0.448 gap=0.045 vehicle1=0.650 vehicle2=0.605 wrank=1.89 reg=0.0534 2s
softmin_d1_beta0p1 ep 005/150* loss=0.00692 val_acc=0.674 both=0.466 one=0.416 gap=0.054 vehicle1=0.701 vehicle2=0.648 wrank=1.75 reg=0.0424 3s
softmin_d1_beta0p1 ep 006/150* loss=0.00636 val_acc=0.717 both=0.529 one=0.376 gap=0.044 vehicle1=0.739 vehicle2=0.695 wrank=1.64 reg=0.0358 3s
softmin_d1_beta0p1 ep 010/150  loss=0.00498 val_acc=0.680 both=0.475 one=0.408 gap=0.031 vehicle1=0.664 vehicle2=0.695 wrank=1.68 reg=0.0429 5s
softmin_d1_beta0p1 ep 014/150* loss=0.00446 val_acc=0.736 both=0.561 one=0.350 gap=0.045 vehicle1=0.713 vehicle2=0.758 wrank=1.57 reg=0.0343 7s
softmin_d1_beta0p1 ep 015/150  loss=0.00429 val_acc=0.726 both=0.547 one=0.358 gap=0.048 vehicle1=0.702 vehicle2=0.750 wrank=1.60 reg=0.0366 7s
softmin_d1_beta0p1 ep 017/150* loss=0.00414 val_acc=0.743 both=0.568 one=0.352 gap=0.033 vehicle1=0.727 vehicle2=0.760 wrank=1.57 reg=0.0328 8s
softmin_d1_beta0p1 ep 019/150* loss=0.00398 val_acc=0.758 both=0.587 one=0.343 gap=0.024 vehicle1=0.746 vehicle2=0.771 wrank=1.54 reg=0.0301 9s
softmin_d1_beta0p1 ep 020/150  loss=0.00389 val_acc=0.754 both=0.577 one=0.352 gap=0.008 vehicle1=0.749 vehicle2=0.758 wrank=1.58 reg=0.0311 10s
softmin_d1_beta0p1 ep 022/150* loss=0.00372 val_acc=0.768 both=0.593 one=0.349 gap=0.002 vehicle1=0.767 vehicle2=0.769 wrank=1.54 reg=0.0279 11s
softmin_d1_beta0p1 ep 025/150  loss=0.00360 val_acc=0.756 both=0.586 one=0.341 gap=0.005 vehicle1=0.754 vehicle2=0.758 wrank=1.54 reg=0.0312 12s
softmin_d1_beta0p1 ep 030/150  loss=0.00334 val_acc=0.732 both=0.552 one=0.360 gap=0.005 vehicle1=0.730 vehicle2=0.735 wrank=1.57 reg=0.0347 15s
softmin_d1_beta0p1 ep 035/150  loss=0.00314 val_acc=0.765 both=0.595 one=0.338 gap=0.003 vehicle1=0.763 vehicle2=0.766 wrank=1.51 reg=0.0291 17s
softmin_d1_beta0p1 ep 040/150  loss=0.00301 val_acc=0.757 both=0.588 one=0.339 gap=0.008 vehicle1=0.753 vehicle2=0.762 wrank=1.52 reg=0.0295 19s
softmin_d1_beta0p1 ep 045/150* loss=0.00284 val_acc=0.781 both=0.614 one=0.334 gap=0.002 vehicle1=0.780 vehicle2=0.782 wrank=1.50 reg=0.0267 22s
softmin_d1_beta0p1 ep 050/150  loss=0.00270 val_acc=0.745 both=0.556 one=0.377 gap=0.003 vehicle1=0.743 vehicle2=0.746 wrank=1.55 reg=0.0304 24s
softmin_d1_beta0p1 ep 055/150  loss=0.00260 val_acc=0.762 both=0.592 one=0.341 gap=0.008 vehicle1=0.766 vehicle2=0.758 wrank=1.50 reg=0.0286 27s
softmin_d1_beta0p1 ep 056/150* loss=0.00258 val_acc=0.785 both=0.618 one=0.333 gap=0.010 vehicle1=0.789 vehicle2=0.780 wrank=1.49 reg=0.0253 27s
softmin_d1_beta0p1 ep 058/150* loss=0.00253 val_acc=0.792 both=0.632 one=0.322 gap=0.000 vehicle1=0.792 vehicle2=0.792 wrank=1.48 reg=0.0236 28s
softmin_d1_beta0p1 ep 060/150  loss=0.00248 val_acc=0.770 both=0.598 one=0.343 gap=0.003 vehicle1=0.771 vehicle2=0.768 wrank=1.50 reg=0.0275 29s
softmin_d1_beta0p1 ep 065/150  loss=0.00241 val_acc=0.765 both=0.586 one=0.358 gap=0.010 vehicle1=0.760 vehicle2=0.770 wrank=1.52 reg=0.0286 31s
softmin_d1_beta0p1 ep 067/150* loss=0.00239 val_acc=0.796 both=0.630 one=0.331 gap=0.013 vehicle1=0.802 vehicle2=0.789 wrank=1.46 reg=0.0234 32s
softmin_d1_beta0p1 ep 070/150  loss=0.00230 val_acc=0.783 both=0.615 one=0.335 gap=0.002 vehicle1=0.782 vehicle2=0.783 wrank=1.48 reg=0.0256 34s
softmin_d1_beta0p1 ep 075/150  loss=0.00222 val_acc=0.794 both=0.639 one=0.310 gap=0.019 vehicle1=0.785 vehicle2=0.804 wrank=1.45 reg=0.0246 36s
softmin_d1_beta0p1 ep 077/150* loss=0.00219 val_acc=0.799 both=0.641 one=0.316 gap=0.011 vehicle1=0.805 vehicle2=0.793 wrank=1.46 reg=0.0240 37s
softmin_d1_beta0p1 ep 079/150* loss=0.00217 val_acc=0.814 both=0.666 one=0.296 gap=0.006 vehicle1=0.811 vehicle2=0.817 wrank=1.42 reg=0.0214 38s
softmin_d1_beta0p1 ep 080/150  loss=0.00214 val_acc=0.811 both=0.666 one=0.289 gap=0.005 vehicle1=0.814 vehicle2=0.808 wrank=1.42 reg=0.0224 38s
softmin_d1_beta0p1 ep 085/150  loss=0.00206 val_acc=0.802 both=0.642 one=0.321 gap=0.005 vehicle1=0.799 vehicle2=0.805 wrank=1.45 reg=0.0236 41s
softmin_d1_beta0p1 ep 090/150  loss=0.00201 val_acc=0.796 both=0.637 one=0.318 gap=0.009 vehicle1=0.792 vehicle2=0.801 wrank=1.47 reg=0.0244 43s
softmin_d1_beta0p1 ep 092/150* loss=0.00200 val_acc=0.832 both=0.698 one=0.267 gap=0.006 vehicle1=0.829 vehicle2=0.835 wrank=1.38 reg=0.0196 44s
softmin_d1_beta0p1 ep 095/150  loss=0.00200 val_acc=0.819 both=0.675 one=0.289 gap=0.010 vehicle1=0.814 vehicle2=0.824 wrank=1.43 reg=0.0221 46s
softmin_d1_beta0p1 ep 100/150  loss=0.00192 val_acc=0.810 both=0.666 one=0.289 gap=0.013 vehicle1=0.804 vehicle2=0.817 wrank=1.44 reg=0.0235 48s
softmin_d1_beta0p1 ep 104/150* loss=0.00186 val_acc=0.843 both=0.710 one=0.265 gap=0.007 vehicle1=0.839 vehicle2=0.846 wrank=1.37 reg=0.0184 50s
softmin_d1_beta0p1 ep 105/150  loss=0.00185 val_acc=0.807 both=0.655 one=0.304 gap=0.001 vehicle1=0.808 vehicle2=0.807 wrank=1.44 reg=0.0240 50s
softmin_d1_beta0p1 ep 110/150  loss=0.00181 val_acc=0.841 both=0.712 one=0.258 gap=0.005 vehicle1=0.838 vehicle2=0.843 wrank=1.38 reg=0.0192 53s
softmin_d1_beta0p1 ep 115/150  loss=0.00177 val_acc=0.832 both=0.698 one=0.268 gap=0.004 vehicle1=0.834 vehicle2=0.830 wrank=1.38 reg=0.0205 55s
softmin_d1_beta0p1 ep 117/150* loss=0.00176 val_acc=0.849 both=0.731 one=0.238 gap=0.014 vehicle1=0.857 vehicle2=0.842 wrank=1.35 reg=0.0183 56s
softmin_d1_beta0p1 ep 120/150  loss=0.00172 val_acc=0.824 both=0.686 one=0.276 gap=0.003 vehicle1=0.823 vehicle2=0.826 wrank=1.42 reg=0.0215 58s
softmin_d1_beta0p1 ep 125/150  loss=0.00168 val_acc=0.835 both=0.704 one=0.262 gap=0.005 vehicle1=0.832 vehicle2=0.838 wrank=1.37 reg=0.0205 60s
softmin_d1_beta0p1 ep 128/150* loss=0.00164 val_acc=0.854 both=0.737 one=0.235 gap=0.002 vehicle1=0.854 vehicle2=0.855 wrank=1.32 reg=0.0169 62s
softmin_d1_beta0p1 ep 130/150  loss=0.00163 val_acc=0.839 both=0.712 one=0.255 gap=0.002 vehicle1=0.840 vehicle2=0.838 wrank=1.35 reg=0.0191 63s
softmin_d1_beta0p1 ep 135/150  loss=0.00165 val_acc=0.851 both=0.733 one=0.237 gap=0.005 vehicle1=0.849 vehicle2=0.854 wrank=1.33 reg=0.0169 65s
softmin_d1_beta0p1 ep 140/150  loss=0.00157 val_acc=0.837 both=0.708 one=0.259 gap=0.013 vehicle1=0.831 vehicle2=0.844 wrank=1.37 reg=0.0198 67s
softmin_d1_beta0p1 ep 142/150* loss=0.00157 val_acc=0.857 both=0.739 one=0.236 gap=0.011 vehicle1=0.851 vehicle2=0.863 wrank=1.32 reg=0.0175 68s
softmin_d1_beta0p1 ep 145/150  loss=0.00154 val_acc=0.849 both=0.726 one=0.246 gap=0.023 vehicle1=0.838 vehicle2=0.860 wrank=1.34 reg=0.0177 70s
softmin_d1_beta0p1 ep 150/150* loss=0.00154 val_acc=0.859 both=0.751 one=0.217 gap=0.023 vehicle1=0.848 vehicle2=0.871 wrank=1.30 reg=0.0168 72s

=== softmin_d1_beta1p0 === Smooth min over per-vehicle d1 utilities with beta=1.0.
softmin_d1_beta1p0 ep 001/150* loss=0.04681 val_acc=0.580 both=0.296 one=0.569 gap=0.009 vehicle1=0.585 vehicle2=0.576 wrank=2.43 reg=0.0738 0s
softmin_d1_beta1p0 ep 002/150* loss=0.01192 val_acc=0.625 both=0.368 one=0.515 gap=0.072 vehicle1=0.661 vehicle2=0.589 wrank=2.08 reg=0.0560 1s
softmin_d1_beta1p0 ep 004/150* loss=0.00741 val_acc=0.637 both=0.414 one=0.446 gap=0.029 vehicle1=0.652 vehicle2=0.623 wrank=1.86 reg=0.0510 2s
softmin_d1_beta1p0 ep 005/150* loss=0.00673 val_acc=0.674 both=0.469 one=0.408 gap=0.034 vehicle1=0.691 vehicle2=0.657 wrank=1.74 reg=0.0431 2s
softmin_d1_beta1p0 ep 006/150* loss=0.00618 val_acc=0.712 both=0.523 one=0.377 gap=0.030 vehicle1=0.727 vehicle2=0.697 wrank=1.63 reg=0.0364 3s
softmin_d1_beta1p0 ep 010/150  loss=0.00489 val_acc=0.670 both=0.469 one=0.403 gap=0.036 vehicle1=0.652 vehicle2=0.688 wrank=1.69 reg=0.0443 5s
softmin_d1_beta1p0 ep 014/150* loss=0.00442 val_acc=0.725 both=0.546 one=0.357 gap=0.040 vehicle1=0.705 vehicle2=0.745 wrank=1.59 reg=0.0362 7s
softmin_d1_beta1p0 ep 015/150  loss=0.00426 val_acc=0.720 both=0.531 one=0.378 gap=0.032 vehicle1=0.703 vehicle2=0.736 wrank=1.62 reg=0.0378 7s
softmin_d1_beta1p0 ep 017/150* loss=0.00412 val_acc=0.732 both=0.546 one=0.374 gap=0.028 vehicle1=0.718 vehicle2=0.746 wrank=1.61 reg=0.0352 8s
softmin_d1_beta1p0 ep 019/150* loss=0.00396 val_acc=0.744 both=0.571 one=0.346 gap=0.010 vehicle1=0.739 vehicle2=0.749 wrank=1.57 reg=0.0330 9s
softmin_d1_beta1p0 ep 020/150* loss=0.00387 val_acc=0.752 both=0.581 one=0.341 gap=0.006 vehicle1=0.749 vehicle2=0.755 wrank=1.57 reg=0.0322 10s
softmin_d1_beta1p0 ep 022/150* loss=0.00371 val_acc=0.762 both=0.589 one=0.347 gap=0.006 vehicle1=0.759 vehicle2=0.765 wrank=1.55 reg=0.0298 11s
softmin_d1_beta1p0 ep 025/150  loss=0.00360 val_acc=0.742 both=0.565 one=0.354 gap=0.022 vehicle1=0.731 vehicle2=0.752 wrank=1.56 reg=0.0338 12s
softmin_d1_beta1p0 ep 030/150  loss=0.00334 val_acc=0.732 both=0.546 one=0.371 gap=0.016 vehicle1=0.724 vehicle2=0.740 wrank=1.59 reg=0.0352 14s
softmin_d1_beta1p0 ep 035/150* loss=0.00315 val_acc=0.777 both=0.602 one=0.351 gap=0.008 vehicle1=0.773 vehicle2=0.781 wrank=1.51 reg=0.0276 17s
softmin_d1_beta1p0 ep 040/150  loss=0.00302 val_acc=0.765 both=0.588 one=0.354 gap=0.005 vehicle1=0.762 vehicle2=0.768 wrank=1.52 reg=0.0287 19s
softmin_d1_beta1p0 ep 042/150* loss=0.00292 val_acc=0.780 both=0.605 one=0.349 gap=0.014 vehicle1=0.773 vehicle2=0.787 wrank=1.51 reg=0.0268 20s
softmin_d1_beta1p0 ep 045/150* loss=0.00285 val_acc=0.791 both=0.623 one=0.337 gap=0.008 vehicle1=0.787 vehicle2=0.795 wrank=1.50 reg=0.0258 22s
softmin_d1_beta1p0 ep 050/150  loss=0.00270 val_acc=0.754 both=0.563 one=0.383 gap=0.017 vehicle1=0.746 vehicle2=0.763 wrank=1.54 reg=0.0303 24s
softmin_d1_beta1p0 ep 053/150* loss=0.00262 val_acc=0.794 both=0.632 one=0.325 gap=0.026 vehicle1=0.781 vehicle2=0.807 wrank=1.48 reg=0.0242 25s
softmin_d1_beta1p0 ep 055/150  loss=0.00261 val_acc=0.778 both=0.608 one=0.340 gap=0.006 vehicle1=0.775 vehicle2=0.781 wrank=1.49 reg=0.0274 26s
softmin_d1_beta1p0 ep 056/150* loss=0.00258 val_acc=0.799 both=0.635 one=0.328 gap=0.001 vehicle1=0.798 vehicle2=0.799 wrank=1.46 reg=0.0240 27s
softmin_d1_beta1p0 ep 060/150  loss=0.00248 val_acc=0.789 both=0.628 one=0.322 gap=0.010 vehicle1=0.784 vehicle2=0.794 wrank=1.46 reg=0.0259 29s
softmin_d1_beta1p0 ep 065/150  loss=0.00241 val_acc=0.773 both=0.602 one=0.342 gap=0.028 vehicle1=0.759 vehicle2=0.787 wrank=1.50 reg=0.0282 31s
softmin_d1_beta1p0 ep 067/150* loss=0.00238 val_acc=0.816 both=0.658 one=0.315 gap=0.009 vehicle1=0.811 vehicle2=0.820 wrank=1.42 reg=0.0222 32s
softmin_d1_beta1p0 ep 070/150  loss=0.00231 val_acc=0.787 both=0.626 one=0.322 gap=0.039 vehicle1=0.768 vehicle2=0.807 wrank=1.47 reg=0.0256 34s
softmin_d1_beta1p0 ep 075/150  loss=0.00223 val_acc=0.801 both=0.648 one=0.306 gap=0.032 vehicle1=0.785 vehicle2=0.817 wrank=1.45 reg=0.0246 36s
softmin_d1_beta1p0 ep 079/150* loss=0.00217 val_acc=0.825 both=0.682 one=0.287 gap=0.020 vehicle1=0.815 vehicle2=0.835 wrank=1.40 reg=0.0202 38s
softmin_d1_beta1p0 ep 080/150  loss=0.00214 val_acc=0.825 both=0.682 one=0.285 gap=0.016 vehicle1=0.817 vehicle2=0.832 wrank=1.40 reg=0.0208 38s
softmin_d1_beta1p0 ep 085/150* loss=0.00206 val_acc=0.828 both=0.682 one=0.292 gap=0.014 vehicle1=0.820 vehicle2=0.835 wrank=1.40 reg=0.0209 41s
softmin_d1_beta1p0 ep 087/150* loss=0.00206 val_acc=0.828 both=0.688 one=0.282 gap=0.020 vehicle1=0.818 vehicle2=0.838 wrank=1.38 reg=0.0202 42s
softmin_d1_beta1p0 ep 090/150  loss=0.00201 val_acc=0.817 both=0.672 one=0.291 gap=0.032 vehicle1=0.802 vehicle2=0.833 wrank=1.41 reg=0.0222 43s
softmin_d1_beta1p0 ep 092/150* loss=0.00201 val_acc=0.840 both=0.707 one=0.266 gap=0.028 vehicle1=0.826 vehicle2=0.854 wrank=1.35 reg=0.0185 44s
softmin_d1_beta1p0 ep 095/150  loss=0.00200 val_acc=0.831 both=0.693 one=0.275 gap=0.028 vehicle1=0.817 vehicle2=0.845 wrank=1.39 reg=0.0209 46s
softmin_d1_beta1p0 ep 100/150  loss=0.00192 val_acc=0.824 both=0.685 one=0.279 gap=0.033 vehicle1=0.808 vehicle2=0.841 wrank=1.39 reg=0.0213 48s
softmin_d1_beta1p0 ep 104/150* loss=0.00187 val_acc=0.854 both=0.735 one=0.238 gap=0.018 vehicle1=0.845 vehicle2=0.863 wrank=1.31 reg=0.0165 50s
softmin_d1_beta1p0 ep 105/150  loss=0.00186 val_acc=0.834 both=0.705 one=0.259 gap=0.001 vehicle1=0.835 vehicle2=0.834 wrank=1.35 reg=0.0196 50s
softmin_d1_beta1p0 ep 110/150  loss=0.00182 val_acc=0.834 both=0.704 one=0.260 gap=0.033 vehicle1=0.817 vehicle2=0.851 wrank=1.36 reg=0.0195 53s
softmin_d1_beta1p0 ep 115/150  loss=0.00178 val_acc=0.837 both=0.711 one=0.253 gap=0.026 vehicle1=0.824 vehicle2=0.851 wrank=1.33 reg=0.0200 55s
softmin_d1_beta1p0 ep 120/150  loss=0.00172 val_acc=0.835 both=0.712 one=0.248 gap=0.015 vehicle1=0.828 vehicle2=0.843 wrank=1.36 reg=0.0203 58s
softmin_d1_beta1p0 ep 125/150  loss=0.00169 val_acc=0.835 both=0.715 one=0.240 gap=0.003 vehicle1=0.833 vehicle2=0.836 wrank=1.34 reg=0.0201 60s
softmin_d1_beta1p0 ep 130/150  loss=0.00164 val_acc=0.842 both=0.723 one=0.238 gap=0.012 vehicle1=0.836 vehicle2=0.848 wrank=1.34 reg=0.0192 62s
softmin_d1_beta1p0 ep 135/150  loss=0.00165 val_acc=0.851 both=0.736 one=0.229 gap=0.012 vehicle1=0.845 vehicle2=0.857 wrank=1.32 reg=0.0174 65s
softmin_d1_beta1p0 ep 140/150  loss=0.00158 val_acc=0.846 both=0.725 one=0.243 gap=0.002 vehicle1=0.847 vehicle2=0.845 wrank=1.34 reg=0.0184 67s
softmin_d1_beta1p0 ep 141/150* loss=0.00159 val_acc=0.861 both=0.749 one=0.223 gap=0.003 vehicle1=0.860 vehicle2=0.863 wrank=1.30 reg=0.0158 68s
softmin_d1_beta1p0 ep 142/150* loss=0.00158 val_acc=0.863 both=0.752 one=0.221 gap=0.004 vehicle1=0.861 vehicle2=0.865 wrank=1.30 reg=0.0169 68s
softmin_d1_beta1p0 ep 145/150  loss=0.00154 val_acc=0.856 both=0.741 one=0.230 gap=0.013 vehicle1=0.850 vehicle2=0.863 wrank=1.32 reg=0.0171 70s
softmin_d1_beta1p0 ep 150/150  loss=0.00154 val_acc=0.843 both=0.729 one=0.229 gap=0.020 vehicle1=0.833 vehicle2=0.854 wrank=1.33 reg=0.0194 72s

=== softmin_d1_beta5p0 === Smooth min over per-vehicle d1 utilities with beta=5.0.
softmin_d1_beta5p0 ep 001/150* loss=0.04217 val_acc=0.601 both=0.326 one=0.550 gap=0.022 vehicle1=0.612 vehicle2=0.590 wrank=2.30 reg=0.0678 0s
softmin_d1_beta5p0 ep 002/150* loss=0.01223 val_acc=0.651 both=0.398 one=0.505 gap=0.070 vehicle1=0.686 vehicle2=0.616 wrank=1.96 reg=0.0546 1s
softmin_d1_beta5p0 ep 004/150* loss=0.00809 val_acc=0.661 both=0.454 one=0.414 gap=0.011 vehicle1=0.666 vehicle2=0.656 wrank=1.75 reg=0.0453 2s
softmin_d1_beta5p0 ep 005/150* loss=0.00744 val_acc=0.682 both=0.489 one=0.385 gap=0.002 vehicle1=0.682 vehicle2=0.681 wrank=1.65 reg=0.0408 2s
softmin_d1_beta5p0 ep 006/150* loss=0.00692 val_acc=0.711 both=0.531 one=0.360 gap=0.005 vehicle1=0.708 vehicle2=0.713 wrank=1.61 reg=0.0366 3s
softmin_d1_beta5p0 ep 007/150* loss=0.00652 val_acc=0.719 both=0.546 one=0.347 gap=0.008 vehicle1=0.715 vehicle2=0.723 wrank=1.57 reg=0.0357 3s
softmin_d1_beta5p0 ep 010/150  loss=0.00578 val_acc=0.689 both=0.503 one=0.372 gap=0.055 vehicle1=0.661 vehicle2=0.716 wrank=1.61 reg=0.0400 5s
softmin_d1_beta5p0 ep 011/150* loss=0.00564 val_acc=0.721 both=0.546 one=0.349 gap=0.032 vehicle1=0.705 vehicle2=0.737 wrank=1.54 reg=0.0361 5s
softmin_d1_beta5p0 ep 015/150  loss=0.00516 val_acc=0.714 both=0.526 one=0.377 gap=0.034 vehicle1=0.697 vehicle2=0.731 wrank=1.61 reg=0.0384 7s
softmin_d1_beta5p0 ep 016/150* loss=0.00503 val_acc=0.725 both=0.534 one=0.381 gap=0.016 vehicle1=0.717 vehicle2=0.733 wrank=1.62 reg=0.0389 8s
softmin_d1_beta5p0 ep 019/150* loss=0.00482 val_acc=0.729 both=0.537 one=0.384 gap=0.004 vehicle1=0.728 vehicle2=0.731 wrank=1.63 reg=0.0389 9s
softmin_d1_beta5p0 ep 020/150* loss=0.00472 val_acc=0.734 both=0.546 one=0.377 gap=0.012 vehicle1=0.728 vehicle2=0.740 wrank=1.62 reg=0.0382 10s
softmin_d1_beta5p0 ep 022/150* loss=0.00457 val_acc=0.738 both=0.548 one=0.381 gap=0.014 vehicle1=0.731 vehicle2=0.746 wrank=1.61 reg=0.0370 11s
softmin_d1_beta5p0 ep 023/150* loss=0.00453 val_acc=0.749 both=0.568 one=0.362 gap=0.008 vehicle1=0.745 vehicle2=0.753 wrank=1.56 reg=0.0344 11s
softmin_d1_beta5p0 ep 025/150* loss=0.00444 val_acc=0.753 both=0.565 one=0.376 gap=0.014 vehicle1=0.746 vehicle2=0.760 wrank=1.59 reg=0.0350 12s
softmin_d1_beta5p0 ep 027/150* loss=0.00428 val_acc=0.762 both=0.581 one=0.362 gap=0.017 vehicle1=0.754 vehicle2=0.771 wrank=1.55 reg=0.0326 13s
softmin_d1_beta5p0 ep 030/150* loss=0.00417 val_acc=0.766 both=0.582 one=0.369 gap=0.029 vehicle1=0.752 vehicle2=0.781 wrank=1.55 reg=0.0315 14s
softmin_d1_beta5p0 ep 031/150* loss=0.00408 val_acc=0.798 both=0.626 one=0.345 gap=0.040 vehicle1=0.778 vehicle2=0.818 wrank=1.49 reg=0.0277 15s
softmin_d1_beta5p0 ep 035/150  loss=0.00391 val_acc=0.791 both=0.616 one=0.350 gap=0.030 vehicle1=0.776 vehicle2=0.806 wrank=1.48 reg=0.0293 17s
softmin_d1_beta5p0 ep 036/150* loss=0.00387 val_acc=0.803 both=0.629 one=0.346 gap=0.073 vehicle1=0.766 vehicle2=0.839 wrank=1.49 reg=0.0275 17s
softmin_d1_beta5p0 ep 040/150  loss=0.00376 val_acc=0.786 both=0.611 one=0.351 gap=0.057 vehicle1=0.758 vehicle2=0.814 wrank=1.48 reg=0.0290 19s
softmin_d1_beta5p0 ep 045/150  loss=0.00356 val_acc=0.773 both=0.593 one=0.360 gap=0.049 vehicle1=0.749 vehicle2=0.798 wrank=1.51 reg=0.0321 22s
softmin_d1_beta5p0 ep 050/150  loss=0.00337 val_acc=0.794 both=0.620 one=0.348 gap=0.057 vehicle1=0.766 vehicle2=0.823 wrank=1.43 reg=0.0267 24s
softmin_d1_beta5p0 ep 053/150* loss=0.00329 val_acc=0.813 both=0.651 one=0.324 gap=0.057 vehicle1=0.785 vehicle2=0.842 wrank=1.41 reg=0.0250 26s
softmin_d1_beta5p0 ep 055/150  loss=0.00326 val_acc=0.776 both=0.600 one=0.352 gap=0.069 vehicle1=0.741 vehicle2=0.811 wrank=1.49 reg=0.0310 26s
softmin_d1_beta5p0 ep 060/150* loss=0.00310 val_acc=0.817 both=0.668 one=0.299 gap=0.050 vehicle1=0.792 vehicle2=0.842 wrank=1.39 reg=0.0244 29s
softmin_d1_beta5p0 ep 065/150  loss=0.00301 val_acc=0.780 both=0.614 one=0.332 gap=0.069 vehicle1=0.745 vehicle2=0.814 wrank=1.45 reg=0.0299 31s
softmin_d1_beta5p0 ep 067/150* loss=0.00298 val_acc=0.820 both=0.670 one=0.300 gap=0.042 vehicle1=0.799 vehicle2=0.842 wrank=1.40 reg=0.0239 32s
softmin_d1_beta5p0 ep 070/150  loss=0.00289 val_acc=0.776 both=0.605 one=0.342 gap=0.040 vehicle1=0.756 vehicle2=0.796 wrank=1.47 reg=0.0306 34s
softmin_d1_beta5p0 ep 071/150* loss=0.00291 val_acc=0.827 both=0.686 one=0.282 gap=0.066 vehicle1=0.794 vehicle2=0.860 wrank=1.38 reg=0.0225 34s
softmin_d1_beta5p0 ep 075/150  loss=0.00279 val_acc=0.795 both=0.635 one=0.320 gap=0.048 vehicle1=0.771 vehicle2=0.819 wrank=1.43 reg=0.0275 36s
softmin_d1_beta5p0 ep 079/150* loss=0.00273 val_acc=0.832 both=0.690 one=0.285 gap=0.050 vehicle1=0.808 vehicle2=0.857 wrank=1.38 reg=0.0221 38s
softmin_d1_beta5p0 ep 080/150* loss=0.00271 val_acc=0.841 both=0.711 one=0.260 gap=0.053 vehicle1=0.814 vehicle2=0.867 wrank=1.36 reg=0.0206 39s
softmin_d1_beta5p0 ep 085/150  loss=0.00261 val_acc=0.823 both=0.677 one=0.292 gap=0.007 vehicle1=0.820 vehicle2=0.826 wrank=1.38 reg=0.0245 41s
softmin_d1_beta5p0 ep 086/150* loss=0.00261 val_acc=0.845 both=0.710 one=0.269 gap=0.029 vehicle1=0.830 vehicle2=0.859 wrank=1.33 reg=0.0197 41s

,utility,best_epoch,val_contains_closest_fraction,val_contains_closest_all,val_dominance_gap,test_contains_closest_fraction,test_contains_closest_all,test_one_closest_rate,test_neither_closest_rate,test_dominance_gap,test_contains_vehicle1,test_contains_vehicle2,test_mean_worst_vehicle_rank,test_mean_abs_vehicle_rank_gap,test_avg_regret
0,softmin_d1_beta5p0,111,0.873585,0.760000,0.044528,0.869057,0.753208,0.231698,0.015094,0.000755,0.869434,0.868679,1.282264,0.267170,0.018317
1,softmin_d1_beta100p0,129,0.869057,0.755472,0.041509,0.838491,0.704906,0.267170,0.027925,0.031698,0.854340,0.822641,1.359245,0.329811,0.024283
2,softmin_d1_beta1p0,142,0.863019,0.752453,0.003774,0.832830,0.711698,0.242264,0.046038,0.015849,0.840755,0.824906,1.329057,0.275472,0.018519
3,softmin_d1_beta20p0,129,0.847547,0.727547,0.018113,0.831698,0.704906,0.253585,0.041509,0.025660,0.844528,0.818868,1.378113,0.329057,0.025630
4,softmin_d1_beta0p1,150,0.859245,0.750943,0.023396,0.817736,0.686038,0.263396,0.050566,0.006792,0.821132,0.814340,1.363774,0.301887,0.020654

In [9]:
# Train the clean softmin d1 utility on all subsets of size <= 5.
# This keeps the optimized dense time x action training path; <=5 gives 637 static actions for 10 nodes.
from pathlib import Path
import sys

PROJECT_ROOT = Path.cwd()
if PROJECT_ROOT.name == "notebooks":
    PROJECT_ROOT = PROJECT_ROOT.parent

SCRIPTS_DIR = PROJECT_ROOT / "scripts"
if str(SCRIPTS_DIR) not in sys.path:
    sys.path.insert(0, str(SCRIPTS_DIR))

import importlib
import multi_vehicle_utility_search as mv_utils

mv_utils = importlib.reload(mv_utils)
from multi_vehicle_utility_search import build_eq5_rssi_static_examples, run_rssi_utility_search

LEQ5_PREFIX = "m02_multi_vehicle_leq5_rssi_static"
LEQ5_REQUIRED = [
    PROJECT_ROOT / "data" / "processed" / f"{LEQ5_PREFIX}_arrays.npz",
    PROJECT_ROOT / "data" / "processed" / f"{LEQ5_PREFIX}_examples_index.csv",
    PROJECT_ROOT / "data" / "processed" / f"{LEQ5_PREFIX}_meta.json",
]

if all(path.exists() for path in LEQ5_REQUIRED):
    print(f"Using existing processed artifact: {LEQ5_PREFIX}")
else:
    leq5_summary_df, leq5_paths_df = build_eq5_rssi_static_examples(
        PROJECT_ROOT,
        prefix=LEQ5_PREFIX,
        exact_subset_size=5,
        subset_size_policy="leq",
    )
    display(leq5_summary_df)
    display(leq5_paths_df)

LEQ5_SOFTMIN_BETA5 = [
    {
        "name": "softmin_d1_beta5",
        "column": "derived_softmin_d1_beta5",
        "description": "Smooth min over per-vehicle d1 utilities with beta=5, trained over all subset sizes <= 5.",
        "kind": "softmin_d1",
        "beta": 5.0,
    }
]

leq5_softmin_summary_df, leq5_softmin_results = run_rssi_utility_search(
    PROJECT_ROOT,
    prefix=LEQ5_PREFIX,
    model_tag="multi_vehicle_rssi_softmin_d1_beta5_leq5_150ep",
    max_epochs=150,
    patience=150,
    log_every=5,
    batch_size=8192,
    time_batch_size=256,
    utility_candidates=LEQ5_SOFTMIN_BETA5,
)

vehicle_cols = [col for col in leq5_softmin_summary_df.columns if col.startswith("test_contains_vehicle")]
display_cols = [
    "utility",
    "best_epoch",
    "val_contains_closest_fraction",
    "val_contains_closest_all",
    "val_dominance_gap",
    "test_contains_closest_fraction",
    "test_contains_closest_all",
    "test_one_closest_rate",
    "test_neither_closest_rate",
    "test_dominance_gap",
    *vehicle_cols,
    "test_mean_worst_vehicle_rank",
    "test_mean_abs_vehicle_rank_gap",
    "test_avg_regret",
]
display(leq5_softmin_summary_df[[col for col in display_cols if col in leq5_softmin_summary_df.columns]])

Interim source: d:\2023-2028_UCLA_Research_Projects\IoBT\17-5-26-MILCOMAttempt\data\interim\20250815_0900_multi_vehicle
valid timestamps=6625, nodes=10, vehicles=['vehicle1', 'vehicle2'], subset sizes <= 5
rho=10.222 m
Saved processed artifact: m02_multi_vehicle_leq5_rssi_static
Elapsed: 2.0 min

,prefix,times,actions_per_time,examples,context_dim,action_dim,mean_contains_fraction_all_actions,both_rate_all_actions,elapsed_min
0,m02_multi_vehicle_leq5_rssi_static,6625,637,4220125,30,21,0.401884,0.167433,2.008007

              artifact                                               path
0           arrays_npz  d:\2023-2028_UCLA_Research_Projects\IoBT\17-5-...
1   examples_index_csv  d:\2023-2028_UCLA_Research_Projects\IoBT\17-5-...
2     feature_wide_csv  d:\2023-2028_UCLA_Research_Projects\IoBT\17-5-...
3  sensor_geometry_csv  d:\2023-2028_UCLA_Research_Projects\IoBT\17-5-...
4            meta_json  d:\2023-2028_UCLA_Research_Projects\IoBT\17-5-...

Building dense train cache from m02_multi_vehicle_leq5_rssi_static_examples_index.csv ...
Saved dense train cache: d:\2023-2028_UCLA_Research_Projects\IoBT\17-5-26-MILCOMAttempt\data\processed\m02_multi_vehicle_leq5_rssi_static_dense_train_cache.npz
PROJECT_ROOT: d:\2023-2028_UCLA_Research_Projects\IoBT\17-5-26-MILCOMAttempt
DEVICE: cuda
data: times=6625, actions/time=637, examples=4,220,125, context_dim=30, action_dim=21
dense cache: d:\2023-2028_UCLA_Research_Projects\IoBT\17-5-26-MILCOMAttempt\data\processed\m02_multi_vehicle_leq5_rssi_static_dense_train_cache.npz
utilities: ['softmin_d1_beta5']

=== softmin_d1_beta5 === Smooth min over per-vehicle d1 utilities with beta=5, trained over all subset sizes <= 5.
softmin_d1_beta5 ep 001/150* loss=0.03755 val_acc=0.587 both=0.313 one=0.547 gap=0.038 vehicle1=0.568 vehicle2=0.606 wrank=2.35 reg=0.0738 2s
softmin_d1_beta5 ep 002/150* loss=0.01169 val_acc=0.640 both=0.395 one=0.491 gap=0.082 vehicle1=0.682 vehicle2=0.599 wrank=2.02 reg=0.0553 3s
softmin_d1_beta5 ep 003/150* loss=0.00889 val_acc=0.684 both=0.481 one=0.407 gap=0.019 vehicle1=0.694 vehicle2=0.675 wrank=1.75 reg=0.0426 4s
softmin_d1_beta5 ep 005/150  loss=0.00711 val_acc=0.668 both=0.444 one=0.449 gap=0.001 vehicle1=0.669 vehicle2=0.668 wrank=1.75 reg=0.0462 6s
softmin_d1_beta5 ep 006/150* loss=0.00661 val_acc=0.689 both=0.468 one=0.442 gap=0.001 vehicle1=0.689 vehicle2=0.688 wrank=1.72 reg=0.0436 7s
softmin_d1_beta5 ep 007/150* loss=0.00625 val_acc=0.689 both=0.474 one=0.429 gap=0.020 vehicle1=0.678 vehicle2=0.699 wrank=1.73 reg=0.0429 8s
softmin_d1_beta5 ep 008/150* loss=0.00600 val_acc=0.703 both=0.493 one=0.421 gap=0.041 vehicle1=0.683 vehicle2=0.724 wrank=1.69 reg=0.0402 9s
softmin_d1_beta5 ep 009/150* loss=0.00575 val_acc=0.734 both=0.525 one=0.417 gap=0.056 vehicle1=0.706 vehicle2=0.762 wrank=1.64 reg=0.0362 10s
softmin_d1_beta5 ep 010/150  loss=0.00560 val_acc=0.731 both=0.517 one=0.429 gap=0.048 vehicle1=0.707 vehicle2=0.755 wrank=1.66 reg=0.0379 11s
softmin_d1_beta5 ep 012/150* loss=0.00530 val_acc=0.738 both=0.537 one=0.401 gap=0.061 vehicle1=0.707 vehicle2=0.768 wrank=1.62 reg=0.0368 13s
softmin_d1_beta5 ep 015/150* loss=0.00494 val_acc=0.754 both=0.574 one=0.361 gap=0.039 vehicle1=0.734 vehicle2=0.774 wrank=1.54 reg=0.0336 16s
softmin_d1_beta5 ep 020/150  loss=0.00451 val_acc=0.734 both=0.543 one=0.380 gap=0.038 vehicle1=0.715 vehicle2=0.752 wrank=1.59 reg=0.0372 21s
softmin_d1_beta5 ep 025/150  loss=0.00418 val_acc=0.715 both=0.511 one=0.408 gap=0.026 vehicle1=0.702 vehicle2=0.728 wrank=1.64 reg=0.0411 26s
softmin_d1_beta5 ep 030/150  loss=0.00395 val_acc=0.707 both=0.499 one=0.416 gap=0.013 vehicle1=0.700 vehicle2=0.713 wrank=1.69 reg=0.0424 31s
softmin_d1_beta5 ep 035/150  loss=0.00372 val_acc=0.707 both=0.504 one=0.405 gap=0.032 vehicle1=0.691 vehicle2=0.723 wrank=1.70 reg=0.0436 36s
softmin_d1_beta5 ep 040/150  loss=0.00355 val_acc=0.708 both=0.514 one=0.388 gap=0.036 vehicle1=0.690 vehicle2=0.726 wrank=1.68 reg=0.0424 41s
softmin_d1_beta5 ep 045/150  loss=0.00332 val_acc=0.708 both=0.510 one=0.396 gap=0.028 vehicle1=0.694 vehicle2=0.722 wrank=1.70 reg=0.0428 46s
softmin_d1_beta5 ep 050/150  loss=0.00320 val_acc=0.705 both=0.503 one=0.403 gap=0.026 vehicle1=0.692 vehicle2=0.718 wrank=1.69 reg=0.0436 52s
softmin_d1_beta5 ep 055/150  loss=0.00306 val_acc=0.715 both=0.516 one=0.397 gap=0.020 vehicle1=0.705 vehicle2=0.725 wrank=1.66 reg=0.0421 57s
softmin_d1_beta5 ep 060/150  loss=0.00292 val_acc=0.708 both=0.505 one=0.406 gap=0.014 vehicle1=0.701 vehicle2=0.715 wrank=1.67 reg=0.0433 62s
softmin_d1_beta5 ep 065/150  loss=0.00281 val_acc=0.711 both=0.511 one=0.399 gap=0.010 vehicle1=0.706 vehicle2=0.715 wrank=1.66 reg=0.0430 67s
softmin_d1_beta5 ep 070/150  loss=0.00271 val_acc=0.700 both=0.497 one=0.405 gap=0.029 vehicle1=0.685 vehicle2=0.714 wrank=1.68 reg=0.0441 72s
softmin_d1_beta5 ep 075/150  loss=0.00260 val_acc=0.715 both=0.522 one=0.386 gap=0.033 vehicle1=0.699 vehicle2=0.732 wrank=1.63 reg=0.0418 77s
softmin_d1_beta5 ep 080/150  loss=0.00251 val_acc=0.720 both=0.528 one=0.383 gap=0.035 vehicle1=0.703 vehicle2=0.737 wrank=1.62 reg=0.0410 82s
softmin_d1_beta5 ep 085/150  loss=0.00249 val_acc=0.725 both=0.537 one=0.377 gap=0.019 vehicle1=0.715 vehicle2=0.734 wrank=1.63 reg=0.0401 88s
softmin_d1_beta5 ep 090/150  loss=0.00237 val_acc=0.716 both=0.529 one=0.374 gap=0.044 vehicle1=0.694 vehicle2=0.738 wrank=1.64 reg=0.0413 93s
softmin_d1_beta5 ep 095/150  loss=0.00234 val_acc=0.726 both=0.536 one=0.380 gap=0.041 vehicle1=0.706 vehicle2=0.746 wrank=1.61 reg=0.0396 98s
softmin_d1_beta5 ep 100/150  loss=0.00223 val_acc=0.734 both=0.541 one=0.385 gap=0.045 vehicle1=0.711 vehicle2=0.756 wrank=1.61 reg=0.0389 103s
softmin_d1_beta5 ep 105/150  loss=0.00216 val_acc=0.745 both=0.563 one=0.364 gap=0.032 vehicle1=0.729 vehicle2=0.761 wrank=1.58 reg=0.0377 108s
softmin_d1_beta5 ep 110/150  loss=0.00211 val_acc=0.743 both=0.559 one=0.368 gap=0.042 vehicle1=0.722 vehicle2=0.764 wrank=1.60 reg=0.0373 114s
softmin_d1_beta5 ep 115/150  loss=0.00208 val_acc=0.729 both=0.538 one=0.383 gap=0.052 vehicle1=0.703 vehicle2=0.755 wrank=1.62 reg=0.0401 119s
softmin_d1_beta5 ep 117/150* loss=0.00205 val_acc=0.757 both=0.574 one=0.365 gap=0.021 vehicle1=0.746 vehicle2=0.768 wrank=1.57 reg=0.0359 121s
softmin_d1_beta5 ep 120/150  loss=0.00202 val_acc=0.734 both=0.552 one=0.364 gap=0.047 vehicle1=0.710 vehicle2=0.757 wrank=1.62 reg=0.0393 124s
softmin_d1_beta5 ep 125/150  loss=0.00197 val_acc=0.748 both=0.568 one=0.361 gap=0.035 vehicle1=0.731 vehicle2=0.765 wrank=1.58 reg=0.0370 129s
softmin_d1_beta5 ep 130/150  loss=0.00191 val_acc=0.742 both=0.562 one=0.360 gap=0.032 vehicle1=0.725 vehicle2=0.758 wrank=1.61 reg=0.0381 134s
softmin_d1_beta5 ep 135/150  loss=0.00190 val_acc=0.741 both=0.568 one=0.347 gap=0.029 vehicle1=0.727 vehicle2=0.755 wrank=1.58 reg=0.0382 140s
softmin_d1_beta5 ep 140/150  loss=0.00183 val_acc=0.745 both=0.568 one=0.354 gap=0.014 vehicle1=0.737 vehicle2=0.752 wrank=1.58 reg=0.0375 145s
softmin_d1_beta5 ep 145/150  loss=0.00180 val_acc=0.756 both=0.589 one=0.334 gap=0.025 vehicle1=0.743 vehicle2=0.768 wrank=1.57 reg=0.0360 150s
softmin_d1_beta5 ep 150/150  loss=0.00176 val_acc=0.728 both=0.549 one=0.358 gap=0.042 vehicle1=0.706 vehicle2=0.749 wrank=1.61 reg=0.0393 155s
Saved histories/metrics to d:\2023-2028_UCLA_Research_Projects\IoBT\17-5-26-MILCOMAttempt\reports\tables\multi_vehicle_rssi_softmin_d1_beta5_leq5_150ep

,utility,best_epoch,val_contains_closest_fraction,val_contains_closest_all,val_dominance_gap,test_contains_closest_fraction,test_contains_closest_all,test_one_closest_rate,test_neither_closest_rate,test_dominance_gap,test_contains_vehicle1,test_contains_vehicle2,test_mean_worst_vehicle_rank,test_mean_abs_vehicle_rank_gap,test_avg_regret
0,softmin_d1_beta5,117,0.756981,0.57434,0.021132,0.77283,0.621887,0.301887,0.076226,0.021132,0.762264,0.783396,1.535094,0.447547,0.034111

In [10]:
# Softmin over full per-vehicle 5-rank utilities, trained for both ==5 and <=5 action sets.
# Per vehicle: u_v = sum_j w_j / (1 + d_j/rho), then U = softmin_beta(u_1, u_2).
from pathlib import Path
import sys
import pandas as pd

PROJECT_ROOT = Path.cwd()
if PROJECT_ROOT.name == "notebooks":
    PROJECT_ROOT = PROJECT_ROOT.parent

SCRIPTS_DIR = PROJECT_ROOT / "scripts"
if str(SCRIPTS_DIR) not in sys.path:
    sys.path.insert(0, str(SCRIPTS_DIR))

import importlib
import multi_vehicle_utility_search as mv_utils

mv_utils = importlib.reload(mv_utils)
from multi_vehicle_utility_search import build_eq5_rssi_static_examples, run_rssi_utility_search

FULL5_WEIGHTS = [1.00, 0.45, 0.20, 0.10, 0.05]
FULL5_SOFTMIN_BETA5 = [
    {
        "name": "softmin_full5_beta5_w100_045_020_010_005",
        "column": "derived_softmin_full5_beta5_w100_045_020_010_005",
        "description": "softmin_beta5 over per-vehicle weighted rank utilities with weights [1,.45,.20,.10,.05].",
        "kind": "softmin_rank_weighted",
        "beta": 5.0,
        "weights": FULL5_WEIGHTS,
    }
]

FULL5_JOBS = [
    {
        "label": "eq5",
        "prefix": "m02_multi_vehicle_eq5_rssi_static_full5ranks",
        "subset_size_policy": "exact",
        "model_tag": "multi_vehicle_rssi_softmin_full5_eq5_150ep",
        "time_batch_size": 256,
    },
    {
        "label": "leq5",
        "prefix": "m02_multi_vehicle_leq5_rssi_static_full5ranks",
        "subset_size_policy": "leq",
        "model_tag": "multi_vehicle_rssi_softmin_full5_leq5_150ep",
        "time_batch_size": 128,
    },
]

full5_summaries = []
full5_results = {}
for job in FULL5_JOBS:
    prefix = job["prefix"]
    required = [
        PROJECT_ROOT / "data" / "processed" / f"{prefix}_arrays.npz",
        PROJECT_ROOT / "data" / "processed" / f"{prefix}_examples_index.csv",
        PROJECT_ROOT / "data" / "processed" / f"{prefix}_meta.json",
    ]
    if all(path.exists() for path in required):
        print(f"Using existing processed artifact: {prefix}")
    else:
        artifact_summary_df, artifact_paths_df = build_eq5_rssi_static_examples(
            PROJECT_ROOT,
            prefix=prefix,
            exact_subset_size=5,
            subset_size_policy=job["subset_size_policy"],
        )
        display(artifact_summary_df)
        display(artifact_paths_df)

    summary_df, results = run_rssi_utility_search(
        PROJECT_ROOT,
        prefix=prefix,
        model_tag=job["model_tag"],
        max_epochs=150,
        patience=150,
        log_every=5,
        batch_size=8192,
        time_batch_size=job["time_batch_size"],
        utility_candidates=FULL5_SOFTMIN_BETA5,
    )
    summary_df = summary_df.copy()
    summary_df.insert(0, "action_set", job["label"])
    full5_summaries.append(summary_df)
    full5_results[job["label"]] = results

full5_summary_df = pd.concat(full5_summaries, ignore_index=True)
vehicle_cols = [col for col in full5_summary_df.columns if col.startswith("test_contains_vehicle")]
display_cols = [
    "action_set",
    "utility",
    "best_epoch",
    "val_contains_closest_fraction",
    "val_contains_closest_all",
    "val_dominance_gap",
    "test_contains_closest_fraction",
    "test_contains_closest_all",
    "test_one_closest_rate",
    "test_neither_closest_rate",
    "test_dominance_gap",
    *vehicle_cols,
    "test_mean_worst_vehicle_rank",
    "test_mean_abs_vehicle_rank_gap",
    "test_avg_regret",
]
display(full5_summary_df[[col for col in display_cols if col in full5_summary_df.columns]])

Interim source: d:\2023-2028_UCLA_Research_Projects\IoBT\17-5-26-MILCOMAttempt\data\interim\20250815_0900_multi_vehicle
valid timestamps=6625, nodes=10, vehicles=['vehicle1', 'vehicle2'], exact subset size=5
rho=10.222 m
Saved processed artifact: m02_multi_vehicle_eq5_rssi_static_full5ranks
Elapsed: 0.9 min

,prefix,times,actions_per_time,examples,context_dim,action_dim,mean_contains_fraction_all_actions,both_rate_all_actions,elapsed_min
0,m02_multi_vehicle_eq5_rssi_static_full5ranks,6625,252,1669500,30,21,0.5,0.245493,0.865493

              artifact                                               path
0           arrays_npz  d:\2023-2028_UCLA_Research_Projects\IoBT\17-5-...
1   examples_index_csv  d:\2023-2028_UCLA_Research_Projects\IoBT\17-5-...
2     feature_wide_csv  d:\2023-2028_UCLA_Research_Projects\IoBT\17-5-...
3  sensor_geometry_csv  d:\2023-2028_UCLA_Research_Projects\IoBT\17-5-...
4            meta_json  d:\2023-2028_UCLA_Research_Projects\IoBT\17-5-...

Building dense train cache from m02_multi_vehicle_eq5_rssi_static_full5ranks_examples_index.csv ...
Saved dense train cache: d:\2023-2028_UCLA_Research_Projects\IoBT\17-5-26-MILCOMAttempt\data\processed\m02_multi_vehicle_eq5_rssi_static_full5ranks_dense_train_cache.npz
PROJECT_ROOT: d:\2023-2028_UCLA_Research_Projects\IoBT\17-5-26-MILCOMAttempt
DEVICE: cuda
data: times=6625, actions/time=252, examples=1,669,500, context_dim=30, action_dim=21
dense cache: d:\2023-2028_UCLA_Research_Projects\IoBT\17-5-26-MILCOMAttempt\data\processed\m02_multi_vehicle_eq5_rssi_static_full5ranks_dense_train_cache.npz
utilities: ['softmin_full5_beta5_w100_045_020_010_005']

=== softmin_full5_beta5_w100_045_020_010_005 === softmin_beta5 over per-vehicle weighted rank utilities with weights [1,.45,.20,.10,.05].
softmin_full5_beta5_w100_045_020_010_005 ep 001/150* loss=0.09535 val_acc=0.600 both=0.330 one=0.541 gap=0.002 vehicle1=0.602 vehicle2=0.599 wrank=2.28 reg=0.1087 1s
softmin_full5_beta5_w100_045_020_010_005 ep 002/150* loss=0.02220 val_acc=0.600 both=0.336 one=0.529 gap=0.048 vehicle1=0.577 vehicle2=0.624 wrank=2.22 reg=0.1034 1s
softmin_full5_beta5_w100_045_020_010_005 ep 003/150* loss=0.01629 val_acc=0.625 both=0.414 one=0.420 gap=0.007 vehicle1=0.628 vehicle2=0.621 wrank=1.89 reg=0.0805 2s
softmin_full5_beta5_w100_045_020_010_005 ep 004/150* loss=0.01408 val_acc=0.629 both=0.408 one=0.443 gap=0.002 vehicle1=0.628 vehicle2=0.630 wrank=1.79 reg=0.0766 2s
softmin_full5_beta5_w100_045_020_010_005 ep 005/150* loss=0.01303 val_acc=0.648 both=0.429 one=0.437 gap=0.010 vehicle1=0.653 vehicle2=0.643 wrank=1.74 reg=0.0734 3s
softmin_full5_beta5_w100_045_020_010_005 ep 006/150* loss=0.01229 val_acc=0.668 both=0.463 one=0.409 gap=0.012 vehicle1=0.662 vehicle2=0.674 wrank=1.72 reg=0.0705 3s
softmin_full5_beta5_w100_045_020_010_005 ep 007/150* loss=0.01166 val_acc=0.683 both=0.497 one=0.371 gap=0.020 vehicle1=0.672 vehicle2=0.693 wrank=1.68 reg=0.0671 4s
softmin_full5_beta5_w100_045_020_010_005 ep 008/150* loss=0.01116 val_acc=0.694 both=0.512 one=0.365 gap=0.013 vehicle1=0.688 vehicle2=0.700 wrank=1.65 reg=0.0650 4s
softmin_full5_beta5_w100_045_020_010_005 ep 009/150* loss=0.01056 val_acc=0.706 both=0.518 one=0.374 gap=0.006 vehicle1=0.703 vehicle2=0.709 wrank=1.65 reg=0.0648 5s
softmin_full5_beta5_w100_045_020_010_005 ep 010/150* loss=0.01020 val_acc=0.707 both=0.514 one=0.386 gap=0.007 vehicle1=0.703 vehicle2=0.710 wrank=1.66 reg=0.0661 5s
softmin_full5_beta5_w100_045_020_010_005 ep 011/150* loss=0.00984 val_acc=0.734 both=0.548 one=0.373 gap=0.023 vehicle1=0.723 vehicle2=0.746 wrank=1.60 reg=0.0612 6s
softmin_full5_beta5_w100_045_020_010_005 ep 012/150* loss=0.00963 val_acc=0.735 both=0.540 one=0.390 gap=0.035 vehicle1=0.717 vehicle2=0.752 wrank=1.62 reg=0.0617 6s
softmin_full5_beta5_w100_045_020_010_005 ep 013/150* loss=0.00942 val_acc=0.760 both=0.580 one=0.358 gap=0.031 vehicle1=0.744 vehicle2=0.775 wrank=1.53 reg=0.0558 7s
softmin_full5_beta5_w100_045_020_010_005 ep 014/150* loss=0.00923 val_acc=0.763 both=0.570 one=0.387 gap=0.038 vehicle1=0.744 vehicle2=0.783 wrank=1.56 reg=0.0566 7s
softmin_full5_beta5_w100_045_020_010_005 ep 015/150* loss=0.00894 val_acc=0.768 both=0.582 one=0.371 gap=0.027 vehicle1=0.754 vehicle2=0.781 wrank=1.55 reg=0.0547 8s
softmin_full5_beta5_w100_045_020_010_005 ep 020/150* loss=0.00812 val_acc=0.770 both=0.593 one=0.353 gap=0.021 vehicle1=0.759 vehicle2=0.780 wrank=1.53 reg=0.0559 10s
softmin_full5_beta5_w100_045_020_010_005 ep 021/150* loss=0.00809 val_acc=0.775 both=0.585 one=0.381 gap=0.025 vehicle1=0.763 vehicle2=0.788 wrank=1.56 reg=0.0562 10s
softmin_full5_beta5_w100_045_020_010_005 ep 022/150* loss=0.00782 val_acc=0.781 both=0.602 one=0.358 gap=0.025 vehicle1=0.768 vehicle2=0.793 wrank=1.50 reg=0.0540 11s
softmin_full5_beta5_w100_045_020_010_005 ep 023/150* loss=0.00782 val_acc=0.786 both=0.610 one=0.352 gap=0.022 vehicle1=0.775 vehicle2=0.797 wrank=1.50 reg=0.0528 11s
softmin_full5_beta5_w100_045_020_010_005 ep 025/150  loss=0.00763 val_acc=0.780 both=0.599 one=0.362 gap=0.010 vehicle1=0.775 vehicle2=0.785 wrank=1.51 reg=0.0542 12s
softmin_full5_beta5_w100_045_020_010_005 ep 026/150* loss=0.00750 val_acc=0.792 both=0.616 one=0.352 gap=0.003 vehicle1=0.790 vehicle2=0.793 wrank=1.48 reg=0.0516 13s
softmin_full5_beta5_w100_045_020_010_005 ep 028/150* loss=0.00733 val_acc=0.793 both=0.613 one=0.361 gap=0.005 vehicle1=0.791 vehicle2=0.795 wrank=1.48 reg=0.0517 14s
softmin_full5_beta5_w100_045_020_010_005 ep 030/150* loss=0.00710 val_acc=0.797 both=0.625 one=0.344 gap=0.005 vehicle1=0.795 vehicle2=0.799 wrank=1.45 reg=0.0511 15s
softmin_full5_beta5_w100_045_020_010_005 ep 031/150* loss=0.00693 val_acc=0.803 both=0.626 one=0.355 gap=0.031 vehicle1=0.788 vehicle2=0.819 wrank=1.46 reg=0.0503 15s
softmin_full5_beta5_w100_045_020_010_005 ep 033/150* loss=0.00699 val_acc=0.804 both=0.629 one=0.351 gap=0.043 vehicle1=0.783 vehicle2=0.826 wrank=1.47 reg=0.0500 16s
softmin_full5_beta5_w100_045_020_010_005 ep 035/150* loss=0.00661 val_acc=0.806 both=0.641 one=0.331 gap=0.031 vehicle1=0.791 vehicle2=0.822 wrank=1.45 reg=0.0496 17s
softmin_full5_beta5_w100_045_020_010_005 ep 036/150* loss=0.00659 val_acc=0.809 both=0.635 one=0.348 gap=0.049 vehicle1=0.785 vehicle2=0.834 wrank=1.47 reg=0.0493 18s
softmin_full5_beta5_w100_045_020_010_005 ep 040/150* loss=0.00643 val_acc=0.814 both=0.642 one=0.343 gap=0.042 vehicle1=0.792 vehicle2=0.835 wrank=1.47 reg=0.0501 20s
softmin_full5_beta5_w100_045_020_010_005 ep 045/150  loss=0.00611 val_acc=0.802 both=0.627 one=0.350 gap=0.041 vehicle1=0.782 vehicle2=0.823 wrank=1.44 reg=0.0497 22s
softmin_full5_beta5_w100_045_020_010_005 ep 049/150* loss=0.00577 val_acc=0.820 both=0.665 one=0.310 gap=0.043 vehicle1=0.798 vehicle2=0.842 wrank=1.44 reg=0.0485 24s
softmin_full5_beta5_w100_045_020_010_005 ep 050/150  loss=0.00567 val_acc=0.791 both=0.623 one=0.337 gap=0.017 vehicle1=0.783 vehicle2=0.799 wrank=1.45 reg=0.0512 24s
softmin_full5_beta5_w100_045_020_010_005 ep 055/150  loss=0.00555 val_acc=0.789 both=0.623 one=0.331 gap=0.029 vehicle1=0.774 vehicle2=0.803 wrank=1.46 reg=0.0519 27s
softmin_full5_beta5_w100_045_020_010_005 ep 060/150  loss=0.00526 val_acc=0.801 both=0.636 one=0.330 gap=0.029 vehicle1=0.786 vehicle2=0.816 wrank=1.46 reg=0.0503 29s
softmin_full5_beta5_w100_045_020_010_005 ep 065/150  loss=0.00511 val_acc=0.777 both=0.608 one=0.338 gap=0.018 vehicle1=0.768 vehicle2=0.786 wrank=1.50 reg=0.0539 32s
softmin_full5_beta5_w100_045_020_010_005 ep 070/150  loss=0.00492 val_acc=0.771 both=0.602 one=0.337 gap=0.023 vehicle1=0.759 vehicle2=0.782 wrank=1.50 reg=0.0552 34s
softmin_full5_beta5_w100_045_020_010_005 ep 071/150* loss=0.00495 val_acc=0.820 both=0.667 one=0.306 gap=0.045 vehicle1=0.798 vehicle2=0.842 wrank=1.45 reg=0.0472 34s
softmin_full5_beta5_w100_045_020_010_005 ep 075/150  loss=0.00480 val_acc=0.771 both=0.593 one=0.355 gap=0.028 vehicle1=0.757 vehicle2=0.785 wrank=1.53 reg=0.0549 36s
softmin_full5_beta5_w100_045_020_010_005 ep 077/150* loss=0.00470 val_acc=0.825 both=0.685 one=0.282 gap=0.031 vehicle1=0.810 vehicle2=0.841 wrank=1.41 reg=0.0474 37s
softmin_full5_beta5_w100_045_020_010_005 ep 080/150  loss=0.00460 val_acc=0.798 both=0.641 one=0.314 gap=0.020 vehicle1=0.788 vehicle2=0.808 wrank=1.44 reg=0.0505 39s
softmin_full5_beta5_w100_045_020_010_005 ep 082/150* loss=0.00462 val_acc=0.828 both=0.682 one=0.294 gap=0.037 vehicle1=0.810 vehicle2=0.847 wrank=1.42 reg=0.0452 40s
softmin_full5_beta5_w100_045_020_010_005 ep 085/150  loss=0.00455 val_acc=0.780 both=0.616 one=0.328 gap=0.002 vehicle1=0.780 vehicle2=0.779 wrank=1.52 reg=0.0555 41s
softmin_full5_beta5_w100_045_020_010_005 ep 090/150  loss=0.00434 val_acc=0.789 both=0.629 one=0.321 gap=0.016 vehicle1=0.781 vehicle2=0.797 wrank=1.50 reg=0.0537 43s
softmin_full5_beta5_w100_045_020_010_005 ep 095/150  loss=0.00431 val_acc=0.806 both=0.657 one=0.299 gap=0.002 vehicle1=0.805 vehicle2=0.807 wrank=1.43 reg=0.0495 46s
softmin_full5_beta5_w100_045_020_010_005 ep 100/150  loss=0.00418 val_acc=0.821 both=0.672 one=0.298 gap=0.020 vehicle1=0.811 vehicle2=0.831 wrank=1.45 reg=0.0480 48s
softmin_full5_beta5_w100_045_020_010_005 ep 105/150  loss=0.00400 val_acc=0.813 both=0.673 one=0.279 gap=0.029 vehicle1=0.798 vehicle2=0.827 wrank=1.44 reg=0.0491 51s
softmin_full5_beta5_w100_045_020_010_005 ep 107/150* loss=0.00400 val_acc=0.831 both=0.690 one=0.282 gap=0.027 vehicle1=0.817 vehicle2=0.845 wrank=1.41 reg=0.0447 52s
softmin_full5_beta5_w100_045_020_010_005 ep 109/150* loss=0.00390 val_acc=0.833 both=0.689 one=0.288 gap=0.022 vehicle1=0.822 vehicle2=0.844 wrank=1.42 reg=0.0458 53s
softmin_full5_beta5_w100_045_020_010_005 ep 110/150* loss=0.00391 val_acc=0.846 both=0.711 one=0.271 gap=0.019 vehicle1=0.837 vehicle2=0.856 wrank=1.39 reg=0.0430 53s
softmin_full5_beta5_w100_045_020_010_005 ep 112/150* loss=0.00391 val_acc=0.855 both=0.734 one=0.243 gap=0.009 vehicle1=0.851 vehicle2=0.860 wrank=1.35 reg=0.0429 54s
softmin_full5_beta5_w100_045_020_010_005 ep 115/150  loss=0.00389 val_acc=0.852 both=0.727 one=0.250 gap=0.011 vehicle1=0.846 vehicle2=0.857 wrank=1.35 reg=0.0422 55s
softmin_full5_beta5_w100_045_020_010_005 ep 118/150* loss=0.00383 val_acc=0.864 both=0.740 one=0.248 gap=0.006 vehicle1=0.861 vehicle2=0.867 wrank=1.36 reg=0.0403 57s
softmin_full5_beta5_w100_045_020_010_005 ep 120/150  loss=0.00375 val_acc=0.815 both=0.663 one=0.304 gap=0.017 vehicle1=0.807 vehicle2=0.824 wrank=1.45 reg=0.0498 58s
softmin_full5_beta5_w100_045_020_010_005 ep 125/150  loss=0.00369 val_acc=0.829 both=0.688 one=0.284 gap=0.014 vehicle1=0.823 vehicle2=0.836 wrank=1.41 reg=0.0472 60s
softmin_full5_beta5_w100_045_020_010_005 ep 130/150  loss=0.00356 val_acc=0.828 both=0.691 one=0.273 gap=0.026 vehicle1=0.841 vehicle2=0.815 wrank=1.45 reg=0.0503 63s
softmin_full5_beta5_w100_045_020_010_005 ep 131/150* loss=0.00354 val_acc=0.872 both=0.758 one=0.228 gap=0.005 vehicle1=0.875 vehicle2=0.870 wrank=1.33 reg=0.0379 63s
softmin_full5_beta5_w100_045_020_010_005 ep 132/150* loss=0.00348 val_acc=0.895 both=0.795 one=0.200 gap=0.002 vehicle1=0.897 vehicle2=0.894 wrank=1.29 reg=0.0343 64s
softmin_full5_beta5_w100_045_020_010_005 ep 135/150  loss=0.00355 val_acc=0.840 both=0.704 one=0.272 gap=0.008 vehicle1=0.836 vehicle2=0.845 wrank=1.42 reg=0.0452 65s
softmin_full5_beta5_w100_045_020_010_005 ep 140/150  loss=0.00339 val_acc=0.848 both=0.713 one=0.269 gap=0.003 vehicle1=0.846 vehicle2=0.849 wrank=1.41 reg=0.0448 67s
softmin_full5_beta5_w100_045_020_010_005 ep 145/150  loss=0.00333 val_acc=0.852 both=0.720 one=0.265 gap=0.004 vehicle1=0.854 vehicle2=0.851 wrank=1.40 reg=0.0432 70s
softmin_full5_beta5_w100_045_020_010_005 ep 150/150  loss=0.00327 val_acc=0.825 both=0.682 one=0.286 gap=0.013 vehicle1=0.831 vehicle2=0.818 wrank=1.46 reg=0.0493 72s
Saved histories/metrics to d:\2023-2028_UCLA_Research_Projects\IoBT\17-5-26-MILCOMAttempt\reports\tables\multi_vehicle_rssi_softmin_full5_eq5_150ep
Interim source: d:\2023-2028_UCLA_Research_Projects\IoBT\17-5-26-MILCOMAttempt\data\interim\20250815_0900_multi_vehicle
valid timestamps=6625, nodes=10, vehicles=['vehicle1', 'vehicle2'], subset sizes <= 5
rho=10.222 m
Saved processed artifact: m02_multi_vehicle_leq5_rssi_static_full5ranks
Elapsed: 2.2 min

,prefix,times,actions_per_time,examples,context_dim,action_dim,mean_contains_fraction_all_actions,both_rate_all_actions,elapsed_min
0,m02_multi_vehicle_leq5_rssi_static_full5ranks,6625,637,4220125,30,21,0.401884,0.167433,2.2433

              artifact                                               path
0           arrays_npz  d:\2023-2028_UCLA_Research_Projects\IoBT\17-5-...
1   examples_index_csv  d:\2023-2028_UCLA_Research_Projects\IoBT\17-5-...
2     feature_wide_csv  d:\2023-2028_UCLA_Research_Projects\IoBT\17-5-...
3  sensor_geometry_csv  d:\2023-2028_UCLA_Research_Projects\IoBT\17-5-...
4            meta_json  d:\2023-2028_UCLA_Research_Projects\IoBT\17-5-...

Building dense train cache from m02_multi_vehicle_leq5_rssi_static_full5ranks_examples_index.csv ...
Saved dense train cache: d:\2023-2028_UCLA_Research_Projects\IoBT\17-5-26-MILCOMAttempt\data\processed\m02_multi_vehicle_leq5_rssi_static_full5ranks_dense_train_cache.npz
PROJECT_ROOT: d:\2023-2028_UCLA_Research_Projects\IoBT\17-5-26-MILCOMAttempt
DEVICE: cuda
data: times=6625, actions/time=637, examples=4,220,125, context_dim=30, action_dim=21
dense cache: d:\2023-2028_UCLA_Research_Projects\IoBT\17-5-26-MILCOMAttempt\data\processed\m02_multi_vehicle_leq5_rssi_static_full5ranks_dense_train_cache.npz
utilities: ['softmin_full5_beta5_w100_045_020_010_005']

=== softmin_full5_beta5_w100_045_020_010_005 === softmin_beta5 over per-vehicle weighted rank utilities with weights [1,.45,.20,.10,.05].
softmin_full5_beta5_w100_045_020_010_005 ep 001/150* loss=0.05062 val_acc=0.641 both=0.377 one=0.528 gap=0.019 vehicle1=0.651 vehicle2=0.632 wrank=2.09 reg=0.1022 2s
softmin_full5_beta5_w100_045_020_010_005 ep 002/150* loss=0.01448 val_acc=0.749 both=0.560 one=0.378 gap=0.017 vehicle1=0.758 vehicle2=0.740 wrank=1.56 reg=0.0671 3s
softmin_full5_beta5_w100_045_020_010_005 ep 003/150* loss=0.01201 val_acc=0.755 both=0.563 one=0.384 gap=0.029 vehicle1=0.770 vehicle2=0.740 wrank=1.56 reg=0.0664 4s
softmin_full5_beta5_w100_045_020_010_005 ep 005/150  loss=0.00983 val_acc=0.742 both=0.558 one=0.369 gap=0.007 vehicle1=0.746 vehicle2=0.739 wrank=1.58 reg=0.0658 6s
softmin_full5_beta5_w100_045_020_010_005 ep 007/150* loss=0.00878 val_acc=0.767 both=0.589 one=0.355 gap=0.016 vehicle1=0.759 vehicle2=0.775 wrank=1.54 reg=0.0623 9s
softmin_full5_beta5_w100_045_020_010_005 ep 008/150* loss=0.00867 val_acc=0.791 both=0.626 one=0.331 gap=0.031 vehicle1=0.776 vehicle2=0.807 wrank=1.51 reg=0.0603 10s
softmin_full5_beta5_w100_045_020_010_005 ep 010/150  loss=0.00801 val_acc=0.786 both=0.626 one=0.318 gap=0.051 vehicle1=0.760 vehicle2=0.811 wrank=1.49 reg=0.0598 12s
softmin_full5_beta5_w100_045_020_010_005 ep 011/150* loss=0.00767 val_acc=0.799 both=0.649 one=0.300 gap=0.063 vehicle1=0.768 vehicle2=0.831 wrank=1.47 reg=0.0570 13s
softmin_full5_beta5_w100_045_020_010_005 ep 015/150  loss=0.00684 val_acc=0.763 both=0.589 one=0.348 gap=0.057 vehicle1=0.734 vehicle2=0.791 wrank=1.58 reg=0.0651 18s
softmin_full5_beta5_w100_045_020_010_005 ep 018/150* loss=0.00633 val_acc=0.808 both=0.656 one=0.304 gap=0.049 vehicle1=0.783 vehicle2=0.832 wrank=1.43 reg=0.0534 22s
softmin_full5_beta5_w100_045_020_010_005 ep 020/150  loss=0.00653 val_acc=0.794 both=0.626 one=0.337 gap=0.035 vehicle1=0.777 vehicle2=0.811 wrank=1.50 reg=0.0571 24s
softmin_full5_beta5_w100_045_020_010_005 ep 021/150* loss=0.00613 val_acc=0.811 both=0.657 one=0.308 gap=0.045 vehicle1=0.789 vehicle2=0.834 wrank=1.41 reg=0.0544 25s
softmin_full5_beta5_w100_045_020_010_005 ep 023/150* loss=0.00589 val_acc=0.813 both=0.647 one=0.332 gap=0.041 vehicle1=0.792 vehicle2=0.833 wrank=1.49 reg=0.0545 28s
softmin_full5_beta5_w100_045_020_010_005 ep 025/150  loss=0.00563 val_acc=0.769 both=0.597 one=0.344 gap=0.050 vehicle1=0.744 vehicle2=0.794 wrank=1.58 reg=0.0628 30s
softmin_full5_beta5_w100_045_020_010_005 ep 028/150* loss=0.00537 val_acc=0.817 both=0.662 one=0.311 gap=0.030 vehicle1=0.802 vehicle2=0.832 wrank=1.44 reg=0.0524 34s
softmin_full5_beta5_w100_045_020_010_005 ep 030/150  loss=0.00529 val_acc=0.782 both=0.611 one=0.343 gap=0.032 vehicle1=0.766 vehicle2=0.798 wrank=1.55 reg=0.0599 36s
softmin_full5_beta5_w100_045_020_010_005 ep 035/150  loss=0.00497 val_acc=0.814 both=0.654 one=0.318 gap=0.035 vehicle1=0.796 vehicle2=0.831 wrank=1.45 reg=0.0537 42s
softmin_full5_beta5_w100_045_020_010_005 ep 040/150  loss=0.00471 val_acc=0.811 both=0.643 one=0.335 gap=0.027 vehicle1=0.797 vehicle2=0.824 wrank=1.48 reg=0.0542 48s
softmin_full5_beta5_w100_045_020_010_005 ep 042/150* loss=0.00453 val_acc=0.824 both=0.669 one=0.309 gap=0.024 vehicle1=0.812 vehicle2=0.836 wrank=1.43 reg=0.0518 50s
softmin_full5_beta5_w100_045_020_010_005 ep 045/150  loss=0.00459 val_acc=0.809 both=0.650 one=0.318 gap=0.048 vehicle1=0.785 vehicle2=0.833 wrank=1.48 reg=0.0569 54s
softmin_full5_beta5_w100_045_020_010_005 ep 050/150  loss=0.00448 val_acc=0.785 both=0.627 one=0.316 gap=0.028 vehicle1=0.771 vehicle2=0.799 wrank=1.49 reg=0.0593 60s
softmin_full5_beta5_w100_045_020_010_005 ep 055/150  loss=0.00405 val_acc=0.797 both=0.628 one=0.338 gap=0.023 vehicle1=0.786 vehicle2=0.808 wrank=1.51 reg=0.0591 66s
softmin_full5_beta5_w100_045_020_010_005 ep 060/150  loss=0.00380 val_acc=0.814 both=0.653 one=0.322 gap=0.020 vehicle1=0.804 vehicle2=0.824 wrank=1.47 reg=0.0554 72s
softmin_full5_beta5_w100_045_020_010_005 ep 065/150  loss=0.00379 val_acc=0.785 both=0.608 one=0.352 gap=0.020 vehicle1=0.774 vehicle2=0.795 wrank=1.53 reg=0.0616 78s
softmin_full5_beta5_w100_045_020_010_005 ep 070/150  loss=0.00353 val_acc=0.787 both=0.617 one=0.339 gap=0.017 vehicle1=0.778 vehicle2=0.795 wrank=1.52 reg=0.0610 84s
softmin_full5_beta5_w100_045_020_010_005 ep 075/150  loss=0.00343 val_acc=0.789 both=0.615 one=0.347 gap=0.012 vehicle1=0.783 vehicle2=0.795 wrank=1.53 reg=0.0632 90s
softmin_full5_beta5_w100_045_020_010_005 ep 080/150  loss=0.00331 val_acc=0.815 both=0.654 one=0.322 gap=0.003 vehicle1=0.814 vehicle2=0.817 wrank=1.48 reg=0.0577 96s
softmin_full5_beta5_w100_045_020_010_005 ep 085/150  loss=0.00313 val_acc=0.816 both=0.663 one=0.306 gap=0.023 vehicle1=0.805 vehicle2=0.828 wrank=1.47 reg=0.0561 102s
softmin_full5_beta5_w100_045_020_010_005 ep 090/150  loss=0.00306 val_acc=0.806 both=0.651 one=0.309 gap=0.006 vehicle1=0.803 vehicle2=0.809 wrank=1.45 reg=0.0565 108s
softmin_full5_beta5_w100_045_020_010_005 ep 095/150  loss=0.00298 val_acc=0.794 both=0.631 one=0.326 gap=0.023 vehicle1=0.783 vehicle2=0.805 wrank=1.48 reg=0.0601 114s
softmin_full5_beta5_w100_045_020_010_005 ep 100/150  loss=0.00298 val_acc=0.816 both=0.657 one=0.318 gap=0.013 vehicle1=0.810 vehicle2=0.823 wrank=1.43 reg=0.0554 120s
softmin_full5_beta5_w100_045_020_010_005 ep 102/150* loss=0.00289 val_acc=0.838 both=0.686 one=0.305 gap=0.006 vehicle1=0.842 vehicle2=0.835 wrank=1.42 reg=0.0524 122s
softmin_full5_beta5_w100_045_020_010_005 ep 105/150  loss=0.00286 val_acc=0.806 both=0.640 one=0.332 gap=0.017 vehicle1=0.798 vehicle2=0.814 wrank=1.47 reg=0.0592 126s
softmin_full5_beta5_w100_045_020_010_005 ep 110/150  loss=0.00310 val_acc=0.824 both=0.662 one=0.325 gap=0.021 vehicle1=0.814 vehicle2=0.835 wrank=1.46 reg=0.0542 132s
softmin_full5_beta5_w100_045_020_010_005 ep 115/150  loss=0.00274 val_acc=0.794 both=0.629 one=0.328 gap=0.023 vehicle1=0.782 vehicle2=0.805 wrank=1.49 reg=0.0592 138s
softmin_full5_beta5_w100_045_020_010_005 ep 120/150  loss=0.00282 val_acc=0.808 both=0.648 one=0.318 gap=0.036 vehicle1=0.789 vehicle2=0.826 wrank=1.47 reg=0.0581 144s
softmin_full5_beta5_w100_045_020_010_005 ep 125/150  loss=0.00263 val_acc=0.793 both=0.629 one=0.329 gap=0.029 vehicle1=0.779 vehicle2=0.808 wrank=1.47 reg=0.0588 150s
softmin_full5_beta5_w100_045_020_010_005 ep 130/150  loss=0.00248 val_acc=0.827 both=0.689 one=0.276 gap=0.029 vehicle1=0.813 vehicle2=0.842 wrank=1.37 reg=0.0511 156s
softmin_full5_beta5_w100_045_020_010_005 ep 131/150* loss=0.00257 val_acc=0.852 both=0.733 one=0.238 gap=0.019 vehicle1=0.842 vehicle2=0.861 wrank=1.32 reg=0.0470 157s
softmin_full5_beta5_w100_045_020_010_005 ep 133/150* loss=0.00276 val_acc=0.869 both=0.751 one=0.235 gap=0.020 vehicle1=0.859 vehicle2=0.878 wrank=1.30 reg=0.0445 160s
softmin_full5_beta5_w100_045_020_010_005 ep 135/150  loss=0.00252 val_acc=0.837 both=0.700 one=0.272 gap=0.034 vehicle1=0.820 vehicle2=0.854 wrank=1.38 reg=0.0498 162s
softmin_full5_beta5_w100_045_020_010_005 ep 140/150  loss=0.00237 val_acc=0.788 both=0.636 one=0.303 gap=0.046 vehicle1=0.765 vehicle2=0.811 wrank=1.43 reg=0.0572 168s
softmin_full5_beta5_w100_045_020_010_005 ep 145/150  loss=0.00227 val_acc=0.837 both=0.713 one=0.247 gap=0.031 vehicle1=0.821 vehicle2=0.852 wrank=1.33 reg=0.0493 174s
softmin_full5_beta5_w100_045_020_010_005 ep 149/150* loss=0.00225 val_acc=0.871 both=0.755 one=0.231 gap=0.026 vehicle1=0.858 vehicle2=0.884 wrank=1.30 reg=0.0433 179s
softmin_full5_beta5_w100_045_020_010_005 ep 150/150  loss=0.00217 val_acc=0.852 both=0.724 one=0.257 gap=0.008 vehicle1=0.848 vehicle2=0.857 wrank=1.34 reg=0.0467 180s
Saved histories/metrics to d:\2023-2028_UCLA_Research_Projects\IoBT\17-5-26-MILCOMAttempt\reports\tables\multi_vehicle_rssi_softmin_full5_leq5_150ep

,action_set,utility,best_epoch,val_contains_closest_fraction,val_contains_closest_all,val_dominance_gap,test_contains_closest_fraction,test_contains_closest_all,test_one_closest_rate,test_neither_closest_rate,test_dominance_gap,test_contains_vehicle1,test_contains_vehicle2,test_mean_worst_vehicle_rank,test_mean_abs_vehicle_rank_gap,test_avg_regret
0,eq5,softmin_full5_beta5_w100_045_020_010_005,132,0.895472,0.795472,0.002264,0.860377,0.744151,0.232453,0.023396,0.063396,0.892075,0.828679,1.350943,0.326792,0.040712
1,leq5,softmin_full5_beta5_w100_045_020_010_005,149,0.870943,0.755472,0.025660,0.838868,0.698868,0.280000,0.021132,0.036981,0.857359,0.820377,1.378113,0.356981,0.044178

In [11]:
# Winning config with v3 refined-band context variants: v3 bands only vs RSSI + v3 bands.
# Keeps exact-5 actions, static action geometry, v3 architecture, and softmin_d1_beta5 utility.
from pathlib import Path
import sys
import pandas as pd

PROJECT_ROOT = Path.cwd()
if PROJECT_ROOT.name == "notebooks":
    PROJECT_ROOT = PROJECT_ROOT.parent

SCRIPTS_DIR = PROJECT_ROOT / "scripts"
if str(SCRIPTS_DIR) not in sys.path:
    sys.path.insert(0, str(SCRIPTS_DIR))

import importlib
import multi_vehicle_utility_search as mv_utils

mv_utils = importlib.reload(mv_utils)
from multi_vehicle_utility_search import build_eq5_rssi_static_examples, run_rssi_utility_search

V3_CONTEXT_AUDIO_FEATURES = list(mv_utils.V3_REFINED_BAND_DB_FEATURES)
print("V3 context audio features:", V3_CONTEXT_AUDIO_FEATURES)

WINNING_SOFTMIN_D1_BETA5 = [
    {
        "name": "softmin_d1_beta5",
        "column": "derived_softmin_d1_beta5",
        "description": "Smooth min over per-vehicle d1 utilities with beta=5.",
        "kind": "softmin_d1",
        "beta": 5.0,
    }
]

FEATURE_CONTEXT_JOBS = [
    {
        "label": "v3_feature_bands",
        "prefix": "m02_multi_vehicle_eq5_v3_feature_bands_static",
        "context_feature_mode": "feature_bands",
        "model_tag": "multi_vehicle_eq5_softmin_d1_beta5_v3_feature_bands_150ep",
    },
    {
        "label": "rssi_plus_v3_feature_bands",
        "prefix": "m02_multi_vehicle_eq5_rssi_plus_v3_feature_bands_static",
        "context_feature_mode": "rssi_plus_feature_bands",
        "model_tag": "multi_vehicle_eq5_softmin_d1_beta5_rssi_plus_v3_feature_bands_150ep",
    },
]

feature_context_summaries = []
feature_context_results = {}
for job in FEATURE_CONTEXT_JOBS:
    prefix = job["prefix"]
    required = [
        PROJECT_ROOT / "data" / "processed" / f"{prefix}_arrays.npz",
        PROJECT_ROOT / "data" / "processed" / f"{prefix}_examples_index.csv",
        PROJECT_ROOT / "data" / "processed" / f"{prefix}_meta.json",
    ]
    if all(path.exists() for path in required):
        print(f"Using existing processed artifact: {prefix}")
    else:
        artifact_summary_df, artifact_paths_df = build_eq5_rssi_static_examples(
            PROJECT_ROOT,
            prefix=prefix,
            exact_subset_size=5,
            subset_size_policy="exact",
            context_feature_mode=job["context_feature_mode"],
            audio_band_features=V3_CONTEXT_AUDIO_FEATURES,
        )
        display(artifact_summary_df)
        display(artifact_paths_df)

    summary_df, results = run_rssi_utility_search(
        PROJECT_ROOT,
        prefix=prefix,
        model_tag=job["model_tag"],
        max_epochs=150,
        patience=150,
        log_every=5,
        batch_size=8192,
        time_batch_size=256,
        utility_candidates=WINNING_SOFTMIN_D1_BETA5,
    )
    summary_df = summary_df.copy()
    summary_df.insert(0, "context_mode", job["label"])
    feature_context_summaries.append(summary_df)
    feature_context_results[job["label"]] = results

feature_context_summary_df = pd.concat(feature_context_summaries, ignore_index=True)
vehicle_cols = [col for col in feature_context_summary_df.columns if col.startswith("test_contains_vehicle")]
display_cols = [
    "context_mode",
    "utility",
    "best_epoch",
    "val_contains_closest_fraction",
    "val_contains_closest_all",
    "val_dominance_gap",
    "test_contains_closest_fraction",
    "test_contains_closest_all",
    "test_one_closest_rate",
    "test_neither_closest_rate",
    "test_dominance_gap",
    *vehicle_cols,
    "test_mean_worst_vehicle_rank",
    "test_mean_abs_vehicle_rank_gap",
    "test_avg_regret",
]
display(feature_context_summary_df[[col for col in display_cols if col in feature_context_summary_df.columns]])

Interim source: d:\2023-2028_UCLA_Research_Projects\IoBT\17-5-26-MILCOMAttempt\data\interim\20250815_0900_multi_vehicle
valid timestamps=6625, nodes=10, vehicles=['vehicle1', 'vehicle2'], exact subset size=5
rho=10.222 m
Saved processed artifact: m02_multi_vehicle_eq5_feature_bands_static
Elapsed: 0.9 min

,prefix,times,actions_per_time,examples,context_dim,action_dim,mean_contains_fraction_all_actions,both_rate_all_actions,elapsed_min
0,m02_multi_vehicle_eq5_feature_bands_static,6625,252,1669500,60,21,0.5,0.245493,0.898481

              artifact                                               path
0           arrays_npz  d:\2023-2028_UCLA_Research_Projects\IoBT\17-5-...
1   examples_index_csv  d:\2023-2028_UCLA_Research_Projects\IoBT\17-5-...
2     feature_wide_csv  d:\2023-2028_UCLA_Research_Projects\IoBT\17-5-...
3  sensor_geometry_csv  d:\2023-2028_UCLA_Research_Projects\IoBT\17-5-...
4            meta_json  d:\2023-2028_UCLA_Research_Projects\IoBT\17-5-...

Building dense train cache from m02_multi_vehicle_eq5_feature_bands_static_examples_index.csv ...
Saved dense train cache: d:\2023-2028_UCLA_Research_Projects\IoBT\17-5-26-MILCOMAttempt\data\processed\m02_multi_vehicle_eq5_feature_bands_static_dense_train_cache.npz
PROJECT_ROOT: d:\2023-2028_UCLA_Research_Projects\IoBT\17-5-26-MILCOMAttempt
DEVICE: cuda
data: times=6625, actions/time=252, examples=1,669,500, context_dim=60, action_dim=21
dense cache: d:\2023-2028_UCLA_Research_Projects\IoBT\17-5-26-MILCOMAttempt\data\processed\m02_multi_vehicle_eq5_feature_bands_static_dense_train_cache.npz
utilities: ['softmin_d1_beta5']

=== softmin_d1_beta5 === Smooth min over per-vehicle d1 utilities with beta=5.
softmin_d1_beta5 ep 001/150* loss=0.04828 val_acc=0.583 both=0.298 one=0.571 gap=0.048 vehicle1=0.559 vehicle2=0.608 wrank=2.09 reg=0.0803 1s
softmin_d1_beta5 ep 003/150* loss=0.00888 val_acc=0.674 both=0.448 one=0.451 gap=0.028 vehicle1=0.660 vehicle2=0.688 wrank=1.74 reg=0.0470 2s
softmin_d1_beta5 ep 005/150  loss=0.00698 val_acc=0.654 both=0.428 one=0.451 gap=0.006 vehicle1=0.657 vehicle2=0.651 wrank=1.85 reg=0.0513 3s
softmin_d1_beta5 ep 010/150  loss=0.00521 val_acc=0.634 both=0.406 one=0.456 gap=0.003 vehicle1=0.632 vehicle2=0.635 wrank=1.81 reg=0.0519 5s
softmin_d1_beta5 ep 015/150  loss=0.00437 val_acc=0.656 both=0.435 one=0.443 gap=0.031 vehicle1=0.641 vehicle2=0.672 wrank=1.82 reg=0.0491 8s
softmin_d1_beta5 ep 020/150* loss=0.00385 val_acc=0.676 both=0.464 one=0.424 gap=0.014 vehicle1=0.669 vehicle2=0.683 wrank=1.80 reg=0.0477 10s
softmin_d1_beta5 ep 021/150* loss=0.00376 val_acc=0.687 both=0.475 one=0.423 gap=0.023 vehicle1=0.675 vehicle2=0.699 wrank=1.77 reg=0.0459 10s
softmin_d1_beta5 ep 022/150* loss=0.00367 val_acc=0.688 both=0.477 one=0.422 gap=0.025 vehicle1=0.675 vehicle2=0.700 wrank=1.77 reg=0.0460 11s
softmin_d1_beta5 ep 024/150* loss=0.00355 val_acc=0.694 both=0.491 one=0.405 gap=0.026 vehicle1=0.681 vehicle2=0.707 wrank=1.75 reg=0.0461 12s
softmin_d1_beta5 ep 025/150  loss=0.00347 val_acc=0.681 both=0.475 one=0.412 gap=0.044 vehicle1=0.659 vehicle2=0.703 wrank=1.75 reg=0.0470 12s
softmin_d1_beta5 ep 030/150  loss=0.00319 val_acc=0.680 both=0.471 one=0.418 gap=0.033 vehicle1=0.663 vehicle2=0.697 wrank=1.75 reg=0.0468 15s
softmin_d1_beta5 ep 035/150* loss=0.00295 val_acc=0.695 both=0.492 one=0.406 gap=0.045 vehicle1=0.672 vehicle2=0.718 wrank=1.72 reg=0.0446 17s
softmin_d1_beta5 ep 040/150  loss=0.00269 val_acc=0.689 both=0.483 one=0.411 gap=0.037 vehicle1=0.670 vehicle2=0.707 wrank=1.74 reg=0.0455 20s
softmin_d1_beta5 ep 045/150  loss=0.00253 val_acc=0.676 both=0.471 one=0.410 gap=0.063 vehicle1=0.645 vehicle2=0.707 wrank=1.75 reg=0.0466 22s
softmin_d1_beta5 ep 047/150* loss=0.00245 val_acc=0.696 both=0.492 one=0.408 gap=0.048 vehicle1=0.672 vehicle2=0.720 wrank=1.71 reg=0.0445 23s
softmin_d1_beta5 ep 049/150* loss=0.00238 val_acc=0.699 both=0.494 one=0.410 gap=0.052 vehicle1=0.673 vehicle2=0.725 wrank=1.72 reg=0.0445 24s
softmin_d1_beta5 ep 050/150  loss=0.00238 val_acc=0.689 both=0.482 one=0.416 gap=0.049 vehicle1=0.665 vehicle2=0.714 wrank=1.76 reg=0.0464 24s
softmin_d1_beta5 ep 055/150  loss=0.00222 val_acc=0.695 both=0.492 one=0.406 gap=0.047 vehicle1=0.672 vehicle2=0.718 wrank=1.73 reg=0.0449 27s
softmin_d1_beta5 ep 057/150* loss=0.00217 val_acc=0.702 both=0.500 one=0.405 gap=0.062 vehicle1=0.671 vehicle2=0.733 wrank=1.70 reg=0.0438 28s
softmin_d1_beta5 ep 058/150* loss=0.00214 val_acc=0.706 both=0.509 one=0.395 gap=0.042 vehicle1=0.685 vehicle2=0.728 wrank=1.70 reg=0.0443 28s
softmin_d1_beta5 ep 059/150* loss=0.00213 val_acc=0.710 both=0.509 one=0.402 gap=0.058 vehicle1=0.681 vehicle2=0.739 wrank=1.71 reg=0.0440 29s
softmin_d1_beta5 ep 060/150  loss=0.00209 val_acc=0.701 both=0.496 one=0.410 gap=0.051 vehicle1=0.675 vehicle2=0.726 wrank=1.73 reg=0.0450 29s
softmin_d1_beta5 ep 062/150* loss=0.00205 val_acc=0.722 both=0.530 one=0.385 gap=0.042 vehicle1=0.701 vehicle2=0.743 wrank=1.69 reg=0.0423 30s
softmin_d1_beta5 ep 065/150  loss=0.00200 val_acc=0.710 both=0.512 one=0.395 gap=0.057 vehicle1=0.682 vehicle2=0.738 wrank=1.72 reg=0.0438 32s
softmin_d1_beta5 ep 070/150  loss=0.00186 val_acc=0.718 both=0.524 one=0.389 gap=0.058 vehicle1=0.689 vehicle2=0.747 wrank=1.69 reg=0.0429 34s
softmin_d1_beta5 ep 071/150* loss=0.00186 val_acc=0.728 both=0.541 one=0.374 gap=0.055 vehicle1=0.700 vehicle2=0.755 wrank=1.67 reg=0.0418 34s
softmin_d1_beta5 ep 075/150  loss=0.00175 val_acc=0.720 both=0.529 one=0.381 gap=0.052 vehicle1=0.694 vehicle2=0.746 wrank=1.66 reg=0.0423 36s
softmin_d1_beta5 ep 077/150* loss=0.00173 val_acc=0.730 both=0.541 one=0.377 gap=0.045 vehicle1=0.707 vehicle2=0.752 wrank=1.68 reg=0.0407 37s
softmin_d1_beta5 ep 078/150* loss=0.00171 val_acc=0.740 both=0.557 one=0.366 gap=0.054 vehicle1=0.713 vehicle2=0.767 wrank=1.64 reg=0.0398 38s
softmin_d1_beta5 ep 079/150* loss=0.00170 val_acc=0.754 both=0.577 one=0.352 gap=0.043 vehicle1=0.732 vehicle2=0.775 wrank=1.57 reg=0.0372 38s
softmin_d1_beta5 ep 080/150  loss=0.00167 val_acc=0.746 both=0.566 one=0.359 gap=0.036 vehicle1=0.728 vehicle2=0.764 wrank=1.64 reg=0.0388 39s
softmin_d1_beta5 ep 082/150* loss=0.00163 val_acc=0.759 both=0.580 one=0.358 gap=0.033 vehicle1=0.743 vehicle2=0.776 wrank=1.60 reg=0.0375 40s
softmin_d1_beta5 ep 084/150* loss=0.00162 val_acc=0.761 both=0.585 one=0.352 gap=0.035 vehicle1=0.743 vehicle2=0.778 wrank=1.58 reg=0.0366 41s
softmin_d1_beta5 ep 085/150  loss=0.00160 val_acc=0.757 both=0.580 one=0.355 gap=0.032 vehicle1=0.741 vehicle2=0.773 wrank=1.61 reg=0.0371 41s
softmin_d1_beta5 ep 086/150* loss=0.00159 val_acc=0.762 both=0.584 one=0.355 gap=0.050 vehicle1=0.737 vehicle2=0.786 wrank=1.57 reg=0.0359 42s
softmin_d1_beta5 ep 090/150* loss=0.00153 val_acc=0.789 both=0.614 one=0.350 gap=0.044 vehicle1=0.767 vehicle2=0.811 wrank=1.53 reg=0.0326 44s
softmin_d1_beta5 ep 092/150* loss=0.00150 val_acc=0.791 both=0.625 one=0.332 gap=0.045 vehicle1=0.768 vehicle2=0.814 wrank=1.51 reg=0.0324 45s
softmin_d1_beta5 ep 095/150  loss=0.00147 val_acc=0.789 both=0.620 one=0.339 gap=0.045 vehicle1=0.767 vehicle2=0.811 wrank=1.50 reg=0.0327 46s
softmin_d1_beta5 ep 098/150* loss=0.00144 val_acc=0.802 both=0.638 one=0.327 gap=0.037 vehicle1=0.783 vehicle2=0.820 wrank=1.48 reg=0.0313 48s
softmin_d1_beta5 ep 099/150* loss=0.00142 val_acc=0.802 both=0.640 one=0.325 gap=0.042 vehicle1=0.781 vehicle2=0.823 wrank=1.48 reg=0.0311 48s
softmin_d1_beta5 ep 100/150  loss=0.00141 val_acc=0.795 both=0.630 one=0.330 gap=0.034 vehicle1=0.778 vehicle2=0.812 wrank=1.52 reg=0.0323 49s
softmin_d1_beta5 ep 102/150* loss=0.00138 val_acc=0.802 both=0.642 one=0.320 gap=0.035 vehicle1=0.785 vehicle2=0.820 wrank=1.50 reg=0.0317 49s
softmin_d1_beta5 ep 103/150* loss=0.00135 val_acc=0.830 both=0.689 one=0.282 gap=0.021 vehicle1=0.820 vehicle2=0.841 wrank=1.49 reg=0.0278 50s
softmin_d1_beta5 ep 105/150  loss=0.00132 val_acc=0.815 both=0.660 one=0.310 gap=0.043 vehicle1=0.794 vehicle2=0.837 wrank=1.47 reg=0.0307 51s
softmin_d1_beta5 ep 110/150  loss=0.00130 val_acc=0.809 both=0.652 one=0.314 gap=0.035 vehicle1=0.792 vehicle2=0.826 wrank=1.51 reg=0.0313 53s
softmin_d1_beta5 ep 115/150  loss=0.00123 val_acc=0.802 both=0.645 one=0.314 gap=0.029 vehicle1=0.788 vehicle2=0.817 wrank=1.49 reg=0.0308 56s
softmin_d1_beta5 ep 120/150  loss=0.00119 val_acc=0.803 both=0.647 one=0.312 gap=0.041 vehicle1=0.783 vehicle2=0.823 wrank=1.50 reg=0.0314 58s
softmin_d1_beta5 ep 121/150* loss=0.00120 val_acc=0.833 both=0.696 one=0.274 gap=0.049 vehicle1=0.808 vehicle2=0.857 wrank=1.42 reg=0.0259 59s
softmin_d1_beta5 ep 122/150* loss=0.00120 val_acc=0.838 both=0.705 one=0.266 gap=0.062 vehicle1=0.807 vehicle2=0.869 wrank=1.39 reg=0.0260 59s
softmin_d1_beta5 ep 125/150  loss=0.00117 val_acc=0.822 both=0.681 one=0.283 gap=0.061 vehicle1=0.792 vehicle2=0.853 wrank=1.45 reg=0.0281 61s
softmin_d1_beta5 ep 130/150  loss=0.00113 val_acc=0.818 both=0.674 one=0.289 gap=0.055 vehicle1=0.791 vehicle2=0.846 wrank=1.43 reg=0.0291 63s
softmin_d1_beta5 ep 132/150* loss=0.00112 val_acc=0.842 both=0.712 one=0.260 gap=0.067 vehicle1=0.808 vehicle2=0.875 wrank=1.38 reg=0.0256 64s
softmin_d1_beta5 ep 135/150  loss=0.00109 val_acc=0.829 both=0.691 one=0.276 gap=0.050 vehicle1=0.805 vehicle2=0.854 wrank=1.43 reg=0.0272 65s
softmin_d1_beta5 ep 137/150* loss=0.00107 val_acc=0.845 both=0.714 one=0.262 gap=0.067 vehicle1=0.811 vehicle2=0.878 wrank=1.38 reg=0.0248 66s
softmin_d1_beta5 ep 140/150  loss=0.00104 val_acc=0.810 both=0.662 one=0.296 gap=0.054 vehicle1=0.783 vehicle2=0.837 wrank=1.46 reg=0.0302 68s
softmin_d1_beta5 ep 145/150  loss=0.00102 val_acc=0.805 both=0.660 one=0.290 gap=0.060 vehicle1=0.775 vehicle2=0.835 wrank=1.46 reg=0.0300 70s
softmin_d1_beta5 ep 150/150  loss=0.00097 val_acc=0.819 both=0.682 one=0.275 gap=0.068 vehicle1=0.785 vehicle2=0.853 wrank=1.41 reg=0.0281 73s
Saved histories/metrics to d:\2023-2028_UCLA_Research_Projects\IoBT\17-5-26-MILCOMAttempt\reports\tables\multi_vehicle_eq5_softmin_d1_beta5_feature_bands_150ep
Interim source: d:\2023-2028_UCLA_Research_Projects\IoBT\17-5-26-MILCOMAttempt\data\interim\20250815_0900_multi_vehicle
valid timestamps=6625, nodes=10, vehicles=['vehicle1', 'vehicle2'], exact subset size=5
rho=10.222 m
Saved processed artifact: m02_multi_vehicle_eq5_rssi_plus_feature_bands_static
Elapsed: 1.0 min

,prefix,times,actions_per_time,examples,context_dim,action_dim,mean_contains_fraction_all_actions,both_rate_all_actions,elapsed_min
0,m02_multi_vehicle_eq5_rssi_plus_feature_bands_...,6625,252,1669500,70,21,0.5,0.245493,0.999383

              artifact                                               path
0           arrays_npz  d:\2023-2028_UCLA_Research_Projects\IoBT\17-5-...
1   examples_index_csv  d:\2023-2028_UCLA_Research_Projects\IoBT\17-5-...
2     feature_wide_csv  d:\2023-2028_UCLA_Research_Projects\IoBT\17-5-...
3  sensor_geometry_csv  d:\2023-2028_UCLA_Research_Projects\IoBT\17-5-...
4            meta_json  d:\2023-2028_UCLA_Research_Projects\IoBT\17-5-...

Building dense train cache from m02_multi_vehicle_eq5_rssi_plus_feature_bands_static_examples_index.csv ...
Saved dense train cache: d:\2023-2028_UCLA_Research_Projects\IoBT\17-5-26-MILCOMAttempt\data\processed\m02_multi_vehicle_eq5_rssi_plus_feature_bands_static_dense_train_cache.npz
PROJECT_ROOT: d:\2023-2028_UCLA_Research_Projects\IoBT\17-5-26-MILCOMAttempt
DEVICE: cuda
data: times=6625, actions/time=252, examples=1,669,500, context_dim=70, action_dim=21
dense cache: d:\2023-2028_UCLA_Research_Projects\IoBT\17-5-26-MILCOMAttempt\data\processed\m02_multi_vehicle_eq5_rssi_plus_feature_bands_static_dense_train_cache.npz
utilities: ['softmin_d1_beta5']

=== softmin_d1_beta5 === Smooth min over per-vehicle d1 utilities with beta=5.
softmin_d1_beta5 ep 001/150* loss=0.03902 val_acc=0.569 both=0.316 one=0.506 gap=0.023 vehicle1=0.558 vehicle2=0.580 wrank=2.18 reg=0.0757 1s
softmin_d1_beta5 ep 002/150* loss=0.01131 val_acc=0.687 both=0.471 one=0.432 gap=0.023 vehicle1=0.698 vehicle2=0.675 wrank=1.75 reg=0.0437 1s
softmin_d1_beta5 ep 003/150* loss=0.00824 val_acc=0.718 both=0.514 one=0.409 gap=0.027 vehicle1=0.732 vehicle2=0.705 wrank=1.72 reg=0.0383 2s
softmin_d1_beta5 ep 004/150* loss=0.00702 val_acc=0.738 both=0.544 one=0.388 gap=0.021 vehicle1=0.728 vehicle2=0.749 wrank=1.65 reg=0.0359 2s
softmin_d1_beta5 ep 005/150* loss=0.00638 val_acc=0.764 both=0.584 one=0.359 gap=0.041 vehicle1=0.743 vehicle2=0.784 wrank=1.54 reg=0.0317 3s
softmin_d1_beta5 ep 010/150  loss=0.00476 val_acc=0.726 both=0.520 one=0.412 gap=0.042 vehicle1=0.705 vehicle2=0.747 wrank=1.64 reg=0.0407 6s
softmin_d1_beta5 ep 015/150  loss=0.00404 val_acc=0.748 both=0.568 one=0.359 gap=0.011 vehicle1=0.743 vehicle2=0.753 wrank=1.55 reg=0.0370 8s
softmin_d1_beta5 ep 020/150  loss=0.00352 val_acc=0.758 both=0.566 one=0.384 gap=0.031 vehicle1=0.743 vehicle2=0.774 wrank=1.55 reg=0.0345 10s
softmin_d1_beta5 ep 024/150* loss=0.00323 val_acc=0.768 both=0.588 one=0.360 gap=0.026 vehicle1=0.755 vehicle2=0.781 wrank=1.51 reg=0.0336 12s
softmin_d1_beta5 ep 025/150  loss=0.00316 val_acc=0.764 both=0.583 one=0.362 gap=0.029 vehicle1=0.749 vehicle2=0.778 wrank=1.53 reg=0.0332 13s
softmin_d1_beta5 ep 027/150* loss=0.00305 val_acc=0.785 both=0.606 one=0.357 gap=0.026 vehicle1=0.771 vehicle2=0.798 wrank=1.50 reg=0.0306 14s
softmin_d1_beta5 ep 028/150* loss=0.00299 val_acc=0.810 both=0.641 one=0.339 gap=0.028 vehicle1=0.796 vehicle2=0.824 wrank=1.46 reg=0.0270 14s
softmin_d1_beta5 ep 030/150  loss=0.00288 val_acc=0.766 both=0.586 one=0.360 gap=0.048 vehicle1=0.743 vehicle2=0.790 wrank=1.55 reg=0.0344 15s
softmin_d1_beta5 ep 034/150* loss=0.00269 val_acc=0.812 both=0.650 one=0.325 gap=0.042 vehicle1=0.791 vehicle2=0.833 wrank=1.44 reg=0.0264 17s
softmin_d1_beta5 ep 035/150  loss=0.00267 val_acc=0.761 both=0.576 one=0.371 gap=0.043 vehicle1=0.740 vehicle2=0.783 wrank=1.53 reg=0.0342 18s
softmin_d1_beta5 ep 040/150  loss=0.00244 val_acc=0.756 both=0.572 one=0.368 gap=0.060 vehicle1=0.726 vehicle2=0.786 wrank=1.58 reg=0.0355 20s
softmin_d1_beta5 ep 045/150  loss=0.00224 val_acc=0.771 both=0.595 one=0.352 gap=0.050 vehicle1=0.746 vehicle2=0.796 wrank=1.54 reg=0.0335 23s
softmin_d1_beta5 ep 050/150  loss=0.00211 val_acc=0.768 both=0.596 one=0.344 gap=0.048 vehicle1=0.744 vehicle2=0.792 wrank=1.52 reg=0.0338 25s
softmin_d1_beta5 ep 055/150  loss=0.00196 val_acc=0.800 both=0.630 one=0.339 gap=0.060 vehicle1=0.770 vehicle2=0.829 wrank=1.49 reg=0.0297 28s
softmin_d1_beta5 ep 060/150  loss=0.00184 val_acc=0.808 both=0.642 one=0.332 gap=0.047 vehicle1=0.784 vehicle2=0.831 wrank=1.46 reg=0.0279 30s
softmin_d1_beta5 ep 065/150* loss=0.00173 val_acc=0.815 both=0.651 one=0.328 gap=0.045 vehicle1=0.792 vehicle2=0.838 wrank=1.47 reg=0.0269 33s
softmin_d1_beta5 ep 067/150* loss=0.00169 val_acc=0.815 both=0.654 one=0.322 gap=0.034 vehicle1=0.798 vehicle2=0.832 wrank=1.45 reg=0.0260 34s
softmin_d1_beta5 ep 070/150  loss=0.00163 val_acc=0.805 both=0.638 one=0.334 gap=0.056 vehicle1=0.777 vehicle2=0.832 wrank=1.48 reg=0.0277 35s
softmin_d1_beta5 ep 071/150* loss=0.00162 val_acc=0.822 both=0.667 one=0.310 gap=0.046 vehicle1=0.799 vehicle2=0.845 wrank=1.42 reg=0.0249 36s
softmin_d1_beta5 ep 075/150  loss=0.00155 val_acc=0.815 both=0.656 one=0.318 gap=0.032 vehicle1=0.798 vehicle2=0.831 wrank=1.44 reg=0.0266 37s
softmin_d1_beta5 ep 076/150* loss=0.00154 val_acc=0.828 both=0.672 one=0.311 gap=0.045 vehicle1=0.805 vehicle2=0.851 wrank=1.41 reg=0.0247 38s
softmin_d1_beta5 ep 080/150  loss=0.00145 val_acc=0.818 both=0.667 one=0.301 gap=0.045 vehicle1=0.795 vehicle2=0.840 wrank=1.46 reg=0.0256 40s
softmin_d1_beta5 ep 085/150  loss=0.00138 val_acc=0.812 both=0.662 one=0.301 gap=0.066 vehicle1=0.780 vehicle2=0.845 wrank=1.46 reg=0.0267 42s
softmin_d1_beta5 ep 090/150  loss=0.00131 val_acc=0.816 both=0.665 one=0.302 gap=0.056 vehicle1=0.788 vehicle2=0.844 wrank=1.44 reg=0.0257 45s
softmin_d1_beta5 ep 095/150  loss=0.00125 val_acc=0.816 both=0.660 one=0.311 gap=0.044 vehicle1=0.794 vehicle2=0.838 wrank=1.46 reg=0.0267 47s
softmin_d1_beta5 ep 100/150  loss=0.00121 val_acc=0.824 both=0.676 one=0.296 gap=0.042 vehicle1=0.803 vehicle2=0.845 wrank=1.45 reg=0.0256 50s
softmin_d1_beta5 ep 105/150  loss=0.00116 val_acc=0.815 both=0.661 one=0.309 gap=0.052 vehicle1=0.789 vehicle2=0.842 wrank=1.46 reg=0.0270 52s
softmin_d1_beta5 ep 110/150  loss=0.00112 val_acc=0.802 both=0.651 one=0.302 gap=0.045 vehicle1=0.779 vehicle2=0.824 wrank=1.49 reg=0.0288 54s
softmin_d1_beta5 ep 115/150  loss=0.00106 val_acc=0.812 both=0.667 one=0.290 gap=0.047 vehicle1=0.789 vehicle2=0.835 wrank=1.49 reg=0.0284 57s
softmin_d1_beta5 ep 120/150  loss=0.00104 val_acc=0.803 both=0.648 one=0.309 gap=0.048 vehicle1=0.779 vehicle2=0.826 wrank=1.51 reg=0.0295 59s
softmin_d1_beta5 ep 125/150  loss=0.00099 val_acc=0.798 both=0.640 one=0.315 gap=0.057 vehicle1=0.769 vehicle2=0.826 wrank=1.49 reg=0.0297 62s
softmin_d1_beta5 ep 130/150  loss=0.00095 val_acc=0.814 both=0.663 one=0.301 gap=0.034 vehicle1=0.797 vehicle2=0.831 wrank=1.47 reg=0.0278 64s
softmin_d1_beta5 ep 135/150  loss=0.00094 val_acc=0.789 both=0.629 one=0.320 gap=0.053 vehicle1=0.763 vehicle2=0.816 wrank=1.51 reg=0.0307 66s
softmin_d1_beta5 ep 140/150  loss=0.00090 val_acc=0.775 both=0.629 one=0.291 gap=0.054 vehicle1=0.748 vehicle2=0.802 wrank=1.56 reg=0.0339 69s
softmin_d1_beta5 ep 145/150  loss=0.00088 val_acc=0.803 both=0.651 one=0.304 gap=0.057 vehicle1=0.774 vehicle2=0.831 wrank=1.48 reg=0.0301 71s
softmin_d1_beta5 ep 150/150  loss=0.00084 val_acc=0.777 both=0.630 one=0.294 gap=0.049 vehicle1=0.752 vehicle2=0.802 wrank=1.54 reg=0.0335 74s
Saved histories/metrics to d:\2023-2028_UCLA_Research_Projects\IoBT\17-5-26-MILCOMAttempt\reports\tables\multi_vehicle_eq5_softmin_d1_beta5_rssi_plus_feature_bands_150ep

,context_mode,utility,best_epoch,val_contains_closest_fraction,val_contains_closest_all,val_dominance_gap,test_contains_closest_fraction,test_contains_closest_all,test_one_closest_rate,test_neither_closest_rate,test_dominance_gap,test_contains_vehicle1,test_contains_vehicle2,test_mean_worst_vehicle_rank,test_mean_abs_vehicle_rank_gap,test_avg_regret
0,feature_bands,softmin_d1_beta5,137,0.844906,0.713962,0.067170,0.864906,0.750189,0.229434,0.020377,0.034717,0.882264,0.847547,1.33434,0.313962,0.019553
1,rssi_plus_feature_bands,softmin_d1_beta5,76,0.827925,0.672453,0.045283,0.834340,0.689811,0.289057,0.021132,0.003774,0.836226,0.832453,1.37283,0.351698,0.025129

In [12]:
# Final RSSI-only exact-5 model: best_model_m_v1
from pathlib import Path
import sys

PROJECT_ROOT = Path.cwd()
if PROJECT_ROOT.name == "notebooks":
    PROJECT_ROOT = PROJECT_ROOT.parent

SCRIPTS_DIR = PROJECT_ROOT / "scripts"
if str(SCRIPTS_DIR) not in sys.path:
    sys.path.insert(0, str(SCRIPTS_DIR))

import importlib
import multi_vehicle_utility_search as mv_utils

mv_utils = importlib.reload(mv_utils)
from multi_vehicle_utility_search import run_rssi_utility_search

BEST_MODEL_M_V1_PREFIX = "m02_multi_vehicle_eq5_rssi_static"
BEST_MODEL_M_V1_TAG = "best_model_m_v1"

BEST_MODEL_M_V1_UTILITY = [
    {
        "name": "softmin_d1_beta5",
        "column": "derived_softmin_d1_beta5",
        "description": "Smooth min over per-vehicle d1 utilities with beta=5.",
        "kind": "softmin_d1",
        "beta": 5.0,
    }
]

best_model_m_v1_summary_df, best_model_m_v1_results = run_rssi_utility_search(
    PROJECT_ROOT,
    prefix=BEST_MODEL_M_V1_PREFIX,
    model_tag=BEST_MODEL_M_V1_TAG,
    max_epochs=400,
    patience=400,
    log_every=10,
    batch_size=8192,
    time_batch_size=256,
    utility_candidates=BEST_MODEL_M_V1_UTILITY,
)

display(best_model_m_v1_summary_df)

print("Checkpoint:", PROJECT_ROOT / "experiments" / BEST_MODEL_M_V1_TAG / "softmin_d1_beta5" / "best_model.pt")
print("Tables:", PROJECT_ROOT / "reports" / "tables" / BEST_MODEL_M_V1_TAG)

PROJECT_ROOT: d:\2023-2028_UCLA_Research_Projects\IoBT\17-5-26-MILCOMAttempt
DEVICE: cuda
data: times=6625, actions/time=252, examples=1,669,500, context_dim=30, action_dim=21
dense cache: d:\2023-2028_UCLA_Research_Projects\IoBT\17-5-26-MILCOMAttempt\data\processed\m02_multi_vehicle_eq5_rssi_static_dense_train_cache.npz
utilities: ['softmin_d1_beta5']

=== softmin_d1_beta5 === Smooth min over per-vehicle d1 utilities with beta=5.
softmin_d1_beta5 ep 001/400* loss=0.04217 val_acc=0.601 both=0.326 one=0.550 gap=0.022 vehicle1=0.612 vehicle2=0.590 wrank=2.30 reg=0.0678 1s
softmin_d1_beta5 ep 002/400* loss=0.01223 val_acc=0.651 both=0.398 one=0.505 gap=0.070 vehicle1=0.686 vehicle2=0.616 wrank=1.96 reg=0.0546 1s
softmin_d1_beta5 ep 004/400* loss=0.00809 val_acc=0.661 both=0.454 one=0.414 gap=0.011 vehicle1=0.666 vehicle2=0.656 wrank=1.75 reg=0.0453 2s
softmin_d1_beta5 ep 005/400* loss=0.00744 val_acc=0.682 both=0.489 one=0.385 gap=0.002 vehicle1=0.682 vehicle2=0.681 wrank=1.65 reg=0.0408 3s
softmin_d1_beta5 ep 006/400* loss=0.00692 val_acc=0.711 both=0.531 one=0.360 gap=0.005 vehicle1=0.708 vehicle2=0.713 wrank=1.61 reg=0.0366 3s
softmin_d1_beta5 ep 007/400* loss=0.00652 val_acc=0.719 both=0.546 one=0.347 gap=0.008 vehicle1=0.715 vehicle2=0.723 wrank=1.57 reg=0.0357 4s
softmin_d1_beta5 ep 010/400  loss=0.00578 val_acc=0.689 both=0.503 one=0.372 gap=0.055 vehicle1=0.661 vehicle2=0.716 wrank=1.61 reg=0.0400 5s
softmin_d1_beta5 ep 011/400* loss=0.00564 val_acc=0.721 both=0.546 one=0.349 gap=0.032 vehicle1=0.705 vehicle2=0.737 wrank=1.54 reg=0.0361 5s
softmin_d1_beta5 ep 016/400* loss=0.00503 val_acc=0.725 both=0.534 one=0.381 gap=0.016 vehicle1=0.717 vehicle2=0.733 wrank=1.62 reg=0.0389 8s
softmin_d1_beta5 ep 019/400* loss=0.00482 val_acc=0.729 both=0.537 one=0.384 gap=0.004 vehicle1=0.728 vehicle2=0.731 wrank=1.63 reg=0.0389 9s
softmin_d1_beta5 ep 020/400* loss=0.00472 val_acc=0.734 both=0.546 one=0.377 gap=0.012 vehicle1=0.728 vehicle2=0.740 wrank=1.62 reg=0.0382 10s
softmin_d1_beta5 ep 022/400* loss=0.00457 val_acc=0.738 both=0.548 one=0.381 gap=0.014 vehicle1=0.731 vehicle2=0.746 wrank=1.61 reg=0.0370 11s
softmin_d1_beta5 ep 023/400* loss=0.00453 val_acc=0.749 both=0.568 one=0.362 gap=0.008 vehicle1=0.745 vehicle2=0.753 wrank=1.56 reg=0.0344 11s
softmin_d1_beta5 ep 025/400* loss=0.00444 val_acc=0.753 both=0.565 one=0.376 gap=0.014 vehicle1=0.746 vehicle2=0.760 wrank=1.59 reg=0.0350 12s
softmin_d1_beta5 ep 027/400* loss=0.00428 val_acc=0.762 both=0.581 one=0.362 gap=0.017 vehicle1=0.754 vehicle2=0.771 wrank=1.55 reg=0.0326 13s
softmin_d1_beta5 ep 030/400* loss=0.00417 val_acc=0.766 both=0.582 one=0.369 gap=0.029 vehicle1=0.752 vehicle2=0.781 wrank=1.55 reg=0.0315 15s
softmin_d1_beta5 ep 031/400* loss=0.00408 val_acc=0.798 both=0.626 one=0.345 gap=0.040 vehicle1=0.778 vehicle2=0.818 wrank=1.49 reg=0.0277 15s
softmin_d1_beta5 ep 036/400* loss=0.00387 val_acc=0.803 both=0.629 one=0.346 gap=0.073 vehicle1=0.766 vehicle2=0.839 wrank=1.49 reg=0.0275 17s
softmin_d1_beta5 ep 040/400  loss=0.00376 val_acc=0.786 both=0.611 one=0.351 gap=0.057 vehicle1=0.758 vehicle2=0.814 wrank=1.48 reg=0.0290 19s
softmin_d1_beta5 ep 050/400  loss=0.00337 val_acc=0.794 both=0.620 one=0.348 gap=0.057 vehicle1=0.766 vehicle2=0.823 wrank=1.43 reg=0.0267 24s
softmin_d1_beta5 ep 053/400* loss=0.00329 val_acc=0.813 both=0.651 one=0.324 gap=0.057 vehicle1=0.785 vehicle2=0.842 wrank=1.41 reg=0.0250 26s
softmin_d1_beta5 ep 060/400* loss=0.00310 val_acc=0.817 both=0.668 one=0.299 gap=0.050 vehicle1=0.792 vehicle2=0.842 wrank=1.39 reg=0.0244 29s
softmin_d1_beta5 ep 067/400* loss=0.00298 val_acc=0.820 both=0.670 one=0.300 gap=0.042 vehicle1=0.799 vehicle2=0.842 wrank=1.40 reg=0.0239 32s
softmin_d1_beta5 ep 070/400  loss=0.00289 val_acc=0.776 both=0.605 one=0.342 gap=0.040 vehicle1=0.756 vehicle2=0.796 wrank=1.47 reg=0.0306 34s
softmin_d1_beta5 ep 071/400* loss=0.00291 val_acc=0.827 both=0.686 one=0.282 gap=0.066 vehicle1=0.794 vehicle2=0.860 wrank=1.38 reg=0.0225 34s
softmin_d1_beta5 ep 079/400* loss=0.00273 val_acc=0.832 both=0.690 one=0.285 gap=0.050 vehicle1=0.808 vehicle2=0.857 wrank=1.38 reg=0.0221 38s
softmin_d1_beta5 ep 080/400* loss=0.00271 val_acc=0.841 both=0.711 one=0.260 gap=0.053 vehicle1=0.814 vehicle2=0.867 wrank=1.36 reg=0.0206 39s
softmin_d1_beta5 ep 086/400* loss=0.00261 val_acc=0.845 both=0.710 one=0.269 gap=0.029 vehicle1=0.830 vehicle2=0.859 wrank=1.33 reg=0.0197 42s
softmin_d1_beta5 ep 090/400  loss=0.00253 val_acc=0.843 both=0.706 one=0.275 gap=0.046 vehicle1=0.820 vehicle2=0.866 wrank=1.36 reg=0.0206 44s
softmin_d1_beta5 ep 092/400* loss=0.00253 val_acc=0.851 both=0.718 one=0.266 gap=0.015 vehicle1=0.843 vehicle2=0.858 wrank=1.32 reg=0.0198 45s
softmin_d1_beta5 ep 100/400  loss=0.00242 val_acc=0.822 both=0.691 one=0.263 gap=0.048 vehicle1=0.798 vehicle2=0.846 wrank=1.38 reg=0.0236 48s
softmin_d1_beta5 ep 102/400* loss=0.00236 val_acc=0.853 both=0.732 one=0.242 gap=0.024 vehicle1=0.841 vehicle2=0.865 wrank=1.31 reg=0.0192 49s
softmin_d1_beta5 ep 104/400* loss=0.00235 val_acc=0.857 both=0.741 one=0.231 gap=0.012 vehicle1=0.851 vehicle2=0.863 wrank=1.30 reg=0.0189 50s
softmin_d1_beta5 ep 109/400* loss=0.00225 val_acc=0.860 both=0.740 one=0.239 gap=0.016 vehicle1=0.852 vehicle2=0.868 wrank=1.34 reg=0.0185 53s
softmin_d1_beta5 ep 110/400  loss=0.00227 val_acc=0.848 both=0.719 one=0.258 gap=0.042 vehicle1=0.827 vehicle2=0.869 wrank=1.33 reg=0.0203 53s
softmin_d1_beta5 ep 111/400* loss=0.00230 val_acc=0.874 both=0.760 one=0.227 gap=0.045 vehicle1=0.851 vehicle2=0.896 wrank=1.32 reg=0.0169 54s
softmin_d1_beta5 ep 120/400  loss=0.00216 val_acc=0.826 both=0.688 one=0.276 gap=0.036 vehicle1=0.808 vehicle2=0.845 wrank=1.38 reg=0.0235 59s
softmin_d1_beta5 ep 130/400  loss=0.00206 val_acc=0.858 both=0.735 one=0.246 gap=0.009 vehicle1=0.854 vehicle2=0.863 wrank=1.31 reg=0.0196 63s
softmin_d1_beta5 ep 140/400  loss=0.00197 val_acc=0.846 both=0.715 one=0.260 gap=0.020 vehicle1=0.835 vehicle2=0.856 wrank=1.35 reg=0.0214 68s
softmin_d1_beta5 ep 150/400  loss=0.00189 val_acc=0.843 both=0.712 one=0.262 gap=0.031 vehicle1=0.827 vehicle2=0.858 wrank=1.35 reg=0.0221 73s
softmin_d1_beta5 ep 160/400  loss=0.00181 val_acc=0.784 both=0.622 one=0.325 gap=0.036 vehicle1=0.766 vehicle2=0.802 wrank=1.49 reg=0.0313 78s
softmin_d1_beta5 ep 170/400  loss=0.00173 val_acc=0.815 both=0.678 one=0.274 gap=0.020 vehicle1=0.805 vehicle2=0.826 wrank=1.45 reg=0.0273 83s
softmin_d1_beta5 ep 180/400  loss=0.00169 val_acc=0.844 both=0.717 one=0.254 gap=0.026 vehicle1=0.831 vehicle2=0.857 wrank=1.36 reg=0.0231 87s
softmin_d1_beta5 ep 190/400  loss=0.00163 val_acc=0.849 both=0.727 one=0.244 gap=0.007 vehicle1=0.845 vehicle2=0.852 wrank=1.35 reg=0.0223 92s
softmin_d1_beta5 ep 200/400  loss=0.00159 val_acc=0.835 both=0.711 one=0.248 gap=0.013 vehicle1=0.829 vehicle2=0.842 wrank=1.38 reg=0.0246 97s
softmin_d1_beta5 ep 210/400  loss=0.00150 val_acc=0.829 both=0.695 one=0.268 gap=0.017 vehicle1=0.820 vehicle2=0.838 wrank=1.40 reg=0.0271 102s
softmin_d1_beta5 ep 220/400  loss=0.00148 val_acc=0.815 both=0.671 one=0.289 gap=0.014 vehicle1=0.808 vehicle2=0.823 wrank=1.45 reg=0.0290 107s
softmin_d1_beta5 ep 230/400  loss=0.00142 val_acc=0.804 both=0.655 one=0.298 gap=0.001 vehicle1=0.804 vehicle2=0.805 wrank=1.45 reg=0.0290 111s
softmin_d1_beta5 ep 240/400  loss=0.00139 val_acc=0.831 both=0.695 one=0.271 gap=0.025 vehicle1=0.818 vehicle2=0.843 wrank=1.41 reg=0.0258 116s
softmin_d1_beta5 ep 250/400  loss=0.00137 val_acc=0.800 both=0.652 one=0.297 gap=0.010 vehicle1=0.795 vehicle2=0.805 wrank=1.46 reg=0.0306 121s
softmin_d1_beta5 ep 260/400  loss=0.00132 val_acc=0.802 both=0.654 one=0.295 gap=0.020 vehicle1=0.792 vehicle2=0.812 wrank=1.48 reg=0.0313 126s
softmin_d1_beta5 ep 270/400  loss=0.00126 val_acc=0.793 both=0.637 one=0.312 gap=0.044 vehicle1=0.771 vehicle2=0.815 wrank=1.53 reg=0.0327 131s
softmin_d1_beta5 ep 280/400  loss=0.00124 val_acc=0.792 both=0.641 one=0.303 gap=0.006 vehicle1=0.789 vehicle2=0.795 wrank=1.52 reg=0.0333 136s
softmin_d1_beta5 ep 290/400  loss=0.00126 val_acc=0.820 both=0.681 one=0.278 gap=0.038 vehicle1=0.801 vehicle2=0.839 wrank=1.47 reg=0.0282 140s
softmin_d1_beta5 ep 300/400  loss=0.00120 val_acc=0.806 both=0.660 one=0.293 gap=0.020 vehicle1=0.796 vehicle2=0.816 wrank=1.49 reg=0.0318 145s
softmin_d1_beta5 ep 310/400  loss=0.00118 val_acc=0.814 both=0.669 one=0.291 gap=0.016 vehicle1=0.806 vehicle2=0.822 wrank=1.44 reg=0.0283 150s
softmin_d1_beta5 ep 320/400  loss=0.00113 val_acc=0.808 both=0.664 one=0.288 gap=0.032 vehicle1=0.792 vehicle2=0.824 wrank=1.48 reg=0.0299 155s
softmin_d1_beta5 ep 330/400  loss=0.00111 val_acc=0.824 both=0.694 one=0.259 gap=0.013 vehicle1=0.817 vehicle2=0.830 wrank=1.42 reg=0.0271 160s
softmin_d1_beta5 ep 340/400  loss=0.00107 val_acc=0.811 both=0.670 one=0.282 gap=0.011 vehicle1=0.806 vehicle2=0.817 wrank=1.45 reg=0.0288 164s
softmin_d1_beta5 ep 350/400  loss=0.00106 val_acc=0.803 both=0.662 one=0.283 gap=0.016 vehicle1=0.811 vehicle2=0.795 wrank=1.48 reg=0.0302 169s
softmin_d1_beta5 ep 360/400  loss=0.00104 val_acc=0.805 both=0.651 one=0.309 gap=0.011 vehicle1=0.799 vehicle2=0.811 wrank=1.49 reg=0.0302 174s
softmin_d1_beta5 ep 370/400  loss=0.00103 val_acc=0.817 both=0.682 one=0.272 gap=0.003 vehicle1=0.819 vehicle2=0.816 wrank=1.44 reg=0.0277 179s
softmin_d1_beta5 ep 380/400  loss=0.00101 val_acc=0.800 both=0.648 one=0.304 gap=0.010 vehicle1=0.805 vehicle2=0.795 wrank=1.51 reg=0.0312 184s
softmin_d1_beta5 ep 390/400  loss=0.00100 val_acc=0.786 both=0.631 one=0.309 gap=0.005 vehicle1=0.788 vehicle2=0.783 wrank=1.52 reg=0.0328 190s
softmin_d1_beta5 ep 400/400  loss=0.00098 val_acc=0.771 both=0.601 one=0.341 gap=0.011 vehicle1=0.766 vehicle2=0.777 wrank=1.57 reg=0.0352 195s
Saved histories/metrics to d:\2023-2028_UCLA_Research_Projects\IoBT\17-5-26-MILCOMAttempt\reports\tables\best_model_m_v1

,utility,utility_column,best_epoch,train_rmse,train_mae,train_r2,train_top1,train_top3,train_mean_rank,train_avg_regret,...,test_mean_rank_vehicle1,test_mean_d1_vehicle1,test_contains_vehicle2,test_mean_rank_vehicle2,test_mean_d1_vehicle2,test_dominance_gap,test_vehicle1_only_rate,test_vehicle2_only_rate,test_mean_abs_vehicle_rank_gap,test_mean_abs_d1_gap_m
0,softmin_d1_beta5,derived_softmin_d1_beta5,111,0.041381,0.030857,0.835095,0.951447,0.951447,4.096352,0.001325,...,1.147925,12.925476,0.868679,1.149434,17.651718,0.000755,0.116226,0.115472,0.26717,6.535304

Checkpoint: d:\2023-2028_UCLA_Research_Projects\IoBT\17-5-26-MILCOMAttempt\experiments\best_model_m_v1\softmin_d1_beta5\best_model.pt
Tables: d:\2023-2028_UCLA_Research_Projects\IoBT\17-5-26-MILCOMAttempt\reports\tables\best_model_m_v1

In [13]:
# Display best_model_m_v1 test metrics clearly
from pathlib import Path
import pandas as pd

PROJECT_ROOT = Path.cwd()
if PROJECT_ROOT.name == "notebooks":
    PROJECT_ROOT = PROJECT_ROOT.parent

MODEL_TAG = "best_model_m_v1"
UTILITY_NAME = "softmin_d1_beta5"
TABLE_DIR = PROJECT_ROOT / "reports" / "tables" / MODEL_TAG
METRICS_PATH = TABLE_DIR / f"{UTILITY_NAME}_metrics.csv"
SUMMARY_PATH = TABLE_DIR / "utility_search_summary.csv"
CHECKPOINT_PATH = PROJECT_ROOT / "experiments" / MODEL_TAG / UTILITY_NAME / "best_model.pt"

if METRICS_PATH.exists():
    all_metrics = pd.read_csv(METRICS_PATH)
    test_metrics = all_metrics.loc[all_metrics["split"].eq("test")].copy()
elif SUMMARY_PATH.exists():
    summary = pd.read_csv(SUMMARY_PATH)
    test_cols = [col for col in summary.columns if col.startswith("test_")]
    test_metrics = summary[["utility", "best_epoch", *test_cols]].rename(
        columns={col: col.replace("test_", "") for col in test_cols}
    )
    test_metrics["split"] = "test"
else:
    raise FileNotFoundError(f"Could not find saved metrics under {TABLE_DIR}")

row = test_metrics.iloc[0]
score_from_parts = row["contains_closest_all"] + 0.5 * row["one_closest_rate"]

m_v1_test_report = pd.DataFrame(
    [
        {
            "model": MODEL_TAG,
            "utility": row["utility"],
            "best_epoch": int(row["best_epoch"]),
            "test_timestamps": int(row["n_timestamps"]),
            "containment_score_%": 100.0 * row["contains_closest_fraction"],
            "both_closest_%": 100.0 * row["contains_closest_all"],
            "one_closest_%": 100.0 * row["one_closest_rate"],
            "neither_closest_%": 100.0 * row["neither_closest_rate"],
            "vehicle1_contained_%": 100.0 * row["contains_vehicle1"],
            "vehicle2_contained_%": 100.0 * row["contains_vehicle2"],
            "dominance_gap_pp": 100.0 * row["dominance_gap"],
            "vehicle1_only_%": 100.0 * row["vehicle1_only_rate"],
            "vehicle2_only_%": 100.0 * row["vehicle2_only_rate"],
            "mean_worst_rank": row["mean_worst_vehicle_rank"],
            "mean_rank_vehicle1": row["mean_rank_vehicle1"],
            "mean_rank_vehicle2": row["mean_rank_vehicle2"],
            "mean_d1_vehicle1_m": row["mean_d1_vehicle1"],
            "mean_d1_vehicle2_m": row["mean_d1_vehicle2"],
            "avg_regret": row["avg_regret"],
            "rmse": row["rmse"],
            "score_check_abs_diff": abs(row["contains_closest_fraction"] - score_from_parts),
        }
    ]
)

percent_cols = [col for col in m_v1_test_report.columns if col.endswith("_%") or col.endswith("_pp")]
rank_cols = ["mean_worst_rank", "mean_rank_vehicle1", "mean_rank_vehicle2"]
distance_cols = ["mean_d1_vehicle1_m", "mean_d1_vehicle2_m"]
rounding = {col: 2 for col in percent_cols}
rounding.update({col: 3 for col in rank_cols})
rounding.update({col: 2 for col in distance_cols})
rounding.update({"avg_regret": 5, "rmse": 5, "score_check_abs_diff": 8})

print(f"Metrics: {METRICS_PATH if METRICS_PATH.exists() else SUMMARY_PATH}")
print(f"Checkpoint: {CHECKPOINT_PATH}")
print("containment_score = both_closest + 0.5 * one_closest")
display(m_v1_test_report.round(rounding))

Metrics: d:\2023-2028_UCLA_Research_Projects\IoBT\17-5-26-MILCOMAttempt\reports\tables\best_model_m_v1\softmin_d1_beta5_metrics.csv
Checkpoint: d:\2023-2028_UCLA_Research_Projects\IoBT\17-5-26-MILCOMAttempt\experiments\best_model_m_v1\softmin_d1_beta5\best_model.pt
containment_score = both_closest + 0.5 * one_closest

,model,utility,best_epoch,test_timestamps,containment_score_%,both_closest_%,one_closest_%,neither_closest_%,vehicle1_contained_%,vehicle2_contained_%,...,vehicle1_only_%,vehicle2_only_%,mean_worst_rank,mean_rank_vehicle1,mean_rank_vehicle2,mean_d1_vehicle1_m,mean_d1_vehicle2_m,avg_regret,rmse,score_check_abs_diff
0,best_model_m_v1,softmin_d1_beta5,111,1325,86.91,75.32,23.17,1.51,86.94,86.87,...,11.62,11.55,1.282,1.148,1.149,12.93,17.65,0.01832,0.06456,4.000000e-08